--------------------------------------------------------
--  Migration script from 3.7.7 to 3.7.8
--------------------------------------------------------
DROP TABLE IF EXISTS TB_ASMI_AZURE_TOKEN;

CREATE TABLE TB_ASMI_AZURE_TOKEN (
  APP_ID varchar(100) NOT NULL,
  USER_ID varchar(100) NOT NULL,
  DEVICE_ID varchar(255) NOT NULL,
  AUTH_CODE text NULL,
  ACCESS_TOKEN text,
  ID_TOKEN text,
  TOKEN_TYPE varchar(300) DEFAULT NULL,
  NOT_BEFORE BIGINT DEFAULT NULL,
  EXPIRES_IN int(11) DEFAULT NULL,
  EXPIRES_ON BIGINT DEFAULT NULL,
  ID_TOKEN_EXPIRES_IN BIGINT DEFAULT NULL,
  REFRESH_TOKEN text,
  REFRESH_TOKEN_EXPIRES_IN BIGINT DEFAULT NULL,
  SESSION_ID varchar(255) DEFAULT NULL,
  CREATED_BY varchar(100) DEFAULT NULL,
  CREATED_TS timestamp NULL DEFAULT NULL,
  MAKER_ID varchar(100) DEFAULT NULL,
  MAKER_TS timestamp NULL DEFAULT NULL,
  PRIMARY KEY (APP_ID,USER_ID,DEVICE_ID)
);