keystorePath=APPZILLONKEYSTOREPATH
keystorePassword=APPZILLONKSPASSWORD
devicedestinationPort=APPZILLONDEVICEDESTPORT
appzilloncommPort=APPZILLONCOMMPORT
internalserverUrl=APPZILLONINTSERVERURL
messageSeperator=,
maxTransactionLogLength=255
trustStorePath=APPZILLONTRUSTPATH
trustStorePassword=APPZILLONTRUSTPASSWORD


