--------------------------------------------------------
--  Migration script from 3.7.7 to 3.7.8
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_AZURE_TOKEN';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE "TB_ASMI_AZURE_TOKEN" (
  "APP_ID" VARCHAR2(100) NOT NULL,
  "USER_ID" VARCHAR2(100) NOT NULL,
  "DEVICE_ID" VARCHAR2(255) NOT NULL,
  "AUTH_CODE" VARCHAR2(4000) NULL,
  "ACCESS_TOKEN" VARCHAR2(4000),
  "ID_TOKEN" VARCHAR2(4000),
  "TOKEN_TYPE" VARCHAR2(300) DEFAULT NULL,
  "NOT_BEFORE" NUMBER(10,0) DEFAULT NULL,
  "EXPIRES_IN" NUMBER(10,0) DEFAULT NULL,
  "EXPIRES_ON" NUMBER(10,0) DEFAULT NULL,
  "ID_TOKEN_EXPIRES_IN" NUMBER(10,0) DEFAULT NULL,
  "REFRESH_TOKEN" VARCHAR2(4000),
  "REFRESH_TOKEN_EXPIRES_IN" NUMBER(10,0) DEFAULT NULL,
  "SESSION_ID" VARCHAR2(255) DEFAULT NULL,
  "CREATED_BY" VARCHAR2(100) DEFAULT NULL,
  "CREATED_TS" TIMESTAMP (6),
  "MAKER_ID" VARCHAR2(100) DEFAULT NULL,
  "MAKER_TS" TIMESTAMP (6),
  PRIMARY KEY ("APP_ID","USER_ID","DEVICE_ID")
);