DROP TABLE TB_ASHS_USER_PASSWORDS;
DROP TABLE TB_ASMI_SECURITY_PARAMETERS;
DROP TABLE TB_ASLG_TXN_DETAIL;
DROP TABLE TB_ASLG_FMW_TXN_DETAIL;
DROP TABLE TB_ASMI_INTF_MASTER;
DROP TABLE TB_ASMI_ROLE_INTF;
DROP TABLE TB_ASMI_ROLE_MASTER;
DROP TABLE TB_ASMI_ROLE_SCR;
DROP TABLE TB_ASMI_SCR_MASTER;
DROP TABLE TB_ASMI_USER;
DROP TABLE TB_ASMI_USER_DEVICES;
DROP TABLE TB_ASMI_USER_ROLE;
DROP TABLE TB_ASMI_SMS_USER;
DROP TABLE TB_ASTP_LAST_LOGIN;
DROP TABLE TB_ASMI_DEVICE_MASTER;
DROP TABLE TB_ASLG_AUDIT_LOG;
DROP TABLE TB_ASLG_SMS_TXN;
DROP TABLE TB_ASLG_USSD_TXN;
DROP TABLE TB_ASLG_TXT_MSLG_LOG;
DROP TABLE TB_ASMI_CONTROLS_MASTER;
DROP TABLE TB_ASMI_ROLE_CONTROLS;
DROP TABLE TB_ASLG_JMS_REQ_RESP;
DROP TABLE TB_ASHS_SECURITY_PARAMETERS;
DROP TABLE TB_ASHS_USER;
DROP TABLE TB_ASHS_USER_DEVICES;
DROP TABLE TB_ASHS_USER_ROLE;
DROP TABLE TB_ASHS_SMS_USER;
DROP TABLE TB_ASHS_ROLE_INTF;
DROP TABLE TB_ASHS_ROLE_MASTER;
DROP TABLE TB_ASHS_ROLE_SCR;
DROP TABLE TB_ASHS_SCR_MASTER;
DROP TABLE IF EXISTS TB_ASMI_USER_APP_ACCESS;
DROP TABLE TB_ASHS_USER_APP_ACCESS;
DROP TABLE TB_ASHS_ROLE_CONTROLS;
DROP TABLE TB_ASMI_APP_MASTER;
DROP TABLE TB_ASNF_APP_OS_NOTIF_CODE;
DROP TABLE TB_ASMI_DEVICE_GRPS;
DROP TABLE  TB_ASMI_SCREEN_LAYOUTS;
DROP TABLE  TB_ASMI_SCREEN_MICRO_APP;
DROP TABLE  TB_ASMI_SCREEN_WIDGETS;
DROP TABLE  TB_ASMI_DESIGN_OBJECTS;
DROP TABLE  TB_ASCZ_SCREEN_LAYOUTS;
DROP TABLE  TB_ASCZ_TEMPLATE_OBJECTS;
DROP TABLE TB_ASTP_SESSION_STORAGE;
DROP TABLE TB_ASMI_CAPTCHA_DTLS;
DROP TABLE TB_ASTP_LD_RECS;

CREATE TABLE TB_ASMI_SECURITY_PARAMETERS (
  APP_ID varchar(100) NOT NULL,
  MIN_NUM_NUM int DEFAULT NULL,
  MIN_NUM_SPCL_CHAR int DEFAULT NULL,
  MIN_NUM_UPPER_CASE_CHAR int DEFAULT NULL,
  MIN_LENGTH int DEFAULT NULL,
  MAX_LENGTH int DEFAULT NULL,
  PASS_CHANGE_FREQ int DEFAULT NULL,
  LAST_N_PASS_NOT_TO_USE int DEFAULT NULL,
  SESSION_TIMEOUT int DEFAULT NULL,
  NOOFFAILEDCOUNTS int DEFAULT NULL,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  SERVER_TOKEN varchar(255) DEFAULT NULL,
  FAIL_COUNT_TIMEOUT int DEFAULT NULL,
  PASSWORD_COUNT int DEFAULT NULL,
  DEFAULT_AUTHORIZATION char(1) DEFAULT 'Y',
  RESTRICT_SPL_CHARS varchar(100) DEFAULT NULL,
  MULTIPLE_SESSION_ALLOWED varchar(1) DEFAULT 'Y',
  /*
   * Below Fields Added by ripu
   * Appzillon - 3.1 - 65, 69 Start (for User creation extensibility and multifactor)
   */
  ALLOW_USER_PASSWORD_ENTRY VARCHAR(1) DEFAULT 'N',
  AUTO_APPROVE VARCHAR(1) DEFAULT 'Y',
  PWD_RSET_VALIDATE_PARAMS VARCHAR(45) DEFAULT 'BOTH',
  PWD_RSET_COMM_CHANNEL VARCHAR(45) DEFAULT 'BOTH',
  PWD_RSET_ACCEPT_USR_PWD VARCHAR(1) DEFAULT 'N',
  TXN_LOG_REQ VARCHAR(45) DEFAULT 'Y',
  MAKER_ID VARCHAR(45),
  MAKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CHECKER_ID VARCHAR(45),
  CHECKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  PWD_COMM_CHANNEL VARCHAR(45) DEFAULT 'BOTH',
  AUTH_STATUS VARCHAR(45) DEFAULT 'U',
  TXN_LOG_PAYLOAD VARCHAR(10) DEFAULT 'NONE',
  FMW_TXN_REQ VARCHAR(1) DEFAULT 'Y',
  /* Appzillon - 3.1 - 65, 69 End*/
  
  /*
   * Below Fields Added by sasidhar
   * for otp resend(yes,no) and otp type(numeric,string,aplhanumeric)
   */
   OTP_LENGTH int DEFAULT NULL,
   OTP_VALIDATION_COUNT int DEFAULT NULL,
   OTP_EXPIRY int DEFAULT NULL,
   OTP_RESEND varchar(10) DEFAULT NULL,
   OTP_FORMAT varchar(20) DEFAULT NULL,
   OTP_RESEND_COUNT int DEFAULT NULL,
   OTP_RESEND_LOCK_TIMEOUT int DEFAULT NULL ,
   OTP_REGEN_COUNT  int DEFAULT 0,
   PWD_CHANGE_COMM_CHANNEL varchar(30) DEFAULT 'BOTH',
   PASSWORD_ON_AUTHORIZATION VARCHAR(1) DEFAULT 'N',
   FMW_TXN_PAYLOAD VARCHAR(10) DEFAULT 'NONE',
   DATA_INTEGRITY VARCHAR(1) DEFAULT 'Y',

   /* changes end */
  PRIMARY KEY (APP_ID)
);

CREATE TABLE TB_ASHS_USER_PASSWORDS (
  USER_ID varchar(100) NOT NULL,
  APP_ID varchar(100) NOT NULL,
  PIN varchar(255) NOT NULL,
  CHANGE_TIME timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (USER_ID,APP_ID,PIN)
 ) ;
CREATE TABLE TB_ASLG_TXN_DETAIL (
  TXN_REF varchar(255) NOT NULL,
  USER_ID varchar(100) DEFAULT NULL,
  USER_APP_ID varchar(100) DEFAULT NULL,
  APP_USER_ID varchar(100) DEFAULT NULL,
  SESSION_ID varchar(255) DEFAULT NULL,
  DEVICE_ID varchar(255) DEFAULT NULL,
  ST_TM timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  END_TM timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  INTERFACE_ID varchar(50) DEFAULT NULL,
  APP_ID varchar(100) DEFAULT NULL,
  TXN_STAT varchar(20) DEFAULT NULL,
  REQ_LD_REFNO varchar(100), 
  REQ_NO_RECS int, 
  RES_LD_REFNO varchar(100), 
  RES_NO_RECS int, 
  INFO1 varchar(255) DEFAULT NULL,
  INFO2 varchar(255) DEFAULT NULL,
  INFO3 varchar(255) DEFAULT NULL,
  INFO4 varchar(255) DEFAULT NULL,
  INFO5 varchar(255) DEFAULT NULL,
  CREATE_BY varchar(200) DEFAULT NULL,
  SOURCE varchar(255),
  LONGITUDE varchar(255),
  LATITUDE varchar(255),
  ORIGINATION varchar(255),
  STATUS varchar(255),
  SUBLOCALITY varchar(255),
  ADMIN_AREA_LVL_1 varchar(255),
  ADMIN_AREA_LVL_2 varchar(255),
  COUNTRY varchar(255),
  FORMATTED_ADDRESS varchar(255),
  EXT_ST_TM timestamp(0) DEFAULT NULL,
  EXT_END_TM timestamp(0) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,  
  PRIMARY KEY (TXN_REF) 
) ;

CREATE TABLE TB_ASTP_LD_RECS(
  REF_NO varchar(100) NOT NULL,
  SEQ_NO int,
  DATA1 varchar(4000),
  DATA2 varchar(4000),
  DATA3 varchar(4000),
  DATA4 varchar(4000),
  DATA5 varchar(4000),
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,  
  PRIMARY KEY (REF_NO,SEQ_NO) 
);

CREATE TABLE TB_ASLG_FMW_TXN_DETAIL (
  TXN_REF varchar(255) NOT NULL,
  MASTER_TXN_REF varchar(255),
  INTERFACE_ID varchar(50) DEFAULT NULL,
  REQ_LD_REFNO VARCHAR(100), 
  REQ_NO_RECS int, 
  RES_LD_REFNO VARCHAR(100), 
  RES_NO_RECS int, 
  ENDPOINT_TYPE varchar(255),
  ST_TM timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  END_TM timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  STATUS varchar(1),
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (TXN_REF)
) ;

CREATE TABLE TB_ASMI_INTF_MASTER (
  INTERFACE_ID varchar(100) NOT NULL,
  APP_ID varchar(100) NOT NULL,
  CATEGORY varchar(30) DEFAULT NULL,
  TYPE varchar(30) DEFAULT NULL,
  DESCRIPTION varchar(100) DEFAULT NULL,
  AUTHRZ_REQ varchar(1) DEFAULT 'Y',
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  MAKER_ID VARCHAR(45),
  MAKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CHECKER_ID VARCHAR(45),
  CHECKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  AUTH_STATUS VARCHAR(45) DEFAULT 'U',
  CAPTCHA_REQ VARCHAR(5) DEFAULT 'TEXT',
  CAPTCHA_TYPE VARCHAR(7) DEFAULT 'N',
  INTERFACE_DEF CLOB DEFAULT NULL,
  DG_TXN_LOG_REQ VARCHAR(1) DEFAULT 'Y',
  TXN_LOG_REQ VARCHAR(1) DEFAULT 'Y',
  TXN_LOG_PAYLOAD_REQ VARCHAR(10) DEFAULT 'NONE',
  FMW_TXN_REQ VARCHAR(1) DEFAULT 'Y',
  FMW_TXN_PAYLOAD_REQ VARCHAR(10) DEFAULT 'NONE',
  PRIMARY KEY (INTERFACE_ID,APP_ID)
 ) ;
 
 CREATE TABLE TB_ASMI_ROLE_INTF (
  APP_ID varchar(100) NOT NULL,
  ROLE_ID varchar(100) NOT NULL,
  INTERFACE_ID varchar(100) NOT NULL,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (APP_ID,ROLE_ID,INTERFACE_ID)
) ;
CREATE TABLE TB_ASMI_ROLE_MASTER (
  ROLE_ID varchar(255) NOT NULL,
  APP_ID varchar(100) NOT NULL,
  ROLE_DESC varchar(255) DEFAULT NULL,
  INTERFACE_ALLOWED varchar(1) DEFAULT 'A',
  SCREEN_ALLOWED varchar(1) DEFAULT 'A',
  CONTROL_ALLOWED varchar(1) DEFAULT 'A',
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  MAKER_ID VARCHAR(45),
  MAKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CHECKER_ID VARCHAR(45),
  CHECKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  AUTH_STATUS VARCHAR(45) DEFAULT 'U',
  PRIMARY KEY (ROLE_ID,APP_ID) 
) ;

CREATE TABLE TB_ASMI_ROLE_SCR (
  APP_ID varchar(100) NOT NULL,
  SCREEN_ID varchar(100) NOT NULL,
  ROLE_ID varchar(100) NOT NULL,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (APP_ID,ROLE_ID,SCREEN_ID) 
);

CREATE TABLE TB_ASMI_SCR_MASTER (
  SCREEN_ID varchar(255) NOT NULL,
  APP_ID varchar(100) NOT NULL,
  SCREEN_DESC varchar(255) DEFAULT NULL,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  MAKER_ID VARCHAR(45),
  MAKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CHECKER_ID VARCHAR(45),
  CHECKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  AUTH_STATUS VARCHAR(45) DEFAULT 'U',
  SCREEN_TYPE VARCHAR(10) DEFAULT NULL,
  SCREEN_NAME VARCHAR(100) DEFAULT NULL,
  SCREEN_ICON longtext,
  CUSTOMISABLE VARCHAR(1) DEFAULT NULL,
  PRIMARY KEY (SCREEN_ID,APP_ID)
 ) ;
 CREATE TABLE TB_ASMI_USER (
  USER_ID varchar(100) NOT NULL,
  APP_ID varchar(100) NOT NULL,
  PIN varchar(300) DEFAULT NULL,
  USER_NAME varchar(100) DEFAULT NULL,
  LAST_NAME varchar(100) DEFAULT NULL,
  LOGIN_STATUS varchar(3) NOT NULL,
  FAIL_COUNT int DEFAULT NULL,
  USER_ACTIVE varchar(3) DEFAULT 'Y',
  USER_LOCKED varchar(3) DEFAULT 'N',
  LANGUAGE varchar(2) DEFAULT 'en',
  EXTERNALIDENTIFIER varchar(30) DEFAULT NULL,
  USER_ADDR1 varchar(50) DEFAULT NULL,
  USER_ADDR2 varchar(50) DEFAULT NULL,
  USER_ADDR3 varchar(50) DEFAULT NULL,
  USER_ADDR4 varchar(50) DEFAULT NULL,
  USER_EML1 varchar(50) DEFAULT NULL,
  USER_EML2 varchar(50) DEFAULT NULL,
  USER_PHNO1 varchar(20) DEFAULT NULL,
  USER_PHNO2 varchar(20) DEFAULT NULL,
  USER_LVL int DEFAULT NULL,
  USER_LOCK_TS timestamp(0) NULL DEFAULT NULL,
  PIN_CHANGE_TS timestamp(0) NULL DEFAULT NULL,
  PROFILE_PIC clob,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  MAKER_ID VARCHAR(45),
  MAKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CHECKER_ID VARCHAR(45),
  DATE_OF_BIRTH DATE,
  CHECKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  AUTH_STATUS VARCHAR(45) DEFAULT 'U',
  ADD_INFO1 VARCHAR(255),
  ADD_INFO2 VARCHAR(255),
  ADD_INFO3 VARCHAR(255),
  ADD_INFO4 VARCHAR(255),
  ADD_INFO5 VARCHAR(255),
  PRIMARY KEY (USER_ID,APP_ID)
) ;

CREATE TABLE TB_ASMI_USER_DEVICES (
  APP_ID varchar(100) NOT NULL,
  DEVICE_ID varchar(250) NOT NULL,
  USER_ID varchar(100) NOT NULL,
  NOTIF_REG_ID varchar(250) DEFAULT NULL,
  DEVICE_STATUS varchar(100) DEFAULT NULL,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  MAKER_ID VARCHAR(45),
  MAKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CHECKER_ID VARCHAR(45),
  CHECKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  AUTH_STATUS VARCHAR(45) DEFAULT 'U',
  PRIMARY KEY (APP_ID,DEVICE_ID,USER_ID)
 ) ;

CREATE TABLE TB_ASMI_USER_ROLE (
  USER_ID varchar(100) NOT NULL,
  ROLE_ID varchar(100) NOT NULL,
  APP_ID varchar(100) NOT NULL,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (USER_ID,ROLE_ID,APP_ID)
 ) ;
  CREATE TABLE TB_ASMI_SMS_USER(
  APP_ID VARCHAR(100) NOT NULL,
  USER_ID VARCHAR(100) NOT NULL,
  MOBILE_NUMBER VARCHAR(20),
  CREATED_BY VARCHAR(50), 
  CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP, 
  VERSION_NO int DEFAULT 1, 
  SMS_REQ VARCHAR(1),
  USSD_REQ VARCHAR(1),
  CONSTRAINT TB_ASMI_SMS_USER_PK PRIMARY KEY(APP_ID, USER_ID)
);
CREATE TABLE TB_ASTP_LAST_LOGIN (
  USER_ID varchar(100) NOT NULL,
  APP_ID varchar(100) NOT NULL,
  DEVICE_ID varchar(255) NOT NULL,
  REQUEST_KEY varchar(255) DEFAULT NULL,
  SESSION_ID varchar(255) DEFAULT NULL,
  LAST_REQ_TIME timestamp(0) NULL DEFAULT NULL,
  LOGIN_TIME timestamp(0) NULL DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  OTP varchar(200) DEFAULT NULL,
  OTP_GENERATION_TIME timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  OTP_STATUS varchar(1) DEFAULT NULL,
  LONGITUDE VARCHAR(255),
  LATITUDE VARCHAR(255),
  SUBLOCALITY VARCHAR2(255),
  ADMIN_AREA_LVL_1 VARCHAR2(255),
  ADMIN_AREA_LVL_2 VARCHAR2(255),
  COUNTRY VARCHAR2(255),
  FORMATTED_ADDRESS VARCHAR2(255),
  ORIGINATION VARCHAR(255),
  PRIMARY KEY (USER_ID,APP_ID,DEVICE_ID)
 ) ;
 CREATE TABLE TB_ASMI_DEVICE_MASTER(
  APP_ID VARCHAR(100) NOT NULL,
  DEVICE_ID VARCHAR(200) NOT NULL,
  OS VARCHAR(20) NULL,
  OS_VERSION VARCHAR(50) NULL,
  MOBILE_NUMBER1 VARCHAR(20) NULL,
  MOBILE_NUMBER2 VARCHAR(20) NULL,
  MODEL VARCHAR(100) NULL,
  MAKE VARCHAR(100) NULL,
  SCREEN_RESOLUTION VARCHAR(100) NULL,
  WIPED_OUT VARCHAR(1) DEFAULT 'N',
  CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
  DEVICE_NAME VARCHAR(100) NULL,
  LONGITUDE VARCHAR(100) NULL,
  LATITUDE VARCHAR(100) NULL,
  CONSTRAINT TB_ASMI_DEVICE_MASTER_PK PRIMARY KEY (APP_ID, DEVICE_ID)
);
    CREATE TABLE TB_ASLG_AUDIT_LOG
  (
    ACCESS_REF     VARCHAR(255) NOT NULL,
    APP_ID         VARCHAR(100)  NULL,
    USER_ID        VARCHAR(100) NULL,
    DEVICE_ID      VARCHAR(250)  NULL,
    SESSION_ID     VARCHAR(100) NULL,
    ACTION         VARCHAR(30) NULL,
    START_TIME_STAMP VARCHAR(30) NULL,
    END_TIME_STAMP VARCHAR(30) NULL,
    FIELD1         VARCHAR(100) NULL,
    FIELD2         VARCHAR(100) NULL,
    FIELD3         VARCHAR(100) NULL,
    FIELD4         VARCHAR(100) NULL,
    FIELD5         VARCHAR(100) NULL,
    CREATE_DATE DATE DEFAULT null,
    CREATE_USER_ID VARCHAR(100) NULL,
    VERSION_NO int DEFAULT 1,
    CONSTRAINT PK_TB_ASLG_AUDIT_LOG PRIMARY KEY ( ACCESS_REF  )
  );
   CREATE TABLE TB_ASLG_SMS_TXN 
   (           
                SMS_TXNREF VARCHAR(255) NOT NULL,
                APP_ID VARCHAR(100),
                MOBILE_NUMBER VARCHAR(13), 
                REQUEST VARCHAR(4000),
                MESSAGE_ID VARCHAR(20), 
                ORIGINATION VARCHAR(20), 
                START_TM TIMESTAMP(0), 
                RESPONSE VARCHAR(4000),
                END_TM TIMESTAMP(0),
                CREATED_BY VARCHAR(20), 
                CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (SMS_TXNREF) 
   ) ;
   
   CREATE TABLE TB_ASLG_USSD_TXN 
   (           
                USSD_TXNREF VARCHAR(255) NOT NULL,
                APP_ID VARCHAR(100),
                MOBILE_NUMBER VARCHAR(13),
                REQUEST VARCHAR(200), 
                ACTION VARCHAR(3000),
                STEP VARCHAR(100),
                ORIGINATION VARCHAR(20), 
                START_TM TIMESTAMP(0), 
                RESPONSE VARCHAR(200),
                END_TM TIMESTAMP(0),
                CREATED_BY VARCHAR(20), 
                CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (USSD_TXNREF) 
   ) ;
   
  CREATE TABLE TB_ASLG_TXT_MSLG_LOG 
   (           
                TXT_TXNREF VARCHAR(255) NOT NULL, 
                APP_ID VARCHAR(100),
                MOBILE_NUMBER VARCHAR(13),
                REQUEST VARCHAR(1000), 
                PORT VARCHAR(10),
                ORIGINATION VARCHAR(20), 
                START_TM TIMESTAMP(0), 
                RESPONSE VARCHAR(200),
                END_TM TIMESTAMP(0),
                CREATED_BY VARCHAR(20), 
                CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (TXT_TXNREF) 
   ) ;
   
	 CREATE TABLE TB_ASMI_CONTROLS_MASTER (
	   APP_ID varchar(100) NOT NULL,
	   CONTROL_ID varchar(255) NOT NULL,
	   CONTROL_DESC varchar(255) DEFAULT NULL,
	   CREATED_BY varchar(100) DEFAULT NULL,
	   CREATED_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
	   MAKER_ID VARCHAR(45),
	   MAKER_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
	   CHECKER_ID VARCHAR(45),
	   CHECKER_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
	   AUTH_STATUS VARCHAR(45) DEFAULT 'U',
	   VERSION_NO int DEFAULT 1,
	   PRIMARY KEY (APP_ID,CONTROL_ID)
	  ) ;
	  CREATE TABLE TB_ASMI_ROLE_CONTROLS (
	   APP_ID varchar(100) NOT NULL,
	   ROLE_ID varchar(100) NOT NULL,
	   CONTROL_ID varchar(100) NOT NULL,
	   CREATED_BY varchar(100) DEFAULT NULL,
	   CREATED_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
	   VERSION_NO int DEFAULT 1,
	   PRIMARY KEY (APP_ID,ROLE_ID,CONTROL_ID)
	) ;
	CREATE TABLE TB_ASLG_JMS_REQ_RESP (
  TRANS_ID int NOT NULL,
  INTERFACE_ID varchar(150) NOT NULL,
  APP_ID varchar(100) NOT NULL,
  REQ_TYPE varchar(150) NOT NULL,
  RES_TYPE varchar(150) NOT NULL,
  SENT_DATE timestamp NOT NULL,
  RECEIVED_DATE timestamp DEFAULT NULL,
  MSG_ID varchar(250) NOT NULL,
  REQ_Q varchar(250) DEFAULT NULL,
  RESP_Q varchar(250) DEFAULT NULL,
  MSG_STATUS int NOT NULL,
  MSG_SENT clob NOT NULL,
  MSG_RECEIVED clob,
  RESP_DESC varchar(250) DEFAULT NULL,
  PRIMARY KEY (TRANS_ID),
  CONSTRAINT TB_ASLG_JMS_REQ_RESP_LOG_UK1 UNIQUE  (MSG_ID)
) ;
CREATE TABLE TB_ASHS_SECURITY_PARAMETERS (
  APP_ID varchar(100) NOT NULL,
  MIN_NUM_NUM int DEFAULT NULL,
  MIN_NUM_SPCL_CHAR int DEFAULT NULL,
  MIN_NUM_UPPER_CASE_CHAR int DEFAULT NULL,
  MIN_NUM_LOWER_CASE_CHAR int DEFAULT NULL,
  MIN_LENGTH int DEFAULT NULL,
  MAX_LENGTH int DEFAULT NULL,
  PASS_CHANGE_FREQ int DEFAULT NULL,
  LAST_N_PASS_NOT_TO_USE int DEFAULT NULL,
  SESSION_TIMEOUT int DEFAULT NULL,
  NOOFFAILEDCOUNTS int DEFAULT NULL,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  SERVER_TOKEN varchar(255) DEFAULT NULL,
  FAIL_COUNT_TIMEOUT int DEFAULT NULL,
  PASSWORD_COUNT int DEFAULT NULL,
  DEFAULT_AUTHORIZATION char(1) DEFAULT 'Y',
  RESTRICT_SPL_CHARS varchar(100) DEFAULT NULL,
  MULTIPLE_SESSION_ALLOWED varchar(1) DEFAULT 'Y',
  /*
   * Below Fields Added by ripu
   * Appzillon - 3.1 - 65, 69 Start (for User creation extensibility and multifactor)
   */
  ALLOW_USER_PASSWORD_ENTRY VARCHAR(1) DEFAULT 'N',
  AUTO_APPROVE VARCHAR(1) DEFAULT 'Y',
  PWD_RSET_VALIDATE_PARAMS VARCHAR(45) DEFAULT 'BOTH',
  PWD_RSET_COMM_CHANNEL VARCHAR(45) DEFAULT 'BOTH',
  PWD_RSET_ACCEPT_USR_PWD VARCHAR(1) DEFAULT 'N',
  TXN_LOG_REQ VARCHAR(45) DEFAULT 'Y',
  MAKER_ID VARCHAR(45),
  MAKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CHECKER_ID VARCHAR(45),
  CHECKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  PWD_COMM_CHANNEL VARCHAR(45) DEFAULT 'BOTH',
  AUTH_STATUS VARCHAR(45) DEFAULT 'U',
  TXN_LOG_PAYLOAD VARCHAR(1) DEFAULT 'Y',
  /* Appzillon - 3.1 - 65, 69 End*/
  OTP_LENGTH int DEFAULT NULL,
   OTP_VALIDATION_COUNT int DEFAULT NULL,
   OTP_EXPIRY int DEFAULT NULL,
   OTP_RESEND varchar(10) DEFAULT NULL,
   OTP_FORMAT varchar(20) DEFAULT NULL,
   OTP_RESEND_COUNT int DEFAULT NULL,
   OTP_RESEND_LOCK_TIMEOUT int DEFAULT NULL ,
   PWD_CHANGE_COMM_CHANNEL varchar(30) DEFAULT 'BOTH',
   PASSWORD_ON_AUTHORIZATION VARCHAR(1) DEFAULT 'N',
  PRIMARY KEY (APP_ID,VERSION_NO)
);
CREATE TABLE TB_ASHS_USER (
  USER_ID varchar(100) NOT NULL,
  APP_ID varchar(100) NOT NULL,
  PIN varchar(300) DEFAULT NULL,
  USER_NAME varchar(100) DEFAULT NULL,
  LAST_NAME varchar(100) DEFAULT NULL,
  LOGIN_STATUS varchar(3) NOT NULL,
  FAIL_COUNT int DEFAULT NULL,
  USER_ACTIVE varchar(3) DEFAULT 'Y',
  USER_LOCKED varchar(3) DEFAULT 'N',
  LANGUAGE varchar(2) DEFAULT 'en',
  EXTERNALIDENTIFIER varchar(30) DEFAULT NULL,
  USER_ADDR1 varchar(50) DEFAULT NULL,
  USER_ADDR2 varchar(50) DEFAULT NULL,
  USER_ADDR3 varchar(50) DEFAULT NULL,
  USER_ADDR4 varchar(50) DEFAULT NULL,
  USER_EML1 varchar(50) DEFAULT NULL,
  USER_EML2 varchar(50) DEFAULT NULL,
  USER_PHNO1 varchar(20) DEFAULT NULL,
  USER_PHNO2 varchar(20) DEFAULT NULL,
  USER_LVL int DEFAULT NULL,
  USER_LOCK_TS timestamp(0) NULL DEFAULT NULL,
  PIN_CHANGE_TS timestamp(0) NULL DEFAULT NULL,
  PROFILE_PIC clob,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  MAKER_ID VARCHAR(45),
  MAKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CHECKER_ID VARCHAR(45),
  DATE_OF_BIRTH DATE,
  CHECKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  AUTH_STATUS VARCHAR(45) DEFAULT 'U',
  ADD_INFO1 VARCHAR(255),
  ADD_INFO2 VARCHAR(255),
  ADD_INFO3 VARCHAR(255),
  ADD_INFO4 VARCHAR(255),
  ADD_INFO5 VARCHAR(255),
  PRIMARY KEY (USER_ID,APP_ID,VERSION_NO)
) ;

CREATE TABLE TB_ASHS_USER_DEVICES (
  APP_ID varchar(100) NOT NULL,
  DEVICE_ID varchar(250) NOT NULL,
  USER_ID varchar(100) NOT NULL,
  DEVICE_STATUS varchar(100) DEFAULT NULL,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  MAKER_ID VARCHAR(45),
  MAKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CHECKER_ID VARCHAR(45),
  CHECKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  AUTH_STATUS VARCHAR(45) DEFAULT 'U',
  PRIMARY KEY (APP_ID,DEVICE_ID,USER_ID,VERSION_NO)
 ) ;

CREATE TABLE TB_ASHS_USER_ROLE (
  USER_ID varchar(100) NOT NULL,
  ROLE_ID varchar(100) NOT NULL,
  APP_ID varchar(100) NOT NULL,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (USER_ID,ROLE_ID,APP_ID,VERSION_NO)
 ) ;
  CREATE TABLE TB_ASHS_SMS_USER(
  APP_ID VARCHAR(100) NOT NULL,
  MOBILE_NUMBER VARCHAR(20),
  USER_ID VARCHAR(100) NOT NULL,
  CREATED_BY VARCHAR(50), 
  CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP, 
  VERSION_NO int DEFAULT 1, 
  SMS_REQ VARCHAR(1),
  USSD_REQ VARCHAR(1),
  CONSTRAINT TB_ASHS_SMS_USER_PK PRIMARY KEY(APP_ID, USER_ID,VERSION_NO)
);
  CREATE TABLE TB_ASHS_ROLE_INTF (
  APP_ID varchar(100) NOT NULL,
  ROLE_ID varchar(100) NOT NULL,
  INTERFACE_ID varchar(100) NOT NULL,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (APP_ID,ROLE_ID,INTERFACE_ID,VERSION_NO)
) ;
CREATE TABLE TB_ASHS_ROLE_MASTER (
  ROLE_ID varchar(255) NOT NULL,
  APP_ID varchar(100) NOT NULL,
  ROLE_DESC varchar(255) DEFAULT NULL,
  INTERFACE_ALLOWED varchar(1) DEFAULT 'A',
  SCREEN_ALLOWED varchar(1) DEFAULT 'A',
  CONTROL_ALLOWED varchar(1) DEFAULT 'A',
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  MAKER_ID VARCHAR(45),
  MAKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CHECKER_ID VARCHAR(45),
  CHECKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  AUTH_STATUS VARCHAR(45) DEFAULT 'U',
  PRIMARY KEY (ROLE_ID,APP_ID,VERSION_NO) 
) ;

CREATE TABLE TB_ASHS_ROLE_SCR (
  APP_ID varchar(100) NOT NULL,
  SCREEN_ID varchar(100) NOT NULL,
  ROLE_ID varchar(100) NOT NULL,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (APP_ID,ROLE_ID,SCREEN_ID,VERSION_NO) 
);
 CREATE TABLE TB_ASHS_ROLE_CONTROLS (
	   APP_ID varchar(100) NOT NULL,
	   ROLE_ID varchar(100) NOT NULL,
	   CONTROL_ID varchar(100) NOT NULL,
	   CREATED_BY varchar(100) DEFAULT NULL,
	   CREATED_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
	   VERSION_NO int DEFAULT 1,
	   PRIMARY KEY (APP_ID,ROLE_ID,CONTROL_ID,VERSION_NO)
	) ;

CREATE TABLE TB_ASMI_USER_APP_ACCESS (
  APP_ID VARCHAR(100) NOT NULL,
  USER_ID VARCHAR(100) NOT NULL,
  ALLOWED_APP_ID VARCHAR(100) NOT NULL,
  APP_ACCESS VARCHAR(1) DEFAULT 'D',
  CREATE_USER_ID VARCHAR(100) DEFAULT NULL,
  CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO INT(10) DEFAULT 1,
  CONSTRAINT TB_ASMI_USER_APP_ACCESS_PK PRIMARY KEY (APP_ID, USER_ID, ALLOWED_APP_ID)
 ) ;
 CREATE TABLE TB_ASHS_USER_APP_ACCESS (
  APP_ID VARCHAR(100) NOT NULL,
  USER_ID VARCHAR(100) NOT NULL,
  ALLOWED_APP_ID VARCHAR(100) NOT NULL,
  APP_ACCESS VARCHAR(1) DEFAULT 'D',
  CREATE_USER_ID VARCHAR(100) DEFAULT NULL,
  CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO INT(10) DEFAULT 1,
  CONSTRAINT TB_ASHS_USER_APP_ACCESS_PK PRIMARY KEY (APP_ID, USER_ID, ALLOWED_APP_ID, VERSION_NO)
 ) ;

 
 CREATE TABLE TB_ASMI_APP_MASTER 
   (  
  APP_ID VARCHAR(100) NOT NULL,
  PARENT_APPID VARCHAR(100) NULL,
  APP_NAME VARCHAR(100) NOT NULL,
  CONTAINER_APP VARCHAR(1),
  OTA_REQ VARCHAR(1),
  REMOTE_DEBUG VARCHAR(1), 
  EXPIRY_DATE TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
  APP_DESCRIPTION VARCHAR(200),
  DEFAULT_LANGUAGE VARCHAR(20),
  CREATE_USER_ID VARCHAR(20), 
  CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP, 
  VERSION_NO int DEFAULT 1,
  BASE_APP VARCHAR(1),
  MICRO_APP_TYPE VARCHAR(10),
  PRIMARY_MICRO_APP VARCHAR(1) DEFAULT 'N',
  APP_ICON longtext,
  APP_VERSION VARCHAR(20) NOT NULL,
  IDE_VERSION VARCHAR(20) NOT NULL,
  MAKER_ID VARCHAR(45),
  MAKER_TS TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  CHECKER_ID VARCHAR(45),
  CHECKER_TS TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  AUTH_STATUS VARCHAR(45) DEFAULT 'U',
  CONSTRAINT TB_ASMI_APP_MASTER_PK PRIMARY KEY (APP_ID)
   ) ;
   
  CREATE TABLE TB_ASNF_APP_OS_NOTIF_CODE(
  	APP_ID VARCHAR(100) NOT NULL, 
	OS_ID VARCHAR(45), 
	NOTIF_CODE VARCHAR(255),
	ACTION_CODE VARCHAR(255),
    ACTION_DISPLAY VARCHAR(255),
   	CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT TB_ASNF_APP_OS_NOTIF_CODE_PK PRIMARY KEY (APP_ID, OS_ID, NOTIF_CODE, ACTION_CODE)
    );
CREATE TABLE TB_ASMI_DEVICE_GRPS (
  APP_ID VARCHAR(100) NOT NULL,
  DEVICE_GROUP_ID VARCHAR(100) NOT NULL,
  DEVICE_GROUP_DESCRIPTION VARCHAR(1000) NOT NULL,
  OS VARCHAR(10) NOT NULL,
  HEIGHT int NOT NULL,
  WIDTH int NOT NULL,
  ORIENTATION_LOCK VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (APP_ID,DEVICE_GROUP_ID)
) ;


CREATE TABLE TB_ASMI_SCREEN_LAYOUTS (
  APP_ID VARCHAR(6) NOT NULL,
  SCREEN_ID VARCHAR(100) NOT NULL,
  LAYOUT_ID VARCHAR(100) NOT NULL,
  LAYOUT_NAME VARCHAR(100) NOT NULL,
  LAYOUT_ICON clob,
  DEFAULT_TEMPLATE VARCHAR(100) NOT NULL,
  PRIMARY KEY (APP_ID,SCREEN_ID,LAYOUT_ID)
) ;

CREATE TABLE TB_ASMI_SCREEN_MICRO_APP (
  APP_ID VARCHAR(6) NOT NULL,
  SCREEN_ID VARCHAR(100) NOT NULL,
  MICRO_APP_ID VARCHAR(6) NOT NULL,
  CREATE_TS TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (APP_ID,SCREEN_ID,MICRO_APP_ID)
) ;

CREATE TABLE TB_ASMI_SCREEN_WIDGETS (
  APP_ID VARCHAR(100) NOT NULL,
  SCREEN_ID VARCHAR(100) NOT NULL,
  CALLFORM_ID VARCHAR(100) NOT NULL,
  CREATE_TS TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (APP_ID,SCREEN_ID,CALLFORM_ID)
) ;


CREATE TABLE TB_ASMI_DESIGN_OBJECTS (
  APP_ID VARCHAR(100) NOT NULL,
  SCREEN_ID VARCHAR(100) NOT NULL,
  LAYOUT_ID VARCHAR(100) NOT NULL,
  DESIGN_ID VARCHAR(100) NOT NULL,
  PARENT_ID VARCHAR(100) NOT NULL,
  CHILD_ID VARCHAR(100) NOT NULL,
  CHILD_SEQ int NOT NULL,
  PRIMARY KEY (APP_ID,SCREEN_ID,LAYOUT_ID,DESIGN_ID,PARENT_ID,CHILD_ID)
) ;


CREATE TABLE TB_ASCZ_SCREEN_LAYOUTS (
  APP_ID varchar(6) NOT NULL,
  SCREEN_ID VARCHAR(100) NOT NULL,
  LAYOUT_ID VARCHAR(100) NOT NULL,
  DEFAULT_TEMPLATE VARCHAR(100) NOT NULL,
  CREATE_TS TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  MAKER_ID VARCHAR(45),
  MAKER_TS TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  CHECKER_ID VARCHAR(45),
  CHECKER_TS TIMESTAMP(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
  AUTH_STATUS VARCHAR(1) DEFAULT 'U',
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (APP_ID,SCREEN_ID,LAYOUT_ID)
) ;

CREATE TABLE TB_ASCZ_TEMPLATE_OBJECTS (
  APP_ID VARCHAR(6) NOT NULL,
  SCREEN_ID VARCHAR(100) NOT NULL,
  LAYOUT_ID VARCHAR(100) NOT NULL,
  TEMPLATE_ID VARCHAR(100) NOT NULL,
  PARENT_ID VARCHAR(100) NOT NULL,
  CHILD_ID VARCHAR(100) NOT NULL,
  CHILD_SEQ int NOT NULL,
  PRIMARY KEY (APP_ID,SCREEN_ID,LAYOUT_ID,TEMPLATE_ID,PARENT_ID,CHILD_ID)
) ;



CREATE TABLE TB_ASTP_SESSION_STORAGE(
APP_ID VARCHAR(100) NOT NULL,
USER_ID VARCHAR(100) NOT NULL,
SESSION_ID VARCHAR(255) NOT NULL,
DEVICE_ID VARCHAR(255) NULL,
SESSION_KEY VARCHAR(255) NOT NULL,
SESSION_VALUE longtext NOT NULL,
CREATED_BY VARCHAR(100) NULL,
CREATE_TS timestamp(3) DEFAULT CURRENT_TIMESTAMP(3),
PRIMARY KEY (APP_ID, USER_ID, SESSION_ID, SESSION_KEY)
);

CREATE TABLE TB_ASMI_CAPTCHA_DTLS (
  CAPTCHA_REF int NOT NULL,
  APP_ID varchar(100) ,
  CAPTCHA_STRING varchar(255),
  AUDIO_CAPTCHA varchar(255),
  INTERFACE_ID varchar(100) ,
  SESSION_ID varchar(255),
  CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP,
  VALIDATE_TS TIMESTAMP(3),
  CAPTCHA_STATUS varchar(2) DEFAULT 'NP',
  VERSION_NO int(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (CAPTCHA_REF)
);

CREATE OR REPLACE VIEW VW_ASMI_DEVICE_GRPS AS
SELECT APP_ID, DEVICE_GROUP_ID, DEVICE_GROUP_DESCRIPTION, OS,HEIGHT, WIDTH, 'PORTRAIT' AS ORIENTATION
FROM TB_ASMI_DEVICE_GRPS WHERE ORIENTATION_LOCK = 'ANY'
UNION ALL
SELECT APP_ID, DEVICE_GROUP_ID, DEVICE_GROUP_DESCRIPTION, OS,HEIGHT, WIDTH, 'LANDSCAPE' AS ORIENTATION
FROM TB_ASMI_DEVICE_GRPS WHERE ORIENTATION_LOCK = 'ANY'
UNION ALL
SELECT APP_ID, DEVICE_GROUP_ID, DEVICE_GROUP_DESCRIPTION, OS,HEIGHT, WIDTH, ORIENTATION_LOCK AS ORIENTATION
FROM TB_ASMI_DEVICE_GRPS WHERE ORIENTATION_LOCK != 'ANY';


CREATE OR REPLACE VIEW VW_ASMI_MICROAPPS AS
SELECT T2.APP_ID AS APP_ID, T2.SCREEN_ID, T2.MICRO_APP_ID AS MICRO_APP_ID, T1.APP_NAME AS MICRO_APP_NAME, T1.APP_ICON AS MICRO_APP_ICON,
T1.MICRO_APP_TYPE AS MICRO_APP_TYPE FROM TB_ASMI_APP_MASTER T1, TB_ASMI_SCREEN_MICRO_APP T2
WHERE T1.APP_ID = T2.MICRO_APP_ID AND T1.BASE_APP = 'N';

--Where AND T1.MICRO_APP_TYPE = 'EXT' or 'NAV';


CREATE OR REPLACE VIEW VW_ASMI_NANOAPPS AS
SELECT T1.APP_ID, T2.SCREEN_ID, T1.SCREEN_ID AS CALLFORM_ID, T1.SCREEN_NAME AS CALLFORM_NAME, T1.SCREEN_ICON AS CALLFORM_ICON
FROM TB_ASMI_SCR_MASTER T1, TB_ASMI_SCREEN_WIDGETS T2
WHERE T1.APP_ID = T2.APP_ID AND T1.SCREEN_ID = T2.CALLFORM_ID AND T1.SCREEN_TYPE = 'CALL'
