DROP TABLE TB_ASMI_LOV_QUERIES;
DROP TABLE TB_ASMI_OS_DTLS;
DROP TABLE TB_ASNF_DEVICES_MASTER;
DROP TABLE TB_ASNF_GROUP_DEVICES;
DROP TABLE TB_ASNF_GROUP_MASTER;
DROP TABLE TB_ASNF_TXN_DEVICES;
DROP TABLE TB_ASNF_TXN_GROUPS;
DROP TABLE TB_ASNF_TXN_LOG;
DROP TABLE TB_ASNF_TXN_MASTER;
DROP TABLE TB_ASTP_SEQ_GEN;
DROP TABLE TB_ASTP_WORKFLOW_DET;
DROP TABLE TB_ASMI_APP_DTLS;
DROP TABLE TB_ASFS_FILE_DETAILS;
DROP TABLE TB_ASMI_APP_USER;
DROP TABLE TB_ASMI_APP_FILES;
DROP TABLE TB_ASMI_APP_OS_VERSION;
DROP TABLE TB_ASHS_WORKFLOW_DET;
DROP TABLE TB_ASTP_BEACON_MASTER;
DROP TABLE TB_ASTP_OTP_ENGINE;
DROP TABLE TB_ASTP_AR_MASTER;
DROP TABLE TB_ASMI_SCHEDULER_JOB_EXP;
DROP TABLE TB_ASMI_SCHEDULER_JOB;




CREATE TABLE TB_ASHS_USER_PASSWORDS (
  USER_ID varchar(100) NOT NULL,
  APP_ID varchar(100) NOT NULL,
  PIN varchar(255) NOT NULL,
  CHANGE_TIME timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CREATE_USER_ID varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (USER_ID,APP_ID,PIN)
 ) ;




CREATE TABLE TB_ASMI_LOV_QUERIES (
  APP_ID varchar(100) NOT NULL,
  QUERY_ID varchar(100) NOT NULL,
  QUERY_STRING varchar(1000) NOT NULL,
  DB_JNDI_NAME varchar(50) NOT NULL,
  QUERY_TYPE varchar(3) DEFAULT 'SQL',
  BINDVAR_COLS varchar(300) DEFAULT NULL,
  BINDVAR_DATA_TYPES varchar(300) DEFAULT NULL,
  FILTER_COLS varchar(300) DEFAULT NULL,
  ORDERBY_COL varchar(40) DEFAULT NULL,
  ORDERBY_TYPE varchar(5) DEFAULT 'ASC',
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CREATE_BY varchar(50) DEFAULT NULL,
  SESSION_REQD varchar(1) DEFAULT NULL,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (APP_ID,QUERY_ID) 
) ;

CREATE TABLE TB_ASMI_OS_DTLS (
  OS_ID varchar(50) NOT NULL,
  OS_DESC varchar(200) DEFAULT NULL,
  CREATE_BY varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (OS_ID)
 );

CREATE TABLE TB_ASNF_DEVICES_MASTER (
  APP_ID varchar(100) NOT NULL,
  NOTIF_REG_ID varchar(255) NOT NULL,
  DEVICE_ID varchar(255) DEFAULT NULL,
  DEVICE_NAME varchar(255) DEFAULT NULL,
  OS_ID varchar(50) DEFAULT NULL,
  OS_VERSION varchar(255) DEFAULT NULL,
  STATUS varchar(20) DEFAULT NULL,
  CREATED_BY varchar(255) DEFAULT NULL,
  CREATED_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  MAKER_ID VARCHAR(45),
  MAKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  CHECKER_ID VARCHAR(45),
  CHECKER_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  AUTH_STATUS VARCHAR(45) DEFAULT 'U',
  PRIMARY KEY (APP_ID,NOTIF_REG_ID)
);

CREATE TABLE TB_ASNF_GROUP_DEVICES (
  APP_ID varchar(100) NOT NULL,
  GROUP_ID varchar(255) NOT NULL,
  NOTIF_REG_ID varchar(255) NOT NULL,
  CREATED_BY varchar(255) DEFAULT NULL,
  CREATED_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (APP_ID,GROUP_ID,NOTIF_REG_ID)
) ;

CREATE TABLE TB_ASNF_GROUP_MASTER (
  APP_ID varchar(100) NOT NULL,
  GROUP_ID varchar(255) NOT NULL,
  GROUP_DESC varchar(500) DEFAULT NULL,
  CREATED_BY varchar(50) DEFAULT NULL,
  CREATED_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (APP_ID,GROUP_ID)
) ;

CREATE TABLE TB_ASNF_TXN_DEVICES (
  NOTIF_ID int NOT NULL,
  APP_ID varchar(100) NOT NULL,
  NOTIF_REG_ID varchar(255) NOT NULL,
  PRIMARY KEY (NOTIF_ID,APP_ID,NOTIF_REG_ID)
);

CREATE TABLE TB_ASNF_TXN_GROUPS (
  NOTIF_ID int NOT NULL,
  APP_ID varchar(100) NOT NULL,
  GROUP_ID varchar(255) NOT NULL,
   PRIMARY KEY (NOTIF_ID,APP_ID,GROUP_ID)
) ;

CREATE TABLE TB_ASNF_TXN_LOG (
  NOTIF_ID int NOT NULL,
  APP_ID varchar(100) NOT NULL,
  NOTIF_REG_ID varchar(255) NOT NULL,
  DEVICE_ID varchar(255) NOT NULL,
  STATUS char(150) DEFAULT NULL,
  CREATED_BY varchar(150) DEFAULT NULL,
  CREATED_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
   PRIMARY KEY (NOTIF_ID,APP_ID,NOTIF_REG_ID,DEVICE_ID)
) ;

CREATE TABLE TB_ASNF_TXN_MASTER (
  NOTIF_ID int NOT NULL,
  APP_ID varchar(100) NOT NULL,
  NOTIF_MSG varchar(255) NOT NULL,
  PRIMARY KEY (NOTIF_ID,APP_ID,NOTIF_MSG)
) ;

CREATE TABLE TB_ASTP_SEQ_GEN (
  SEQUENCE_NAME varchar(50) NOT NULL,
  SEQUENCE_VALUE int NOT NULL,
  CREATE_BY varchar(20) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (SEQUENCE_NAME)
 );
 

 
 CREATE TABLE TB_ASTP_WORKFLOW_DET
  (
    TRANSACTION_REF_NO VARCHAR(30) NOT NULL ,
    VERSION_NO DECIMAL(10, 0) NULL, 
   WORKFLOW_ID        VARCHAR(100) NOT NULL ,
   APP_ID             VARCHAR(100) NOT NULL ,
   CURRENT_STAGE       VARCHAR(100) NULL ,
    SCREEN_ID          VARCHAR(100) NULL ,
    NEXT_STAGE         VARCHAR(100) NULL ,
    STATUS             VARCHAR(20) NULL ,
    INTERFACE_ID        VARCHAR(100) NULL ,
   USER_ID             VARCHAR(100) NULL ,
    SCREEN_DATA clob NULL ,
    STAGE_SEQ_NO   VARCHAR(255 ) NULL ,
    ACTION         VARCHAR(255 ) NULL ,
    CREATE_USER_ID VARCHAR(100 ) NULL ,
    CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP ,
    CONSTRAINT TB_ASTP_WORKFLOW_DET_PK PRIMARY KEY (TRANSACTION_REF_NO, WORKFLOW_ID, APP_ID)
  );

CREATE TABLE TB_ASMI_APP_DTLS (
  APP_ID varchar(100) NOT NULL,
  OS_ID varchar(50) NOT NULL,
  APP_DESC varchar(200) DEFAULT NULL,
  CREATE_BY varchar(100) DEFAULT NULL,
  CREATE_TS timestamp(0) DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  CONSTRAINT TB_ASMI_APP_DTLS_PK PRIMARY KEY (APP_ID,OS_ID)
) ;

CREATE TABLE TB_ASFS_FILE_DETAILS 
( 
  APP_ID VARCHAR(100) NOT NULL 
, SCREEN_ID VARCHAR(100) NULL 
, USER_ID VARCHAR(100)  NULL 
, FILE_NAME VARCHAR(150)  NOT NULL  
, FILE_TYPE VARCHAR(20) NULL 
, INTERFACE_ID VARCHAR(30) NULL
, CREATE_USER_ID VARCHAR(100) NULL 
, LAST_UPLOADED_DATE TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP 
, RECENT_UPLOADED_DATE TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP
, PRIMARY KEY (APP_ID,FILE_NAME)
);



/*
 * Changes made by Ripu
 * Below table added for FS item : Appzillon - 3.1 - 13, 15, 65 Start
 */


/* Appzillon - 3.1 - 13, 15, 65 END */

/*
 * Changes made by Ripu
 * Below tables added for (OTA) FS item : Appzillon - 3.1 - 13 Start
 */

  CREATE TABLE TB_ASMI_APP_USER
   (   
  USER_ID VARCHAR(50) NOT NULL, 
    PARENT_APP_ID VARCHAR(100) NOT NULL,
  CHILD_APP_ID VARCHAR(100) NOT NULL, 
  CREATE_USER_ID VARCHAR(50), 
  CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP, 
  VERSION_NO int DEFAULT 1, 
   CONSTRAINT TB_ASMI_APP_USER_PK PRIMARY KEY (USER_ID, PARENT_APP_ID, CHILD_APP_ID)
    ) ;
    
    
  CREATE TABLE TB_ASMI_APP_FILES 
   (  
  APP_ID VARCHAR(100) NOT NULL, 
  APP_VERSION VARCHAR(10) NOT NULL,
    OS VARCHAR(20) NOT NULL,
    FILE_NAME VARCHAR(100) NOT NULL,
  FILE_PATH VARCHAR(255), 
  ACTION VARCHAR(10),
  CREATE_USER_ID VARCHAR(100), 
  CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP, 
  VERSION_NO int DEFAULT 1,
  CONSTRAINT TB_ASMI_APP_FILES_PK PRIMARY KEY (APP_ID, APP_VERSION, OS, FILE_NAME)
   ) ;
   

  CREATE TABLE TB_ASMI_APP_OS_VERSION
   (   
    APP_ID VARCHAR(100) NOT NULL, 
    OS VARCHAR(20) NOT NULL,
    APP_VERSION VARCHAR(10) NOT NULL, 
    CREATE_USER_ID VARCHAR(50), 
    CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP, 
    VERSION_NO int DEFAULT 1, 
    CONSTRAINT TB_ASMI_APP_OS_VERSION_PK PRIMARY KEY (APP_ID, OS, APP_VERSION)
    ) ;
    
 /* Appzillon - 3.1 - 13 END */
   
/* 
    * Changes Made By Ripu
    * Appzillon - 3.1 - Audit Log Start
    */
   

  /* Appzillon - 3.1 - Audit Log End */
  
  /*
   * Changes done by Ripu on (10-Feb-2015)
   * Appzillon - 3.1 - Send SMS to User Start
   */
  

/* Appzillon - 3.1 - Send SMS to user End*/

/*
 * Changes done by Ripu
 * Appzillon - 3.1 - Task Repair Start
 */
/*CREATE TABLE `TB_AFHS_WORKFLOW_DET`
  (
    `TRANSACTION_REF_NO` VARCHAR(30) NOT NULL ,
    `VERSION_NO`         DECIMAL(10, 0) NOT NULL,
   `WORKFLOW_ID`        VARCHAR(100) NOT NULL ,
   `CURRENT_STAGE`       VARCHAR(100) NOT NULL ,
    `SCREEN_ID`          VARCHAR(100) NOT NULL ,
    `NEXT_STAGE`         VARCHAR(100) NULL ,
    `STATUS`             VARCHAR(20) NULL ,
    `APP_ID`             VARCHAR(100) NOT NULL ,
    `INTERFACE_ID`        VARCHAR(100) NOT NULL ,
   `USER_ID`             VARCHAR(100) NULL ,
    `SCREEN_DATA` longtext NULL ,
    `STAGE_SEQ_NO`   VARCHAR(255) NULL ,
    `ACTION`         VARCHAR(255) NULL ,
    `CREATE_USER_ID` VARCHAR(100) NULL ,
    `CREATE_TS` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    `HISTORY_VERSION_NO` INT(11) NOT NULL,
    CONSTRAINT `TB_AFHS_WORKFLOW_DET_PK` PRIMARY KEY (`TRANSACTION_REF_NO`, `VERSION_NO`, `WORKFLOW_ID`, `CURRENT_STAGE`,`SCREEN_ID` ,`APP_ID` ,`INTERFACE_ID`,`HISTORY_VERSION_NO` )
  );*/

CREATE TABLE TB_ASHS_WORKFLOW_DET
  (
    TRANSACTION_REF_NO VARCHAR(30) NOT NULL ,
    VERSION_NO         INT NOT NULL,
   WORKFLOW_ID        VARCHAR(100) NOT NULL ,
   APP_ID             VARCHAR(100) NOT NULL ,
   CURRENT_STAGE       VARCHAR(100) NULL ,
    SCREEN_ID          VARCHAR(100) NULL ,
    NEXT_STAGE         VARCHAR(100) NULL ,
    STATUS             VARCHAR(20) NULL ,
    INTERFACE_ID        VARCHAR(100) NULL ,
   USER_ID             VARCHAR(100) NULL ,
    SCREEN_DATA clob NULL ,
    STAGE_SEQ_NO   VARCHAR(255) NULL ,
    ACTION         VARCHAR(255) NULL ,
    CREATE_USER_ID VARCHAR(100) NULL ,
    CREATE_TS TIMESTAMP(0) DEFAULT CURRENT_TIMESTAMP ,
    CONSTRAINT TB_ASHS_WORKFLOW_DET_PK PRIMARY KEY (TRANSACTION_REF_NO, VERSION_NO, WORKFLOW_ID, APP_ID)
  );
  /* Appzillon - 3.1 - Task Repair End*/
  

CREATE TABLE TB_ASTP_BEACON_MASTER (
  APP_ID varchar(100) DEFAULT NULL,
  ID int NOT NULL,
  DEVICE_ID varchar(225) DEFAULT NULL,
  USER_ID varchar(100) DEFAULT NULL,
  ENTRY_TIME timestamp(0) NULL DEFAULT NULL,
  STATUS varchar(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE TB_ASTP_OTP_ENGINE 
   (  
    REF_NO int NOT NULL, 
  APP_ID varchar(100), 
  USER_ID varchar(255), 
  INTERFACE_ID varchar(255), 
  SESSION_ID varchar(255), 
  OTP varchar(255), 
  OTP_GEN_TS timestamp(0),
  OTP_EXP_TS timestamp(0),
  OTP_STATUS varchar(255) DEFAULT 'N', 
  OTP_VAL_TS timestamp(0),
  REQ_LD_REFNO varchar(100), 
  REQ_NO_RECS int, 
  REQ_PAYLOAD_STATUS varchar(200), 
  REQ_PAYLOAD_PROCESS_TS timestamp(0), 
  OTP_VALIDATION_COUNT int,
  OTP_RESENT_COUNT int,
  OTP_RESEND_LOCK varchar(1),
  OTP_RESEND_LOCK_TS timestamp(0),
  OTP_REGEN_COUNT int DEFAULT 0,
  VERSION_NO int NOT NULL DEFAULT 0,
  CONSTRAINT TB_ASTP_OTP_ENGINE_PK PRIMARY KEY (REF_NO)
);

CREATE TABLE TB_ASTP_AR_MASTER (
APP_ID varchar(255) DEFAULT NULL,
ID int NOT NULL,
REGION_CODE varchar(255) DEFAULT NULL,
CATEGORY varchar(255) DEFAULT NULL,
LATITUDE varchar(255) DEFAULT NULL,
LONGITUDE varchar(255) DEFAULT NULL,
TITLE  varchar(255) DEFAULT NULL,
ADDITIONAL_INFO varchar(255) DEFAULT NULL,
DESCRIPTION varchar(255) DEFAULT NULL,
IMAGE varchar(255) DEFAULT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE TB_ASMI_SCHEDULER_JOB_EXP (
  JOB_NAME varchar(45) NOT NULL,
  START_DATE varchar(45) DEFAULT NULL,
  END_DATE varchar(45) DEFAULT NULL,
  EXP_START_SEC varchar(45) DEFAULT NULL,
  EXP_SEC varchar(45) DEFAULT NULL,
  EXP_MIN varchar(45) DEFAULT NULL,
  EXP_HR varchar(45) DEFAULT NULL,
  EXP_DOM varchar(45) DEFAULT NULL,
  EXP_MONTH varchar(45) DEFAULT NULL,
  EXP_DOW varchar(45) DEFAULT NULL,
  EXP_YEAR varchar(45) DEFAULT NULL,
  EXPRESSION varchar(45) DEFAULT NULL,
  PRIMARY KEY (JOB_NAME)
);

CREATE TABLE TB_ASMI_SCHEDULER_JOB (
  APP_ID varchar(45) DEFAULT NULL,
  JOB_NAME varchar(45) NOT NULL,
  JOB_CLASS varchar(45) DEFAULT NULL,
  JOB_DATA varchar(255) DEFAULT NULL,
  JOB_STATUS varchar(45) DEFAULT 'P',
  JOB_CREATED_TS timestamp(0) NULL DEFAULT NULL,
  JOB_EXECUTED_TS timestamp(0) NULL DEFAULT NULL,
  PRIMARY KEY (JOB_NAME)
);


  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('ADMIN_DOMAIN',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('GROUP_NO',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('NOTIFICATION_NO',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('TXNREF',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('WORKFLOW',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('JMS_TXN_ID',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('ACCESS_REF',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('BEACON_REF',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('ISO8583_F11',1,NULL,SYSDATE,1);
  INSERT into TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) values ('OTP_REF_NO',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('AR_REF',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('SMS_TXNREF',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('USSD_TXNREF',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('TXT_TXNREF',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('SOURCE_MSG_ID',1,NULL,SYSDATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('CAPTCHA_REF_NO',1,NULL,SYSDATE,1);
