/*
 * Migration script from 3.27.2 to 3.27.3
 */
ALTER TABLE TB_ASLG_JMS_REQ_RESP DROP CONSTRAINT TB_ASLG_JMS_REQ_RESP_PKEY;
 
ALTER TABLE TB_ASLG_JMS_REQ_RESP 
  ALTER COLUMN TRANS_ID type BIGINT;

ALTER TABLE TB_ASLG_JMS_REQ_RESP ADD CONSTRAINT TB_ASLG_JMS_REQ_RESP_PKEY Primary Key ( TRANS_ID );

ALTER TABLE TB_ASLG_AUDIT_LOG DROP CONSTRAINT PK_TB_ASLG_AUDIT_LOG;

ALTER TABLE TB_ASLG_AUDIT_LOG
  ALTER COLUMN ACCESS_REF type BIGINT NOT NULL;
  
ALTER TABLE TB_ASLG_AUDIT_LOG ADD CONSTRAINT PK_TB_ASLG_AUDIT_LOG Primary Key ( ACCESS_REF );


ALTER TABLE TB_ASMI_CAPTCHA_DTLS DROP CONSTRAINT TB_ASMI_CAPTCHA_DTLS_PKEY;
  
ALTER TABLE TB_ASMI_CAPTCHA_DTLS
  ALTER COLUMN CAPTCHA_REF type BIGINT;
  
ALTER TABLE TB_ASMI_CAPTCHA_DTLS ADD CONSTRAINT TB_ASMI_CAPTCHA_DTLS_PKEY Primary Key ( CAPTCHA_REF );


