/*
 * Migration script from 3.27.2 to 3.27.3
 */
ALTER TABLE TB_ASTP_BEACON_MASTER DROP CONSTRAINT TB_ASTP_BEACON_MASTER_PKEY;

ALTER TABLE TB_ASTP_BEACON_MASTER
  ALTER COLUMN ID type BIGINT;
  
ALTER TABLE TB_ASTP_BEACON_MASTER ADD CONSTRAINT TB_ASTP_BEACON_MASTER_PKEY Primary Key ( ID );

ALTER TABLE TB_ASTP_OTP_ENGINE DROP CONSTRAINT TB_ASTP_OTP_ENGINE_PK;

ALTER TABLE TB_ASTP_OTP_ENGINE
  ALTER COLUMN REF_NO type BIGINT;
  
ALTER TABLE TB_ASTP_OTP_ENGINE ADD CONSTRAINT TB_ASTP_OTP_ENGINE_PK Primary Key ( REF_NO );

ALTER TABLE TB_ASTP_AR_MASTER DROP CONSTRAINT TB_ASTP_AR_MASTER_PKEY;

ALTER TABLE TB_ASTP_AR_MASTER
  ALTER COLUMN ID type BIGINT;
  
ALTER TABLE TB_ASTP_AR_MASTER ADD CONSTRAINT TB_ASTP_AR_MASTER_PKEY Primary Key ( ID );


