<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	
	<parent>
	  	<groupId>com.iexceed.appzillon</groupId>
  		<artifactId>AppzillonServer</artifactId>
  		<version>3.37.0</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>appzillon-notification</artifactId>
	<packaging>jar</packaging>
	<name>appzillon-notification</name>
	<url>http://maven.apache.org</url>

	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>net.rim.pushsdk</groupId>
			<artifactId>pap</artifactId>
			<version>1.1.0.16</version>
			<scope>system</scope>
			<systemPath>${basedir}/../appzillon-server/src/main/webapp/WEB-INF/lib/pap-1.1.0.16.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>net.rim.pushsdk</groupId>
			<artifactId>commons-pushsdk</artifactId>
			<version>1.1.0.16</version>
			<scope>system</scope>
			<systemPath>${basedir}/../appzillon-server/src/main/webapp/WEB-INF/lib/commons-pushsdk-1.1.0.16.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>com.iexceed.appzillon</groupId>
			<artifactId>appzillon-domain</artifactId>
			<version>${appzillon.version}</version>
		</dependency>
		<dependency>
			<groupId>com.iexceed.appzillon</groupId>
			<artifactId>appzillon-commons-utils</artifactId>
			<version>${appzillon.version}</version>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>com.eatthepath</groupId>
			<artifactId>pushy</artifactId>
			<version>0.15.1</version>
			<exclusions>
				<exclusion>
					<groupId>io.netty</groupId>
					<artifactId>netty-codec-http2</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.slf4j</groupId>
					<artifactId>slf4j-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-codec-http2</artifactId>
			<version>4.1.95.Final</version>
		</dependency>
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-handler-proxy</artifactId>
			<version>4.1.95.Final</version>
		</dependency>
		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-resolver-dns</artifactId>
			<version>4.1.95.Final</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.11</version>
		</dependency>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>32.1.1-jre</version>
		</dependency>

		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>fastjson</artifactId>
			<version>2.0.8</version>
		</dependency>

	</dependencies>
</project>
