redis.password=123456
redis.usessl=false
redis.verifyPeer=false

redis.cluster0.host=172.31.40.1
redis.cluster0.port=6379
 
redis.cluster1.host=172.31.43.223
redis.cluster1.port=6379
 
redis.cluster2.host=172.31.46.239
redis.cluster2.port=6379

redis.cluster3.host=172.31.38.20
redis.cluster3.port=6379

redis.cluster4.host=172.31.35.22
redis.cluster4.port=6379

redis.cluster5.host=172.31.37.234
redis.cluster5.port=6379
