package com.iexceed.appzillon.domain.entity;
// Generated Aug 6, 2013 11:23:55 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbAdtpFileDetailsId generated by hbm2java
 */
@Embeddable
public class TbAsfsFileDetailsId implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    private String appId;
    private String fileName;

    public TbAsfsFileDetailsId() {
    }

    public TbAsfsFileDetailsId(String appId, String fileId) {
        this.appId = appId;

    }


    @Column(name = "APP_ID", nullable = false, length = 200)
    public String getAppId() {
        return this.appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }


    @Override
    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof TbAsfsFileDetailsId)) return false;
        TbAsfsFileDetailsId castOther = (TbAsfsFileDetailsId) other;

        return ((this.getAppId() == castOther.getAppId()) || (this.getAppId() != null && castOther.getAppId() != null && this.getAppId().equals(castOther.getAppId())))
                && ((this.getFileName() == castOther.getFileName()) || (this.getFileName() != null && castOther.getFileName() != null && this.getFileName().equals(castOther.getFileName())));

    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getAppId() == null ? 0 : this.getAppId().hashCode());
        result = 37 * result + (getFileName() == null ? 0 : this.getFileName().hashCode());
        return result;
    }


    @Column(name = "FILE_NAME", nullable = false, length = 150)
    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }


}


