package com.iexceed.appzillon.domain.entity;
// Generated Aug 6, 2013 11:23:55 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.*;
import java.sql.Timestamp;

/**
 * TbAdtpFileDetails generated by hbm2java
 */
@Entity
@Table(name = "TB_ASFS_FILE_DETAILS")
public class TbAsfsFileDetails implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
    private TbAsfsFileDetailsId id;
    //  private String fileName;
    private String fileType;
    private Timestamp lastUploadedDate;
    private Timestamp recentUploadedDate;
    private String createUserId;
    private String screenId;
    private String userId;
    private String interfaceId;
    //  private Timestamp createTs;
    //   private Integer versionNo;

    public TbAsfsFileDetails() {
    }


    public TbAsfsFileDetails(TbAsfsFileDetailsId id, Timestamp lastUploadedDate, Timestamp recentUploadedDate, Timestamp createTs) {
        this.id = id;
        this.lastUploadedDate = lastUploadedDate;
        this.recentUploadedDate = recentUploadedDate;
        //  this.createTs = createTs;
    }

    public TbAsfsFileDetails(TbAsfsFileDetailsId id, String fileName, String fileType, Timestamp lastUploadedDate, Timestamp recentUploadedDate, String createUserId, Timestamp createTs, Integer versionNo) {
        this.id = id;
        //  this.fileName = fileName;
        this.fileType = fileType;
        this.lastUploadedDate = lastUploadedDate;
        this.recentUploadedDate = recentUploadedDate;
        this.createUserId = createUserId;
        //  this.createTs = createTs;
        // this.versionNo = versionNo;
    }

    @EmbeddedId

    @AttributeOverrides({
            @AttributeOverride(name = "appId", column = @Column(name = "APP_ID", nullable = false, length = 200)),
            @AttributeOverride(name = "fileName", column = @Column(name = "FILE_NAME", nullable = false, length = 100))})
    public TbAsfsFileDetailsId getId() {
        return this.id;
    }

    public void setId(TbAsfsFileDetailsId id) {
        this.id = id;
    }

    /* @Column(name="FILE_NAME", length=150)
    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
     */
    @Column(name = "FILE_TYPE", length = 20)
    public String getFileType() {
        return this.fileType;
    }

    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    @Column(name = "USER_ID", length = 100)
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "INTERFACE_ID", length = 30)
    public String getInterfaceId() {
        return interfaceId;
    }

    public void setInterfaceId(String interfaceId) {
        this.interfaceId = interfaceId;
    }

    @Column(name = "LAST_UPLOADED_DATE", length = 19)
    public Timestamp getLastUploadedDate() {
        return this.lastUploadedDate;
    }

    public void setLastUploadedDate(Timestamp lastUploadedDate) {
        this.lastUploadedDate = lastUploadedDate;
    }

    @Column(name = "RECENT_UPLOADED_DATE", length = 19)
    public Timestamp getRecentUploadedDate() {
        return this.recentUploadedDate;
    }

    public void setRecentUploadedDate(Timestamp recentUploadedDate) {
        this.recentUploadedDate = recentUploadedDate;
    }

    @Column(name = "CREATE_USER_ID", length = 100)
    public String getCreateUserId() {
        return this.createUserId;
    }

    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    @Column(name = "SCREEN_ID", length = 100)
    public String getScreenId() {
        return screenId;
    }

    public void setScreenId(String screenId) {
        this.screenId = screenId;
    }

    /*  @Column(name="CREATE_TS", nullable=false, length=19)
    public Timestamp getCreateTs() {
        return this.createTs;
    }

    public void setCreateTs(Timestamp createTs) {
        this.createTs = createTs;
    }

    @Column(name="VERSION_NO")
    public Integer getVersionNo() {
        return this.versionNo;
    }

    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

     */
    public String toString() {
        return "TbAdtpFileDetails [AppId=" + id.getAppId() + ", fileName=" + id.getFileName()
                + ", fileType=" + fileType + ", lastUploadedDate="
                + lastUploadedDate + ", recentUploadedDate="
                + recentUploadedDate + ", createUserId=" + createUserId + "]";
        //	+ ", createTs=" + createTs + ", versionNo=" + versionNo + "]";
    }


}


