package com.iexceed.appzillon.domain.entity;
// Generated Aug 16, 2013 4:31:46 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.*;
import java.util.Date;

/**
 * TbAslgJmsReqRespLog generated by hbm2java
 */
@Entity
@Table(name = "TB_ASLG_JMS_REQ_RESP"

        , uniqueConstraints = @UniqueConstraint(columnNames = {"MSG_ID"})
)
/*
 * @TableGenerator( name = "LOGGINGSEQUENCE2", table = "TB_ASTP_SEQ_GEN",
 * pkColumnName = "SEQUENCE_NAME", valueColumnName = "SEQUENCE_VALUE",
 * pkColumnValue = "JMS_TXN_ID", allocationSize = 1)
 */
public class TbAslgJmsReqResp implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    private long transId;
    private String interfaceId;
    private String appId;
    private String reqType;
    private String resType;
    private Date sentDate;
    private Date receivedDate;
    private String msgId;
    private String reqQ;
    private String respQ;
    private int msgStatus;
    private String msgSent;
    private String msgReceived;
    private String respDesc;

    public TbAslgJmsReqResp() {
        // Default constructor
    }

    @Id
    //@GeneratedValue(strategy = GenerationType.TABLE, generator = "LOGGINGSEQUENCE2")
    @Column(name = "TRANS_ID", nullable = false)
    public long getTransId() {
        return transId;
    }


    public void setTransId(long transId) {
        this.transId = transId;
    }

    @Column(name = "INTERFACE_ID", nullable = false, length = 300)
    public String getInterfaceId() {
        return interfaceId;
    }


    public void setInterfaceId(String interfaceId) {
        this.interfaceId = interfaceId;
    }

    @Column(name = "APP_ID", nullable = false, length = 300)
    public String getAppId() {
        return appId;
    }


    public void setAppId(String appId) {
        this.appId = appId;
    }


    @Column(name = "REQ_TYPE", nullable = false, length = 50)
    public String getReqType() {
        return this.reqType;
    }

    public void setReqType(String reqType) {
        this.reqType = reqType;
    }

    @Column(name = "RES_TYPE", nullable = false, length = 50)
    public String getResType() {
        return this.resType;
    }

    public void setResType(String resType) {
        this.resType = resType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "SENT_DATE", length = 19)
    public Date getSentDate() {
        return this.sentDate;
    }

    public void setSentDate(Date sentDate) {
        this.sentDate = sentDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "RECEIVED_DATE", length = 19)
    public Date getReceivedDate() {
        return this.receivedDate;
    }

    public void setReceivedDate(Date receivedDate) {
        this.receivedDate = receivedDate;
    }

    @Column(name = "MSG_ID", nullable = false, length = 100)
    public String getMsgId() {
        return this.msgId;
    }

    public void setMsgId(String msgId) {
        this.msgId = msgId;
    }

    @Column(name = "REQ_Q", length = 100)
    public String getReqQ() {
        return this.reqQ;
    }

    public void setReqQ(String reqQ) {
        this.reqQ = reqQ;
    }

    @Column(name = "RESP_Q", length = 100)
    public String getRespQ() {
        return this.respQ;
    }

    public void setRespQ(String respQ) {
        this.respQ = respQ;
    }

    @Column(name = "MSG_STATUS", nullable = false)
    public int getMsgStatus() {
        return this.msgStatus;
    }

    public void setMsgStatus(int msgStatus) {
        this.msgStatus = msgStatus;
    }

    @Column(name = "MSG_SENT", nullable = false)
    public String getMsgSent() {
        return this.msgSent;
    }

    public void setMsgSent(String msgSent) {
        this.msgSent = msgSent;
    }

    @Column(name = "MSG_RECEIVED")
    public String getMsgReceived() {
        return this.msgReceived;
    }

    public void setMsgReceived(String msgReceived) {
        this.msgReceived = msgReceived;
    }

    @Column(name = "RESP_DESC", length = 100)
    public String getRespDesc() {
        return this.respDesc;
    }

    public void setRespDesc(String respDesc) {
        this.respDesc = respDesc;
    }


}


