
DROP TABLE IF EXISTS TB_ASMI_LOV_QUERIES;
CREATE TABLE TB_ASMI_LOV_QUERIES (
  APP_ID varchar(100) NOT NULL,
  QUERY_ID varchar(100) NOT NULL,
  QUERY_STRING varchar(1000) NOT NULL,
  DB_JNDI_NAME varchar(50) NOT NULL,
  QUERY_TYPE varchar(3) DEFAULT 'SQL',
  BINDVAR_COLS varchar(300) DEFAULT NULL,
  BINDVAR_DATA_TYPES varchar(300) DEFAULT NULL,
  FILTER_COLS varchar(300) DEFAULT NULL,
  ORDERBY_COL varchar(40) DEFAULT NULL,
  ORDERBY_TYPE varchar(5) DEFAULT 'ASC',
  CREATE_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATE_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CREATE_BY varchar(50) DEFAULT NULL,
  SESSION_REQD varchar(1) DEFAULT NULL,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (APP_ID,QUERY_ID) 
) ;

DROP TABLE IF EXISTS TB_ASMI_OS_DTLS;
CREATE TABLE TB_ASMI_OS_DTLS (
  OS_ID varchar(50) NOT NULL,
  OS_DESC varchar(200) DEFAULT NULL,
  CREATE_BY varchar(100) DEFAULT NULL,
  CREATE_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (OS_ID)
 );

DROP TABLE IF EXISTS TB_ASNF_DEVICES_MASTER CASCADE;
CREATE TABLE TB_ASNF_DEVICES_MASTER (
  APP_ID varchar(100) NOT NULL,
  NOTIF_REG_ID varchar(255) NOT NULL,
  DEVICE_ID varchar(255) DEFAULT NULL,
  DEVICE_NAME varchar(255) DEFAULT NULL,
  OS_ID varchar(50) DEFAULT NULL,
  OS_VERSION varchar(255) DEFAULT NULL,
  STATUS varchar(20) DEFAULT NULL,
  CREATED_BY varchar(255) DEFAULT NULL,
  CREATED_TS timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  MAKER_ID VARCHAR(45),
  MAKER_TS timestamp DEFAULT CURRENT_TIMESTAMP,
  CHECKER_ID VARCHAR(45),
  CHECKER_TS timestamp DEFAULT CURRENT_TIMESTAMP,
  AUTH_STATUS VARCHAR(45) DEFAULT 'U',
  NOTIF_MSG_SERVER varchar(255) DEFAULT NULL,
  PRIMARY KEY (APP_ID,NOTIF_REG_ID)
);

DROP TABLE IF EXISTS TB_ASNF_GROUP_DEVICES;
CREATE TABLE TB_ASNF_GROUP_DEVICES (
  APP_ID varchar(100) NOT NULL,
  GROUP_ID varchar(255) NOT NULL,
  NOTIF_REG_ID varchar(255) NOT NULL,
  CREATED_BY varchar(255) DEFAULT NULL,
  CREATED_TS timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (APP_ID,GROUP_ID,NOTIF_REG_ID)
) ;

DROP TABLE IF EXISTS TB_ASNF_GROUP_MASTER;
CREATE TABLE TB_ASNF_GROUP_MASTER (
  APP_ID varchar(100) NOT NULL,
  GROUP_ID varchar(255) NOT NULL,
  GROUP_DESC varchar(500) DEFAULT NULL,
  CREATED_BY varchar(50) DEFAULT NULL,
  CREATED_TS timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (APP_ID,GROUP_ID)
) ;

DROP TABLE IF EXISTS TB_ASNF_TXN_DEVICES;
CREATE TABLE TB_ASNF_TXN_DEVICES (
  NOTIF_ID int NOT NULL,
  APP_ID varchar(100) NOT NULL,
  NOTIF_REG_ID varchar(255) NOT NULL,
  PRIMARY KEY (NOTIF_ID,APP_ID,NOTIF_REG_ID)
);

DROP TABLE IF EXISTS TB_ASNF_TXN_GROUPS;
CREATE TABLE TB_ASNF_TXN_GROUPS (
  NOTIF_ID int NOT NULL,
  APP_ID varchar(100) NOT NULL,
  GROUP_ID varchar(255) NOT NULL,
   PRIMARY KEY (NOTIF_ID,APP_ID,GROUP_ID)
) ;

DROP TABLE IF EXISTS TB_ASNF_TXN_LOG;
CREATE TABLE TB_ASNF_TXN_LOG (
  NOTIF_ID int NOT NULL,
  APP_ID varchar(100) NOT NULL,
  USER_ID varchar(100),
  NOTIF_REG_ID varchar(255) NOT NULL,
  DEVICE_ID varchar(255) NOT NULL,
  STATUS char(150) DEFAULT NULL,
  CREATED_BY varchar(150) DEFAULT NULL,
  CREATED_TS timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
   PRIMARY KEY (NOTIF_ID,APP_ID,NOTIF_REG_ID,DEVICE_ID)
) ;

DROP TABLE IF EXISTS TB_ASNF_TXN_MASTER;
CREATE TABLE TB_ASNF_TXN_MASTER (
  NOTIF_ID int NOT NULL,
  APP_ID varchar(100) NOT NULL,
  NOTIF_MSG varchar(255) NOT NULL,
  TITLE varchar(255) ,
   SUBTITLE varchar(255) ,
   IMAGE_URL varchar(255) ,
   CATEGORY varchar(255) ,
   CREATE_TS timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (NOTIF_ID,APP_ID,NOTIF_MSG)
) ;


 DROP TABLE IF EXISTS TB_ASTP_SEQ_GEN;
CREATE TABLE TB_ASTP_SEQ_GEN (
  SEQUENCE_NAME varchar(50) NOT NULL,
  SEQUENCE_VALUE int NOT NULL,
  CREATE_BY varchar(20) DEFAULT NULL,
  CREATE_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  PRIMARY KEY (SEQUENCE_NAME)
 );
 
 /*CREATE TABLE TB_AFTP_WORKFLOW_DET 
( 
  TRANSACTION_REF_NO VARCHAR(30) NOT NULL 
, VERSION_NO DECIMAL(10, 0) NOT NULL 
, WORKFLOW_ID VARCHAR(100) NOT NULL 
, CURRENT_STAGE VARCHAR(100) NOT NULL 
, SCREEN_ID VARCHAR(100) NOT NULL 
, NEXT_STAGE VARCHAR(100) NULL 
, STATUS VARCHAR(20) NULL 
, APP_ID VARCHAR(100) NOT NULL 
, INTERFACE_ID VARCHAR(100) NOT NULL 
, USER_ID VARCHAR(100) NULL 
, SCREEN_DATA text NULL 
, STAGE_SEQ_NO VARCHAR(255) NULL 
, ACTION VARCHAR(255) NULL 
, CREATE_USER_ID VARCHAR(100) NULL
, CREATE_TS TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
, PRIMARY KEY ( TRANSACTION_REF_NO, VERSION_NO, WORKFLOW_ID, CURRENT_STAGE, SCREEN_ID, APP_ID, INTERFACE_ID )
);
*/
 
 DROP TABLE IF EXISTS TB_ASTP_WORKFLOW_DET;
 CREATE TABLE TB_ASTP_WORKFLOW_DET
  (
    TRANSACTION_REF_NO VARCHAR(30) NOT NULL ,
    VERSION_NO DECIMAL(10, 0) NULL, 
   WORKFLOW_ID        VARCHAR(100) NOT NULL ,
   APP_ID             VARCHAR(100) NOT NULL ,
   CURRENT_STAGE       VARCHAR(100) NULL ,
    SCREEN_ID          VARCHAR(100) NULL ,
    NEXT_STAGE         VARCHAR(100) NULL ,
    STATUS             VARCHAR(20) NULL ,
    INTERFACE_ID        VARCHAR(100) NULL ,
   USER_ID             VARCHAR(100) NULL ,
    SCREEN_DATA text NULL ,
    STAGE_SEQ_NO   VARCHAR(255 ) NULL ,
    ACTION         VARCHAR(255 ) NULL ,
    CREATE_USER_ID VARCHAR(100 ) NULL ,
    CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    CONSTRAINT TB_ASTP_WORKFLOW_DET_PK PRIMARY KEY (TRANSACTION_REF_NO, WORKFLOW_ID, APP_ID)
  );

  DROP TABLE IF EXISTS TB_ASMI_APP_DTLS;
CREATE TABLE TB_ASMI_APP_DTLS (
  APP_ID varchar(100) NOT NULL,
  OS_ID varchar(50) NOT NULL,
  APP_DESC varchar(200) DEFAULT NULL,
  CREATE_BY varchar(100) DEFAULT NULL,
  CREATE_TS timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  VERSION_NO int DEFAULT 1,
  CONSTRAINT TB_ASMI_APP_DTLS_PK PRIMARY KEY (APP_ID,OS_ID)
) ;

DROP TABLE IF EXISTS TB_ASFS_FILE_DETAILS;
CREATE TABLE TB_ASFS_FILE_DETAILS 
( 
  APP_ID VARCHAR(100) NOT NULL 
, SCREEN_ID VARCHAR(100) NULL 
, USER_ID VARCHAR(100)  NULL 
, FILE_NAME VARCHAR(150)  NOT NULL  
, FILE_TYPE VARCHAR(20) NULL 
, INTERFACE_ID VARCHAR(30) NULL
, CREATE_USER_ID VARCHAR(100) NULL 
, LAST_UPLOADED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP 
, RECENT_UPLOADED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
, PRIMARY KEY ( APP_ID,FILE_NAME) 
);

/*
 * Changes made by Ripu
 * Below table added for FS item : Appzillon - 3.1 - 13, 15, 65 Start
 */

/* Appzillon - 3.1 - 13, 15, 65 END */

/*
 * Changes made by Ripu
 * Below tables added for (OTA) FS item : Appzillon - 3.1 - 13 Start
 */

DROP TABLE IF EXISTS TB_ASMI_APP_USER;
  CREATE TABLE TB_ASMI_APP_USER
   (   
  USER_ID VARCHAR(50) NOT NULL, 
    PARENT_APP_ID VARCHAR(100) NOT NULL,
  CHILD_APP_ID VARCHAR(100) NOT NULL, 
  CREATE_USER_ID VARCHAR(50), 
  CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
  VERSION_NO int DEFAULT 1, 
   CONSTRAINT TB_ASMI_APP_USER_PK PRIMARY KEY (USER_ID, PARENT_APP_ID, CHILD_APP_ID)
    ) ;
    
    
    DROP TABLE IF EXISTS TB_ASMI_APP_FILES;
  CREATE TABLE TB_ASMI_APP_FILES 
   (  
  APP_ID VARCHAR(100) NOT NULL, 
  APP_VERSION VARCHAR(10) NOT NULL,
    OS VARCHAR(20) NOT NULL,
    FILE_NAME VARCHAR(100) NOT NULL,
  FILE_PATH VARCHAR(255), 
  ACTION VARCHAR(10),
  CREATE_USER_ID VARCHAR(100), 
  CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
  VERSION_NO int DEFAULT 1,
  CONSTRAINT TB_ASMI_APP_FILES_PK PRIMARY KEY (APP_ID, APP_VERSION, OS, FILE_NAME)
   ) ;
   

   DROP TABLE IF EXISTS TB_ASMI_APP_OS_VERSION;
  CREATE TABLE TB_ASMI_APP_OS_VERSION
   (   
    APP_ID VARCHAR(100) NOT NULL, 
    OS VARCHAR(20) NOT NULL,
    APP_VERSION VARCHAR(10) NOT NULL, 
    CREATE_USER_ID VARCHAR(50), 
    CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    VERSION_NO int DEFAULT 1,
    APP_ACTION VARCHAR(10) NOT NULL DEFAULT 'IGNORE',
    CONSTRAINT TB_ASMI_APP_OS_VERSION_PK PRIMARY KEY (APP_ID, OS, APP_VERSION)
    ) ;
    
    
 /* Appzillon - 3.1 - 13 END */
   
/* 
    * Changes Made By Ripu
    * Appzillon - 3.1 - Audit Log Start
    */
   
/* Appzillon - 3.1 - Send SMS to user End*/


/*
 * Changes done by Ripu
 * Appzillon - 3.1 - Task Repair Start
 */
/*CREATE TABLE TB_AFHS_WORKFLOW_DET
  (
    TRANSACTION_REF_NO VARCHAR(30) NOT NULL ,
    VERSION_NO         DECIMAL(10, 0) NOT NULL,
   WORKFLOW_ID        VARCHAR(100) NOT NULL ,
   CURRENT_STAGE       VARCHAR(100) NOT NULL ,
    SCREEN_ID          VARCHAR(100) NOT NULL ,
    NEXT_STAGE         VARCHAR(100) NULL ,
    STATUS             VARCHAR(20) NULL ,
    APP_ID             VARCHAR(100) NOT NULL ,
    INTERFACE_ID        VARCHAR(100) NOT NULL ,
   USER_ID             VARCHAR(100) NULL ,
    SCREEN_DATA text NULL ,
    STAGE_SEQ_NO   VARCHAR(255) NULL ,
    ACTION         VARCHAR(255) NULL ,
    CREATE_USER_ID VARCHAR(100) NULL ,
    CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    HISTORY_VERSION_NO INT NOT NULL,
    CONSTRAINT TB_AFHS_WORKFLOW_DET_PK PRIMARY KEY (TRANSACTION_REF_NO, VERSION_NO, WORKFLOW_ID, CURRENT_STAGE,SCREEN_ID ,APP_ID ,INTERFACE_ID,HISTORY_VERSION_NO )
  );*/

DROP TABLE IF EXISTS TB_ASHS_WORKFLOW_DET;
CREATE TABLE TB_ASHS_WORKFLOW_DET
  (
    TRANSACTION_REF_NO VARCHAR(30) NOT NULL ,
    VERSION_NO         INT NOT NULL,
   WORKFLOW_ID        VARCHAR(100) NOT NULL ,
   APP_ID             VARCHAR(100) NOT NULL ,
   CURRENT_STAGE       VARCHAR(100) NULL ,
    SCREEN_ID          VARCHAR(100) NULL ,
    NEXT_STAGE         VARCHAR(100) NULL ,
    STATUS             VARCHAR(20) NULL ,
    INTERFACE_ID        VARCHAR(100) NULL ,
   USER_ID             VARCHAR(100) NULL ,
    SCREEN_DATA text NULL ,
    STAGE_SEQ_NO   VARCHAR(255) NULL ,
    ACTION         VARCHAR(255) NULL ,
    CREATE_USER_ID VARCHAR(100) NULL ,
    CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    CONSTRAINT TB_ASHS_WORKFLOW_DET_PK PRIMARY KEY (TRANSACTION_REF_NO, VERSION_NO, WORKFLOW_ID, APP_ID)
  );
  /* Appzillon - 3.1 - Task Repair End*/
  
 /*
 * Changes done by Ripu
 * Appzillon - 3.1 - Drag and drop Start
 */
  
  DROP TABLE IF EXISTS TB_ASMI_DRAG_DROP;
     /*CREATE TABLE TB_ASMI_DRAG_DROP
     (  
     APP_ID VARCHAR(100), 
     USER_ID VARCHAR(50), 
    SCREEN_ID VARCHAR(100), 
    LAYOUT VARCHAR(100), 
    PARENT_ID VARCHAR(100),
    HTML_ID VARCHAR(100),
    SEQUENCE_NO INT,
    CREATED_BY VARCHAR(50), 
    CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    VERSION_NO int DEFAULT 1,
    CONSTRAINT PK_TB_ASMI_DRAG_DROP PRIMARY KEY (APP_ID, USER_ID, SCREEN_ID, LAYOUT, PARENT_ID, HTML_ID)
    ) ;*/
   /* Appzillon - 3.1 - Drag and Drop End*/
    
    
DROP TABLE IF EXISTS TB_ASTP_BEACON_MASTER;
CREATE TABLE TB_ASTP_BEACON_MASTER (
  APP_ID varchar(100) DEFAULT NULL,
  ID BIGINT NOT NULL,
  DEVICE_ID varchar(225) DEFAULT NULL,
  USER_ID varchar(100) DEFAULT NULL,
  ENTRY_TIME timestamp NULL DEFAULT NULL,
  STATUS varchar(45) DEFAULT NULL,
  PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS TB_ASTP_OTP_ENGINE;
CREATE TABLE TB_ASTP_OTP_ENGINE 
   (  
  REF_NO BIGINT NOT NULL, 
  APP_ID varchar(100), 
  USER_ID varchar(255), 
  INTERFACE_ID varchar(255), 
  SESSION_ID varchar(255), 
  OTP varchar(255), 
  OTP_GEN_TS timestamp,
  OTP_EXP_TS timestamp,
  OTP_STATUS varchar(255) DEFAULT 'N', 
  OTP_VAL_TS timestamp,
  REQ_LD_REFNO varchar(100), 
  REQ_NO_RECS int, 
  REQ_PAYLOAD_STATUS varchar(200), 
  REQ_PAYLOAD_PROCESS_TS timestamp, 
  /*
  * Below Fields Added by sasidhar
  * 
  */
  OTP_VALIDATION_COUNT int,
  OTP_RESENT_COUNT int,
  OTP_REGEN_COUNT int DEFAULT 0,
  OTP_RESEND_LOCK varchar(1),
  OTP_RESEND_LOCK_TS timestamp,
  VERSION_NO int NOT NULL DEFAULT 0,
  CONSTRAINT TB_ASTP_OTP_ENGINE_PK PRIMARY KEY (REF_NO)
   );

DROP TABLE IF EXISTS TB_ASTP_AR_MASTER;
CREATE TABLE TB_ASTP_AR_MASTER (
APP_ID varchar(255) DEFAULT NULL,
ID BIGINT NOT NULL,
REGION_CODE varchar(255) DEFAULT NULL,
CATEGORY varchar(255) DEFAULT NULL,
LATITUDE varchar(255) DEFAULT NULL,
LONGITUDE varchar(255) DEFAULT NULL,
TITLE  varchar(255) DEFAULT NULL,
ADDITIONAL_INFO varchar(255) DEFAULT NULL,
DESCRIPTION varchar(255) DEFAULT NULL,
IMAGE varchar(255) DEFAULT NULL,
PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS TB_ASMI_SCHEDULER_JOB_EXP;
CREATE TABLE TB_ASMI_SCHEDULER_JOB_EXP (
  JOB_NAME varchar(45) NOT NULL,
  START_DATE varchar(45) DEFAULT NULL,
  END_DATE varchar(45) DEFAULT NULL,
  EXP_START_SEC varchar(45) DEFAULT NULL,
  EXP_SEC varchar(45) DEFAULT NULL,
  EXP_MIN varchar(45) DEFAULT NULL,
  EXP_HR varchar(45) DEFAULT NULL,
  EXP_DOM varchar(45) DEFAULT NULL,
  EXP_MONTH varchar(45) DEFAULT NULL,
  EXP_DOW varchar(45) DEFAULT NULL,
  EXP_YEAR varchar(45) DEFAULT NULL,
  EXPRESSION varchar(45) DEFAULT NULL,
  PRIMARY KEY (JOB_NAME)
);

DROP TABLE IF EXISTS TB_ASMI_SCHEDULER_JOB;
CREATE TABLE TB_ASMI_SCHEDULER_JOB (
  APP_ID varchar(45) DEFAULT NULL,
  JOB_NAME varchar(45) NOT NULL,
  JOB_CLASS varchar(45) DEFAULT NULL,
  JOB_DATA varchar(255) DEFAULT NULL,
  JOB_STATUS varchar(45) DEFAULT 'P',
  JOB_CREATED_TS timestamp NULL DEFAULT NULL,
  JOB_EXECUTED_TS timestamp NULL DEFAULT NULL,
  PRIMARY KEY (JOB_NAME)
);

DROP TABLE IF EXISTS TB_OS;
CREATE TABLE TB_OS (
  OS_ID varchar(15) NOT NULL,
  CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (OS_ID)
);

DROP TABLE IF EXISTS TB_ASMI_APP_ID_VERSION;
  CREATE TABLE TB_ASMI_APP_ID_VERSION
   (   
    APP_ID VARCHAR(100) NOT NULL,
    OS VARCHAR(20) NOT NULL,
    APP_ID_VERSION VARCHAR(10) NOT NULL,
    CREATE_USER_ID VARCHAR(50), 
    CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    VERSION_NO int DEFAULT 1,
    CONSTRAINT TB_ASMI_APP_ID_VERSION_PK PRIMARY KEY (APP_ID,OS,APP_ID_VERSION)
    ) ;

    

CREATE OR REPLACE VIEW VW_NOTIFY_APPID as select DISTINCT(APP_ID) appId from TB_ASNF_DEVICES_MASTER;

CREATE OR REPLACE VIEW VW_DIGITS AS
  SELECT 0 AS digit UNION ALL
  SELECT 1 UNION ALL
  SELECT 2 UNION ALL
  SELECT 3 UNION ALL
  SELECT 4 UNION ALL
  SELECT 5 UNION ALL
  SELECT 6 UNION ALL
  SELECT 7 UNION ALL
  SELECT 8 UNION ALL
  SELECT 9;
  
CREATE OR REPLACE VIEW VW_NUMBERS AS
  SELECT
    ones.digit + tens.digit * 10 + hundreds.digit * 100 + thousands.digit * 1000 AS number
  FROM
    VW_DIGITS as ones,
    VW_DIGITS as tens,
    VW_DIGITS as hundreds,
    VW_DIGITS as thousands;
    
CREATE OR REPLACE VIEW VW_DATES AS
SELECT
CAST((current_date-number) as Date) AS date
FROM VW_NUMBERS;

CREATE OR REPLACE VIEW VW_OS_DATES as select d.date osdates,OS_ID AS datesos,appId from VW_DATES d,TB_OS o,VW_NOTIFY_APPID ap;

CREATE OR REPLACE VIEW VW_MESSAGE_STATS AS
select DATE(tnl.CREATED_TS) AS TXNDATE,count(0) AS num,tnm.OS_ID AS os,tnl.APP_ID AS appId
from TB_ASNF_TXN_LOG tnl,TB_ASNF_DEVICES_MASTER tnm
where tnl.NOTIF_REG_ID = tnm.NOTIF_REG_ID
group by DATE(tnl.CREATED_TS),tnm.OS_ID,tnl.APP_ID;

CREATE OR REPLACE VIEW VW_MESSAGE_NOTIFY_STATS AS
SELECT VW_OS_DATES.appId,osdates,COALESCE(num,0) count,datesos 
FROM VW_MESSAGE_STATS RIGHT OUTER JOIN VW_OS_DATES ON osdates=TXNDATE AND datesos=os and 
VW_OS_DATES.appId=VW_MESSAGE_STATS.appId;

  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('ADMIN_DOMAIN',1,NULL,CURRENT_TIMESTAMP,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('GROUP_NO',1,NULL,CURRENT_DATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('NOTIFICATION_NO',1,NULL,CURRENT_DATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('TXNREF',1,NULL,CURRENT_DATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('WORKFLOW',1,NULL,CURRENT_DATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('JMS_TXN_ID',1,NULL,CURRENT_DATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('ACCESS_REF',1,NULL,CURRENT_DATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('BEACON_REF',1,NULL,CURRENT_DATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('ISO8583_F11',1,NULL,CURRENT_DATE,1);
  INSERT into TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) values ('OTP_REF_NO',1,NULL,CURRENT_DATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('AR_REF',1,NULL,CURRENT_DATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('SMS_TXNREF',1,NULL,CURRENT_DATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('USSD_TXNREF',1,NULL,CURRENT_DATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('TXT_TXNREF',1,NULL,CURRENT_DATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('SOURCE_MSG_ID',1,NULL,CURRENT_DATE,1);
  INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('CAPTCHA_REF_NO',1,NULL,CURRENT_DATE,1);
  
  INSERT INTO TB_OS (OS_ID,CREATE_TS) VALUES ('ANDROID',CURRENT_DATE);
  INSERT INTO TB_OS (OS_ID,CREATE_TS) VALUES ('IOS',CURRENT_DATE);
  INSERT INTO TB_OS (OS_ID,CREATE_TS) VALUES ('WINDOWS',CURRENT_DATE);
