apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: {{ lower .Values.appId }}-public-pem
  namespace: {{ .Values.nameSpace }}
spec:
  encryptedData:
    public.pem: {{ index (index .Values .Values.appId) "publicPem" }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: {{ lower .Values.appId }}-public-pem
      namespace: {{ .Values.nameSpace }}