package com.iexceed.appzillon.intf;

import com.iexceed.appzillon.json.JSONObject;
import com.iexceed.appzillon.jsonutils.JSONUtils;
import com.iexceed.appzillon.logging.LoggerFactory;
import com.iexceed.appzillon.maputils.MapUtils;
import com.iexceed.appzillon.utilsexception.UtilsException;

import java.util.HashMap;
import java.util.Map;

import static com.iexceed.appzillon.utils.ServerConstants.*;

public final class AppzillonInterfaceDetails {

    private static final com.iexceed.appzillon.logging.Logger LOG = LoggerFactory.getLoggerFactory()
            .getRestServicesLogger(LOGGER_RESTFULL_SERVICES, AppzillonInterfaceDetails.class.getName());
    private static AppzillonInterfaceDetails cInterfaceDtls = null;
    private final Map<String, AppzillonInterface> interfaceDtlsMap;
    private final Map<String, String[]> lAppzillonInterface;

    private final String[] lKey = {INTERFACE_ID_AUTHENTICATION,
            INTERFACE_ID_CHANGE_PIN,
            INTERFACE_ID_RE_LOGIN,
            INTERFACE_ID_AUDIT_LOG,
            INTERFACE_ID_USER_REGISTER,
            INTERFACE_ID_INTF_AUTH_REQ,
            INTERFACE_ID_SCREEN_AUTH_REQ,
            INTERFACE_ID_FETCH_PRIVILEGE_SERVICE,
            INTERFACE_ID_LOGOUT,
            INTERFACE_ID_LOV,
            INTERFACE_ID_VALIDATE_AND_PROCESSIFACE,
            INTERFACE_ID_DEVICE_REGISTRATION,
            INTERFACE_ID_USER_DEVICE_REGISTRATION,
            INTERFACE_ID_VALIDATE_OTP,
            INTERFACE_ID_REGENERATE_OTP,
            INTERFACE_ID_SEND_SMS,
            INTERFACE_ID_SCHEDULER,
            INTERFACE_ID_SMS_TXN,
            INTERFACE_ID_USSD_TXN,
            INTERFACE_ID_TXT_MSLG_LOG,
            INTERFACE_ID_SMS_USER,
            INTERFACE_ID_CHECK_SERVER,
            INTERFACE_ID_OTAFILE_DOWNLOADREQ,
            INTERFACE_ID_OTA_GET_APP_FILE,
            INTERFACE_MULTIFACTOR_DEVICE_REGISTRATION,
            INTERFACE_ID_TRACK_LOCATION,
            INTERFACE_ID_GENERATE_CAPTCHA,
            INTERFACE_ID_ERROR_LOGGING,
            INTERFACE_ID_GET_CNVUI_WELCOME_MSG,
            INTERFACE_ID_GET_FIRST_CNVUI_DLG,
            INTERFACE_ID_GET_CNVUI_DLG,
            INTERFACE_ID_PROCESS_NLP_DATA,
            INTERFACE_ID_GET_APP_SEC_TOKENS,
            INTERFACE_ID_CREATE_TENANT,
            INTERFACE_ID_APP_USAGE_REPORT,
            INTERFACE_ID_CREATE_DEVICE,
            INTERFACE_ID_CREATE_GROUP,
            INTERFACE_ID_CREATE_ROLE_MASTER,
            INTERFACE_ID_CREATE_SCREEN,
            INTERFACE_ID_CREATE_USER,
            INTERFACE_ID_DELETE_DEVICE,
            INTERFACE_ID_DELETE_FILE,
            INTERFACE_ID_DELETE_GROUP,
            INTERFACE_ID_DELETE_SCREEN,
            INTERFACE_ID_FILE_PUSH_SERVICE,
            INTERFACE_ID_FILE_PUSH_SERVICE_WS,
            INTERFACE_ID_FILE_PUSH_SERVICE_AUTH,
            INTERFACE_ID_GET_GROUP_DETAIL,
            INTERFACE_ID_GET_REQ_RESP,
            INTERFACE_ID_LOGIN_REPORT,
            INTERFACE_ID_NOTIFICATION_APP_DETAIL,
            INTERFACE_ID_PUSH_NOTIFICATION,
            INTERFACE_ID_SEARCH_DEVICE,
            INTERFACE_ID_SEARCH_FILE,
            INTERFACE_ID_SEARCH_GROUP,
            INTERFACE_ID_SEARCH_SCREEN,
            INTERFACE_ID_SEARCH_TXN_LOG,
            INTERFACE_ID_UPDATE_DEVICE,
            INTERFACE_ID_UPDATE_GROUP,
            INTERFACE_ID_UPDATE_SCREEN,
            INTERFACE_ID_UPLOAD_FILE,
            INTERFACE_ID_UPLOAD_FILE_WS,
            INTERFACE_ID_UPLOAD_FILE_AUTH,
            INTERFACE_ID_DECRYPT,
            INTERFACE_ID_LOGGING_REQ,
            INTERFACE_ID_WF_DASHBOARD_QUERY,
            INTERFACE_ID_WF_PERSIST,
            INTERFACE_ID_WF_QUERY,
            INTERFACE_ID_WF_QUERY_DB,
            INTERFACE_ID_WF_QUERY_REQ,
            INTERFACE_ID_CREATE_PIN_RULES,
            INTERFACE_ID_DELETE_PIN_RULES,
            INTERFACE_ID_GET_PIN_RULES,
            INTERFACE_ID_UPDATE_PIN_RULES,
            INTERFACE_ID_UPDATE_USER,
            INTERFACE_ID_DELETE_USER,
            INTERFACE_ID_SEARCH_USER,
            INTERFACE_ID_GET_ROLES_APPID_USERID,
            INTERFACE_ID_GET_ROLES_APPID,
            INTERFACE_ID_PIN_RESET,
            INTERFACE_ID_UNLOCK_USER,
            INTERFACE_ID_GET_USER,
            INTERFACE_ID_UPDATE_ROLE_MASTER,
            INTERFACE_ID_DELETE_ROLE_MASTER,
            INTERFACE_ID_GET_ROLE_MASTER,
            INTERFACE_ID_GET_SCREENS_INTF_APPID,
            INTERFACE_ID_GET_SCREENS_INTF_APPID_ROLEID,
            INTERFACE_ID_SEARCH_INTF_MASTER,
            INTERFACE_ID_CREATE_INTF_MASTER,
            INTERFACE_ID_DELETE_INTF_MASTER,
            INTERFACE_ID_UPDATE_INTF_MASTER,
            INTERFACE_ID_DEVICE_STATUS_REQ,
            INTERFACE_ID_OTA_GET_APP_MASTER_DETAILS,
            INTERFACE_ID_OTA_CREATE_APP_MASTER,
            INTERFACE_ID_OTA_UPDATE_APP_MASTER,
            INTERFACE_ID_OTA_SEARCH_APP_MASTER,
            INTERFACE_ID_OTA_DELETE_APP_MASTER,
            INTERFACE_ID_OTA_GET_CHILD_APP_DETAILS,
            INTERFACE_ID_OTA_CREATE_APP_FILE,
            INTERFACE_ID_OTA_UPDATE_APP_FILE,
            INTERFACE_ID_OTA_SEARCH_APP_FILE,
            INTERFACE_ID_OTA_DELETE_APP_FILE,
            INTERFACE_ID_TASK_REPAIR_SEARCH,
            INTERFACE_ID_TASK_REPAIR_UPDATE,
            INTERFACE_ID_SEARCH_DEVICE_MASTER,
            INTERFACE_ID_DELETE_DEVICE_MASTER,
            INTERFACE_ID_UPDATE_DEVICE_MASTER,
            INTERFACE_ID_DRAG_DROP_INSERT,
            INTERFACE_ID_DRAG_DROP_DELETE,
            INTERFACE_ID_DRAG_DROP_SEARCH,
            INTERFACE_ID_DRAG_DROP_UPDATE,
            INTERFACE_ID_NOTIFY_MOBILE_NUMBER,
            INTERFACE_ID_NOTIFY_DEVICE,
            INTERFACE_ID_INSERT_BEACON,
            INTERFACE_ID_FETCH_BEACONDETAILS,
            INTERFACE_ID_UPDATE_BEACONDETAILS,
            INTERFACE_ID_FORGOT_PIN,
            INTERFACE_ID_FETCH_AUGUMENTED_REALITY,
            INTERFACE_ID_USER_AUTHORIZATION,
            INTERFACE_ID_DASHBOARD,
            INTERFACE_ID_MSG_STATS,
            INTERFACE_ID_CUSTOMER,
            INTERFACE_ID_CUSTOMER_LOCATION,
            INTERFACE_ID_CUSTOMER_DETAILS,
            INTERFACE_ID_GET_QUERY_DESIGNER_DATA,
            INTERFACE_ID_DEVICE_GRP_QUERY,
            INTERFACE_ID_APP_SCREEN_QUERY,
            INTERFACE_ID_SAVE_CUSTOMIZATION_DATA,
            INTERFACE_ID_GET_CUSTOMIZER_DETAILS,
            INTERFACE_ID_SAVE_APPACCESS,
            INTERFACE_ID_GET_INTF_DEF,
            INTERFACE_ID_WORKFLOW_START,
            INTERFACE_ID_WORKFLOW_NEXT,
            INTERFACE_ID_WORKFLOW_PREV,
            INTERFACE_ID_WORKFLOW_SAVE,
            INTERFACE_ID_WORKFLOW_TERMINATE,
            INTERFACE_ID_WORKFLOW_QUERY,
            INTERFACE_ID_WORKFLOW_ASSIGN,
            INTERFACE_ID_WORKFLOW_REASSIGN,
            INTERFACE_ID_WORKFLOW_ACQUIRE,
            INTERFACE_ID_WORKFLOW_UNASSIGN,
            INTERACE_ID_GET_USER_APPACCESS_TOKEN,
            INTERFACE_ID_PARSE_PRODUCT_JSON,
            INTERFACE_ID_PARSE_WIDGET_JSON,
            INTERFACE_ID_PARSE_META_JSON,
            INTERFACE_ID_INSERT_HTML_JSON,
            INTERACE_ID_RELOAD_LOGGER,
            INTERACE_ID_RELOAD_SERVER_PROPERTIES,
            INTERFACE_ID_ON_APP_LAUNCH};

    String[][] lValue = {
            /*
             * Internal interfaces for which Authorization is not required
             */
            {INTERFACE_ID_AUTHENTICATION, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Carry the request for user authentication", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_CHANGE_PIN, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_RE_LOGIN, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_AUDIT_LOG, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Carry the request for Access Logging", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_USER_REGISTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "To Register new User", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_INTF_AUTH_REQ, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "firstlevel", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_SCREEN_AUTH_REQ, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "firstlevel", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_FETCH_PRIVILEGE_SERVICE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Authorization Service for screen, interface or control", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_LOGOUT, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Used for Logout ", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_LOV, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_LOV, "Appzillon LOV services.", "", YES, NO, NO, NO, NO},
            {INTERFACE_ID_VALIDATE_AND_PROCESSIFACE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_OTP, "To validate OTP and Proccess Interface PayLoad", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_DEVICE_REGISTRATION, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request for device registration.", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_USER_DEVICE_REGISTRATION, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "To Register User Device", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_VALIDATE_OTP, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Carry the request to validate otp", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_REGENERATE_OTP, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Carry the request to generate otp", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_SEND_SMS, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "To send SMS ", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_SCHEDULER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SCHEDULER, "To Schedule jobs.", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_SMS_TXN, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "To log sms txn detail", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_USSD_TXN, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "To log uss txn detail", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_TXT_MSLG_LOG, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "To log sms txn detail", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_SMS_USER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "fetching details from user and app-master table", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_CHECK_SERVER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Checking Appzillon Server Is Up", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_OTAFILE_DOWNLOADREQ, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for  OTA file download ", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_OTA_GET_APP_FILE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "to get app file detail", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_MULTIFACTOR_DEVICE_REGISTRATION, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for register notification at app launch", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_TRACK_LOCATION, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "To track device location", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_GENERATE_CAPTCHA, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for  refreshing Captcha", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_ERROR_LOGGING, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for writting error logs", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_GET_CNVUI_WELCOME_MSG, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "To display cnvUI welcome message", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_GET_FIRST_CNVUI_DLG, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_CNVUI, "To fetch the first dialogue for the conversation id", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_GET_CNVUI_DLG, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_CNVUI, "To fetch the next dialogue for the given dialogue", INTERFACE_SESSION_REQ_NO, NO, NO, NO, NO, NO},
            {INTERFACE_ID_PROCESS_NLP_DATA, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NLP, "To process NLP", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_GET_APP_SEC_TOKENS, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "To Get Server Nonce", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_CREATE_TENANT, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Creation of New App at runtime", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            /*
            * Internal interfaces for which Authorization is required
            */
            {INTERFACE_ID_APP_USAGE_REPORT, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Carry the request to generate App usage report", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_CREATE_DEVICE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to Create a  Device", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_CREATE_GROUP, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to Create a new Group", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_CREATE_ROLE_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Carry Request to Persist in Role", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_CREATE_SCREEN, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Carry the request to create screen", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_CREATE_USER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Add User", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DELETE_DEVICE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to Delete a  Device", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DELETE_FILE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to delete uploaded file ", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DELETE_GROUP, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to Delete a Group", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DELETE_SCREEN, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Carry the request to delete screen", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_FILE_PUSH_SERVICE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to download a file", INTERFACE_SESSION_REQ_YES, YES, NO, YES, NO, NO},
            {INTERFACE_ID_FILE_PUSH_SERVICE_WS, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to download a file", INTERFACE_SESSION_REQ_NO, YES, NO, YES, NO, NO},
            {INTERFACE_ID_FILE_PUSH_SERVICE_WS, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to download a file after checking authorization for that user-id", INTERFACE_SESSION_REQ_YES, YES, NO, YES, NO, NO},
            {INTERFACE_ID_GET_GROUP_DETAIL, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to get group detail", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_GET_REQ_RESP, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Carry the request to get req/resp of a transaction", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_LOGIN_REPORT, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Carry the request to generate users login report", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_NOTIFICATION_APP_DETAIL, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to get app detail for notification", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_PUSH_NOTIFICATION, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to send Notification", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_SEARCH_DEVICE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to Search Devices", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_SEARCH_FILE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to search uploaded file detail", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_SEARCH_GROUP, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to Search Groups", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_SEARCH_SCREEN, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Carry the request to Search screens", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_SEARCH_TXN_LOG, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Carry the request to search transaction detail", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_UPDATE_DEVICE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to Update a  Device", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_UPDATE_GROUP, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to Create a new Group", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_UPDATE_SCREEN, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Carry the request to update screen", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_UPLOAD_FILE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to enter uploaded file detail with session", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_UPLOAD_FILE_WS, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to enter uploaded file detail without session", INTERFACE_SESSION_REQ_NO, YES, YES, YES, NO, NO},
            {INTERFACE_ID_UPLOAD_FILE_AUTH, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Carry the request to enter uploaded file detail after checking authorization of that userId", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DECRYPT, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Decrypt", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_LOGGING_REQ, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_INTERFACE, "Device Logging", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_WF_DASHBOARD_QUERY, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_WORKFLOW, "Workflow Dashboard Query", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_WF_PERSIST, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_WORKFLOW, "Workflow Persist", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_WF_QUERY, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_WORKFLOW, "Workflow Query", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_WF_QUERY_DB, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_WORKFLOW, "Workflow QueryDB", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_WF_QUERY_REQ, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_WORKFLOW, "Workflow Query Request", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_CREATE_PIN_RULES, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "password rules creation", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DELETE_PIN_RULES, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "password rules creation deletion", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_GET_PIN_RULES, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "password rules get", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_UPDATE_PIN_RULES, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "password rules updating", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_UPDATE_USER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "user creation", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DELETE_USER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "user deletion", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_SEARCH_USER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "user get", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_GET_ROLES_APPID_USERID, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Get User roles", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_GET_ROLES_APPID, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Get roles", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_PIN_RESET, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Password reset", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_UNLOCK_USER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Unlock user", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_GET_USER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Get User details ", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_UPDATE_ROLE_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Update role master", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DELETE_ROLE_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Delete role master", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_GET_ROLE_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Get role master", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_GET_SCREENS_INTF_APPID, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Get screens and interface", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_GET_SCREENS_INTF_APPID_ROLEID, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Get screen, interface and roles", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_SEARCH_INTF_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_INTERFACE, "Used for searching Interface master record ", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_CREATE_INTF_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_INTERFACE, "Used for creating Interface master record ", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DELETE_INTF_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_INTERFACE, "Used for deleting Interface master record ", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_UPDATE_INTF_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_INTERFACE, "Used for updating Interface master record ", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DEVICE_STATUS_REQ, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "to check the device status", INTERFACE_SESSION_REQ_NO, YES, YES, YES, NO, NO},
            {INTERFACE_ID_OTA_GET_APP_MASTER_DETAILS, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "to get app master detail", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_OTA_CREATE_APP_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for creating app master", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_OTA_UPDATE_APP_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for updating app master", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_OTA_SEARCH_APP_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for searching app master", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_OTA_DELETE_APP_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for deleting app master", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_OTA_GET_CHILD_APP_DETAILS, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "to get child app details for the user", INTERFACE_SESSION_REQ_NO, YES, YES, YES, NO, NO},
            {INTERFACE_ID_OTA_CREATE_APP_FILE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for creating app file", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_OTA_UPDATE_APP_FILE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for updating app file", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_OTA_SEARCH_APP_FILE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for searching app file", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_OTA_DELETE_APP_FILE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for deleting app file", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_TASK_REPAIR_SEARCH, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_WORKFLOW, "Task Repair Search", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_TASK_REPAIR_UPDATE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_WORKFLOW, "Task Repair update", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_SEARCH_DEVICE_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "search device master", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DELETE_DEVICE_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "delete device master", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_UPDATE_DEVICE_MASTER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "update device master", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DRAG_DROP_INSERT, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Insert into drag and drop", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DRAG_DROP_DELETE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Delete Record from drag and drop", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DRAG_DROP_SEARCH, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Search Record from drag and drop", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DRAG_DROP_UPDATE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Insert into drag and drop", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_NOTIFY_MOBILE_NUMBER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Send notification to mobile Number", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_NOTIFY_DEVICE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_NOTIFICATIONS, "Send notification to device.", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_INSERT_BEACON, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Insert Beacon Details", INTERFACE_SESSION_REQ_NO, YES, YES, YES, NO, NO},
            {INTERFACE_ID_FETCH_BEACONDETAILS, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Fetch user beacon details", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_UPDATE_BEACONDETAILS, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Update user beacon details", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_FORGOT_PIN, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "forget password", INTERFACE_SESSION_REQ_NO, YES, YES, YES, NO, NO},
            {INTERFACE_ID_FETCH_AUGUMENTED_REALITY, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "To fetch Augmented Reality Details.", INTERFACE_SESSION_REQ_NO, YES, YES, YES, NO, NO},
            {INTERFACE_ID_USER_AUTHORIZATION, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Authorize User", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DASHBOARD, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "DashBoard Service", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_MSG_STATS, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Message Statistics Service", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_CUSTOMER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Customer Overview Service", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_CUSTOMER_LOCATION, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Customer Location Service", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_CUSTOMER_DETAILS, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Customer Detail Report Service", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_GET_QUERY_DESIGNER_DATA, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Query the designer data", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_DEVICE_GRP_QUERY, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for microApps device groups querying", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_APP_SCREEN_QUERY, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "for MicroApps to query list of screens", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_SAVE_CUSTOMIZATION_DATA, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Save the customized data", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_GET_CUSTOMIZER_DETAILS, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Save the customized data", INTERFACE_SESSION_REQ_NO, YES, YES, YES, NO, NO},
            {INTERFACE_ID_SAVE_APPACCESS, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "insert/update user app access record", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_GET_INTF_DEF, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_INTERFACE, "Used for searching Interfaces Definition ", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_WORKFLOW_START, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_APPZILLON_WORKFLOW, "start workflow", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_WORKFLOW_NEXT, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_APPZILLON_WORKFLOW, "To get next stage(s) details", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_WORKFLOW_PREV, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_APPZILLON_WORKFLOW, "To get prev stage(s) details", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_WORKFLOW_SAVE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_APPZILLON_WORKFLOW, "To save the details about current stage", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_WORKFLOW_TERMINATE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_APPZILLON_WORKFLOW, "To end the workflow", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_WORKFLOW_QUERY, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_APPZILLON_WORKFLOW, "To fetch the details of the stage details for a given workflow sequence number", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_WORKFLOW_ASSIGN, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_APPZILLON_WORKFLOW, "To assign the specific stage details to a specific user", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_WORKFLOW_REASSIGN, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_APPZILLON_WORKFLOW, "To re-assign the specific stage details to a specific user", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_WORKFLOW_ACQUIRE, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_APPZILLON_WORKFLOW, "To acquire the ownership of specific stage details by a specific user", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERFACE_ID_WORKFLOW_UNASSIGN, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_APPZILLON_WORKFLOW, "To unAssign the ownership of specific stage details", INTERFACE_SESSION_REQ_YES, YES, YES, NO, NO, NO},
            {INTERACE_ID_GET_USER_APPACCESS_TOKEN, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "To Get UserAppAccess Token", INTERFACE_SESSION_REQ_NO, YES, YES, NO, NO, NO},
            {INTERFACE_ID_PARSE_PRODUCT_JSON, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Parse Product Json", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_PARSE_WIDGET_JSON, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Parse Widget Json", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_PARSE_META_JSON, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Parse Citi widget Json", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERFACE_ID_INSERT_HTML_JSON, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Insert Citi Screen Details", INTERFACE_SESSION_REQ_YES, YES, YES, YES, NO, NO},
            {INTERACE_ID_RELOAD_LOGGER, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Reload Un-bundled Logger File", INTERFACE_SESSION_REQ_NO, NO, NO, NO, NO, NO},
            {INTERACE_ID_RELOAD_SERVER_PROPERTIES, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_SMS, "Load server properties from DB", INTERFACE_SESSION_REQ_NO, NO, NO, NO, NO, NO},
            // merging requests for ios and android on app launch
            {INTERFACE_ID_ON_APP_LAUNCH, DEFAULT_APP_ID, INTERFACE_CATEGORY_INTERNAL, INTERFACE_TYPE_MULTI, "To process all the requests during app launch ", INTERFACE_SESSION_REQ_NO, NO, NO, NO, NO, NO}
    };


    private AppzillonInterfaceDetails() {
        LOG.debug("{} Inside Appzillon Interface Details", LOGGER_PREFIX_RESTFULL);
        interfaceDtlsMap = new HashMap<>();

        lAppzillonInterface = new HashMap<>();
        for (int i = 0; i < lValue.length; i++) {
            lAppzillonInterface.put(lKey[i], lValue[i]);
        }

        for (Map.Entry<String, String[]> entry : lAppzillonInterface.entrySet()) {
            interfaceDtlsMap.put(entry.getKey(), new AppzillonInterface(entry.getValue()));
        }
    }

    public static AppzillonInterfaceDetails getInstance() {
        if (cInterfaceDtls == null) {
            cInterfaceDtls = new AppzillonInterfaceDetails();
        }
        return cInterfaceDtls;
    }

    public void addInterface(String pInterfaceId,
                             AppzillonInterface pInterface) {
        LOG.debug("{} Add Interface", LOGGER_PREFIX_RESTFULL);
        interfaceDtlsMap.put(pInterfaceId, pInterface);
    }

    public void deleteInterface(String pInterfaceId) {
        LOG.debug("{} Delete Interface", LOGGER_PREFIX_RESTFULL);
        interfaceDtlsMap.remove(pInterfaceId);
    }

    public void updateInterface(String pInterfaceId,
                                AppzillonInterface pInterface) {
        LOG.debug("{} Update Interface", LOGGER_PREFIX_RESTFULL);
        AppzillonInterface lInterfaceDtls = interfaceDtlsMap.get(pInterfaceId);

        if (lInterfaceDtls == null) {
            LOG.error("{} Header's interface details not found and set message as not found under internal category", LOGGER_PREFIX_RESTFULL);
            UtilsException lUtilsException = UtilsException.getUtilsExceptionInstance();
            lUtilsException.setCode(UtilsException.Code.APZ_UT_003
                    .toString());
            throw lUtilsException;
        } else {
            LOG.debug("{} Header's interface details found and update interface id", LOGGER_PREFIX_RESTFULL);
            interfaceDtlsMap.remove(pInterfaceId);
            interfaceDtlsMap.put(pInterfaceId, pInterface);
        }

    }

    public AppzillonInterface getInterfaceDtls(String pInterfaceId) {
        return interfaceDtlsMap.get(pInterfaceId);
    }

    public JSONObject getInterfaceDtlsJson(String pInterfaceId) {
        JSONObject lInterfaceDtlsJson = null;
        try {
            AppzillonInterface lInterfaceDtls = interfaceDtlsMap.get(pInterfaceId);

            if (lInterfaceDtls == null) {
                LOG.error("{} Header's interface details not found and set message as not found under internal category", LOGGER_PREFIX_RESTFULL);
                UtilsException lUtilsException = UtilsException.getUtilsExceptionInstance();
                lUtilsException.setMessage(lUtilsException.getUtilsExceptionMessage(UtilsException.Code.APZ_UT_003));
                lUtilsException.setCode(UtilsException.Code.APZ_UT_003.toString());
                throw lUtilsException;
            } else {
                LOG.debug("{} Header's interface details found and update interface id", LOGGER_PREFIX_RESTFULL);
                lInterfaceDtlsJson = JSONUtils.getJsonStringFromMap(MapUtils.convertObjectToMap(lInterfaceDtls));
            }
        } catch (IllegalArgumentException ex) {
            LOG.error(LOGGER_PREFIX_RESTFULL, ex);
        }
        return lInterfaceDtlsJson;
    }

}
