apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: grafana-secret
  namespace: {{ .Values.nameSpace}}
spec:
  encryptedData:
    admin-password: {{ .Values.grafana_pass }}
    admin-user: {{ .Values.grafana_user }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: grafana-secret
      namespace: {{ .Values.nameSpace}}