{
 "title": "apz-notification-service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Application Properties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "delete",
     "type": "timeseries",
     "description": "delete_fetch api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "delete_fetch_time_seconds" },
      {
       "expr": "delete_fetch_time_seconds_count"
      },
      { "expr": "delete_fetch_time_seconds_max" },
      { "expr": "delete_fetch_time_seconds_sum" }
     ]
    },
    {
     "title": "list",
     "type": "timeseries",
     "description": "fetchAppProperties_fetch api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "fetchAppProperties_fetch_time_seconds"
      },
      {
       "expr": "fetchAppProperties_fetch_time_seconds_count"
      },
      {
       "expr": "fetchAppProperties_fetch_time_seconds_max"
      },
      {
       "expr": "fetchAppProperties_fetch_time_seconds_sum"
      }
     ]
    },
    {
     "title": "reload",
     "type": "timeseries",
     "description": "reload_fetch api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      { "expr": "reload_fetch_time_seconds" },
      {
       "expr": "reload_fetch_time_seconds_count"
      },
      { "expr": "reload_fetch_time_seconds_max" },
      { "expr": "reload_fetch_time_seconds_sum" }
     ]
    },
    {
     "title": "save",
     "type": "timeseries",
     "description": "addAppProperties_fetch api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "addAppProperties_fetch_time_seconds"
      },
      {
       "expr": "addAppProperties_fetch_time_seconds_count"
      },
      {
       "expr": "addAppProperties_fetch_time_seconds_max"
      },
      {
       "expr": "addAppProperties_fetch_time_seconds_sum"
      }
     ]
    },
    {
     "title": "update ",
     "type": "timeseries",
     "description": "update_fetch api metrics",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "targets": [
      { "expr": "update_fetch_time_seconds" },
      {
       "expr": "update_fetch_time_seconds_count"
      },
      { "expr": "update_fetch_time_seconds_max" },
      { "expr": "update_fetch_time_seconds_sum" }
     ]
    }
   ]
  },
  {
   "title": "Email",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "sendEmail",
     "type": "timeseries",
     "description": "sendEmail api metrics ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      { "expr": "sendEmail_fetch_time_seconds" },
      {
       "expr": "sendEmail_fetch_time_seconds_count"
      },
      {
       "expr": "sendEmail_fetch_time_seconds_max"
      },
      {
       "expr": "sendEmail_fetch_time_seconds_sum"
      }
     ]
    },
    {
     "title": "sendEmailWithAttachment",
     "type": "timeseries",
     "description": "sendEmailWithAttachment api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "sendEmailWithAttachment_fetch_time_seconds"
      },
      {
       "expr": "sendEmailWithAttachment_fetch_time_seconds_count"
      },
      {
       "expr": "sendEmailWithAttachment_fetch_time_seconds_max"
      },
      {
       "expr": "sendEmailWithAttachment_fetch_time_seconds_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "List of values queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "lovQuery",
     "type": "timeseries",
     "description": "lovQuery api metrics",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "targets": [
      { "expr": "lovQuery_fetch_time_seconds" },
      {
       "expr": "lovQuery_fetch_time_seconds_count"
      },
      {
       "expr": "lovQuery_fetch_time_seconds_max"
      },
      {
       "expr": "lovQuery_fetch_time_seconds_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Notification",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "createDevice",
     "type": "timeseries",
     "description": "createDevice api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      { "expr": "createDevice_time_seconds" },
      {
       "expr": "createDevice_fetch_time_seconds"
      },
      {
       "expr": "createDevice_fetch_time_seconds_count"
      },
      {
       "expr": "createDevice_fetch_time_seconds_max"
      },
      {
       "expr": "createDevice_fetch_time_seconds_sum"
      }
     ]
    },
    {
     "title": "deleteDevice",
     "type": "timeseries",
     "description": "deleteDevice",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "deleteDevice_fetch_time_seconds"
      },
      {
       "expr": "deleteDevice_fetch_time_seconds_count"
      },
      {
       "expr": "deleteDevice_fetch_time_seconds_max"
      },
      {
       "expr": "deleteDevice_fetch_time_seconds_sum"
      }
     ]
    },
    {
     "title": "getNotifRegId",
     "type": "timeseries",
     "description": "getNotifRegId api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "getNotifRegId_fetch_time_seconds"
      },
      {
       "expr": "getNotifRegId_fetch_time_seconds_count"
      },
      {
       "expr": "getNotifRegId_fetch_time_seconds_max"
      },
      {
       "expr": "getNotifRegId_fetch_time_seconds_sum"
      }
     ]
    },
    {
     "title": "notifyDevice",
     "type": "timeseries",
     "description": "notifyDevice",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "notifyDevice_fetch_time_seconds"
      },
      {
       "expr": "notifyDevice_fetch_time_seconds_count"
      },
      {
       "expr": "notifyDevice_fetch_time_seconds_max"
      },
      {
       "expr": "notifyDevice_fetch_time_seconds_sum"
      }
     ]
    },
    {
     "title": "registerDevice",
     "type": "timeseries",
     "description": "registerDevice api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "registerDevice_fetch_time_seconds"
      },
      {
       "expr": "registerDevice_fetch_time_seconds_count"
      },
      {
       "expr": "registerDevice_fetch_time_seconds_max"
      },
      {
       "expr": "registerDevice_fetch_time_seconds_sum"
      }
     ]
    },
    {
     "title": "searchDevices",
     "type": "timeseries",
     "description": "searchDevices api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "searchDevices_fetch_time_seconds"
      },
      {
       "expr": "searchDevices_fetch_time_seconds_count"
      },
      {
       "expr": "searchDevices_fetch_time_seconds_max"
      },
      {
       "expr": "searchDevices_fetch_time_seconds_sum"
      }
     ]
    },
    {
     "title": "updateDevice",
     "type": "timeseries",
     "description": "updateDevice api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "updateDevice_fetch_time_seconds"
      },
      {
       "expr": "updateDevice_fetch_time_seconds_count"
      },
      {
       "expr": "updateDevice_fetch_time_seconds_max"
      },
      {
       "expr": "updateDevice_fetch_time_seconds_sum"
      }
     ]
    },
    {
     "title": "createGroup",
     "type": "timeseries",
     "description": "createGroup api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "createGroupMaster_fetch_time_seconds"
      },
      {
       "expr": "createGroupMaster_fetch_time_seconds_count"
      },
      {
       "expr": "createGroupMaster_fetch_time_seconds_max"
      },
      {
       "expr": "createGroupMaster_fetch_time_seconds_sum"
      }
     ]
    },
    {
     "title": "getGroupDetail",
     "type": "timeseries",
     "description": "getGroupDetail api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "getGroupDetail_fetch_time_seconds"
      },
      {
       "expr": "getGroupDetail_fetch_time_seconds_count"
      },
      {
       "expr": "getGroupDetail_fetch_time_seconds_max"
      },
      {
       "expr": "getGroupDetail_fetch_time_seconds_sum"
      }
     ]
    },
    {
     "title": "deleteGroup",
     "type": "timeseries",
     "description": "deleteGroup api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      { "expr": "deleteGroup_fetch_time_seconds" },
      {
       "expr": "deleteGroup_fetch_time_seconds_count"
      },
      {
       "expr": "deleteGroup_fetch_time_seconds_max"
      },
      {
       "expr": "deleteGroup_fetch_time_seconds_sum"
      }
     ]
    },
    {
     "title": "updateGroupDetails",
     "type": "timeseries",
     "description": "updateGroupDetails api metrics",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "updateGroupDetails_fetch_time_seconds"
      },
      {
       "expr": "updateGroupDetails_fetch_time_seconds_count"
      },
      {
       "expr": "updateGroupDetails_fetch_time_seconds_max"
      },
      {
       "expr": "updateGroupDetails_fetch_time_seconds_sum"
      }
     ]
    }
   ]
  }
 ]
}