{
 "title": "apz-auth-service",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Application Properties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "properties_delete",
     "type": "timeseries",
     "description": "properties_delete",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "properties_delete_time_seconds" },
      {
       "expr": "properties_delete_time_seconds_count"
      },
      {
       "expr": "properties_delete_time_seconds_max"
      },
      {
       "expr": "properties_delete_time_seconds_sum"
      }
     ]
    },
    {
     "title": "properties_reload",
     "type": "timeseries",
     "description": "properties_reload",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "expr": "properties_reload_time_seconds" },
      {
       "expr": "properties_reload_time_seconds_count"
      },
      {
       "expr": "properties_reload_time_seconds_max"
      },
      {
       "expr": "properties_reload_time_seconds_sum"
      }
     ]
    },
    {
     "title": "properties_list",
     "type": "timeseries",
     "description": "properties_list",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      { "expr": "properties_list_time_seconds" },
      {
       "expr": "properties_list_time_seconds_count"
      },
      {
       "expr": "properties_list_time_seconds_max"
      },
      {
       "expr": "properties_list_time_seconds_sum"
      }
     ]
    },
    {
     "title": "properties_update",
     "type": "timeseries",
     "description": "properties_update",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      { "expr": "properties_update_time_seconds" },
      {
       "expr": "properties_update_time_seconds_count"
      },
      {
       "expr": "properties_update_time_seconds_max"
      },
      {
       "expr": "properties_update_time_seconds_sum"
      }
     ]
    },
    {
     "title": "properties_create",
     "type": "timeseries",
     "description": "properties_create",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
     "targets": [
      { "expr": "properties_create_time_seconds" },
      {
       "expr": "properties_create_time_seconds_count"
      },
      {
       "expr": "properties_create_time_seconds_max"
      },
      {
       "expr": "properties_create_time_seconds_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "authentication_authReqeust",
     "type": "timeseries",
     "description": "authentication_authReqeust",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "authentication_authReqeust_time_seconds"
      },
      {
       "expr": "authentication_authReqeust_time_seconds_count"
      },
      {
       "expr": "authentication_authReqeust_time_seconds_max"
      },
      {
       "expr": "authentication_authReqeust_time_seconds_sum"
      }
     ]
    },
    {
     "title": "authentication_logout",
     "type": "timeseries",
     "description": "authentication_logout",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "authentication_logout_time_seconds"
      },
      {
       "expr": "authentication_logout_time_seconds_count"
      },
      {
       "expr": "authentication_logout_time_seconds_max"
      },
      {
       "expr": "authentication_logout_time_seconds_sum"
      }
     ]
    },
    {
     "title": "authentication_changePassword",
     "type": "timeseries",
     "description": "authentication_changePassword",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "authentication_changePassword_time_seconds"
      },
      {
       "expr": "authentication_changePassword_time_seconds_count"
      },
      {
       "expr": "authentication_changePassword_time_seconds_max"
      },
      {
       "expr": "authentication_changePassword_time_seconds_sum"
      }
     ]
    },
    {
     "title": "authentication_login",
     "type": "timeseries",
     "description": "authentication_login",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "authentication_login_time_seconds"
      },
      {
       "expr": "authentication_login_time_seconds_count"
      },
      {
       "expr": "authentication_login_time_seconds_max"
      },
      {
       "expr": "authentication_login_time_seconds_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Authorization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "authorization_getScreensInterfaceByAppIdRoleId",
     "type": "timeseries",
     "description": "authorization_getScreensInterfaceByAppIdRoleId api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "authorization_getScreensInterfaceByAppIdRoleId_time_seconds"
      },
      {
       "expr": "authorization_getScreensInterfaceByAppIdRoleId_time_seconds_count"
      },
      {
       "expr": "authorization_getScreensInterfaceByAppIdRoleId_time_seconds_max"
      },
      {
       "expr": "authorization_getScreensInterfaceByAppIdRoleId_time_seconds_sum"
      }
     ]
    },
    {
     "title": "authorization_interfaces",
     "type": "timeseries",
     "description": "authorization_interfaces api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "authorization_interfaces_time_seconds"
      },
      {
       "expr": "authorization_interfaces_time_seconds_count"
      },
      {
       "expr": "authorization_interfaces_time_seconds_max"
      },
      {
       "expr": "authorization_interfaces_time_seconds_sum"
      }
     ]
    },
    {
     "title": "authorization_screens ",
     "type": "timeseries",
     "description": "authorization_screens api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "authorization_screens_time_seconds"
      },
      {
       "expr": "authorization_screens_time_seconds_count"
      },
      {
       "expr": "authorization_screens_time_seconds_max"
      },
      {
       "expr": "authorization_screens_time_seconds_sum"
      }
     ]
    },
    {
     "title": "authorization_fetchPrivilege",
     "type": "timeseries",
     "description": "authorization_fetchPrivilege api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "authorization_fetchPrivilege_time_seconds"
      },
      {
       "expr": "authorization_fetchPrivilege_time_seconds_count"
      },
      {
       "expr": "authorization_fetchPrivilege_time_seconds_max"
      },
      {
       "expr": "authorization_fetchPrivilege_time_seconds_sum"
      }
     ]
    },
    {
     "title": "authorization_getScreensInterfaceByAppId",
     "type": "timeseries",
     "description": "authorization_getScreensInterfaceByAppId api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "authorization_getScreensInterfaceByAppId_time_seconds"
      },
      {
       "expr": "authorization_getScreensInterfaceByAppId_time_seconds_count"
      },
      {
       "expr": "authorization_getScreensInterfaceByAppId_time_seconds_max"
      },
      {
       "expr": "authorization_getScreensInterfaceByAppId_time_seconds_sum"
      }
     ]
    },
    {
     "title": "authorization_defaultAuth",
     "type": "timeseries",
     "description": "authorization_defaultAuth api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "authorization_defaultAuth_time_seconds"
      },
      {
       "expr": "authorization_defaultAuth_time_seconds_count"
      },
      {
       "expr": "authorization_defaultAuth_time_seconds_max"
      },
      {
       "expr": "authorization_defaultAuth_time_seconds_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Devices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "device_userdevice ",
     "type": "timeseries",
     "description": "device_userdevice api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      { "expr": "device_userdevice_time_seconds" },
      {
       "expr": "device_userdevice_time_seconds_count"
      },
      {
       "expr": "device_userdevice_time_seconds_max"
      },
      {
       "expr": "device_userdevice_time_seconds_sum"
      }
     ]
    },
    {
     "title": "device_get ",
     "type": "timeseries",
     "description": "device_get api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      { "expr": "device_get_time_seconds" },
      { "expr": "device_get_time_seconds_count" },
      { "expr": "device_get_time_seconds_max" },
      { "expr": "device_get_time_seconds_sum" }
     ]
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "interface_list",
     "type": "timeseries",
     "description": "interface_list",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      { "expr": "interface_list_time_seconds" },
      {
       "expr": "interface_list_time_seconds_count"
      },
      {
       "expr": "interface_list_time_seconds_max"
      },
      {
       "expr": "interface_list_time_seconds_sum"
      }
     ]
    },
    {
     "title": "interface_update",
     "type": "timeseries",
     "description": "interface_update",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      { "expr": "interface_update_time_seconds" },
      {
       "expr": "interface_update_time_seconds_count"
      },
      {
       "expr": "interface_update_time_seconds_max"
      },
      {
       "expr": "interface_update_time_seconds_sum"
      }
     ]
    },
    {
     "title": "interface_create",
     "type": "timeseries",
     "description": "interface_create metrics api",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      { "expr": "interface_create_time_seconds" },
      {
       "expr": "interface_create_time_seconds_count"
      },
      {
       "expr": "interface_create_time_seconds_max"
      },
      {
       "expr": "interface_create_time_seconds_sum"
      }
     ]
    },
    {
     "title": "interface_description",
     "type": "timeseries",
     "description": "interface_description",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "interface_description_time_seconds"
      },
      {
       "expr": "interface_description_time_seconds_count"
      },
      {
       "expr": "interface_description_time_seconds_max"
      },
      {
       "expr": "interface_description_time_seconds_sum"
      }
     ]
    },
    {
     "title": "interface_updateDefinition",
     "type": "timeseries",
     "description": "interface_updateDefinition",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "interface_updateDefinition_time_seconds"
      },
      {
       "expr": "interface_updateDefinition_time_seconds_count"
      },
      {
       "expr": "interface_updateDefinition_time_seconds_max"
      },
      {
       "expr": "interface_updateDefinition_time_seconds_sum"
      }
     ]
    },
    {
     "title": "interface_search",
     "type": "timeseries",
     "description": "interface_search",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      { "expr": "interface_search_time_seconds" },
      {
       "expr": "interface_search_time_seconds_count"
      },
      {
       "expr": "interface_search_time_seconds_max"
      },
      {
       "expr": "interface_search_time_seconds_sum"
      }
     ]
    },
    {
     "title": "interface_interfaceDefinition",
     "type": "timeseries",
     "description": "interface_interfaceDefinition",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "interface_interfaceDefinition_time_seconds"
      },
      {
       "expr": "interface_interfaceDefinition_time_seconds_count"
      },
      {
       "expr": "interface_interfaceDefinition_time_seconds_max"
      },
      {
       "expr": "interface_interfaceDefinition_time_seconds_sum"
      }
     ]
    },
    {
     "title": "interface_delete",
     "type": "timeseries",
     "description": "interface_delete api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      { "expr": "interface_delete_time_seconds" },
      {
       "expr": "interface_delete_time_seconds_count"
      },
      {
       "expr": "interface_delete_time_seconds_max"
      },
      {
       "expr": "interface_delete_time_seconds_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "List of values queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "LOV Service",
     "type": "timeseries",
     "description": "lov service api metrics",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "targets": [
      { "expr": "lovQuery_service_time_seconds" },
      {
       "expr": "lovQuery_service_time_seconds_count"
      },
      {
       "expr": "lovQuery_service_time_seconds_max"
      },
      {
       "expr": "lovQuery_service_time_seconds_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Nonce",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "nonce_validate",
     "type": "timeseries",
     "description": "nonce_validate api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      { "expr": "nonce_validate_time_seconds" },
      {
       "expr": "nonce_validate_time_seconds_count"
      },
      {
       "expr": "nonce_validate_time_seconds_max"
      },
      {
       "expr": "nonce_validate_time_seconds_sum"
      }
     ]
    },
    {
     "title": "nonce_purge",
     "type": "timeseries",
     "description": "nonce_purge api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      { "expr": "nonce_purge_time_seconds" },
      { "expr": "nonce_purge_time_seconds_count" },
      { "expr": "nonce_purge_time_seconds_max" },
      { "expr": "nonce_purge_time_seconds_sum" }
     ]
    },
    {
     "title": "nonce_clearExpired",
     "type": "timeseries",
     "description": "nonce_clearExpired api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "nonce_clearExpired_time_seconds"
      },
      {
       "expr": "nonce_clearExpired_time_seconds_count"
      },
      {
       "expr": "nonce_clearExpired_time_seconds_max"
      },
      {
       "expr": "nonce_clearExpired_time_seconds_sum"
      }
     ]
    },
    {
     "title": "nonce_generate",
     "type": "timeseries",
     "description": "nonce_generate api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      { "expr": "nonce_generate_time_seconds" },
      {
       "expr": "nonce_generate_time_seconds_count"
      },
      {
       "expr": "nonce_generate_time_seconds_max"
      },
      {
       "expr": "nonce_generate_time_seconds_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "OTA Maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "ota_getAppMaster ",
     "type": "timeseries",
     "description": "ota_getAppMaster api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      { "expr": "ota_getAppMaster_time_seconds" },
      {
       "expr": "ota_getAppMaster_time_seconds_count"
      },
      {
       "expr": "ota_getAppMaster_time_seconds_max"
      },
      {
       "expr": "ota_getAppMaster_time_seconds_sum"
      }
     ]
    },
    {
     "title": "ota_getAppFile ",
     "type": "timeseries",
     "description": "ota_getAppFile api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      { "expr": "ota_getAppFile_time_seconds" },
      {
       "expr": "ota_getAppFile_time_seconds_count"
      },
      {
       "expr": "ota_getAppFile_time_seconds_max"
      },
      {
       "expr": "ota_getAppFile_time_seconds_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Role Maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "role_get",
     "type": "timeseries",
     "description": "role_get api  metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      { "expr": "role_get_time_seconds" },
      { "expr": "role_get_time_seconds_count" },
      { "expr": "role_get_time_seconds_max" },
      { "expr": "role_get_time_seconds_sum" }
     ]
    },
    {
     "title": "role_update",
     "type": "timeseries",
     "description": "role_update api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      { "expr": "role_update_time_seconds" },
      { "expr": "role_update_time_seconds_count" },
      { "expr": "role_update_time_seconds_max" },
      { "expr": "role_update_time_seconds_sum" }
     ]
    },
    {
     "title": "role_create",
     "type": "timeseries",
     "description": "role_create api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      { "expr": "role_create_time_seconds" },
      { "expr": "role_create_time_seconds_count" },
      { "expr": "role_create_time_seconds_max" },
      { "expr": "role_create_time_seconds_sum" }
     ]
    },
    {
     "title": "role_delete",
     "type": "timeseries",
     "description": "role_delete api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      { "expr": "role_delete_time_seconds" },
      { "expr": "role_delete_time_seconds_count" },
      { "expr": "role_delete_time_seconds_max" },
      { "expr": "role_delete_time_seconds_sum" }
     ]
    }
   ]
  },
  {
   "title": "Screen Maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "screen_search",
     "type": "timeseries",
     "description": "screen_search  api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      { "expr": "screen_search_time_seconds" },
      {
       "expr": "screen_search_time_seconds_count"
      },
      { "expr": "screen_search_time_seconds_max" },
      { "expr": "screen_search_time_seconds_sum" }
     ]
    },
    {
     "title": "screen_create",
     "type": "timeseries",
     "description": "screen_create api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      { "expr": "screen_create_time_seconds" },
      {
       "expr": "screen_create_time_seconds_count"
      },
      { "expr": "screen_create_time_seconds_max" },
      { "expr": "screen_create_time_seconds_sum" }
     ]
    },
    {
     "title": "screen_delete",
     "type": "timeseries",
     "description": "screen_delete api metrics",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      { "expr": "screen_delete_time_seconds" },
      {
       "expr": "screen_delete_time_seconds_count"
      },
      { "expr": "screen_delete_time_seconds_max" },
      { "expr": "screen_delete_time_seconds_sum" }
     ]
    },
    {
     "title": "screen_update",
     "type": "timeseries",
     "description": "screen_update",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      { "expr": "screen_update_time_seconds" },
      {
       "expr": "screen_update_time_seconds_count"
      },
      { "expr": "screen_update_time_seconds_max" },
      { "expr": "screen_update_time_seconds_sum" }
     ]
    }
   ]
  },
  {
   "title": "Security Parameters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Security Parameters",
     "type": "timeseries",
     "description": "Security Parameters API metrics",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "securityParams_fetch_time_seconds"
      },
      {
       "expr": "securityParams_fetch_time_seconds_count"
      },
      {
       "expr": "securityParams_fetch_time_seconds_max"
      },
      {
       "expr": "securityParams_fetch_time_seconds_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Session Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "session_validate",
     "type": "timeseries",
     "description": "session.validate api metrics",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "targets": [
      { "expr": "session_validate_time_seconds" },
      {
       "expr": "session_validate_time_seconds_count"
      },
      {
       "expr": "session_validate_time_seconds_max"
      },
      {
       "expr": "session_validate_time_seconds_sum"
      }
     ]
    },
    {
     "title": "session_updateLastReqTime",
     "type": "timeseries",
     "description": "session_updateLastReqTime api metrics",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "session_updateLastReqTime_time_seconds"
      },
      {
       "expr": "session_updateLastReqTime_time_seconds_count"
      },
      {
       "expr": "session_updateLastReqTime_time_seconds_max"
      },
      {
       "expr": "session_updateLastReqTime_time_seconds_sum"
      }
     ]
    },
    {
     "title": "Session_Update",
     "type": "timeseries",
     "description": "Session_Update api metrics",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
     "targets": [
      { "expr": "session_update_time_seconds" },
      {
       "expr": "session_update_time_seconds_count"
      },
      {
       "expr": "session_update_time_seconds_max"
      },
      {
       "expr": "session_update_time_seconds_sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "user_create",
     "type": "timeseries",
     "description": "user_create",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      { "expr": "user_create_time_seconds" },
      { "expr": "user_create_time_seconds_count" },
      { "expr": "user_create_time_seconds_max" },
      { "expr": "user_create_time_seconds_sum" }
     ]
    },
    {
     "title": "user_get",
     "type": "timeseries",
     "description": "user_get",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      { "expr": "user_get_time_seconds" },
      { "expr": "user_get_time_seconds_count" },
      { "expr": "user_get_time_seconds_max" },
      { "expr": "user_get_time_seconds_sum" }
     ]
    },
    {
     "title": "user_register",
     "type": "timeseries",
     "description": "user_register",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      { "expr": "user_register_time_seconds" },
      {
       "expr": "user_register_time_seconds_count"
      },
      { "expr": "user_register_time_seconds_max" },
      { "expr": "user_register_time_seconds_sum" }
     ]
    },
    {
     "title": "user_update",
     "type": "timeseries",
     "description": "user_update",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      { "expr": "user_update_time_seconds" },
      { "expr": "user_update_time_seconds_count" },
      { "expr": "user_update_time_seconds_max" },
      { "expr": "user_update_time_seconds_sum" }
     ]
    }
   ]
  }
 ]
}