--------------------------------------------------------
--  Migration script from 3.7.6 to 3.7.7
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE APZ_SERVER_PROPS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "APZ_SERVER_PROPS" (
  "APP_ID" VARCHAR2(10) NOT NULL,
  "APZ_SERVER_PROPS_KEY" VARCHAR2(100) NOT NULL,
  "APZ_SERVER_PROPS_VALUE" VARCHAR2(500),
  "APZ_SERVER_PROPS_DESC" VARCHAR2(255) ,
  PRIMARY KEY ("APP_ID", "APZ_SERVER_PROPS_KEY")
);
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE APZ_ENV_PROPS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "APZ_ENV_PROPS" (
  "APP_ID" VARCHAR2(10) NOT NULL,
  "ENVIRONMENT" VARCHAR2(10)  NOT NULL,
  "APZ_ENV_PROPS_KEY" VARCHAR2(100) NOT NULL,
  "APZ_ENV_PROPS_VALUE" VARCHAR2(500),
  "APZ_ENV_PROPS_DESC" VARCHAR2(255) ,
  PRIMARY KEY ("APP_ID", "APZ_ENV_PROPS_KEY","ENVIRONMENT")
);
