redis.password=FQHPcFWPSx5jlI5bUqKfwSeoZTxsTdykQDsybxZgJgTLgODc56DBrTR55PdQjb0Rpav+XMbJG64r8FT
redis.usessl=true
redis.verifyPeer=false

redis.cluster0.host=transit-passwd-0001-001.transit-passwd.5lpuro.use2.cache.amazonaws.com
redis.cluster0.port=6379
 
redis.cluster1.host=transit-passwd-0001-002.transit-passwd.5lpuro.use2.cache.amazonaws.com
redis.cluster1.port=6379
 
redis.cluster2.host=transit-passwd-0001-003.transit-passwd.5lpuro.use2.cache.amazonaws.com
redis.cluster2.port=6379

redis.cluster3.host=transit-passwd-0002-001.transit-passwd.5lpuro.use2.cache.amazonaws.com
redis.cluster3.port=6379

redis.cluster4.host=transit-passwd-0002-002.transit-passwd.5lpuro.use2.cache.amazonaws.com
redis.cluster4.port=6379

redis.cluster5.host=transit-passwd-0002-003.transit-passwd.5lpuro.use2.cache.amazonaws.com
redis.cluster5.port=6379