--------------------------------------------------------
--  DDL for Table TB_ASMI_SECURITY_PARAMETERS
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_SECURITY_PARAMETERS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_SECURITY_PARAMETERS" 
   (	"APP_ID" VARCHAR2(100), 
	"MIN_NUM_NUM" NUMBER(10,0), 
	"MIN_NUM_SPCL_CHAR" NUMBER(10,0), 
	"MIN_NUM_UPPER_CASE_CHAR" NUMBER(10,0),
	"MIN_NUM_LOWER_CASE_CHAR" NUMBER(10,0),
	"MIN_LENGTH" NUMBER(10,0), 
	"MAX_LENGTH" NUMBER(10,0), 
	"PASS_CHANGE_FREQ" NUMBER(10,0), 
	"LAST_N_PASS_NOT_TO_USE" NUMBER(10,0), 
	"SESSION_TIMEOUT" NUMBER(10,0), 
	"NOOFFAILEDCOUNTS" NUMBER(10,0), 
	"SERVER_TOKEN" VARCHAR2(255), 
	"FAIL_COUNT_TIMEOUT" NUMBER(10,0), 
	"PASSWORD_COUNT" NUMBER(10,0), 
	"DEFAULT_AUTHORIZATION" CHAR(1) DEFAULT 'Y',
	"RESTRICT_SPL_CHARS" VARCHAR2(100),
	"ALLOW_USER_PASSWORD_ENTRY" VARCHAR2(1) DEFAULT 'N',
	"AUTO_APPROVE" VARCHAR2(1) DEFAULT 'Y',
	"PWD_RSET_VALIDATE_PARAMS" VARCHAR2(45) DEFAULT 'BOTH',
	"PWD_RSET_COMM_CHANNEL" VARCHAR2(45) DEFAULT 'BOTH',
	"PWD_RSET_ACCEPT_USR_PWD" VARCHAR2(1) DEFAULT 'N',
	"TXN_LOG_REQ" VARCHAR2(45) DEFAULT 'Y',
	"CREATE_USER_ID" VARCHAR2(100), 
	"MAKER_ID" VARCHAR(45),
	"MAKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CHECKER_ID" VARCHAR(45),
	"CHECKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"AUTH_STATUS" VARCHAR(45) DEFAULT 'U',
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"PWD_COMM_CHANNEL" VARCHAR(45) DEFAULT 'BOTH',
	"MULTIPLE_SESSION_ALLOWED" VARCHAR2(1) DEFAULT 'Y',
	"TXN_LOG_PAYLOAD" VARCHAR(10) DEFAULT 'NONE',
	"VERSION_NO" NUMBER(10,0) DEFAULT 1,
	"OTP_LENGTH" NUMBER(10,0),
  	"OTP_VALIDATION_COUNT" NUMBER(10,0),
  	"OTP_EXPIRY" NUMBER(10,0),
	"OTP_RESEND" VARCHAR2(10),
	"OTP_FORMAT" VARCHAR2(20),
  	"OTP_RESEND_COUNT" NUMBER(10,0),
  	"OTP_REGEN_COUNT" NUMBER(10,0) DEFAULT 0,
  	"OTP_RESEND_LOCK_TIMEOUT" NUMBER(10,0),
  	"PWD_CHANGE_COMM_CHANNEL" varchar(30) DEFAULT 'BOTH',
  	"PASSWORD_ON_AUTHORIZATION" VARCHAR2(1) DEFAULT 'N',
  	"DATA_INTEGRITY" VARCHAR2(1) DEFAULT 'Y',
  	"FMW_TXN_REQ" VARCHAR(1) DEFAULT 'Y',
        "FMW_TXN_PAYLOAD" VARCHAR(10) DEFAULT 'NONE',
        "ACCESS_TOKEN_EXPIRY" NUMBER(10,0) DEFAULT 0
	   ) ;
   
--------------------------------------------------------
--  DDL for Table TB_ASHS_USER_PASSWORDS
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_USER_PASSWORDS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASHS_USER_PASSWORDS" 
   (	"USER_ID" VARCHAR2(100), 
	"APP_ID" VARCHAR2(100), 
	"PIN" VARCHAR2(255), 
	"CHANGE_TIME" TIMESTAMP (6), 
	"CREATE_USER_ID" VARCHAR2(100), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER(10,0) DEFAULT 1,
	CONSTRAINT "TB_ASHS_USER_PASSWORDS_PK" PRIMARY KEY ("USER_ID", "APP_ID", "PIN")  
   ) ;

--------------------------------------------------------
--  DDL for Table TB_ASLG_TXN_DETAIL
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASLG_TXN_DETAIL';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASLG_TXN_DETAIL" 
   (  "TXN_REF" VARCHAR2(255), 
  "USER_ID" VARCHAR2(100),
  "USER_APP_ID" VARCHAR2(100),
  "APP_USER_ID" VARCHAR2(100),
  "SESSION_ID" VARCHAR2(255),
  "DEVICE_ID" VARCHAR2(255), 
  "ST_TM" TIMESTAMP (6), 
  "END_TM" TIMESTAMP (6), 
  "INTERFACE_ID" VARCHAR2(50), 
  "APP_ID" VARCHAR2(100), 
  "TXN_STAT" VARCHAR2(20), 
  "REQ_LD_REFNO" VARCHAR2(100), 
  "REQ_NO_RECS" NUMBER(10,0), 
  "RES_LD_REFNO" VARCHAR2(100), 
  "RES_NO_RECS" NUMBER(10,0), 
  "INFO1" VARCHAR2(255) DEFAULT NULL,
  "INFO2" VARCHAR2(255) DEFAULT NULL,
  "INFO3" VARCHAR2(255) DEFAULT NULL,
  "INFO4" VARCHAR2(255) DEFAULT NULL,
  "INFO5" VARCHAR2(255) DEFAULT NULL,
  "CREATE_BY" VARCHAR2(200), 
   "SOURCE" VARCHAR2(4000),
   "LONGITUDE" VARCHAR2(4000),
   "LATITUDE" VARCHAR2(4000),
   "ORIGINATION" VARCHAR2(4000),
   "STATUS" VARCHAR2(4000),
   "SUBLOCALITY" VARCHAR2(4000),
   "ADMIN_AREA_LVL_1" VARCHAR2(4000),
   "ADMIN_AREA_LVL_2" VARCHAR2(4000),
   "COUNTRY" VARCHAR2(4000),
   "FORMATTED_ADDRESS" VARCHAR2(4000),
   "EXT_ST_TM" timestamp(6) DEFAULT NULL,
   "EXT_END_TM" timestamp(6) DEFAULT NULL,
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;

  --------------------------------------------------------
--  DDL for Table TB_ASTP_LD_RECS
--------------------------------------------------------

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASTP_LD_RECS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASTP_LD_RECS"
(
  "REF_NO" VARCHAR2(100),
  "SEQ_NO" NUMBER(10,0),
  "DATA1" VARCHAR2(4000),
  "DATA2" VARCHAR2(4000),
  "DATA3" VARCHAR2(4000),
  "DATA4" VARCHAR2(4000),
  "DATA5" VARCHAR2(4000),
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
);



   --------------------------------------------------------
--  DDL for Table TB_ASLG_FMW_TXN_DETAIL
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASLG_FMW_TXN_DETAIL';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASLG_FMW_TXN_DETAIL"
   (	"TXN_REF" VARCHAR2(255) PRIMARY KEY,
	    "MASTER_TXN_REF" VARCHAR2(255),
	    "INTERFACE_ID" VARCHAR2(50),
	    "REQ_LD_REFNO" VARCHAR2(100), 
  		"REQ_NO_RECS" NUMBER(10,0), 
  		"RES_LD_REFNO" VARCHAR2(100), 
  		"RES_NO_RECS" NUMBER(10,0), 
	    "ENDPOINT_TYPE" VARCHAR2(255),
	    "ST_TM" TIMESTAMP (6) DEFAULT NULL,
	    "END_TM" TIMESTAMP (6) DEFAULT NULL,
	    "STATUS" VARCHAR(1),
	    "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) ;

   --------------------------------------------------------
--  DDL for Table TB_ASMI_INTF_MASTER
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_INTF_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_INTF_MASTER" 
   (	"INTERFACE_ID" VARCHAR2(100), 
	"APP_ID" VARCHAR2(100), 
	"CATEGORY" VARCHAR2(30), 
	"TYPE" VARCHAR2(30), 
	"DESCRIPTION" VARCHAR2(100), 
	"AUTHRZ_REQ" VARCHAR2(1) DEFAULT 'Y',
	"CREATE_USER_ID" VARCHAR2(100), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"MAKER_ID" VARCHAR(45),
	"MAKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CHECKER_ID" VARCHAR(45),
	"CHECKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"AUTH_STATUS" VARCHAR(45) DEFAULT 'U',
	"CAPTCHA_REQ" VARCHAR2(5) DEFAULT 'TEXT',
	"CAPTCHA_TYPE" VARCHAR2(7) DEFAULT 'N',
	"INTERFACE_DEF" CLOB,
	"DG_TXN_LOG_REQ" VARCHAR2(1) DEFAULT 'Y',
	"TXN_LOG_REQ" VARCHAR2(1) DEFAULT 'Y',
	"TXN_LOG_PAYLOAD_REQ" VARCHAR2(10) DEFAULT 'NONE',
	"FMW_TXN_REQ" VARCHAR2(1) DEFAULT 'Y',
	"FMW_TXN_PAYLOAD_REQ" VARCHAR2(10) DEFAULT 'NONE',
	"VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_ROLE_INTF
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_ROLE_INTF';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_ROLE_INTF" 
   (	"APP_ID" VARCHAR2(100), 
	"ROLE_ID" VARCHAR2(100), 
	"INTERFACE_ID" VARCHAR2(100), 
	"CREATE_USER_ID" VARCHAR2(100), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_ROLE_MASTER
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_ROLE_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_ROLE_MASTER" 
   (	"ROLE_ID" VARCHAR2(255), 
	"APP_ID" VARCHAR2(100), 
	"ROLE_DESC" VARCHAR2(255), 
	"INTERFACE_ALLOWED" VARCHAR2(1) DEFAULT 'A',
  "SCREEN_ALLOWED" VARCHAR2(1) DEFAULT 'A',
  "CONTROL_ALLOWED" VARCHAR2(1) DEFAULT 'A',
	"CREATE_USER_ID" VARCHAR2(100), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	"MAKER_ID" VARCHAR(45),
	"MAKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CHECKER_ID" VARCHAR(45),
	"CHECKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"AUTH_STATUS" VARCHAR(45) DEFAULT 'U',	
	"VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_ROLE_SCR
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_ROLE_SCR';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_ROLE_SCR" 
   (	"APP_ID" VARCHAR2(100), 
	"SCREEN_ID" VARCHAR2(100), 
	"ROLE_ID" VARCHAR2(100), 
	"CREATE_USER_ID" VARCHAR2(100), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_SCR_MASTER
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_SCR_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_SCR_MASTER" 
   (	"SCREEN_ID" VARCHAR2(255), 
	"APP_ID" VARCHAR2(100), 
	"SCREEN_DESC" VARCHAR2(255), 
	"CREATE_USER_ID" VARCHAR2(100), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"MAKER_ID" VARCHAR(45),
	"MAKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CHECKER_ID" VARCHAR(45),
	"CHECKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"AUTH_STATUS" VARCHAR(45) DEFAULT 'U',	
	"VERSION_NO" NUMBER(10,0) DEFAULT 1,
	"SCREEN_TYPE" VARCHAR2(10) DEFAULT NULL,
    "SCREEN_NAME" VARCHAR2(100) DEFAULT NULL,
    "SCREEN_ICON" CLOB,
    "CUSTOMISABLE" VARCHAR2(1) DEFAULT NULL
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_USER
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_USER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_USER" 
   (	"USER_ID" VARCHAR2(100), 
	"APP_ID" VARCHAR2(100), 
	"PIN" VARCHAR2(300), 
	"USER_NAME" VARCHAR2(100),
	"LAST_NAME" VARCHAR2(100),
	"LOGIN_STATUS" VARCHAR2(3), 
	"FAIL_COUNT" NUMBER(10,0), 
	"USER_ACTIVE" VARCHAR2(3) DEFAULT 'Y', 
	"USER_LOCKED" VARCHAR2(3) DEFAULT 'N', 
	"LANGUAGE" VARCHAR2(2) DEFAULT 'en', 
	"EXTERNALIDENTIFIER" VARCHAR2(30), 
	"USER_ADDR1" VARCHAR2(50), 
	"USER_ADDR2" VARCHAR2(50), 
	"USER_ADDR3" VARCHAR2(50), 
	"USER_ADDR4" VARCHAR2(50), 
	"USER_EML1" VARCHAR2(255), 
	"USER_EML2" VARCHAR2(255), 
	"USER_PHNO1" VARCHAR2(20), 
	"USER_PHNO2" VARCHAR2(20), 
	"USER_LVL" NUMBER(11,0), 
	"USER_LOCK_TS" TIMESTAMP (6), 
	"PIN_CHANGE_TS" TIMESTAMP (6),
	"PROFILE_PIC" CLOB,
	"CREATE_USER_ID" VARCHAR2(100), 
	"MAKER_ID" VARCHAR2(45),
	"MAKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CHECKER_ID" VARCHAR2(45),
	"CHECKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"AUTH_STATUS" VARCHAR2(45) DEFAULT 'U',
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"DATE_OF_BIRTH" DATE,
	"ADD_INFO1" VARCHAR2(255),
  	"ADD_INFO2" VARCHAR2(255),
  	"ADD_INFO3" VARCHAR2(255),
  	"ADD_INFO4" VARCHAR2(255),
  	"ADD_INFO5" VARCHAR2(255),
	"VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_USER_DEVICES
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_USER_DEVICES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_USER_DEVICES" 
   (
	"APP_ID" VARCHAR2(100),   
	"DEVICE_ID" VARCHAR2(255), 
	"USER_ID" VARCHAR2(100), 
	"NOTIF_REG_ID" VARCHAR2(255), 
	"DEVICE_STATUS" VARCHAR2(100), 
	"CREATE_USER_ID" VARCHAR2(100), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"MAKER_ID" VARCHAR(45),
	"MAKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CHECKER_ID" VARCHAR(45),
	"CHECKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"AUTH_STATUS" VARCHAR(45) DEFAULT 'U',
	"VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_USER_ROLE
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_USER_ROLE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_USER_ROLE" 
   (	"USER_ID" VARCHAR2(100), 
	"ROLE_ID" VARCHAR2(100), 
	"APP_ID" VARCHAR2(100), 
	"CREATE_USER_ID" VARCHAR2(100), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASTP_LAST_LOGIN
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASTP_LAST_LOGIN';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASTP_LAST_LOGIN" 
   (	"USER_ID" VARCHAR2(100), 
	"APP_ID" VARCHAR2(100), 
	"DEVICE_ID" VARCHAR2(255), 
	"REQUEST_KEY" VARCHAR2(255), 
	"SESSION_ID" VARCHAR2(255), 
	"LAST_REQ_TIME" TIMESTAMP (6), 
	"LOGIN_TIME" TIMESTAMP (6), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER(10,0) DEFAULT 1,
	"OTP" varchar2(200),
	"OTP_GENERATION_TIME" timestamp(6) default SYSTIMESTAMP,
	"OTP_STATUS" VARCHAR2(1),
	"OTP_VALIDATION_COUNT" NUMBER(10,0) DEFAULT 0,
	"LONGITUDE" VARCHAR2(4000),
    "LATITUDE" VARCHAR2(4000),
    "SUBLOCALITY" VARCHAR2(4000),
    "ADMIN_AREA_LVL_1" VARCHAR2(4000),
    "ADMIN_AREA_LVL_2" VARCHAR2(4000),
    "COUNTRY" VARCHAR2(4000),
    "FORMATTED_ADDRESS" VARCHAR2(4000),
    "ORIGINATION" VARCHAR2(4000)
   ) ;
  
--------------------------------------------------------
--  DDL for Table TB_ASMI_DEVICE_MASTER
--------------------------------------------------------

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_DEVICE_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE TB_ASMI_DEVICE_MASTER(
	"APP_ID" VARCHAR2(100) NOT NULL,
	"DEVICE_ID" VARCHAR2(200) NOT NULL,
	"OS" VARCHAR2(20) NULL,
	"OS_VERSION" VARCHAR2(50) NULL,
	"MOBILE_NUMBER1" VARCHAR2(20) NULL,
	"MOBILE_NUMBER2" VARCHAR2(20) NULL,
	"MODEL" VARCHAR2(100) NULL,
	"MAKE" VARCHAR2(100) NULL,
	"SCREEN_RESOLUTION" VARCHAR2(100) NULL,
	"WIPED_OUT" VARCHAR2(1) DEFAULT 'N',
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	"DEVICE_NAME" VARCHAR2(100) NULL,
	"LONGITUDE" VARCHAR2(100) NULL,
	"LATITUDE" VARCHAR2(100) NULL,
	"APP_VERSION" VARCHAR2(50) NULL,
	CONSTRAINT TB_ASMI_DEVICE_MASTER_PK PRIMARY KEY (APP_ID, DEVICE_ID)
);
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASLG_AUDIT_LOG';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASLG_AUDIT_LOG"
  (
    "ACCESS_REF"     NUMBER(20,0) NOT NULL,
    "APP_ID"         VARCHAR2(100)  NULL,
    "USER_ID"        VARCHAR2(100) NULL,
    "DEVICE_ID"      VARCHAR2(250)  NULL,
    "SESSION_ID"     VARCHAR2(100) NULL,
    "ACTION"         VARCHAR2(30) NULL,
    "START_TIME_STAMP" VARCHAR2(30) NULL,
    "END_TIME_STAMP" VARCHAR2(30) NULL,
    "FIELD1"         VARCHAR2(100) NULL,
    "FIELD2"         VARCHAR2(100) NULL,
    "FIELD3"         VARCHAR2(100) NULL,
    "FIELD4"         VARCHAR2(100) NULL,
    "FIELD5"         VARCHAR2(100) NULL,
    "CREATE_DATE" DATE DEFAULT SYSDATE,
    "CREATE_USER_ID" VARCHAR2(100) NULL,
    "VERSION_NO" NUMBER(10,0) DEFAULT 1,
    CONSTRAINT "PK_TB_ASLG_AUDIT_LOG" PRIMARY KEY ( "ACCESS_REF"  )
  );
  
  
  /*
   * Changes done by Ripu on (10-Feb-2015)
   * Appzillon - 3.1 - Send SMS to User Start
   */
  
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_SMS_USER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASMI_SMS_USER"(
  "APP_ID" VARCHAR2(100 BYTE) NOT NULL,
  "USER_ID" VARCHAR2(100 BYTE) NOT NULL,
  "MOBILE_NUMBER" VARCHAR2(20 BYTE),
  "CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT systimestamp, 
	"VERSION_NO" NUMBER DEFAULT 0, 
	"SMS_REQ" VARCHAR2(1 BYTE),
	"USSD_REQ" VARCHAR2(1 BYTE),
  CONSTRAINT "TB_ASMI_SMS_USER_PK" PRIMARY KEY("APP_ID", "USER_ID")
);

--------------------------------------------------------
--  DDL for Table TB_ASLG_SMS_TXN
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASLG_SMS_TXN';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASLG_SMS_TXN" 
   (           
                "SMS_TXNREF" VARCHAR2(255) NOT NULL,
                "APP_ID" VARCHAR2(100),
                "MOBILE_NUMBER" VARCHAR2(20), 
                "REQUEST" VARCHAR2(4000),
                "MESSAGE_ID" VARCHAR2(20), 
                "ORIGINATION" VARCHAR2(20), 
                "START_TM" TIMESTAMP (6), 
				"RESPONSE" VARCHAR2(4000),
				"END_TM" TIMESTAMP (6), 
                "CREATED_BY" VARCHAR2(20), 
                "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
                PRIMARY KEY ("SMS_TXNREF") 
   ) ;
   
--------------------------------------------------------
--  DDL for Table TB_ASLG_USSD_TXN
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASLG_USSD_TXN';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASLG_USSD_TXN" 
   (           
                "USSD_TXNREF" VARCHAR2(255) NOT NULL,
                "APP_ID" VARCHAR2(100),
                "MOBILE_NUMBER" VARCHAR2(20),
                "REQUEST" VARCHAR2(200), 
				"ACTION" VARCHAR2(3000),
				"STEP" VARCHAR2(100),
                "ORIGINATION" VARCHAR2(20), 
                "START_TM" TIMESTAMP (6), 
				"RESPONSE" VARCHAR2(200),
				"END_TM" TIMESTAMP (6), 
                "CREATED_BY" VARCHAR2(20), 
                "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
                PRIMARY KEY ("USSD_TXNREF") 
   ) ;
   
--------------------------------------------------------
--  DDL for Table TB_ASLG_TXT_MSLG_LOG
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASLG_TXT_MSLG_LOG';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASLG_TXT_MSLG_LOG" 
   (           
                "TXT_TXNREF" VARCHAR2(255) NOT NULL, 
                "APP_ID" VARCHAR2(100),
                "MOBILE_NUMBER" VARCHAR2(20),
                "REQUEST" VARCHAR2(1000), 
                "PORT" VARCHAR2(10),
                "ORIGINATION" VARCHAR2(20), 
                "START_TM" TIMESTAMP (6), 
                "RESPONSE" VARCHAR2(200),
                "END_TM" TIMESTAMP (6),
                "CREATED_BY" VARCHAR2(20), 
                "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
                PRIMARY KEY ("TXT_TXNREF") 
   ) ;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_CONTROLS_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASMI_CONTROLS_MASTER" (
   "APP_ID" VARCHAR2(100) NOT NULL,
   "CONTROL_ID" VARCHAR2(255) NOT NULL,
   "CONTROL_DESC" VARCHAR2(255) DEFAULT NULL,
   "CREATED_BY" VARCHAR2(100) DEFAULT NULL,
   "CREATED_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
   "MAKER_ID" VARCHAR2(45),
   "MAKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
   "CHECKER_ID" VARCHAR2(45),
   "CHECKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
   "AUTH_STATUS" VARCHAR2(45) DEFAULT 'U',
   "VERSION_NO" NUMBER(10,0) DEFAULT 1,
   PRIMARY KEY ("APP_ID","CONTROL_ID")
  ) ;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_ROLE_CONTROLS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASMI_ROLE_CONTROLS" (
   "APP_ID" VARCHAR2(100) NOT NULL,
   "ROLE_ID" VARCHAR2(100) NOT NULL,
   "CONTROL_ID" VARCHAR2(100) NOT NULL,
   "CREATED_BY" VARCHAR2(100) DEFAULT NULL,
   "CREATED_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
   "VERSION_NO" NUMBER(10,0) DEFAULT 1,
   PRIMARY KEY ("APP_ID","ROLE_ID","CONTROL_ID")
) ;
 --------------------------------------------------------
--  DDL for Table TB_ASLG_JMS_REQ_RESP
--------------------------------------------------------

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASLG_JMS_REQ_RESP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASLG_JMS_REQ_RESP" 
   (	"TRANS_ID" NUMBER(20,0), 
	"INTERFACE_ID" VARCHAR2(150), 
	"APP_ID" VARCHAR2(100), 
	"REQ_TYPE" VARCHAR2(150), 
	"RES_TYPE" VARCHAR2(150), 
	"SENT_DATE" DATE, 
	"RECEIVED_DATE" DATE, 
	"MSG_ID" VARCHAR2(250), 
	"REQ_Q" VARCHAR2(250), 
	"RESP_Q" VARCHAR2(250), 
	"MSG_STATUS" NUMBER(1,0), 
	"MSG_SENT" CLOB, 
	"MSG_RECEIVED" CLOB, 
	"RESP_DESC" VARCHAR2(250),
  CONSTRAINT PK_TB_ASLG_JMS_REQ_RESP PRIMARY KEY (TRANS_ID, INTERFACE_ID, APP_ID) 
   ) ;
  BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_SECURITY_PARAMETERS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASHS_SECURITY_PARAMETERS" 
   (  "APP_ID" VARCHAR2(100), 
  "MIN_NUM_NUM" NUMBER(10,0), 
  "MIN_NUM_SPCL_CHAR" NUMBER(10,0), 
  "MIN_NUM_UPPER_CASE_CHAR" NUMBER(10,0), 
  "MIN_LENGTH" NUMBER(10,0), 
  "MAX_LENGTH" NUMBER(10,0), 
  "PASS_CHANGE_FREQ" NUMBER(10,0), 
  "LAST_N_PASS_NOT_TO_USE" NUMBER(10,0), 
  "SESSION_TIMEOUT" NUMBER(10,0), 
  "NOOFFAILEDCOUNTS" NUMBER(10,0), 
  "SERVER_TOKEN" VARCHAR2(255), 
  "FAIL_COUNT_TIMEOUT" NUMBER(10,0), 
  "PASSWORD_COUNT" NUMBER(10,0), 
  "DEFAULT_AUTHORIZATION" CHAR(1) DEFAULT 'Y',
  "RESTRICT_SPL_CHARS" VARCHAR2(100),
  "ALLOW_USER_PASSWORD_ENTRY" VARCHAR2(1) DEFAULT 'N',
  "AUTO_APPROVE" VARCHAR2(1) DEFAULT 'Y',
  "PWD_RSET_VALIDATE_PARAMS" VARCHAR2(45) DEFAULT 'BOTH',
  "PWD_RSET_COMM_CHANNEL" VARCHAR2(45) DEFAULT 'BOTH',
  "PWD_RSET_ACCEPT_USR_PWD" VARCHAR2(1) DEFAULT 'N',
  "TXN_LOG_REQ" VARCHAR2(45) DEFAULT 'Y',
  "CREATE_USER_ID" VARCHAR2(100), 
  "MAKER_ID" VARCHAR(45),
  "MAKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "CHECKER_ID" VARCHAR(45),
  "CHECKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "AUTH_STATUS" VARCHAR(45) DEFAULT 'U',
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "PWD_COMM_CHANNEL" VARCHAR(45) DEFAULT 'BOTH',
  "MULTIPLE_SESSION_ALLOWED" VARCHAR2(1) DEFAULT 'Y',
  "TXN_LOG_PAYLOAD" VARCHAR(1) DEFAULT 'Y',
  "VERSION_NO" NUMBER(10,0) DEFAULT 1,
  "OTP_LENGTH" NUMBER(10,0),
  	"OTP_VALIDATION_COUNT" NUMBER(10,0),
  	"OTP_EXPIRY" NUMBER(10,0),
	"OTP_RESEND" VARCHAR2(10),
	"OTP_FORMAT" VARCHAR2(20),
  	"OTP_RESEND_COUNT" NUMBER(10,0),
  	"OTP_RESEND_LOCK_TIMEOUT" NUMBER(10,0),
  	"PWD_CHANGE_COMM_CHANNEL" varchar(30) DEFAULT 'BOTH',
  	"PASSWORD_ON_AUTHORIZATION" VARCHAR2(1) DEFAULT 'N',
  	"DATA_INTEGRITY" VARCHAR2(1) DEFAULT 'Y',
        "ACCESS_TOKEN_EXPIRY" NUMBER(10,0) DEFAULT 0
     ) ;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_ROLE_INTF';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASHS_ROLE_INTF" 
   (  "APP_ID" VARCHAR2(100), 
  "ROLE_ID" VARCHAR2(100), 
  "INTERFACE_ID" VARCHAR2(100), 
  "CREATE_USER_ID" VARCHAR2(100), 
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASHS_ROLE_MASTER
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_ROLE_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASHS_ROLE_MASTER" 
   (  "ROLE_ID" VARCHAR2(255), 
  "APP_ID" VARCHAR2(100), 
  "ROLE_DESC" VARCHAR2(255), 
  "INTERFACE_ALLOWED" VARCHAR2(1) DEFAULT 'A',
  "SCREEN_ALLOWED" VARCHAR2(1) DEFAULT 'A',
  "CONTROL_ALLOWED" VARCHAR2(1) DEFAULT 'A',
  "CREATE_USER_ID" VARCHAR2(100), 
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
  "MAKER_ID" VARCHAR(45),
  "MAKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "CHECKER_ID" VARCHAR(45),
  "CHECKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "AUTH_STATUS" VARCHAR(45) DEFAULT 'U',  
  "VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASHS_ROLE_SCR
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_ROLE_SCR';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASHS_ROLE_SCR" 
   (  "APP_ID" VARCHAR2(100), 
  "SCREEN_ID" VARCHAR2(100), 
  "ROLE_ID" VARCHAR2(100), 
  "CREATE_USER_ID" VARCHAR2(100), 
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_USER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASHS_USER" 
   (  "USER_ID" VARCHAR2(100), 
  "APP_ID" VARCHAR2(100), 
  "PIN" VARCHAR2(300), 
  "USER_NAME" VARCHAR2(100),
  "LAST_NAME" VARCHAR2(100),
  "LOGIN_STATUS" VARCHAR2(3), 
  "FAIL_COUNT" NUMBER(10,0), 
  "USER_ACTIVE" VARCHAR2(3) DEFAULT 'Y', 
  "USER_LOCKED" VARCHAR2(3) DEFAULT 'N', 
  "LANGUAGE" VARCHAR2(2) DEFAULT 'en', 
  "EXTERNALIDENTIFIER" VARCHAR2(30), 
  "USER_ADDR1" VARCHAR2(50), 
  "USER_ADDR2" VARCHAR2(50), 
  "USER_ADDR3" VARCHAR2(50), 
  "USER_ADDR4" VARCHAR2(50), 
  "USER_EML1" VARCHAR2(255), 
  "USER_EML2" VARCHAR2(255), 
  "USER_PHNO1" VARCHAR2(20), 
  "USER_PHNO2" VARCHAR2(20), 
  "USER_LVL" NUMBER(11,0), 
  "USER_LOCK_TS" TIMESTAMP (6), 
  "PIN_CHANGE_TS" TIMESTAMP (6),
  "PROFILE_PIC" CLOB,
  "CREATE_USER_ID" VARCHAR2(100), 
  "MAKER_ID" VARCHAR2(45),
  "MAKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "CHECKER_ID" VARCHAR2(45),
  "CHECKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "AUTH_STATUS" VARCHAR2(45) DEFAULT 'U',
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "DATE_OF_BIRTH" DATE,
  "ADD_INFO1" VARCHAR2(255),
    "ADD_INFO2" VARCHAR2(255),
    "ADD_INFO3" VARCHAR2(255),
    "ADD_INFO4" VARCHAR2(255),
    "ADD_INFO5" VARCHAR2(255),
  "VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASHS_USER_DEVICES
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_USER_DEVICES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASHS_USER_DEVICES" 
   (
  "APP_ID" VARCHAR2(100),   
  "DEVICE_ID" VARCHAR2(255), 
  "USER_ID" VARCHAR2(100), 
  "DEVICE_STATUS" VARCHAR2(100), 
  "CREATE_USER_ID" VARCHAR2(100), 
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "MAKER_ID" VARCHAR(45),
  "MAKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "CHECKER_ID" VARCHAR(45),
  "CHECKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "AUTH_STATUS" VARCHAR(45) DEFAULT 'U',
  "VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASHS_USER_ROLE
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_USER_ROLE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASHS_USER_ROLE" 
   (  "USER_ID" VARCHAR2(100), 
  "ROLE_ID" VARCHAR2(100), 
  "APP_ID" VARCHAR2(100), 
  "CREATE_USER_ID" VARCHAR2(100), 
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
  "VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_SMS_USER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
 CREATE TABLE "TB_ASHS_SMS_USER"(
  "APP_ID" VARCHAR2(100 BYTE) NOT NULL,
  "MOBILE_NUMBER" VARCHAR2(20 BYTE),
  "USER_ID" VARCHAR2(100 BYTE) NOT NULL,
  "CREATED_BY" VARCHAR2(50 BYTE), 
  "CREATE_TS" TIMESTAMP (6) DEFAULT systimestamp, 
  "VERSION_NO" NUMBER DEFAULT 0, 
  "SMS_REQ" VARCHAR2(1 BYTE),
  "USSD_REQ" VARCHAR2(1 BYTE),
  CONSTRAINT "TB_ASHS_SMS_USER_PK" PRIMARY KEY("APP_ID", "USER_ID","VERSION_NO")
);
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_ROLE_CONTROLS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASHS_ROLE_CONTROLS" (
   "APP_ID" VARCHAR2(100) NOT NULL,
   "ROLE_ID" VARCHAR2(100) NOT NULL,
   "CONTROL_ID" VARCHAR2(100) NOT NULL,
   "CREATED_BY" VARCHAR2(100) DEFAULT NULL,
   "CREATED_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
   "VERSION_NO" NUMBER(10,0) DEFAULT 1,
   PRIMARY KEY ("APP_ID","ROLE_ID","CONTROL_ID","VERSION_NO")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_USER_APP_ACCESS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASMI_USER_APP_ACCESS" (
	"APP_ID" VARCHAR2(100) NOT NULL,
  	"USER_ID" VARCHAR2(100) NOT NULL,
  	"ALLOWED_APP_ID" VARCHAR2(100) NOT NULL,
  	"APP_ACCESS" VARCHAR2(1) DEFAULT 'D',
  	"CREATE_USER_ID" VARCHAR2(100) DEFAULT NULL,
  	"CREATE_TS" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  	"VERSION_NO" NUMBER(10,0) DEFAULT 1,
  CONSTRAINT "TB_ASMI_USER_APP_ACCESS_PK" PRIMARY KEY ("APP_ID", "USER_ID", "ALLOWED_APP_ID")
);
 
 BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_USER_APP_ACCESS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASHS_USER_APP_ACCESS" (
    "APP_ID" VARCHAR2(100) NOT NULL,
  	"USER_ID" VARCHAR2(100) NOT NULL,
  	"ALLOWED_APP_ID" VARCHAR2(100) NOT NULL,
  	"APP_ACCESS" VARCHAR2(1) DEFAULT 'D',
  	"CREATE_USER_ID" VARCHAR2(100) DEFAULT NULL,
  	"CREATE_TS" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  	"VERSION_NO" NUMBER(10,0) DEFAULT 1,
  CONSTRAINT "TB_ASHS_USER_APP_ACCESS_PK" PRIMARY KEY ("APP_ID", "USER_ID", "ALLOWED_APP_ID","VERSION_NO")
 ) ;
 

 -------------------------------------
--  DDL for Index TB_ASMI_APP_MASTER
----------------------------------------

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_APP_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
   CREATE TABLE "TB_ASMI_APP_MASTER" 
   (	
	"APP_ID" VARCHAR2(100) NOT NULL,
	"PARENT_APPID" VARCHAR2(100) NULL,
	"APP_NAME" VARCHAR2(100) NOT NULL,
    "CONTAINER_APP" VARCHAR2(1),
    "OTA_REQ" VARCHAR2(1),
	"REMOTE_DEBUG" VARCHAR2(1), 
	"EXPIRY_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	"APP_DESCRIPTION" VARCHAR2(200),
	"DEFAULT_LANGUAGE" VARCHAR2(20),
	"CREATE_USER_ID" VARCHAR2(20), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER(10,0) DEFAULT 1,
	 "BASE_APP" VARCHAR2(1),
    "MICRO_APP_TYPE" VARCHAR2(10),
    "PRIMARY_MICRO_APP" VARCHAR2(1) DEFAULT 'N',
    "APP_ICON" CLOB,
    "APP_VERSION" VARCHAR2(20) NOT NULL,
    "IDE_VERSION" VARCHAR2(20) NOT NULL,
    "MAKER_ID" VARCHAR2(45),
    "MAKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
    "CHECKER_ID" VARCHAR2(45),
    "CHECKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
    "AUTH_STATUS" VARCHAR2(45) DEFAULT 'U',
    "WELCOME_MSG" VARCHAR2(255),
    "ANDROID_SIGNATURE" VARCHAR2(200),
	CONSTRAINT "TB_ASMI_APP_MASTER_PK" PRIMARY KEY ("APP_ID")
   ) ;
   
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASNF_APP_OS_NOTIF_CODE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

  	CREATE TABLE TB_ASNF_APP_OS_NOTIF_CODE(
  	"APP_ID" VARCHAR2(100) NOT NULL, 
	"OS_ID" VARCHAR2(45), 
	"NOTIF_CODE" VARCHAR2(255),
	"ACTION_CODE" VARCHAR2(255),
    "ACTION_DISPLAY" VARCHAR2(255),
   	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
   	CONSTRAINT "TB_ASNF_APP_OS_NOTIF_CODE_PK" PRIMARY KEY("APP_ID", "OS_ID", "NOTIF_CODE","ACTION_CODE")
   	);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_DEVICE_GRPS';
EXCEPTION
   WHEN OTHERS THEN
   IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE TB_ASMI_DEVICE_GRPS (
  "APP_ID" VARCHAR2(100) NOT NULL,
  "DEVICE_GROUP_ID" VARCHAR2(100) NOT NULL,
  "DEVICE_GROUP_DESCRIPTION" VARCHAR2(1000) NOT NULL,
  "OS" VARCHAR2(10) NOT NULL,
  "HEIGHT" number(10) NOT NULL,
  "WIDTH" number(10) NOT NULL,
  "ORIENTATION_LOCK" VARCHAR2(10) DEFAULT NULL,
  PRIMARY KEY (APP_ID,DEVICE_GROUP_ID)
) ;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_SCREEN_LAYOUTS';
EXCEPTION
   WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/
CREATE TABLE TB_ASMI_SCREEN_LAYOUTS (
  "APP_ID" VARCHAR2(6) NOT NULL,
  "SCREEN_ID" VARCHAR2(100) NOT NULL,
  "LAYOUT_ID" VARCHAR2(100) NOT NULL,
  "LAYOUT_NAME" VARCHAR2(100) NOT NULL,
  "LAYOUT_ICON" clob,
  "DEFAULT_TEMPLATE" VARCHAR2(100) NOT NULL,
  PRIMARY KEY (APP_ID,SCREEN_ID,LAYOUT_ID)
) ;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_SCREEN_MICRO_APP';
EXCEPTION
   WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE TB_ASMI_SCREEN_MICRO_APP (
  "APP_ID" VARCHAR2(6) NOT NULL,
  "SCREEN_ID" VARCHAR2(100) NOT NULL,
  "MICRO_APP_ID" VARCHAR2(6) NOT NULL,
  "CREATE_TS" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL ,
  PRIMARY KEY (APP_ID,SCREEN_ID,MICRO_APP_ID)
) ;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_SCREEN_WIDGETS';
EXCEPTION
   WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
     RAISE;
    END IF;
END;
/

CREATE TABLE TB_ASMI_SCREEN_WIDGETS (
  "APP_ID" VARCHAR2(100) NOT NULL,
  "SCREEN_ID" VARCHAR2(100) NOT NULL,
  "CALLFORM_ID" VARCHAR2(100) NOT NULL,
  "CREATE_TS" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL ,
  PRIMARY KEY (APP_ID,SCREEN_ID,CALLFORM_ID)
) ;


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_DESIGN_OBJECTS';
EXCEPTION
   WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
     RAISE;
    END IF;
END;
/

CREATE TABLE TB_ASMI_DESIGN_OBJECTS (
  "APP_ID" VARCHAR2(100) NOT NULL,
  "SCREEN_ID" VARCHAR2(100) NOT NULL,
  "LAYOUT_ID" VARCHAR2(100) NOT NULL,
  "DESIGN_ID" VARCHAR2(100) NOT NULL,
  "PARENT_ID" VARCHAR2(100) NOT NULL,
  "CHILD_ID" VARCHAR2(100) NOT NULL,
  "CHILD_SEQ" number(10) NOT NULL,
  PRIMARY KEY (APP_ID,SCREEN_ID,LAYOUT_ID,DESIGN_ID,PARENT_ID,CHILD_ID)
) ;


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASCZ_SCREEN_LAYOUTS';
EXCEPTION
   WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
     RAISE;
    END IF;
END;
/

CREATE TABLE TB_ASCZ_SCREEN_LAYOUTS (
  "APP_ID" varchar2(6) NOT NULL,
  "SCREEN_ID" VARCHAR2(100) NOT NULL,
  "LAYOUT_ID" VARCHAR2(100) NOT NULL,
  "DEFAULT_TEMPLATE" VARCHAR2(100) NOT NULL,
  "CREATE_TS" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL ,
  "MAKER_ID" VARCHAR2(45),
  "MAKER_TS" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  "CHECKER_ID" VARCHAR2(45),
  "CHECKER_TS" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) NULL ,
  "AUTH_STATUS" VARCHAR2(1) DEFAULT 'U',
  "VERSION_NO" number(10) DEFAULT 1,
  PRIMARY KEY (APP_ID,SCREEN_ID,LAYOUT_ID)
) ;


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASCZ_TEMPLATE_OBJECTS';
EXCEPTION
   WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
     RAISE;
    END IF;
END;
/

CREATE TABLE TB_ASCZ_TEMPLATE_OBJECTS (
  "APP_ID" VARCHAR2(6) NOT NULL,
  "SCREEN_ID" VARCHAR2(100) NOT NULL,
  "LAYOUT_ID" VARCHAR2(100) NOT NULL,
  "TEMPLATE_ID" VARCHAR2(100) NOT NULL,
  "PARENT_ID" VARCHAR2(100) NOT NULL,
  "CHILD_ID" VARCHAR2(100) NOT NULL,
  "CHILD_SEQ" number(10) NOT NULL,
  PRIMARY KEY (APP_ID,SCREEN_ID,LAYOUT_ID,TEMPLATE_ID,PARENT_ID,CHILD_ID)
) ;


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASTP_SESSION_STORAGE';
EXCEPTION
   WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
     RAISE;
    END IF;
END;
/

CREATE TABLE "TB_ASTP_SESSION_STORAGE"(
"APP_ID" VARCHAR2(100) NOT NULL,
"USER_ID" VARCHAR2(100) NOT NULL,
"SESSION_ID" VARCHAR2(255) NOT NULL,
"DEVICE_ID" VARCHAR2(255) NULL,
"SESSION_KEY" VARCHAR2(255) NOT NULL,
"SESSION_VALUE" CLOB NOT NULL,
"CREATED_BY" VARCHAR2(100) NULL,
"CREATE_TS" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
PRIMARY KEY ("APP_ID","USER_ID","SESSION_ID", "SESSION_KEY")
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_DBTP_TXN_MASTER';
EXCEPTION
   WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
     RAISE;
    END IF;
END;
/

CREATE TABLE TB_DBTP_TXN_MASTER (
  "TXN_REF_NO" VARCHAR2(255) NOT NULL,
  "APP_ID" VARCHAR2(6) NOT NULL,
  "USER_ID" VARCHAR2(100) NOT NULL,
  "CUSTOMER_ID" VARCHAR2(100) NOT NULL,
  "AMOUNT" NUMBER(22,3) NOT NULL,
  "TXN_TYPE" VARCHAR2(20) NOT NULL,
  "TXN_STATUS" VARCHAR2(1) DEFAULT 'U',
  "CREATION_TS" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  "COMPLETION_TS" TIMESTAMP(6) NULL,
   PRIMARY KEY (TXN_REF_NO)
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASLG_DEVICE_LOCATION';
EXCEPTION
   WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
     RAISE;
    END IF;
END;
/

CREATE TABLE TB_ASLG_DEVICE_LOCATION (
  "APP_ID" VARCHAR2(100) NOT NULL,
  "DEVICE_ID" VARCHAR2(255) NOT NULL,
  "LATITUDE" VARCHAR2(255) DEFAULT NULL,
  "LONGITUDE" VARCHAR2(255) DEFAULT NULL,
  "CREATE_TS"  TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
   PRIMARY KEY (APP_ID,DEVICE_ID)
 );

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_CAPTCHA_DTLS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE "TB_ASMI_CAPTCHA_DTLS" (
  "CAPTCHA_REF" NUMBER(20,0) NOT NULL,
  "APP_ID" VARCHAR2(100) ,
  "CAPTCHA_STRING" VARCHAR2(255),
  "AUDIO_CAPTCHA" VARCHAR2(255),
  "INTERFACE_ID" VARCHAR2(100) ,
  "SESSION_ID" VARCHAR2(255),
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
  "VALIDATE_TS" TIMESTAMP,
  "CAPTCHA_STATUS" VARCHAR(2) DEFAULT 'NP',
  "VERSION_NO" NUMBER(10,0) DEFAULT 0 NOT NULL,
  CONSTRAINT "TB_ASMI_CAPTCHA_DTLS_PK" PRIMARY KEY ("CAPTCHA_REF")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_CNVUI_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASMI_CNVUI_MASTER" (
  "APP_ID" VARCHAR2(100) NOT NULL,
  "CNVUI_ID" VARCHAR2(100) NOT NULL,
  "CNVUI_DESC" VARCHAR2(100),
  "CREATE_USER_ID" VARCHAR2(100) DEFAULT NULL,
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
  "VERSION_NO" NUMBER(10,0) DEFAULT 1,
  CONSTRAINT "TB_ASMI_CNVUI_MASTER_PK" PRIMARY KEY ("APP_ID","CNVUI_ID")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_DLG_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASMI_DLG_MASTER" (
  "APP_ID" VARCHAR2(100) NOT NULL,
  "CNVUI_ID" VARCHAR2(100) NOT NULL,
  "DLG_ID" VARCHAR2(100) NOT NULL,
  "DLG_DESC" VARCHAR2(100),
  "DLG_TYPE" VARCHAR2(100),
  "DLG_SEQ" NUMBER(10,0),
  "NXT_DLG_ID" VARCHAR2(100),
  "RESP_DLG_ID" VARCHAR2(100),
  "RESP_TYPE" VARCHAR2(100),
  "SCREEN_ID" VARCHAR2(100),
  "INTERFACE_ID" VARCHAR2(100),
  "CREATE_USER_ID" VARCHAR2(100) DEFAULT NULL,
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
  "MAKER_ID" VARCHAR2(45),
  "MAKER_TS" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  "CHECKER_ID" VARCHAR2(45),
  "CHECKER_TS" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) NULL ,
  "AUTH_STATUS" VARCHAR2(1) DEFAULT 'U',
  "VERSION_NO" NUMBER(10,0) DEFAULT 1,
  CONSTRAINT "TB_ASMI_DLG_MASTER_PK" PRIMARY KEY ("APP_ID","CNVUI_ID","DLG_ID")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_CNVUI_SCR';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASMI_CNVUI_SCR" (
  "APP_ID" VARCHAR2(100) NOT NULL,
  "SCREEN_ID" VARCHAR2(100) NOT NULL,
  "SCREEN_DESC" VARCHAR2(100),
  "SCREEN_DEF" CLOB,
  "SCREEN_DESIGN" CLOB,
  "SCREEN_HTML" CLOB,
  "SCREEN_LAYOUT" CLOB,
  "TEMPLATE" CLOB,
  "CREATE_USER_ID" VARCHAR2(100) DEFAULT NULL,
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
  "VERSION_NO" NUMBER(10,0) DEFAULT 1,
  CONSTRAINT "TB_ASMI_CNVUI_SCR_PK" PRIMARY KEY ("APP_ID","SCREEN_ID")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASLG_CNVUI_TXN_LOG';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASLG_CNVUI_TXN_LOG" (
  "TXN_REF" VARCHAR2(255) NOT NULL,
  "APP_ID" VARCHAR2(100),
  "CNVUI_ID" VARCHAR2(100),
  "RESP_DLG_ID" VARCHAR2(100),
  "SCREEN_DATA" CLOB,
  "CREATE_USER_ID" VARCHAR2(100) DEFAULT NULL,
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
  "UPDATE_TS" TIMESTAMP (6),
  CONSTRAINT "TB_ASLG_CNVUI_TXN_LOG_PK" PRIMARY KEY ("TXN_REF")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_CS_NONCEDETAILS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
 CREATE TABLE "TB_ASMI_CS_NONCEDETAILS"
    ("DEVICE_ID" VARCHAR2(100),
 "APP_ID" VARCHAR2(100),
 "REQUEST_ID" VARCHAR2(255),
 "CLIENT_NONCE" VARCHAR2(100),
 "SERVER_NONCE" VARCHAR2(100),
 "STATUS" VARCHAR2(100),
 "SERVER_TOKEN" VARCHAR2(100),
 "CREATE_TS" TIMESTAMP (6),
 "CREATED_ON" DATE DEFAULT SYSDATE
 );
  
 create unique index TB_ASMI_CS_NONCEDETAILS_IDX01 on TB_ASMI_CS_NONCEDETAILS(CREATED_ON, DEVICE_ID, APP_ID, REQUEST_ID, CLIENT_NONCE, SERVER_NONCE);



BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_WORKFLOW_DEFN';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE "TB_ASMI_WORKFLOW_DEFN" (
	"APP_ID" VARCHAR2(100) NOT NULL,
	"WORKFLOW_ID" VARCHAR2(100) NOT NULL,
	"WORKFLOW_DESC" VARCHAR2(255),
	"VERSION_NO" number(10,0),
	"MAKER_ID" VARCHAR2(255),
	"MAKER_TS" TIMESTAMP(3) DEFAULT SYSTIMESTAMP,
	"CHECKER_ID" VARCHAR2(255),
	"CHECKER_TS" TIMESTAMP(3) NULL,
	"AUTH_STATUS" VARCHAR2(1),
	"ACTIVE" CHAR(1),
	"TXN_TYPE" VARCHAR2(100),
	"ONCE_AUTH" VARCHAR2(1),
	PRIMARY KEY ("APP_ID", "WORKFLOW_ID")
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_WORKFLOW_RULES';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE "TB_ASMI_WORKFLOW_RULES"(
	"APP_ID" VARCHAR2(100) NOT NULL,
	"WORKFLOW_ID" VARCHAR2(100) NOT NULL,
	"RULE_ID" VARCHAR2(50) NOT NULL,
	"RULE_DESC" VARCHAR2(255),
	"RULE_BEAN" VARCHAR2(255),	
	"VERSION_NO" number(10,0),
	"MAKER_ID" VARCHAR2(45),
	"MAKER_TS" TIMESTAMP(3) DEFAULT SYSTIMESTAMP,
	"CHECKER_ID" VARCHAR2(45),
	"CHECKER_TS" TIMESTAMP(3) NULL,
	"AUTH_STATUS" VARCHAR2(1),
	"ACTIVE" CHAR(1),
	"ONCE_AUTH" VARCHAR2(1),
	PRIMARY KEY ("APP_ID", "RULE_ID", "WORKFLOW_ID")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_WORKFLOW_STAGES';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE "TB_ASMI_WORKFLOW_STAGES" (
	"APP_ID" VARCHAR2(100) NOT NULL,
	"WORKFLOW_ID" VARCHAR2(100) NOT NULL,
	"STAGE_ID" VARCHAR2(50) NOT NULL,
	"STAGE_SEQ_NO" number(10,0),
	"STAGE_TYPE" VARCHAR2(50),
	"STAGE_DESC" VARCHAR2(255),
	"RULE_ID" VARCHAR2(50),
	"SCREEN_ID" VARCHAR2(50),
	"IS_AUTH_MATRIX_REQD" VARCHAR2(1),
	PRIMARY KEY ("APP_ID", "STAGE_ID", "WORKFLOW_ID")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASTP_WORKFLOW_TXN_DETAIL';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE "TB_ASTP_WORKFLOW_TXN_DETAIL" (
	"APP_ID" VARCHAR2(100) NOT NULL,
	"WORKFLOW_REF_NO" VARCHAR2(100) NOT NULL,
	"WORKFLOW_SEQ_NO" number(10,0),
	"STAGE_ID" VARCHAR2(50) NOT NULL,
	"WORKFLOW_ID" VARCHAR2(100),
	"TASK_DATA" CLOB,
	"USER_ID" VARCHAR2(50),
	"STATUS" VARCHAR2(50),
	"UPDATED_NEXT_STAGES" VARCHAR2(255),
	"LAST_EVENT_NO" number(10,0),
	"START_TS" TIMESTAMP(3) DEFAULT SYSTIMESTAMP,
	"END_TS" TIMESTAMP(3),
	"REMARKS" VARCHAR2(255),
	"CUSTOM_FIELD_1" VARCHAR2(100),
	"CUSTOM_FIELD_2" VARCHAR2(100),
	"CUSTOM_FIELD_3" VARCHAR2(100),
	"CUSTOM_FIELD_4" VARCHAR2(100),
	"CUSTOM_FIELD_5" VARCHAR2(100),	
	PRIMARY KEY ("APP_ID", "WORKFLOW_REF_NO", "WORKFLOW_SEQ_NO")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASTP_WORKFLOW_EVENT';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE "TB_ASTP_WORKFLOW_EVENT" (
	"APP_ID" VARCHAR2(100) NOT NULL,
	"WORKFLOW_REF_NO" VARCHAR2(100) NOT NULL,
	"WORKFLOW_SEQ_NO" number(10,0) NOT NULL,
	"EVENT_SEQ_NO" number(10,0) NOT NULL,
	"WORKFLOW_ID" VARCHAR2(100),
	"STAGE_ID" VARCHAR2(50) NOT NULL,
	"EVENT_ID" VARCHAR2(50),
	"TASK_DATA" CLOB,
	"USER_ID" VARCHAR2(50),
	"EVENT_TS" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
	"REMARKS" VARCHAR2(255),
	"CUSTOM_FIELD_1" VARCHAR2(100),
	"CUSTOM_FIELD_2" VARCHAR2(100),
	"CUSTOM_FIELD_3" VARCHAR2(100),
	"CUSTOM_FIELD_4" VARCHAR2(100),
	"CUSTOM_FIELD_5" VARCHAR2(100),	
	PRIMARY KEY ("APP_ID", "WORKFLOW_REF_NO", "WORKFLOW_SEQ_NO", "EVENT_SEQ_NO")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASTP_WORKFLOW_TXN_MASTER';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE "TB_ASTP_WORKFLOW_TXN_MASTER" (
	"APP_ID" VARCHAR2(100) NOT NULL,
	"WORKFLOW_REF_NO" VARCHAR2(100) NOT NULL,
	"WORKFLOW_ID" VARCHAR2(100),
	"STATUS" VARCHAR2(50),
	"START_TS" TIMESTAMP(3) DEFAULT SYSTIMESTAMP,
	"MODIFIED_TS" TIMESTAMP(3),
	"END_TS" TIMESTAMP(3) NULL,
	"CUSTOM_FIELD_1" VARCHAR(100),
	"CUSTOM_FIELD_2" VARCHAR(100),
	"CUSTOM_FIELD_3" VARCHAR(100),
	"CUSTOM_FIELD_4" VARCHAR(100),
	"CUSTOM_FIELD_5" VARCHAR(100),
	PRIMARY KEY ("APP_ID", "WORKFLOW_REF_NO")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_WORKFLOW_TXN_DETAILS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE "TB_ASHS_WORKFLOW_TXN_DETAILS" (
	"APP_ID" VARCHAR2(100) NOT NULL,
	"WORKFLOW_REF_NO" VARCHAR2(100) NOT NULL,
	"WORKFLOW_SEQ_NO" number(10,0) NOT NULL,
	"WORKFLOW_ID" VARCHAR2(100),
	"STAGE_ID" VARCHAR2(50),
	"TASK_DATA" CLOB,
	"USER_ID" VARCHAR2(50),
	"STATUS" VARCHAR2(50),
	"UPDATED_NEXT_STAGES" VARCHAR2(255),
	"LAST_ACTION" VARCHAR2(50),
	"CUSTOM_FIELD_1" VARCHAR2(100),
	"CUSTOM_FIELD_2" VARCHAR2(100),
	"CUSTOM_FIELD_3" VARCHAR2(100),
	"CUSTOM_FIELD_4" VARCHAR2(100),
	"CUSTOM_FIELD_5" VARCHAR2(100),	
	PRIMARY KEY ("APP_ID", "WORKFLOW_REF_NO", "WORKFLOW_SEQ_NO")
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_WORKFLOW_TXN_MASTER';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE "TB_ASHS_WORKFLOW_TXN_MASTER" (
	"APP_ID" VARCHAR2(100) NOT NULL,
	"WORKFLOW_REF_NO" VARCHAR2(100) NOT NULL,
	"WORKFLOW_ID" VARCHAR2(100),
	"STATUS" VARCHAR2(50),
	"START_TS" TIMESTAMP(3) DEFAULT SYSTIMESTAMP,
	"MODIFIED_TS" TIMESTAMP(3),
	"END_TS" TIMESTAMP(3),
	"CUSTOM_FIELD_1" VARCHAR(100),
	"CUSTOM_FIELD_2" VARCHAR(100),
	"CUSTOM_FIELD_3" VARCHAR(100),
	"CUSTOM_FIELD_4" VARCHAR(100),
	"CUSTOM_FIELD_5" VARCHAR(100),	
	PRIMARY KEY ("APP_ID", "WORKFLOW_REF_NO")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_WORKFLOW_LINKED_STAGES';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE "TB_ASMI_WORKFLOW_LINKED_STAGES" (
	"APP_ID" VARCHAR2(100) NOT NULL,
	"WORKFLOW_ID" VARCHAR2(100),
	"STAGE_ID" VARCHAR2(50),
	"LINKAGE_TYPE" char(1),
	"LINKED_STAGE_ID" VARCHAR2(50),
	PRIMARY KEY ("APP_ID", "LINKAGE_TYPE", "LINKED_STAGE_ID", "STAGE_ID", "WORKFLOW_ID")
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_ROLE_WORKFLOWS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE "TB_ASMI_ROLE_WORKFLOWS" (
	"APP_ID" VARCHAR2(100) NOT NULL,
	"ROLE_ID" VARCHAR2(100) NOT NULL,
	"WORKFLOW_ID" VARCHAR2(100) NOT NULL,
	"STAGE_ID" VARCHAR2(50) NOT NULL,
	PRIMARY KEY ("APP_ID", "ROLE_ID", "WORKFLOW_ID", "STAGE_ID")
);


BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_APP_ACCESS_TOKEN';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_APP_ACCESS_TOKEN" 
   ("APP_ID" VARCHAR2(100), 
   "USER_ID" VARCHAR2(100), 
   "ACCESS_TOKEN" VARCHAR2(255) ,
   "CLIENT_NONCE" VARCHAR2(255),
   "CREATE_TS" TIMESTAMP (6), 
    CONSTRAINT "TB_ASMI_APP_ACCESS_TOKEN_PK" PRIMARY KEY (APP_ID,USER_ID,ACCESS_TOKEN,CLIENT_NONCE)
) ;

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_COOKIES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASMI_COOKIES" (
  "APP_ID" VARCHAR2(100) NOT NULL,
  "USER_ID" VARCHAR2(100) NOT NULL,
  "USR_SELECTOR" VARCHAR2(50) NOT NULL,
  "USR_VALIDATOR" VARCHAR2(255) NOT NULL,
  "CREATE_TS" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "EXPIRY_TS" TIMESTAMP (3) DEFAULT CURRENT_TIMESTAMP(3) NOT NULL,
  "VERSION_NO" NUMBER(10,0) DEFAULT 1,
  PRIMARY KEY ("APP_ID", "USR_SELECTOR") 
);

--Returns The Number Of Seconds Between Two Date-Time Values
CREATE OR REPLACE FUNCTION time_diff (DATE_1 IN DATE, DATE_2 IN DATE) RETURN NUMBER IS
 NDATE_1   NUMBER;
 NDATE_2   NUMBER;
 NSECOND_1 NUMBER(5,0);
 NSECOND_2 NUMBER(5,0);
BEGIN
  -- return Julian date number from first date (DATE_1)
  NDATE_1 := TO_NUMBER(TO_CHAR(DATE_1, 'J'));

  -- return Julian date number from second date (DATE_2)
  NDATE_2 := TO_NUMBER(TO_CHAR(DATE_2, 'J'));

  -- return seconds since midnight from first date (DATE_1)
  NSECOND_1 := TO_NUMBER(TO_CHAR(DATE_1, 'SSSSS'));

  -- return seconds since midnight from second date (DATE_2)
  NSECOND_2 := TO_NUMBER(TO_CHAR(DATE_2, 'SSSSS'));

  RETURN (((NDATE_2 - NDATE_1) * 86400)+(NSECOND_2 - NSECOND_1));
END time_diff;
/

CREATE OR REPLACE FUNCTION time_diff_milliSecs (aTimestamp timestamp, bTimestamp timestamp)
  RETURN NUMBER
as
  vMS NUMBER DEFAULT 0;
BEGIN
  select
    (extract(day from bTimestamp - aTimestamp)*86400+
    extract(hour from bTimestamp - aTimestamp)*3600+
    extract(minute from bTimestamp - aTimestamp)*60+
    extract(second from bTimestamp - aTimestamp)) * 1000 into vMS
    from dual;
  RETURN vMS;
END;
/

CREATE OR REPLACE VIEW VW_ACTIVE_SESSIONS
AS
SELECT B.OS, A.APP_ID, COUNT(*) as COUNT
FROM TB_ASTP_LAST_LOGIN A,TB_ASMI_DEVICE_MASTER B
WHERE A.APP_ID =B.APP_ID
AND A.DEVICE_ID = B.DEVICE_ID AND A.SESSION_ID IS NOT NULL
AND  time_diff (A.LAST_REQ_TIME, SYSTIMESTAMP) < 
(SELECT SESSION_TIMEOUT FROM TB_ASMI_SECURITY_PARAMETERS C WHERE A.APP_ID=C.APP_ID )
GROUP BY B.OS, A.APP_ID
UNION ALL
SELECT A.DEVICE_ID,A.APP_ID, COUNT(*) as COUNT
FROM TB_ASTP_LAST_LOGIN A
WHERE A.DEVICE_ID IN ('WEB','SIMULATOR')
AND A.SESSION_ID IS NOT NULL
AND time_diff (A.LAST_REQ_TIME, SYSTIMESTAMP) < 
(SELECT SESSION_TIMEOUT FROM TB_ASMI_SECURITY_PARAMETERS C WHERE A.APP_ID=C.APP_ID )
GROUP BY A.DEVICE_ID, A.APP_ID;

CREATE OR REPLACE VIEW VW_ACTIVE_INACTIVE_USERS
AS
SELECT t1.APP_ID, trunc(t1.CREATE_TS) as CREATE_TS, count(*) as ACTIVE , 0 INACTIVE
FROM TB_ASMI_USER t1
LEFT JOIN TB_ASTP_LAST_LOGIN t2 ON t2.USER_ID = t1.USER_ID AND t2.APP_ID = t1.APP_ID 
WHERE t2.USER_ID IS NOT NULL AND t1.USER_ACTIVE='Y'
GROUP BY t1.APP_ID, trunc(t1.CREATE_TS)
UNION ALL
SELECT t1.APP_ID,trunc(t1.CREATE_TS) as CREATE_TS, 0 ACTIVE, count(*) as INACTIVE
FROM TB_ASMI_USER t1
LEFT JOIN TB_ASTP_LAST_LOGIN t2 ON t2.USER_ID = t1.USER_ID AND t2.APP_ID = t1.APP_ID 
WHERE t2.USER_ID IS NULL AND t1.USER_ACTIVE='Y'
GROUP BY t1.APP_ID, trunc(t1.CREATE_TS);


CREATE OR REPLACE VIEW VW_LOGIN_REPORT AS
SELECT tb.APP_ID,tb.DEVICE_ID,trunc(tb.CREATE_TS) as AccessDate,count(*) as TotalTxns,0 Logins,0 DistinctLogins
FROM  TB_ASLG_TXN_DETAIL tb WHERE tb.TXN_STAT='S'
GROUP BY tb.APP_ID,tb.DEVICE_ID,trunc(tb.CREATE_TS)
UNION ALL
SELECT tb2.APP_ID,tb2.DEVICE_ID,trunc(tb2.CREATE_TS) as AccessDate,0 TotalTxns,count(*) as Logins,
count(distinct trunc(tb2.CREATE_TS)) as DistinctLogins
FROM TB_ASLG_TXN_DETAIL tb2 WHERE 
(tb2.INTERFACE_ID='appzillonReLoginRequest' OR tb2.INTERFACE_ID='appzillonAuthenticationRequest')
AND tb2.TXN_STAT='S' 
GROUP BY tb2.APP_ID,tb2.USER_ID,tb2.DEVICE_ID,trunc(tb2.CREATE_TS);

CREATE OR REPLACE VIEW VW_LOCATION_DETAILS
AS
SELECT * FROM TB_ASTP_LAST_LOGIN A where A.SESSION_ID IS NOT NULL
AND time_diff(A.LAST_REQ_TIME, SYSTIMESTAMP) < (SELECT SESSION_TIMEOUT FROM TB_ASMI_SECURITY_PARAMETERS C WHERE A.APP_ID=C.APP_ID );

CREATE OR REPLACE VIEW VW_CUSTOMER_DETAILS AS
SELECT APP_ID,USER_ID,trunc(CREATE_TS) AS AccessDate,SESSION_ID,min(ST_TM) as ST_TM,max(END_TM) as END_TM,Count(*) As 
TotalTxns,0 DistinctTxns,LATITUDE,LONGITUDE,FORMATTED_ADDRESS
FROM TB_ASLG_TXN_DETAIL tb
WHERE TXN_STAT='S' 
GROUP BY APP_ID,USER_ID,trunc(CREATE_TS),SESSION_ID,LATITUDE,LONGITUDE,FORMATTED_ADDRESS
Union ALL
SELECT APP_ID,USER_ID,trunc(CREATE_TS) AS AccessDate,SESSION_ID,min(ST_TM) as ST_TM,max(END_TM) as END_TM,0 TotalTxns, 
Count(distinct(INTERFACE_ID)) AS DistinctTxns,LATITUDE,LONGITUDE,FORMATTED_ADDRESS
FROM TB_ASLG_TXN_DETAIL
WHERE TXN_STAT='S'
GROUP BY APP_ID,USER_ID,trunc(CREATE_TS),SESSION_ID,INTERFACE_ID,LATITUDE,LONGITUDE,FORMATTED_ADDRESS;

CREATE OR REPLACE VIEW VW_CUSTOMER_REPORT
AS
SELECT tb.APP_ID,tb.USER_ID,tb.SESSION_ID,
time_diff_milliSecs(MIN(ST_TM),MAX(END_TM)) tm,
count(*) as TotalTxns,count(distinct(tb.INTERFACE_ID)) as DistinctTxns, 0 Logins,0 DistinctLogins
FROM  TB_ASLG_TXN_DETAIL tb WHERE tb.TXN_STAT='S' GROUP BY tb.APP_ID, tb.USER_ID,tb.SESSION_ID
UNION ALL
SELECT tb2.APP_ID,tb2.USER_ID, null SESSION_ID, 
null tm,0 TotalTxns,0 DistinctTxns,count(*) as Logins, count(distinct trunc(tb2.CREATE_TS)) as DistinctLogins
FROM TB_ASLG_TXN_DETAIL tb2 WHERE 
(tb2.INTERFACE_ID='appzillonReLoginRequest' OR tb2.INTERFACE_ID='appzillonAuthenticationRequest')
and tb2.TXN_STAT='S' GROUP BY tb2.APP_ID, tb2.USER_ID;

CREATE OR REPLACE VIEW VW_LAT_LON_DETAILS
AS
SELECT APP_ID,USER_ID,COUNT(LONGITUDE) as COUNT_LON, LONGITUDE, 
COUNT(LATITUDE) as COUNT_LAT,LATITUDE, FORMATTED_ADDRESS FROM TB_ASLG_TXN_DETAIL GROUP BY LONGITUDE, LATITUDE, FORMATTED_ADDRESS, APP_ID, USER_ID;

CREATE OR REPLACE VIEW VW_TXN_APP_USAGE AS
SELECT txn.APP_ID,trunc(txn.CREATE_TS) AS AccessDate,intf.DESCRIPTION, txn.TXN_STAT,
MIN(time_diff_milliSecs(txn.ST_TM,txn.END_TM)) AS MinTime, MAX(time_diff_milliSecs(txn.ST_TM,txn.END_TM)) AS MaxTime, 
AVG(time_diff_milliSecs(txn.ST_TM,txn.END_TM)) AS AvgTime, count(txn.INTERFACE_ID) AS IntfCount 
FROM TB_ASLG_TXN_DETAIL txn,TB_ASMI_INTF_MASTER intf 
WHERE txn.INTERFACE_ID = intf.INTERFACE_ID
GROUP BY txn.APP_ID,txn.INTERFACE_ID,trunc(txn.CREATE_TS),intf.DESCRIPTION,txn.TXN_STAT;

CREATE INDEX TB_ASMI_CS_NONCEDETAILS_INDEX ON TB_ASMI_CS_NONCEDETAILS ("SERVER_NONCE");

--CREATE UNIQUE INDEX "TB_ASMI_ROLE_SCR_PK" ON "TB_ASMI_ROLE_SCR" ("APP_ID", "ROLE_ID", "SCREEN_ID") ;
--------------------------------------------------------
--  Constraints for Table TB_ASMI_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "TB_ASMI_USER_ROLE" ADD CONSTRAINT "TB_ASMI_USER_ROLE_PK" PRIMARY KEY ("USER_ID", "ROLE_ID", "APP_ID") ENABLE;
  ALTER TABLE "TB_ASMI_USER_ROLE" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_USER_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_USER_ROLE" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_ASLG_TXN_DETAIL
--------------------------------------------------------

  ALTER TABLE "TB_ASLG_TXN_DETAIL" ADD CONSTRAINT "TB_ASLG_TXN_DETAIL_PK" PRIMARY KEY ("TXN_REF") ENABLE;
  ALTER TABLE "TB_ASLG_TXN_DETAIL" MODIFY ("TXN_REF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_ASTP_LD_RECS
--------------------------------------------------------

  ALTER TABLE "TB_ASTP_LD_RECS" ADD CONSTRAINT "TTB_ASTP_LD_RECS_PK" PRIMARY KEY ("REF_NO","SEQ_NO") ENABLE;
  ALTER TABLE "TB_ASTP_LD_RECS" MODIFY ("REF_NO" NOT NULL ENABLE);
  ALTER TABLE "TB_ASTP_LD_RECS" MODIFY ("SEQ_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_ASMI_SCR_MASTER
--------------------------------------------------------

  ALTER TABLE "TB_ASMI_SCR_MASTER" ADD CONSTRAINT "TB_ASMI_SCR_MASTER_PK" PRIMARY KEY ("SCREEN_ID", "APP_ID") ENABLE;
  ALTER TABLE "TB_ASMI_SCR_MASTER" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_SCR_MASTER" MODIFY ("SCREEN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_ASMI_USER
--------------------------------------------------------

  ALTER TABLE "TB_ASMI_USER" MODIFY ("PIN_CHANGE_TS" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_USER" ADD CONSTRAINT "TB_ASMI_USER_PK" PRIMARY KEY ("USER_ID", "APP_ID") ENABLE;
  ALTER TABLE "TB_ASMI_USER" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_USER" MODIFY ("USER_LOCKED" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_USER" MODIFY ("USER_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_USER" MODIFY ("LOGIN_STATUS" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_USER" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_ASMI_INTF_MASTER
--------------------------------------------------------

  ALTER TABLE "TB_ASMI_INTF_MASTER" ADD CONSTRAINT "TB_ASMI_INTF_MASTER_PK" PRIMARY KEY ("INTERFACE_ID", "APP_ID") ENABLE;
  ALTER TABLE "TB_ASMI_INTF_MASTER" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_INTF_MASTER" MODIFY ("INTERFACE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_ASMI_ROLE_SCR
--------------------------------------------------------

  ALTER TABLE "TB_ASMI_ROLE_SCR" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_ROLE_SCR" MODIFY ("SCREEN_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_ROLE_SCR" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_ROLE_SCR" ADD CONSTRAINT "TB_ASMI_ROLE_SCR_PK" PRIMARY KEY ("APP_ID", "ROLE_ID", "SCREEN_ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_ASMI_ROLE_INTF
--------------------------------------------------------

  ALTER TABLE "TB_ASMI_ROLE_INTF" ADD CONSTRAINT "TB_ASMI_ROLE_INTF_PK" PRIMARY KEY ("APP_ID", "ROLE_ID", "INTERFACE_ID") ENABLE;
  ALTER TABLE "TB_ASMI_ROLE_INTF" MODIFY ("INTERFACE_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_ROLE_INTF" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_ROLE_INTF" MODIFY ("APP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_ASTP_LAST_LOGIN
--------------------------------------------------------

  ALTER TABLE "TB_ASTP_LAST_LOGIN" ADD CONSTRAINT "TB_ASTP_LAST_LOGIN_PK" PRIMARY KEY ("USER_ID", "APP_ID", "DEVICE_ID") ENABLE;
  ALTER TABLE "TB_ASTP_LAST_LOGIN" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASTP_LAST_LOGIN" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASTP_LAST_LOGIN" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_ASMI_ROLE_MASTER
--------------------------------------------------------

  ALTER TABLE "TB_ASMI_ROLE_MASTER" ADD CONSTRAINT "TB_ASMI_ROLE_MASTER_PK" PRIMARY KEY ("ROLE_ID", "APP_ID") ENABLE;
  ALTER TABLE "TB_ASMI_ROLE_MASTER" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_ROLE_MASTER" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_ASMI_USER_DEVICES
--------------------------------------------------------

  ALTER TABLE "TB_ASMI_USER_DEVICES" ADD CONSTRAINT "TB_ASMI_USER_DEVICES_PK" PRIMARY KEY ("APP_ID", "DEVICE_ID", "USER_ID") ENABLE;
  ALTER TABLE "TB_ASMI_USER_DEVICES" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_USER_DEVICES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_USER_DEVICES" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
  
  --------------------------------------------------------
--  Constraints for Table TB_ASMI_SECURITY_PARAMETERS
--------------------------------------------------------

  ALTER TABLE "TB_ASMI_SECURITY_PARAMETERS" ADD CONSTRAINT "TB_ASMI_SECURITY_PARAMETER_PK" PRIMARY KEY ("APP_ID") ENABLE;
  ALTER TABLE "TB_ASMI_SECURITY_PARAMETERS" MODIFY ("APP_ID" NOT NULL ENABLE);
  
  --CREATE UNIQUE INDEX "TB_ASHS_ROLE_SCR_PK" ON "TB_ASHS_ROLE_SCR" ("APP_ID", "ROLE_ID", "SCREEN_ID") ;
--------------------------------------------------------
--  Constraints for Table TB_ASHS_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "TB_ASHS_USER_ROLE" ADD CONSTRAINT "TB_ASHS_USER_ROLE_PK" PRIMARY KEY ("USER_ID", "ROLE_ID", "APP_ID","VERSION_NO") ENABLE;
  ALTER TABLE "TB_ASHS_USER_ROLE" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_USER_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_USER_ROLE" MODIFY ("USER_ID" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table TB_ASHS_USER
--------------------------------------------------------

  ALTER TABLE "TB_ASHS_USER" MODIFY ("PIN_CHANGE_TS" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_USER" ADD CONSTRAINT "TB_ASHS_USER_PK" PRIMARY KEY ("USER_ID", "APP_ID","VERSION_NO") ENABLE;
  ALTER TABLE "TB_ASHS_USER" MODIFY ("LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_USER" MODIFY ("USER_LOCKED" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_USER" MODIFY ("USER_ACTIVE" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_USER" MODIFY ("LOGIN_STATUS" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_USER" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_USER" MODIFY ("USER_ID" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table TB_ASHS_ROLE_SCR
--------------------------------------------------------

  ALTER TABLE "TB_ASHS_ROLE_SCR" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_ROLE_SCR" MODIFY ("SCREEN_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_ROLE_SCR" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_ROLE_SCR" ADD CONSTRAINT "TB_ASHS_ROLE_SCR_PK" PRIMARY KEY ("APP_ID", "ROLE_ID", "SCREEN_ID","VERSION_NO") ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_ASHS_ROLE_INTF
--------------------------------------------------------

  ALTER TABLE "TB_ASHS_ROLE_INTF" ADD CONSTRAINT "TB_ASHS_ROLE_INTF_PK" PRIMARY KEY ("APP_ID", "ROLE_ID", "INTERFACE_ID","VERSION_NO") ENABLE;
  ALTER TABLE "TB_ASHS_ROLE_INTF" MODIFY ("INTERFACE_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_ROLE_INTF" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_ROLE_INTF" MODIFY ("APP_ID" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table TB_ASHS_ROLE_MASTER
--------------------------------------------------------

  ALTER TABLE "TB_ASHS_ROLE_MASTER" ADD CONSTRAINT "TB_ASHS_ROLE_MASTER_PK" PRIMARY KEY ("ROLE_ID", "APP_ID","VERSION_NO") ENABLE;
  ALTER TABLE "TB_ASHS_ROLE_MASTER" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_ROLE_MASTER" MODIFY ("ROLE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_ASHS_USER_DEVICES
--------------------------------------------------------

  ALTER TABLE "TB_ASHS_USER_DEVICES" ADD CONSTRAINT "TB_ASHS_USER_DEVICES_PK" PRIMARY KEY ("APP_ID", "DEVICE_ID", "USER_ID","VERSION_NO") ENABLE;
  ALTER TABLE "TB_ASHS_USER_DEVICES" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_USER_DEVICES" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASHS_USER_DEVICES" MODIFY ("DEVICE_ID" NOT NULL ENABLE);

  --------------------------------------------------------
--  Constraints for Table TB_ASHS_SECURITY_PARAMETERS
--------------------------------------------------------

  ALTER TABLE "TB_ASHS_SECURITY_PARAMETERS" ADD CONSTRAINT "TB_ASHS_SECURITY_PARAMETER_PK" PRIMARY KEY ("APP_ID","VERSION_NO") ENABLE;
  ALTER TABLE "TB_ASHS_SECURITY_PARAMETERS" MODIFY ("APP_ID" NOT NULL ENABLE);

CREATE OR REPLACE VIEW VW_ASMI_DEVICE_GRPS AS
SELECT APP_ID, DEVICE_GROUP_ID, DEVICE_GROUP_DESCRIPTION, OS,HEIGHT, WIDTH, 'PORTRAIT' AS ORIENTATION
FROM TB_ASMI_DEVICE_GRPS WHERE ORIENTATION_LOCK = 'ANY'
UNION ALL
SELECT APP_ID, DEVICE_GROUP_ID, DEVICE_GROUP_DESCRIPTION, OS,HEIGHT, WIDTH, 'LANDSCAPE' AS ORIENTATION
FROM TB_ASMI_DEVICE_GRPS WHERE ORIENTATION_LOCK = 'ANY'
UNION ALL
SELECT APP_ID, DEVICE_GROUP_ID, DEVICE_GROUP_DESCRIPTION, OS,HEIGHT, WIDTH, ORIENTATION_LOCK AS ORIENTATION
FROM TB_ASMI_DEVICE_GRPS WHERE ORIENTATION_LOCK != 'ANY';


CREATE OR REPLACE VIEW VW_ASMI_MICROAPPS AS
SELECT T2.APP_ID AS APP_ID, T2.SCREEN_ID, T2.MICRO_APP_ID AS MICRO_APP_ID, T1.APP_NAME AS MICRO_APP_NAME, T1.APP_ICON AS MICRO_APP_ICON,
T1.MICRO_APP_TYPE AS MICRO_APP_TYPE FROM TB_ASMI_APP_MASTER T1, TB_ASMI_SCREEN_MICRO_APP T2
WHERE T1.APP_ID = T2.MICRO_APP_ID AND T1.BASE_APP = 'N';


CREATE OR REPLACE VIEW VW_ASMI_NANOAPPS AS
SELECT T1.APP_ID, T2.SCREEN_ID, T1.SCREEN_ID AS CALLFORM_ID, T1.SCREEN_NAME AS CALLFORM_NAME, T1.SCREEN_ICON AS CALLFORM_ICON
FROM TB_ASMI_SCR_MASTER T1, TB_ASMI_SCREEN_WIDGETS T2
WHERE T1.APP_ID = T2.APP_ID AND T1.SCREEN_ID = T2.CALLFORM_ID AND T1.SCREEN_TYPE = 'CALL';
