--------------------------------------------------------
--  File created - Wednesday-July-02-2014   
--------------------------------------------------------
   
--------------------------------------------------------
--  DDL for Table TB_ASMI_APP_DTLS
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_APP_DTLS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_APP_DTLS" 
   (	"APP_ID" VARCHAR2(100), 
	"APP_DESC" VARCHAR2(200), 
	"OS_ID" VARCHAR2(50), 
	"CREATE_BY" VARCHAR2(100), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER DEFAULT 1
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_LOV_QUERIES
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_LOV_QUERIES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_LOV_QUERIES" 
   (	"APP_ID" VARCHAR2(100), 
	"QUERY_ID" VARCHAR2(100), 
	"QUERY_STRING" VARCHAR2(1000), 
	"DB_JNDI_NAME" VARCHAR2(50), 
	"QUERY_TYPE" VARCHAR2(3) DEFAULT 'SQL', 
	"BINDVAR_COLS" VARCHAR2(300), 
	"BINDVAR_DATA_TYPES" VARCHAR2(300), 
	"FILTER_COLS" VARCHAR2(300), 
	"ORDERBY_COL" VARCHAR2(40), 
	"ORDERBY_TYPE" VARCHAR2(5) DEFAULT 'ASC', 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATE_TS" TIMESTAMP (6), 
	"CREATE_BY" VARCHAR2(50),
	"SESSION_REQD" VARCHAR2(1) NULL,
	"VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_OS_DTLS
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_OS_DTLS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_OS_DTLS" 
   (	"OS_ID" VARCHAR2(50), 
	"OS_DESC" VARCHAR2(200), 
	"CREATE_BY" VARCHAR2(100), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;

--------------------------------------------------------
--  DDL for Table TB_ASTP_SEQ_GEN
--------------------------------------------------------
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASTP_SEQ_GEN';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASTP_SEQ_GEN" 
   (	"SEQUENCE_NAME" VARCHAR2(50), 
	"SEQUENCE_VALUE" NUMBER, 
	"CREATE_BY" VARCHAR2(20), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER(10,0) DEFAULT 1
   ) ;

   
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASNF_DEVICES_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASNF_DEVICES_MASTER" 
   (	"APP_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"NOTIF_REG_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"DEVICE_ID" VARCHAR2(255 BYTE), 
	"DEVICE_NAME" VARCHAR2(255 BYTE), 
	"OS_ID" VARCHAR2(50 BYTE), 
	"OS_VERSION" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"CREATED_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"MAKER_ID" VARCHAR(45),
	"MAKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"CHECKER_ID" VARCHAR(45),
	"CHECKER_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"AUTH_STATUS" VARCHAR(45) DEFAULT 'U',	
	"VERSION_NO" NUMBER(10,0) DEFAULT 1,
	"NOTIF_MSG_SERVER" VARCHAR2(255 BYTE) DEFAULT NULL,
	 CONSTRAINT "TB_ASNF_DEVICES_MASTER_PK" PRIMARY KEY ("APP_ID", "NOTIF_REG_ID")  
   ) ;

   
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASNF_GROUP_DEVICES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASNF_GROUP_DEVICES"
   (	"APP_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"GROUP_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"NOTIF_REG_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255 BYTE), 
	"CREATED_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER(10,0) DEFAULT 1, 
	 CONSTRAINT "TB_ASNF_GROUP_DEVICES_PK" PRIMARY KEY ("APP_ID", "GROUP_ID", "NOTIF_REG_ID") 
   ) ;

 BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASNF_GROUP_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASNF_GROUP_MASTER"
   (	"APP_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"GROUP_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"GROUP_DESC" VARCHAR2(500 BYTE), 
	"CREATED_BY" VARCHAR2(50 BYTE), 
	"CREATED_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER(10,0) DEFAULT 1, 
	 CONSTRAINT "TB_ASNF_GROUP_MASTER_PK" PRIMARY KEY ("APP_ID", "GROUP_ID")
    ) ;

    
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASNF_TXN_DEVICES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASNF_TXN_DEVICES"
   (	"NOTIF_ID" NUMBER NOT NULL ENABLE, 
	"APP_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"NOTIF_REG_ID" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "TB_ASNF_TXN_DEVICES_PK" PRIMARY KEY ("NOTIF_ID", "APP_ID", "NOTIF_REG_ID")
    ); 

    
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASNF_TXN_GROUPS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASNF_TXN_GROUPS"
   (	"NOTIF_ID" NUMBER, 
	"APP_ID" VARCHAR2(100 BYTE), 
	"GROUP_ID" VARCHAR2(255 BYTE),
	 CONSTRAINT "TB_ASNF_TXN_GROUPS_PK" PRIMARY KEY ("NOTIF_ID", "APP_ID", "GROUP_ID")
   ) ;

   
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASNF_TXN_LOG';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASNF_TXN_LOG"
   ("NOTIF_ID" NUMBER, 
	"APP_ID" VARCHAR2(100 BYTE),
	"USER_ID" VARCHAR2(100 BYTE),
	"NOTIF_REG_ID" VARCHAR2(255 BYTE), 
	"DEVICE_ID" VARCHAR2(255 BYTE), 
	"STATUS" CHAR(150 BYTE), 
	"CREATED_BY" VARCHAR2(150 BYTE), 
	"CREATED_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER(10,0) DEFAULT 1,
	 CONSTRAINT "TB_ASNF_TXN_LOG_PK" PRIMARY KEY ("NOTIF_ID", "APP_ID", "NOTIF_REG_ID", "DEVICE_ID")
   );

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASNF_TXN_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASNF_TXN_MASTER" 
   (	"NOTIF_ID" NUMBER NOT NULL ENABLE, 
	"APP_ID" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"NOTIF_MSG" VARCHAR2(4000 BYTE) NOT NULL ENABLE,
	"TITLE" VARCHAR2(4000 BYTE),
	"SUBTITLE" VARCHAR2(4000 BYTE),
	"IMAGE_URL" VARCHAR2(4000 BYTE),
	"CATEGORY" VARCHAR2(4000 BYTE),
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	 CONSTRAINT "TB_ASNF_TXN_MASTER_PK" PRIMARY KEY ("NOTIF_ID", "APP_ID", "NOTIF_MSG")
   );

 /*  CREATE TABLE "TB_AFTP_WORKFLOW_DET"
  (
    "TRANSACTION_REF_NO" VARCHAR2(30 BYTE) NOT NULL ,
    "VERSION_NO"         DECIMAL(10, 0) NOT NULL ,
   "WORKFLOW_ID"        VARCHAR2(100 BYTE) NOT NULL ,
   "CURRENT_STAGE"       VARCHAR2(100 BYTE) NOT NULL ,
    "SCREEN_ID"          VARCHAR2(100 BYTE) NOT NULL ,
    "NEXT_STAGE"         VARCHAR2(100 BYTE) NULL ,
    "STATUS"             VARCHAR2(20 BYTE) NULL ,
    "APP_ID"             VARCHAR2(100 BYTE) NOT NULL ,
    "INTERFACE_ID"        VARCHAR2(100 BYTE) NOT NULL ,
   "USER_ID"             VARCHAR2(100 BYTE) NULL ,
    "SCREEN_DATA" CLOB NULL ,
    "STAGE_SEQ_NO"   VARCHAR2(255 BYTE) NULL ,
    "ACTION"         VARCHAR2(255 BYTE) NULL ,
    "CREATE_USER_ID" VARCHAR2(100 BYTE) NULL ,
    "CREATE_TS" TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CONSTRAINT "TB_AFTP_WORKFLOW_DET_PK" PRIMARY KEY ( "TRANSACTION_REF_NO", "VERSION_NO", "WORKFLOW_ID", "CURRENT_STAGE","SCREEN_ID" ,"APP_ID" ,"INTERFACE_ID" )
  );
  */
   
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASTP_WORKFLOW_DET';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
   CREATE TABLE "TB_ASTP_WORKFLOW_DET"
  (
    "TRANSACTION_REF_NO" VARCHAR2(30 BYTE) NOT NULL ,
    "VERSION_NO"         DECIMAL(10, 0) NULL ,
   "WORKFLOW_ID"        VARCHAR2(100 BYTE) NOT NULL ,
   "APP_ID"             VARCHAR2(100 BYTE) NOT NULL ,
   "CURRENT_STAGE"       VARCHAR2(100 BYTE) NULL ,
    "SCREEN_ID"          VARCHAR2(100 BYTE) NULL ,
    "NEXT_STAGE"         VARCHAR2(100 BYTE) NULL ,
    "STATUS"             VARCHAR2(20 BYTE) NULL ,
    "INTERFACE_ID"        VARCHAR2(100 BYTE) NULL ,
   "USER_ID"             VARCHAR2(100 BYTE) NULL ,
    "SCREEN_DATA" CLOB NULL ,
    "STAGE_SEQ_NO"   VARCHAR2(255 BYTE) NULL ,
    "ACTION"         VARCHAR2(255 BYTE) NULL ,
    "CREATE_USER_ID" VARCHAR2(100 BYTE) NULL ,
    "CREATE_TS" TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CONSTRAINT "TB_ASTP_WORKFLOW_DET_PK" PRIMARY KEY ("TRANSACTION_REF_NO", "WORKFLOW_ID", "APP_ID")
  );

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASFS_FILE_DETAILS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASFS_FILE_DETAILS"
  (
    "APP_ID"    VARCHAR2(200) NOT NULL ,
    "SCREEN_ID"   VARCHAR2(100) NULL ,
    "USER_ID"   VARCHAR2(100) NULL ,
    "FILE_NAME" VARCHAR2(150) NOT NULL ,
    "FILE_TYPE" VARCHAR2(20) NULL ,
    "CREATE_USER_ID" VARCHAR(100) NULL ,
    "INTERFACE_ID" VARCHAR(30) NULL,
    "LAST_UPLOADED_DATE" TIMESTAMP DEFAULT SYSTIMESTAMP ,
    "RECENT_UPLOADED_DATE" TIMESTAMP DEFAULT SYSTIMESTAMP ,
    CONSTRAINT PK_TB_ASFS_FILE_DETAILS PRIMARY KEY ( APP_ID,FILE_NAME )
  );
  
 /*
 * Changes made by Ripu
 * Below table added for FS item : Appzillon - 3.1 - 13, 15, 65 Start
 */
/* Appzillon - 3.1 - 13, 15, 65 END */

/*
 * Changes made by Ripu
 * Below tables added for (OTA) FS item : Appzillon - 3.1 - 13 Start
 */
--------------------------------------------------------
--  DDL for Table TB_ASMI_APP_USER
--------------------------------------------------------

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_APP_USER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_APP_USER"
   (	 
	"USER_ID" VARCHAR2(50) NOT NULL, 
  	"PARENT_APP_ID" VARCHAR2(100) NOT NULL,
	"CHILD_APP_ID" VARCHAR2(100) NOT NULL, 
	"CREATE_USER_ID" VARCHAR2(50 BYTE), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER(10,0) DEFAULT 1, 
	 CONSTRAINT "TB_ASMI_APP_USER_PK" PRIMARY KEY ("USER_ID", "PARENT_APP_ID", "CHILD_APP_ID")
    ) ;
   
--------------------------------------------------------
--  DDL for Table TB_ASMI_APP_FILES
--------------------------------------------------------

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_APP_FILES';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_APP_FILES" 
   (	
	"APP_ID" VARCHAR2(100) NOT NULL, 
	"APP_VERSION" VARCHAR2(10) NOT NULL,
    "OS" VARCHAR2(20) NOT NULL,
    "FILE_NAME" VARCHAR2(100) NOT NULL,
	"FILE_PATH" VARCHAR2(255), 
	"ACTION" VARCHAR2(10),
	"CREATE_USER_ID" VARCHAR2(100), 
	"CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"VERSION_NO" NUMBER(10,0) DEFAULT 1,
	CONSTRAINT "TB_ASMI_APP_FILES_PK" PRIMARY KEY ("APP_ID", "APP_VERSION", "OS", "FILE_NAME")
   ) ;
   
--------------------------------------------------------
--  DDL for Table TB_ASMI_APP_OS_VERSION
--------------------------------------------------------

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_APP_OS_VERSION';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_APP_OS_VERSION"
   (	 
    "APP_ID" VARCHAR2(100) NOT NULL, 
  	"OS" VARCHAR2(20) NOT NULL,
    "APP_VERSION" VARCHAR2(10) NOT NULL, 
    "CREATE_USER_ID" VARCHAR2(50 BYTE), 
    "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
    "VERSION_NO" NUMBER(10,0) DEFAULT 1,
    "APP_ACTION" VARCHAR2(10) DEFAULT 'IGNORE' NOT NULL,
    CONSTRAINT "TB_ASMI_APP_OS_VERSION_PK" PRIMARY KEY ("APP_ID", "OS", "APP_VERSION")
    ) ;
    
 /* Appzillon - 3.1 - 13 END */



/*
 * Changes done by Ripu
 * Appzillon - 3.1 - Task Repair Start
 */
/*CREATE TABLE "TB_AFHS_WORKFLOW_DET"
  (
    "TRANSACTION_REF_NO" VARCHAR2(30) NOT NULL ,
    "VERSION_NO"         DECIMAL(10, 0) NOT NULL,
   "WORKFLOW_ID"        VARCHAR2(100) NOT NULL ,
   "CURRENT_STAGE"       VARCHAR2(100) NOT NULL ,
    "SCREEN_ID"          VARCHAR2(100) NOT NULL ,
    "NEXT_STAGE"         VARCHAR2(100) NULL ,
    "STATUS"             VARCHAR2(20) NULL ,
    "APP_ID"             VARCHAR2(100) NOT NULL ,
    "INTERFACE_ID"        VARCHAR2(100) NOT NULL ,
   "USER_ID"             VARCHAR2(100) NULL ,
    "SCREEN_DATA" CLOB NULL ,
    "STAGE_SEQ_NO"   VARCHAR2(255) NULL ,
    "ACTION"         VARCHAR2(255) NULL ,
    "CREATE_USER_ID" VARCHAR2(100) NULL ,
    "CREATE_TS" TIMESTAMP DEFAULT systimestamp ,
    "HISTORY_VERSION_NO" DECIMAL(10, 0) NOT NULL,
    CONSTRAINT "TB_AFHS_WORKFLOW_DET_PK" PRIMARY KEY ("TRANSACTION_REF_NO", "VERSION_NO", "WORKFLOW_ID", "CURRENT_STAGE","SCREEN_ID" ,"APP_ID" ,"INTERFACE_ID","HISTORY_VERSION_NO" )
  );*/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASHS_WORKFLOW_DET';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASHS_WORKFLOW_DET"
  (
    "TRANSACTION_REF_NO" VARCHAR2(30) NOT NULL ,
    "VERSION_NO"         DECIMAL(10, 0) NOT NULL,
   "WORKFLOW_ID"        VARCHAR2(100) NOT NULL ,
   "APP_ID"             VARCHAR2(100) NOT NULL ,
   "CURRENT_STAGE"       VARCHAR2(100) NULL ,
    "SCREEN_ID"          VARCHAR2(100) NULL ,
    "NEXT_STAGE"         VARCHAR2(100) NULL ,
    "STATUS"             VARCHAR2(20) NULL ,
    "INTERFACE_ID"        VARCHAR2(100) NULL ,
   "USER_ID"             VARCHAR2(100) NULL ,
    "SCREEN_DATA" CLOB NULL ,
    "STAGE_SEQ_NO"   VARCHAR2(255) NULL ,
    "ACTION"         VARCHAR2(255) NULL ,
    "CREATE_USER_ID" VARCHAR2(100) NULL ,
    "CREATE_TS" TIMESTAMP DEFAULT systimestamp ,
    CONSTRAINT "TB_ASHS_WORKFLOW_DET_PK" PRIMARY KEY ("TRANSACTION_REF_NO", "VERSION_NO", "WORKFLOW_ID", "APP_ID")
  );
  /* Appzillon - 3.1 - Task Repair End*/
 

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASTP_BEACON_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASTP_BEACON_MASTER" 
   (   
   "APP_ID" VARCHAR2(100),
  "ID" NUMBER(20,0),
  "DEVICE_ID" VARCHAR2(225),
  "USER_ID" VARCHAR2(100),
  "ENTRY_TIME" TIMESTAMP (6),
  "STATUS" VARCHAR2(45),
  CONSTRAINT "TB_ASTP_BEACON_MASTER_PK" PRIMARY KEY ("ID")
   );
   
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASTP_OTP_ENGINE';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/   
CREATE TABLE "TB_ASTP_OTP_ENGINE" 
   (	"REF_NO" NUMBER(20,0), 
	"APP_ID" VARCHAR2(100 BYTE), 
	"USER_ID" VARCHAR2(255 BYTE), 
	"INTERFACE_ID" VARCHAR2(255 BYTE), 
	"SESSION_ID" VARCHAR2(255 BYTE), 
	"OTP" VARCHAR2(255 BYTE), 
	"OTP_GEN_TS" TIMESTAMP (6),
	"OTP_EXP_TS" TIMESTAMP (6), 
	"OTP_STATUS" VARCHAR2(255 BYTE) DEFAULT 'N', 
	"OTP_VAL_TS" TIMESTAMP (6),
	"REQ_LD_REFNO" VARCHAR2(100), 
    "REQ_NO_RECS" NUMBER(10,0), 
	"REQ_PAYLOAD_STATUS" VARCHAR2(200 BYTE), 
	"REQ_PAYLOAD_PROCESS_TS" TIMESTAMP (6),
	"OTP_VALIDATION_COUNT" NUMBER(10,0),
  	"OTP_RESENT_COUNT" NUMBER(10,0),
  	"OTP_REGEN_COUNT" NUMBER(10,0) DEFAULT 0,
 	"OTP_RESEND_LOCK" VARCHAR2(100 BYTE),
	"OTP_RESEND_LOCK_TS" TIMESTAMP (6),
	"VERSION_NO" NUMBER(10,0) DEFAULT 0 NOT NULL
   );
    

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASTP_AR_MASTER';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASTP_AR_MASTER" 
   (
	"APP_ID" VARCHAR2(255),
   	"ID" NUMBER(20,0) NOT NULL ENABLE,
    "REGION_CODE" VARCHAR2(255),
    "CATEGORY"    VARCHAR2(255),
    "LATITUDE"  VARCHAR2(255),
    "LONGITUDE" VARCHAR2(255),
    "TITLE" VARCHAR2(255),
    "ADDITIONAL_INFO" VARCHAR2(255),
    "DESCRIPTION" VARCHAR2(255),
    "IMAGE" VARCHAR2(255),
    CONSTRAINT "TB_ASTP_AR_MASTER_PK" PRIMARY KEY ("ID")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_SCHEDULER_JOB_EXP';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASMI_SCHEDULER_JOB_EXP" (
  "JOB_NAME" VARCHAR2(45) NOT NULL,
  "START_DATE" VARCHAR2(45) NULL,
  "END_DATE" VARCHAR2(45) NULL,
  "EXP_START_SEC" VARCHAR2(45) NULL,
  "EXP_SEC" VARCHAR2(45) NULL,
  "EXP_MIN" VARCHAR2(45) NULL,
  "EXP_HR" VARCHAR2(45) NULL,
  "EXP_DOM" VARCHAR2(45) NULL,
  "EXP_MONTH" VARCHAR2(45) NULL,
  "EXP_DOW" VARCHAR2(45) NULL,
  "EXP_YEAR" VARCHAR2(45) NULL,
  "EXPRESSION" VARCHAR2(45) NULL,
  CONSTRAINT "TB_ASMI_SCHEDULER_JOB_EXP_PK" PRIMARY KEY ("JOB_NAME")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_SCHEDULER_JOB';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
CREATE TABLE "TB_ASMI_SCHEDULER_JOB" (
  "APP_ID" VARCHAR2(45) NULL,
  "JOB_NAME" VARCHAR2(255) NOT NULL,
  "JOB_CLASS" VARCHAR2(255) NULL,
  "JOB_DATA" VARCHAR2(255) NULL,
  "JOB_STATUS" VARCHAR2(45) DEFAULT 'P',
  "JOB_CREATED_TS" TIMESTAMP (6),
  "JOB_EXECUTED_TS" TIMESTAMP (6),
  CONSTRAINT "TB_ASMI_SCHEDULER_JOB_PK" PRIMARY KEY ("JOB_NAME")
);

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_OS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE TB_OS (
  "OS_ID" varchar(15) NOT NULL,
  "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
  PRIMARY KEY ("OS_ID")
);

--------------------------------------------------------
--  DDL for Table TB_ASMI_APP_OS_VERSION
--------------------------------------------------------

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_APP_ID_VERSION';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/
  CREATE TABLE "TB_ASMI_APP_ID_VERSION"
   (	 
    "APP_ID" VARCHAR2(100) NOT NULL,
    "OS" VARCHAR2(20) NOT NULL,
  	"APP_ID_VERSION" VARCHAR2(10) NOT NULL,
    "CREATE_USER_ID" VARCHAR2(50 BYTE), 
    "CREATE_TS" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
    "VERSION_NO" NUMBER(10,0) DEFAULT 1,
    CONSTRAINT "TB_ASMI_APP_ID_VERSION_PK" PRIMARY KEY ("APP_ID","OS","APP_ID_VERSION")
    ) ;

  
CREATE OR REPLACE VIEW VW_NOTIFY_APPID as select DISTINCT(APP_ID) appId from TB_ASNF_DEVICES_MASTER;

CREATE OR REPLACE VIEW VW_DIGITS AS
  SELECT 0 as digit from DUAL UNION ALL
  SELECT 1 from DUAL UNION ALL
  SELECT 2 from DUAL UNION ALL
  SELECT 3 from DUAL UNION ALL
  SELECT 4 from DUAL UNION ALL
  SELECT 5 from DUAL UNION ALL
  SELECT 6 from DUAL UNION ALL
  SELECT 7 from DUAL UNION ALL
  SELECT 8 from DUAL UNION ALL
  SELECT 9 from DUAL;

CREATE OR REPLACE VIEW VW_NUMBERS AS
  SELECT
    ones.digit + tens.digit * 10 + hundreds.digit * 100 + thousands.digit * 1000 AS numbers
  FROM
    VW_DIGITS ones,
    VW_DIGITS tens,
    VW_DIGITS hundreds,
    VW_DIGITS thousands;
 
CREATE OR REPLACE VIEW VW_DATES AS
  SELECT
    CURRENT_DATE - numbers AS dates
  FROM
    VW_NUMBERS;
    
CREATE OR REPLACE VIEW VW_OS_DATES as select trunc(d.dates) osdates,OS_ID AS datesos,appId from VW_DATES d,TB_OS o,VW_NOTIFY_APPID ap;
  
CREATE OR REPLACE VIEW VW_MESSAGE_STATS AS
select trunc(tnl.CREATED_TS) AS TXNDATE,count(0) AS num,tnm.OS_ID AS os,tnl.APP_ID AS appId
from TB_ASNF_TXN_LOG tnl,TB_ASNF_DEVICES_MASTER tnm
where (tnl.NOTIF_REG_ID = tnm.NOTIF_REG_ID) group by trunc(tnl.CREATED_TS),tnm.OS_ID,tnl.APP_ID;

CREATE OR REPLACE VIEW VW_MESSAGE_NOTIFY_STATS AS
SELECT VW_OS_DATES.appId,osdates,COALESCE(num,0) count,datesos 
FROM VW_MESSAGE_STATS RIGHT OUTER JOIN VW_OS_DATES ON osdates=TXNDATE AND 
datesos=os and VW_OS_DATES.appId=VW_MESSAGE_STATS.appId;

--------------------------------------------------------
--  DDL for Index TB_ASMI_INTF_MASTER_PK
--------------------------------------------------------

  --CREATE UNIQUE INDEX "TB_ASMI_INTF_MASTER_PK" ON "TB_ASMI_INTF_MASTER" ("INTERFACE_ID", "APP_ID") ;

--------------------------------------------------------
--  DDL for Index TB_ASLG_TXN_DETAIL_PK
--------------------------------------------------------

  --CREATE UNIQUE INDEX "TB_ASLG_TXN_DETAIL_PK" ON "TB_ASLG_TXN_DETAIL" ("TXN_REF") ;
--------------------------------------------------------
--  DDL for Index TB_ASTP_LAST_LOGIN_PK
--------------------------------------------------------

  --CREATE UNIQUE INDEX "TB_ASTP_LAST_LOGIN_PK" ON "TB_ASTP_LAST_LOGIN" ("USER_ID", "APP_ID", "DEVICE_ID") ;
--------------------------------------------------------
--  DDL for Index TB_ASMI_USER_ROLE_PK
--------------------------------------------------------

  --CREATE UNIQUE INDEX "TB_ASMI_USER_ROLE_PK" ON "TB_ASMI_USER_ROLE" ("USER_ID", "ROLE_ID", "APP_ID") ;
--------------------------------------------------------
--  DDL for Index TB_ASMI_ROLE_MASTER_PK
--------------------------------------------------------

  --CREATE UNIQUE INDEX "TB_ASMI_ROLE_MASTER_PK" ON "TB_ASMI_ROLE_MASTER" ("ROLE_ID", "APP_ID") ;
--------------------------------------------------------
--  DDL for Index TB_ASMI_APP_DTLS_PK
--------------------------------------------------------

  --CREATE UNIQUE INDEX "TB_ASMI_APP_DTLS_PK" ON "TB_ASMI_APP_DTLS" ("APP_ID", "OS_ID") ;

--------------------------------------------------------
--  DDL for Index TB_ASMI_USER_DEVICES_PK
--------------------------------------------------------

  --CREATE UNIQUE INDEX "TB_ASMI_USER_DEVICES_PK" ON "TB_ASMI_USER_DEVICES" ("APP_ID", "DEVICE_ID", "USER_ID") ;
--------------------------------------------------------
--  DDL for Index TB_NFMI_LOV_QUERIES_PK
--------------------------------------------------------

  --CREATE UNIQUE INDEX "TB_NFMI_LOV_QUERIES_PK" ON "TB_ASMI_LOV_QUERIES" ("APP_ID", "QUERY_ID") ;
--------------------------------------------------------
--  DDL for Index TB_ASMI_SECURITY_PARAMETER_PK
--------------------------------------------------------

  --CREATE UNIQUE INDEX "TB_ASMI_SECURITY_PARAMETER_PK" ON "TB_ASMI_SECURITY_PARAMETERS" ("APP_ID") ;
--------------------------------------------------------
--  DDL for Index TB_ASMI_SCR_MASTER_PK
--------------------------------------------------------

  --CREATE UNIQUE INDEX "TB_ASMI_SCR_MASTER_PK" ON "TB_ASMI_SCR_MASTER" ("SCREEN_ID", "APP_ID") ;
--------------------------------------------------------
--  DDL for Index TB_ASMI_ROLE_INTF_PK
--------------------------------------------------------

  --CREATE UNIQUE INDEX "TB_ASMI_ROLE_INTF_PK" ON "TB_ASMI_ROLE_INTF" ("APP_ID", "ROLE_ID", "INTERFACE_ID") ;
--------------------------------------------------------
--  DDL for Index TB_ASMI_OS_DTLS_PK
--------------------------------------------------------

 -- CREATE UNIQUE INDEX "TB_ASMI_OS_DTLS_PK" ON "TB_ASMI_OS_DTLS" ("OS_ID") ;
--------------------------------------------------------
--  DDL for Index TB_ASTP_SEQ_GEN_PK
--------------------------------------------------------

  --CREATE UNIQUE INDEX "TB_ASTP_SEQ_GEN_PK" ON "TB_ASTP_SEQ_GEN" ("SEQUENCE_NAME") ;

--------------------------------------------------------
--  DDL for Index TB_ASMI_USER_PK
--------------------------------------------------------

  --CREATE UNIQUE INDEX "TB_ASMI_USER_PK" ON "TB_ASMI_USER" ("USER_ID", "APP_ID") ;
--------------------------------------------------------
--  DDL for Index TB_ASMI_ROLE_SCR_PK
--------------------------------------------------------

  --------------------------------------------------------
--  Constraints for Table TB_ASMI_LOV_QUERIES
--------------------------------------------------------

  ALTER TABLE "TB_ASMI_LOV_QUERIES" ADD CONSTRAINT "TB_NFMI_LOV_QUERIES_PK" PRIMARY KEY ("APP_ID", "QUERY_ID") ENABLE;
  ALTER TABLE "TB_ASMI_LOV_QUERIES" MODIFY ("DB_JNDI_NAME" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_LOV_QUERIES" MODIFY ("QUERY_STRING" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_LOV_QUERIES" MODIFY ("QUERY_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_LOV_QUERIES" MODIFY ("APP_ID" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table TB_ASMI_APP_DTLS
--------------------------------------------------------

  ALTER TABLE "TB_ASMI_APP_DTLS" MODIFY ("OS_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_APP_DTLS" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_APP_DTLS" ADD CONSTRAINT "TB_ASMI_APP_DTLS_PK" PRIMARY KEY ("APP_ID", "OS_ID") ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_ASTP_SEQ_GEN
--------------------------------------------------------

  ALTER TABLE "TB_ASTP_SEQ_GEN" ADD CONSTRAINT "TB_ASTP_SEQ_GEN_PK" PRIMARY KEY ("SEQUENCE_NAME") ENABLE;
  ALTER TABLE "TB_ASTP_SEQ_GEN" MODIFY ("SEQUENCE_VALUE" NOT NULL ENABLE);
  ALTER TABLE "TB_ASTP_SEQ_GEN" MODIFY ("SEQUENCE_NAME" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table TB_ASMI_OS_DTLS
--------------------------------------------------------

  ALTER TABLE "TB_ASMI_OS_DTLS" MODIFY ("OS_ID" NOT NULL ENABLE);
  ALTER TABLE "TB_ASMI_OS_DTLS" ADD CONSTRAINT "TB_ASMI_OS_DTLS_PK" PRIMARY KEY ("OS_ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table TB_ASMI_APP_DTLS
--------------------------------------------------------

 -- ALTER TABLE "TB_ASMI_APP_DTLS" ADD CONSTRAINT "TB_ASMI_APP_DTLS_FK1" FOREIGN KEY ("OS_ID")
	--  REFERENCES "TB_ASMI_OS_DTLS" ("OS_ID") ENABLE;
	  
	ALTER TABLE "TB_ASTP_OTP_ENGINE" ADD CONSTRAINT "TB_ASTP_OTP_ENGINE_PK" PRIMARY KEY ("REF_NO") ENABLE;
  
INSERT into "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) values ('ADMIN_DOMAIN',1,NULL,sysdate,1);
INSERT into "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) values ('GROUP_NO',1,NULL,sysdate,1);
INSERT into "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) values ('NOTIFICATION_NO',1,NULL,sysdate,1);
INSERT into "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) values ('TXNREF',1,NULL,sysdate,1);
INSERT into "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) values ('WORKFLOW',1,NULL,sysdate,1);
INSERT into "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) values ('JMS_TXN_ID',1,NULL,sysdate,1);
INSERT into "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) values ('ACCESS_REF',1,NULL,sysdate,1);
INSERT into "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) values ('BEACON_REF',1,NULL,sysdate,1);
INSERT into "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) values ('ISO8583_F11',1,NULL,sysdate,1);
INSERT into "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) values ('OTP_REF_NO',1,NULL,sysdate,1);
INSERT INTO "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('AR_REF',1,NULL,sysdate,1);
INSERT INTO "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('SMS_TXNREF',1,NULL,sysdate,1);
INSERT INTO "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('USSD_TXNREF',1,NULL,sysdate,1);
INSERT INTO "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('TXT_TXNREF',1,NULL,sysdate,1);
INSERT INTO "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('SOURCE_MSG_ID',1,NULL,sysdate,1);
INSERT INTO "TB_ASTP_SEQ_GEN" (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('CAPTCHA_REF_NO',1,NULL,sysdate,1);
	
INSERT INTO TB_OS (OS_ID,CREATE_TS) VALUES ('ANDROID',sysdate);
INSERT INTO TB_OS (OS_ID,CREATE_TS) VALUES ('IOS',sysdate);
INSERT INTO TB_OS (OS_ID,CREATE_TS) VALUES ('WINDOWS',sysdate);
