apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: {{ lower .Values.secretAppTag }}-private-pem
  namespace:  {{ .Values.nameSpace }}
spec:
  encryptedData:
    private.pem: {{ index (index .Values .Values.serverWarName) "privatePem" }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: {{ lower .Values.secretAppTag }}-private-pem
      namespace:  {{ .Values.nameSpace }}

