{{- if .Values.openshift.cluster }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: {{ lower .Values.secretAppTag }}-tls-secret-server
  namespace:  {{ .Values.nameSpace }}
spec:
  encryptedData: 
    tls.crt: {{ index (index .Values .Values.serverWarName) "tlsCrt" }}
    tls.key: {{ index (index .Values .Values.serverWarName) "tlsKey" }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: {{ lower .Values.secretAppTag }}-tls-secret-server
      namespace:  {{ .Values.nameSpace }}
    type: kubernetes.io/tls
{{- end }}
