--------------------------------------------------------
--  Migration script from 3.18.0 to 3.19.0
--------------------------------------------------------
--NOTE : Take backup of the existing table data

--NOTE: Please make oracle database server

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE TB_ASMI_CS_NONCEDETAILS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/


 CREATE TABLE "TB_ASMI_CS_NONCEDETAILS"
   ("DEVICE_ID" VARCHAR2(100),
"APP_ID" VARCHAR2(100),
"REQUEST_ID" VARCHAR2(255),
"CLIENT_NONCE" VARCHAR2(100),
"SERVER_NONCE" VARCHAR2(100),
"STATUS" VARCHAR2(100),
"SERVER_TOKEN" VARCHAR2(100),
"CREATE_TS" TIMESTAMP (6),
    "CREATED_ON" DATE DEFAULT SYSDATE
)
 PARTITION BY RANGE ("CREATED_ON") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
  SUBPARTITION BY HASH ("DEVICE_ID")
  SUBPARTITIONS 64
 (PARTITION "CS_NON_PARTITION"  VALUES LESS THAN (TO_DATE(' 2021-04-06 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  STORAGE(BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"
 ( SUBPARTITION "SYS_SUBP44538" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44539" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44540" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44541" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44542" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44543" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44544" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44545" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44546" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44547" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44548" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44549" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44550" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44551" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44552" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44553" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44554" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44555" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44556" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44557" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44558" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44559" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44560" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44561" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44562" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44563" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44564" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44565" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44566" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44567" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44568" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44569" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44570" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44571" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44572" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44573" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44574" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44575" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44576" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44577" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44578" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44579" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44580" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44581" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44582" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44583" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44584" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44585" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44586" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44587" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44588" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44589" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44590" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44591" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44592" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44593" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44594" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44595" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44596" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44597" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44598" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44599" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44600" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ,
  SUBPARTITION "SYS_SUBP44601" SEGMENT CREATION DEFERRED
  TABLESPACE "USERS"
 NOCOMPRESS ));

create unique index TB_ASMI_CS_NONCEDETAILS_IDX01 on TB_ASMI_CS_NONCEDETAILS(CREATED_ON, DEVICE_ID, APP_ID, REQUEST_ID, CLIENT_NONCE, SERVER_NONCE) local;

