/*
 * Migration script from 3.27.2 to 3.27.3
 */

ALTER TABLE TB_ASTP_BEACON_MASTER DROP CONSTRAINT PK_TB_ASTP_BEACON_MASTER;

ALTER TABLE "TB_ASTP_BEACON_MASTER"
ALTER COLUMN "ID" BIGINT NOT NULL;

ALTER TABLE TB_ASTP_BEACON_MASTER ADD CONSTRAINT PK_TB_ASTP_BEACON_MASTER Primary Key ( ID );

ALTER TABLE TB_ASTP_OTP_ENGINE DROP CONSTRAINT TB_ASTP_OTP_ENGINE_PK;

ALTER TABLE "TB_ASTP_OTP_ENGINE"
ALTER COLUMN "REF_NO" BIGINT NOT NULL;

ALTER TABLE TB_ASTP_OTP_ENGINE ADD CONSTRAINT TB_ASTP_OTP_ENGINE_PK Primary Key ( REF_NO );

ALTER TABLE TB_ASTP_AR_MASTER DROP CONSTRAINT PK_TB_ASTP_AR_MASTER;

ALTER TABLE "TB_ASTP_AR_MASTER"
ALTER COLUMN "ID" BIGINT NOT NULL;

ALTER TABLE TB_ASTP_AR_MASTER ADD CONSTRAINT PK_TB_ASTP_AR_MASTER Primary Key ( ID );
