--------------------------------------------------------
--  Migration script from 3.7.6 to 3.7.7
--------------------------------------------------------
DROP TABLE IF EXISTS "APZ_SERVER_PROPS";

CREATE TABLE "APZ_SERVER_PROPS" (
  "APP_ID" NVARCHAR(10) NOT NULL,
  "APZ_SERVER_PROPS_KEY" NVARCHAR(100) NOT NULL,
  "APZ_SERVER_PROPS_VALUE" NVARCHAR(500) ,
  "APZ_SERVER_PROPS_DESC" NVARCHAR(255) ,
  CONSTRAINT "APZ_SERVER_PROPS_PK" PRIMARY KEY ("APP_ID", "APZ_SERVER_PROPS_KEY")
);

DROP TABLE IF EXISTS "APZ_ENV_PROPS";

CREATE TABLE "APZ_ENV_PROPS" (
"APP_ID" NVARCHAR(10),
"ENVIRONMENT" NVARCHAR(10),
"APZ_ENV_PROPS_KEY" NVARCHAR(100),
"APZ_ENV_PROPS_VALUE" NVARCHAR(500) NULL,
"APZ_ENV_PROPS_DESC" NVARCHAR(100) NULL,
CONSTRAINT "APZ_ENV_PROPS_PK" PRIMARY KEY ("APP_ID", "APZ_ENV_PROPS_KEY","ENVIRONMENT")
);
