<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<groupId>com.iexceed.appzillon</groupId>
		<artifactId>AppzillonServer</artifactId>
		<version>3.37.0</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>appzillon-server</artifactId>
	<packaging>war</packaging>
	<name>appzillon-server</name>
	
	<properties>
		<jersey.version>2.38</jersey.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-web-api</artifactId>
			<version>6.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.core</groupId>
			<artifactId>jersey-server</artifactId>
			<version>${jersey.version}</version>  
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.14.2</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-multipart</artifactId>
			<version>${jersey.version}</version> 
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.containers</groupId>
			<artifactId>jersey-container-servlet-core</artifactId>
			<version>${jersey.version}</version> 
		</dependency>

		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-json-jackson</artifactId>
			<version>${jersey.version}</version>
			<exclusions>
				<exclusion>
					<groupId>com.fasterxml.jackson.module</groupId>
					<artifactId>jackson-module-jaxb-annotations</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.module</groupId>
			<artifactId>jackson-module-jaxb-annotations</artifactId>
			<version>2.14.0</version>
			<exclusions>
				<exclusion>
					<groupId>jakarta.xml.bind</groupId>
					<artifactId>jakarta.xml.bind-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
    		<groupId>org.glassfish.jersey.inject</groupId>
    		<artifactId>jersey-hk2</artifactId>
    		<version>${jersey.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.javassist</groupId>
					<artifactId>javassist</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.javassist</groupId>
			<artifactId>javassist</artifactId>
			<version>3.28.0-GA</version>
		</dependency>
		<dependency>
			<groupId>com.iexceed.appzillon</groupId>
			<artifactId>appzillon-services-router</artifactId>
			<version>${appzillon.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.4.15</version>
		</dependency>
		<dependency>
			<groupId>org.owasp.encoder</groupId>
			<artifactId>encoder</artifactId>
			<version>1.2.3</version>
		</dependency>	
	</dependencies>

	<build>
		<finalName>AppzillonServer</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.10.1</version>
				<configuration>
					<source>17</source>
					<target>17</target>
					<compilerArguments>
						<endorseddirs>${endorsed.dir}</endorseddirs>
					</compilerArguments>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.3.2</version>
				<configuration>
					<failOnMissingWebXml>false</failOnMissingWebXml>
					<packagingExcludes>
						WEB-INF/lib/servlet-api-2.5.jar,WEB-INF/lib/geronimo-servlet_3.0_spec-1.0.jar,WEB-INF/lib/javaee-api-8.0.1.jar
						,WEB-INF/lib/wsdl4j.jar,WEB-INF/lib/xmlParserAPIs-2.0.2.jar
						,WEB-INF/lib/mysql-connector-java-5.1.6.jar,WEB-INF/lib/jaxb-impl-3.0.0.jar,
						WEB-INF/lib/jaxb-impl-2.2.3-1.jar
						,WEB-INF/lib/xercesImpl-2.12.2.jar,
						WEB-INF/lib/javax.comm-1.0.0.jar,
						WEB-INF/lib/javaee-web-api-7.0.jar,WEB-INF/lib/javaee-api-6.0.jar,WEB-INF/lib/org.apache.xerces-2.9.0.jar
						,WEB-INF/lib/javaee-api-6.0-5.jar,WEB-INF/lib/javaee-api-7.0.jar,WEB-INF/lib/xercesImpl-2.12.2.jar
						,WEB-INF/lib/org.apache.commons.codec-1.3.0.jar,
						WEB-INF/lib/log4j-1.2.17.jar,
						WEB-INF/lib/bcprov-jdk14-138.jar,WEB-INF/lib/bcmail-jdk14-138.jar,WEB-INF/lib/geronimo-servlet_2.5_spec-1.2.jar,/WEB-INF/lib/spring-batch-infrastructure-4.3.1.jar
					</packagingExcludes>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.3.0</version>
				<executions/>
			</plugin>
		</plugins>
	</build>
</project>
