<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
	  	<groupId>com.iexceed.appzillon</groupId>
  		<artifactId>AppzillonServer</artifactId>
  		<version>3.37.0</version>
	</parent>
	<modelVersion>4.0.0</modelVersion>
	<artifactId>appzillon-services-router</artifactId>
	<packaging>jar</packaging>
	<dependencies>
		<dependency>
			<groupId>com.iexceed.appzillon</groupId>
			<artifactId>appzillon-commons-utils</artifactId>
			<version>${appzillon.version}</version>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>com.iexceed.appzillon</groupId>
			<artifactId>appzillon-sms</artifactId>
			<version>${appzillon.version}</version>
		</dependency>
		<dependency>
			<groupId>com.iexceed.appzillon</groupId>
			<artifactId>appzillon-frameworks</artifactId>
			<version>${appzillon.version}</version>
		</dependency>
		<dependency>
			<groupId>com.iexceed.appzillon</groupId>
			<artifactId>appzillon-notification</artifactId>
			<version>${appzillon.version}</version>
		</dependency>
		<dependency>
			<groupId>com.iexceed.appzillon</groupId>
			<artifactId>appzillon-scheduler</artifactId>
			<version>${appzillon.version}</version>
		</dependency>
		<dependency>
			<groupId>com.iexceed.appzillon</groupId>
			<artifactId>appzillon-appsec</artifactId>
			<version>${appzillon.version}</version>
		</dependency>
		<dependency>
			<groupId>com.iexceed.appzillon</groupId>
			<artifactId>appzillon-citi-utils</artifactId>
			<version>${appzillon.version}</version>
		</dependency>
		<dependency>
			<groupId>com.iexceed.appzillon</groupId>
			<artifactId>appzillon-workflow</artifactId>
			<version>${appzillon.version}</version>
		</dependency>
	</dependencies>
</project>
