--------------------------------------------------------
--  Migration script from 3.7.7 to 3.7.8
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_AZURE_TOKEN";

CREATE TABLE "TB_ASMI_AZURE_TOKEN" (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "USER_ID" NVARCHAR(100) NOT NULL,
  "DEVICE_ID" NVARCHAR(255) NOT NULL,
  "AUTH_CODE" NTEXT NULL,
  "ACCESS_TOKEN" NTEXT,
  "ID_TOKEN" NTEXT,
  "TOKEN_TYPE" NVARCHAR(300) DEFAULT NULL,
  "NOT_BEFORE" BIGINT DEFAULT NULL,
  "EXPIRES_IN" INT DEFAULT NULL,
  "EXPIRES_ON" BIGINT DEFAULT NULL,
  "ID_TOKEN_EXPIRES_IN" BIGINT DEFAULT NULL,
  "REFRESH_TOKEN" NTEXT,
  "REFRESH_TOKEN_EXPIRES_IN" BIGINT DEFAULT NULL,
  "SESSION_ID" NVARCHAR(255) DEFAULT NULL,
  "CREATED_BY" NVARCHAR(100) DEFAULT NULL,
  "CREATED_TS" DATETIME NULL DEFAULT NULL,
  "MAKER_ID" NVARCHAR(100) DEFAULT NULL,
  "MAKER_TS" DATETIME NULL DEFAULT NULL,
  CONSTRAINT "TB_ASMI_AZURE_TOKEN_PK" PRIMARY KEY ("APP_ID","USER_ID","DEVICE_ID")
);