spring.liquibase.change-log=classpath:/db/changelog/mssql/master.xml
logging.level.liquibase = INFO
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://192.168.2.4:1433;DatabaseName=test
spring.datasource.username=xxxx
spring.datasource.password=xxxxx
liquibase.liquibaseProLicenseKey=
liquibase.verbose=true 
liquibase.dropFirst=false