spring.liquibase.change-log=classpath:/db/changelog/postgresql/master.xml
logging.level.liquibase = INFO
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://18.118.80.177:5432/test
spring.datasource.username=test
spring.datasource.password=xxxx
liquibase.liquibaseProLicenseKey=
liquibase.verbose=true 
liquibase.dropFirst=false