spring.liquibase.change-log=classpath:/db/changelog/mysql/master.xml
logging.level.liquibase = INFO
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://18.220.120.85:3306/test
spring.datasource.username=test
spring.datasource.password=xxxx
liquibase.liquibaseProLicenseKey=
liquibase.verbose=true 
liquibase.dropFirst=false