spring.liquibase.change-log=classpath:/db/changelog/oracle/master.xml
logging.level.liquibase = INFO
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@192.168.1.1:1521:xxxx
spring.datasource.username=test
spring.datasource.password=xxxx
liquibase.liquibaseProLicenseKey=
liquibase.verbose=true 
liquibase.dropFirst=false