/* App Details */
DELETE FROM TB_ASMI_APP_OS_VERSION WHERE (APP_ID='Admin'AND OS='WEB' );
INSERT INTO TB_ASMI_APP_OS_VERSION (APP_ID,OS,APP_VERSION,CREATE_USER_ID,CREATE_TS,VERSION_NO)
 VALUES('Admin','WEB','1.0.0.0','Admin',now(),1);
DELETE FROM TB_ASMI_APP_ID_VERSION WHERE (APP_ID='Admin'AND OS='WEB' );
INSERT INTO TB_ASMI_APP_ID_VERSION (APP_ID,OS,APP_ID_VERSION,CREATE_USER_ID,CREATE_TS,VERSION_NO)
 VALUES('Admin','WEB','1.0.0.0','Admin',now(),1);
/* LOV Details  */
DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchAllApps');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchAllApps','SELECT APP_ID FROM TB_ASMI_APP_MASTER','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','','','',null,null,now(),now(),'Admin',1);

DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchAllowApp_ID');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchAllowApp_ID','select APP_ID from TB_ASMI_SECURITY_PARAMETERS where APP_ID IN (select ALLOWED_APP_ID from TB_ASMI_USER_APP_ACCESS
where USER_ID=? AND APP_ACCESS = ''A'' AND APP_ID=?)','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','B0|B1','STRING|STRING','',null,null,now(),now(),'Admin',1);

DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchAuthRole_ID');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchAuthRole_ID','select ROLE_ID from TB_ASMI_ROLE_MASTER where APP_ID=? and AUTH_STATUS=''A''','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','B0','STRING','ROLE_ID',null,null,now(),now(),'Admin',1);

DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchControl_ID');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchControl_ID','Select CONTROL_ID,CONTROL_DESC from TB_ASMI_CONTROLS_MASTER where APP_ID=?
','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','B0','STRING','CONTROL_ID|CONTROL_DESC',null,null,now(),now(),'Admin',1);

DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchConv_ID');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchConv_ID','Select CNVUI_ID from TB_ASMI_CNVUI_MASTER where APP_ID=?','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','B0','STRING','CNVUI_ID',null,null,now(),now(),'Admin',1);

DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchDevice_ID');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchDevice_ID','Select DEVICE_ID from TB_ASNF_DEVICES_MASTER where APP_ID=? and STATUS=''Y''
','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','B0','STRING','DEVICE_ID',null,null,now(),now(),'Admin',1);

DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchDlgScreens');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchDlgScreens','select SCREEN_ID,SCREEN_DESC from TB_ASMI_CNVUI_SCR where APP_ID=?','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','B0','STRING','',null,null,now(),now(),'Admin',1);

DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchGroup_ID');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchGroup_ID','select GROUP_ID,GROUP_DESC from TB_ASNF_GROUP_MASTER
','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','','','GROUP_ID|GROUP_DESC',null,null,now(),now(),'Admin',1);

DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchInterface_ID');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchInterface_ID','Select INTERFACE_ID,DESCRIPTION from TB_ASMI_INTF_MASTER where APP_ID=? and AUTHRZ_REQ = ''Y''
','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','B0','STRING','INTERFACE_ID|DESCRIPTION',null,null,now(),now(),'Admin',1);

DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchNextDlgId');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchNextDlgId','Select DLG_ID from TB_ASMI_DLG_MASTER where APP_ID=? AND CNVUI_ID=?','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','B0|B1','STRING|STRING','DLG_ID',null,null,now(),now(),'Admin',1);

DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchOperations');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchOperations','Select INTERFACE_ID,DESCRIPTION from TB_ASMI_INTF_MASTER where APP_ID=?
','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','B0','STRING','INTERFACE_ID|DESCRIPTION',null,null,now(),now(),'Admin',1);

DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchRole_ID');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchRole_ID','select ROLE_ID from TB_ASMI_ROLE_MASTER where APP_ID=?','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','B0','STRING','ROLE_ID',null,null,now(),now(),'Admin',1);

DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchScreen_ID');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchScreen_ID','select SCREEN_ID,SCREEN_DESC from TB_ASMI_SCR_MASTER where APP_ID=?','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','B0','STRING','SCREEN_ID|SCREEN_DESC',null,null,now(),now(),'Admin',1);

DELETE FROM TB_ASMI_LOV_QUERIES WHERE (APP_ID = 'Admin' AND QUERY_ID='Admin__FetchUser_ID');
 INSERT INTO TB_ASMI_LOV_QUERIES(APP_ID,QUERY_ID,QUERY_STRING,DB_JNDI_NAME,SESSION_REQD,QUERY_TYPE,BINDVAR_COLS,BINDVAR_DATA_TYPES,FILTER_COLS,ORDERBY_COL,ORDERBY_TYPE,CREATE_TS,UPDATE_TS,CREATE_BY,VERSION_NO) VALUES('Admin','Admin__FetchUser_ID','Select USER_ID,USER_NAME from TB_ASMI_USER where APP_ID=?','java:comp/env/jdbc/AppzillonServerDS','Y','SQL','B0','STRING','USER_ID|USER_NAME',null,null,now(),now(),'Admin',1);

/* Admin Details */
DELETE FROM TB_ASMI_SECURITY_PARAMETERS WHERE APP_ID='Admin' AND CREATE_USER_ID='System';
INSERT INTO TB_ASMI_SECURITY_PARAMETERS (APP_ID,MIN_NUM_NUM,MIN_NUM_SPCL_CHAR,MIN_NUM_UPPER_CASE_CHAR,MIN_NUM_LOWER_CASE_CHAR,MIN_LENGTH,MAX_LENGTH,PASS_CHANGE_FREQ,LAST_N_PASS_NOT_TO_USE,SESSION_TIMEOUT,NOOFFAILEDCOUNTS,CREATE_USER_ID,CREATE_TS,VERSION_NO,SERVER_TOKEN,FAIL_COUNT_TIMEOUT,PASSWORD_COUNT,DEFAULT_AUTHORIZATION,ALLOW_USER_PASSWORD_ENTRY,AUTO_APPROVE,PWD_COMM_CHANNEL,AUTH_STATUS,MULTIPLE_SESSION_ALLOWED,OTP_LENGTH,OTP_VALIDATION_COUNT,OTP_EXPIRY,OTP_RESEND,OTP_FORMAT,OTP_RESEND_COUNT,OTP_RESEND_LOCK_TIMEOUT,OTP_REGEN_COUNT,DATA_INTEGRITY,TXN_LOG_REQ,TXN_LOG_PAYLOAD,FMW_TXN_REQ,FMW_TXN_PAYLOAD, ACCESS_TOKEN_EXPIRY)
 VALUES('Admin',1,1,1,1,8,32,30,1,'3000',5,'System',null,1,'ADMIN',5,5,'Y','N','Y','BOTH','A','Y','6','5','600','N','numeric','3','300','0','Y','Y','NONE','Y','NONE','1800');

/*Internal Interface Generation Begin*/
DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonUploadFile' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonUploadFile','Admin','INTERNAL','INTERNAL','appzillonUploadFile','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonUploadFile' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonUploadFile','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonUploadFileWS' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonUploadFileWS','Admin','INTERNAL','INTERNAL','appzillonUploadFileWS','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonUploadFileWS' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonUploadFileWS','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonUploadFileAuth' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonUploadFileAuth','Admin','INTERNAL','INTERNAL','appzillonUploadFileAuth','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonUploadFileAuth' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonUploadFileAuth','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonFlushCacheReq' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonFlushCacheReq','Admin','INTERNAL','INTERNAL','appzillonFlushCacheReq','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonFlushCacheReq' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonFlushCacheReq','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonAppUsageReport' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonAppUsageReport','Admin','INTERNAL','INTERNAL','appzillonAppUsageReport','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonAppUsageReport' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonAppUsageReport','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonCreateDevice' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonCreateDevice','Admin','INTERNAL','INTERNAL','appzillonCreateDevice','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonCreateDevice' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonCreateDevice','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonCreateGroup' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonCreateGroup','Admin','INTERNAL','INTERNAL','appzillonCreateGroup','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonCreateGroup' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonCreateGroup','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonCreateRoleMaster' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonCreateRoleMaster','Admin','INTERNAL','INTERNAL','appzillonCreateRoleMaster','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonCreateRoleMaster' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonCreateRoleMaster','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonCreateScreen' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonCreateScreen','Admin','INTERNAL','INTERNAL','appzillonCreateScreen','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonCreateScreen' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonCreateScreen','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonCreateUser' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonCreateUser','Admin','INTERNAL','INTERNAL','appzillonCreateUser','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonCreateUser' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonCreateUser','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonUserAuthorization' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonUserAuthorization','Admin','INTERNAL','INTERNAL','appzillonUserAuthorization','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonUserAuthorization' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonUserAuthorization','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonDeleteDevice' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonDeleteDevice','Admin','INTERNAL','INTERNAL','appzillonDeleteDevice','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonDeleteDevice' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonDeleteDevice','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonDeleteFile' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonDeleteFile','Admin','INTERNAL','INTERNAL','appzillonDeleteFile','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonDeleteFile' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonDeleteFile','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonDeleteGroup' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonDeleteGroup','Admin','INTERNAL','INTERNAL','appzillonDeleteGroup','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonDeleteGroup' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonDeleteGroup','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonDeleteScreen' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonDeleteScreen','Admin','INTERNAL','INTERNAL','appzillonDeleteScreen','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonDeleteScreen' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonDeleteScreen','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonFilePushService' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonFilePushService','Admin','INTERNAL','INTERNAL','appzillonFilePushService','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonFilePushService' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonFilePushService','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonFilePushServiceAuth' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonFilePushServiceAuth','Admin','INTERNAL','INTERNAL','appzillonFilePushServiceAuth','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonFilePushServiceAuth' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonFilePushServiceAuth','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonFilePushServiceWS' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonFilePushServiceWS','Admin','INTERNAL','INTERNAL','appzillonFilePushServiceWS','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonFilePushServiceWS' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonFilePushServiceWS','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonGetGroupDetail' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonGetGroupDetail','Admin','INTERNAL','INTERNAL','appzillonGetGroupDetail','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonGetGroupDetail' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonGetGroupDetail','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonGetReqResp' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonGetReqResp','Admin','INTERNAL','INTERNAL','appzillonGetReqResp','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonGetReqResp' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonGetReqResp','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonLoginReport' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonLoginReport','Admin','INTERNAL','INTERNAL','appzillonLoginReport','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonLoginReport' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonLoginReport','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonNotificationAppDetail' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonNotificationAppDetail','Admin','INTERNAL','INTERNAL','appzillonNotificationAppDetail','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonNotificationAppDetail' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonNotificationAppDetail','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonPushNotification' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonPushNotification','Admin','INTERNAL','INTERNAL','appzillonPushNotification','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonPushNotification' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonPushNotification','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonSearchDevice' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonSearchDevice','Admin','INTERNAL','INTERNAL','appzillonSearchDevice','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonSearchDevice' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonSearchDevice','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonSearchFile' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonSearchFile','Admin','INTERNAL','INTERNAL','appzillonSearchFile','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonSearchFile' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonSearchFile','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonSearchGroup' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonSearchGroup','Admin','INTERNAL','INTERNAL','appzillonSearchGroup','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonSearchGroup' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonSearchGroup','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonSearchScreen' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonSearchScreen','Admin','INTERNAL','INTERNAL','appzillonSearchScreen','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonSearchScreen' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonSearchScreen','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonSearchTxnLogging' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonSearchTxnLogging','Admin','INTERNAL','INTERNAL','appzillonSearchTxnLogging','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonSearchTxnLogging' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonSearchTxnLogging','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonUpdateDevice' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonUpdateDevice','Admin','INTERNAL','INTERNAL','appzillonUpdateDevice','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonUpdateDevice' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonUpdateDevice','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonUpdateGroup' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonUpdateGroup','Admin','INTERNAL','INTERNAL','appzillonUpdateGroup','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonUpdateGroup' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonUpdateGroup','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonUpdateScreen' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonUpdateScreen','Admin','INTERNAL','INTERNAL','appzillonUpdateScreen','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonUpdateScreen' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonUpdateScreen','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonDecrypt' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonDecrypt','Admin','INTERNAL','INTERNAL','appzillonDecrypt','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonDecrypt' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonDecrypt','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonLoggingRequest' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonLoggingRequest','Admin','INTERNAL','INTERNAL','appzillonLoggingRequest','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonLoggingRequest' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonLoggingRequest','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonWorkflowDashboardQuery' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonWorkflowDashboardQuery','Admin','INTERNAL','INTERNAL','appzillonWorkflowDashboardQuery','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonWorkflowDashboardQuery' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonWorkflowDashboardQuery','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonWorkflowPersist' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonWorkflowPersist','Admin','INTERNAL','INTERNAL','appzillonWorkflowPersist','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonWorkflowPersist' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonWorkflowPersist','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonWorkflowQuery' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonWorkflowQuery','Admin','INTERNAL','INTERNAL','appzillonWorkflowQuery','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonWorkflowQuery' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonWorkflowQuery','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonWorkflowQueryDb' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonWorkflowQueryDb','Admin','INTERNAL','INTERNAL','appzillonWorkflowQueryDb','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonWorkflowQueryDb' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonWorkflowQueryDb','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonWorkflowQueryRequest' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonWorkflowQueryRequest','Admin','INTERNAL','INTERNAL','appzillonWorkflowQueryRequest','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonWorkflowQueryRequest' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonWorkflowQueryRequest','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonCreatePasswordRules' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonCreatePasswordRules','Admin','INTERNAL','INTERNAL','appzillonCreatePasswordRules','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonCreatePasswordRules' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonCreatePasswordRules','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonDeletePasswordRules' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonDeletePasswordRules','Admin','INTERNAL','INTERNAL','appzillonDeletePasswordRules','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonDeletePasswordRules' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonDeletePasswordRules','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonGetPasswordRules' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonGetPasswordRules','Admin','INTERNAL','INTERNAL','appzillonGetPasswordRules','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonGetPasswordRules' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonGetPasswordRules','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonGetPasswordByRules' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonGetPasswordByRules','Admin','INTERNAL','INTERNAL','appzillonGetPasswordByRules','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonGetPasswordByRules' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonGetPasswordByRules','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonUpdatePasswordRules' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonUpdatePasswordRules','Admin','INTERNAL','INTERNAL','appzillonUpdatePasswordRules','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonUpdatePasswordRules' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonUpdatePasswordRules','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonUpdateUser' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonUpdateUser','Admin','INTERNAL','INTERNAL','appzillonUpdateUser','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonUpdateUser' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonUpdateUser','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonDeleteUser' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonDeleteUser','Admin','INTERNAL','INTERNAL','appzillonDeleteUser','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonDeleteUser' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonDeleteUser','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonSearchUser' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonSearchUser','Admin','INTERNAL','INTERNAL','appzillonSearchUser','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonSearchUser' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonSearchUser','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonGetRolesByAppIDUserID' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonGetRolesByAppIDUserID','Admin','INTERNAL','INTERNAL','appzillonGetRolesByAppIDUserID','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonGetRolesByAppIDUserID' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonGetRolesByAppIDUserID','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonGetRolesByAppID' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonGetRolesByAppID','Admin','INTERNAL','INTERNAL','appzillonGetRolesByAppID','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonGetRolesByAppID' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonGetRolesByAppID','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonPasswordReset' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonPasswordReset','Admin','INTERNAL','INTERNAL','appzillonPasswordReset','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonPasswordReset' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonPasswordReset','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonForgotPassword' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonForgotPassword','Admin','INTERNAL','INTERNAL','appzillonForgotPassword','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonForgotPassword' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonForgotPassword','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonUnlockUser' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ,VERSION_NO,INTERFACE_DEF ) values('appzillonUnlockUser','Admin','INTERNAL','INTERNAL','appzillonUnlockUser','Y','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N',1,'');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonUnlockUser' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonUnlockUser','Admin',now(),1);
