
DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonValNProcessIface' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonValNProcessIface','Admin','INTERNAL','INTERNAL','appzillonValNProcessIface','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonValNProcessIface' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonValNProcessIface','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonDeviceRegistration' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonDeviceRegistration','Admin','INTERNAL','INTERNAL','appzillonDeviceRegistration','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonDeviceRegistration' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonDeviceRegistration','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonUserDeviceRegistration' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonUserDeviceRegistration','Admin','INTERNAL','INTERNAL','appzillonUserDeviceRegistration','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonUserDeviceRegistration' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonUserDeviceRegistration','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonValidateOTP' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonValidateOTP','Admin','INTERNAL','INTERNAL','appzillonValidateOTP','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonValidateOTP' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonValidateOTP','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonReGenerateOtp' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonReGenerateOtp','Admin','INTERNAL','INTERNAL','appzillonReGenerateOtp','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonReGenerateOtp' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonReGenerateOtp','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonSendSMS' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonSendSMS','Admin','INTERNAL','INTERNAL','appzillonSendSMS','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonSendSMS' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonSendSMS','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonScheduler' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonScheduler','Admin','INTERNAL','INTERNAL','appzillonScheduler','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonScheduler' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonScheduler','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonSmsLogTxn' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonSmsLogTxn','Admin','INTERNAL','INTERNAL','appzillonSmsLogTxn','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonSmsLogTxn' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonSmsLogTxn','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonUssdLogTxn' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonUssdLogTxn','Admin','INTERNAL','INTERNAL','appzillonUssdLogTxn','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonUssdLogTxn' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonUssdLogTxn','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonTxtMslgLog' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonTxtMslgLog','Admin','INTERNAL','INTERNAL','appzillonTxtMslgLog','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonTxtMslgLog' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonTxtMslgLog','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonSmsUser' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonSmsUser','Admin','INTERNAL','INTERNAL','appzillonSmsUser','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonSmsUser' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonSmsUser','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonGenerateCaptcha' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonGenerateCaptcha','Admin','INTERNAL','INTERNAL','appzillonGenerateCaptcha','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonGenerateCaptcha' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonGenerateCaptcha','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonTrackLocation' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonTrackLocation','Admin','INTERNAL','INTERNAL','appzillonTrackLocation','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonTrackLocation' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonTrackLocation','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonCheckServer' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonCheckServer','Admin','INTERNAL','INTERNAL','appzillonCheckServer','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonCheckServer' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonCheckServer','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'getCnvUIWelcomeMsg' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('getCnvUIWelcomeMsg','Admin','INTERNAL','INTERNAL','getCnvUIWelcomeMsg','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='getCnvUIWelcomeMsg' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','getCnvUIWelcomeMsg','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'getFirstCnvUIDlg' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('getFirstCnvUIDlg','Admin','INTERNAL','INTERNAL','getFirstCnvUIDlg','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='getFirstCnvUIDlg' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','getFirstCnvUIDlg','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'getCnvUIDlg' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('getCnvUIDlg','Admin','INTERNAL','INTERNAL','getCnvUIDlg','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='getCnvUIDlg' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','getCnvUIDlg','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'processNLPData' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('processNLPData','Admin','INTERNAL','INTERNAL','processNLPData','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='processNLPData' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','processNLPData','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonGetIntfDef' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonGetIntfDef','Admin','INTERNAL','INTERNAL','appzillonGetIntfDef','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonGetIntfDef' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonGetIntfDef','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonGetAppMasterDetails' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonGetAppMasterDetails','Admin','INTERNAL','INTERNAL','appzillonGetAppMasterDetails','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonGetAppMasterDetails' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonGetAppMasterDetails','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonGetAppSecTokens' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonGetAppSecTokens','Admin','INTERNAL','INTERNAL','appzillonGetAppSecTokens','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonGetAppSecTokens' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonGetAppSecTokens','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'workflowAcquire' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('workflowAcquire','Admin','INTERNAL','INTERNAL','workflowAcquire','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='workflowAcquire' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','workflowAcquire','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'workflowAssign' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('workflowAssign','Admin','INTERNAL','INTERNAL','workflowAssign','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='workflowAssign' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','workflowAssign','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'workflowUnassign' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('workflowUnassign','Admin','INTERNAL','INTERNAL','workflowUnassign','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='workflowUnassign' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','workflowUnassign','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'workflowQuery' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('workflowQuery','Admin','INTERNAL','INTERNAL','workflowQuery','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='workflowQuery' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','workflowQuery','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'workflowReassign' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('workflowReassign','Admin','INTERNAL','INTERNAL','workflowReassign','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='workflowReassign' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','workflowReassign','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'workflowSave' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('workflowSave','Admin','INTERNAL','INTERNAL','workflowSave','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='workflowSave' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','workflowSave','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'workflowStart' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('workflowStart','Admin','INTERNAL','INTERNAL','workflowStart','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='workflowStart' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','workflowStart','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'workflowTerminate' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('workflowTerminate','Admin','INTERNAL','INTERNAL','workflowTerminate','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='workflowTerminate' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','workflowTerminate','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'workflowNext' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('workflowNext','Admin','INTERNAL','INTERNAL','workflowNext','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='workflowNext' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','workflowNext','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'workflowPrev' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('workflowPrev','Admin','INTERNAL','INTERNAL','workflowPrev','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='workflowPrev' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','workflowPrev','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonGetUserAppAccessToken' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonGetUserAppAccessToken','Admin','INTERNAL','INTERNAL','appzillonGetUserAppAccessToken','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonGetUserAppAccessToken' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonGetUserAppAccessToken','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonReloadLogger' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonReloadLogger','Admin','INTERNAL','INTERNAL','appzillonReloadLogger','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonReloadLogger' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonReloadLogger','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'apzParseMetaJSON' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('apzParseMetaJSON','Admin','INTERNAL','INTERNAL','apzParseMetaJSON','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='apzParseMetaJSON' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','apzParseMetaJSON','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'apzParseProductJSON' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('apzParseProductJSON','Admin','INTERNAL','INTERNAL','apzParseProductJSON','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='apzParseProductJSON' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','apzParseProductJSON','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'apzParseWidgetJSON' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('apzParseWidgetJSON','Admin','INTERNAL','INTERNAL','apzParseWidgetJSON','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='apzParseWidgetJSON' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','apzParseWidgetJSON','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'apzPersistHTMLInfo' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('apzPersistHTMLInfo','Admin','INTERNAL','INTERNAL','apzPersistHTMLInfo','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='apzPersistHTMLInfo' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','apzPersistHTMLInfo','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'appzillonCreateTenant' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('appzillonCreateTenant','Admin','INTERNAL','INTERNAL','appzillonCreateTenant','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='appzillonCreateTenant' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','appzillonCreateTenant','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'reloadServerProperties' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('reloadServerProperties','Admin','INTERNAL','INTERNAL','reloadServerProperties','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='reloadServerProperties' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','reloadServerProperties','Admin',now(),1);

DELETE FROM TB_ASMI_INTF_MASTER WHERE (INTERFACE_ID = 'reloadEnvProperties' AND APP_ID='Admin');
insert into TB_ASMI_INTF_MASTER  (INTERFACE_ID, APP_ID, CATEGORY, TYPE, DESCRIPTION, AUTHRZ_REQ, CREATE_USER_ID,CREATE_TS, MAKER_ID , MAKER_TS , CHECKER_ID , CHECKER_TS , AUTH_STATUS,CAPTCHA_REQ, VERSION_NO,INTERFACE_DEF,TXN_LOG_REQ,TXN_LOG_PAYLOAD_REQ,DG_TXN_LOG_REQ) values('reloadEnvProperties','Admin','INTERNAL','INTERNAL','reloadEnvProperties','N','Admin',now(), 'admin' , now(), 'admin' , now(), 'A','N' ,1,'','N','N','N');
DELETE FROM TB_ASMI_ROLE_INTF WHERE (APP_ID='Admin' AND INTERFACE_ID='reloadEnvProperties' AND ROLE_ID='admin' );
insert  into TB_ASMI_ROLE_INTF(APP_ID, ROLE_ID,INTERFACE_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) values('Admin','admin','reloadEnvProperties','Admin',now(),1);

/*Internal Interface Generation End*/
DELETE FROM TB_ASMI_USER_APP_ACCESS WHERE (APP_ID='Admin' AND USER_ID='admin');
	insert into TB_ASMI_USER_APP_ACCESS (USER_ID, APP_ID, ALLOWED_APP_ID,APP_ACCESS, CREATE_USER_ID, CREATE_TS) VALUES ('admin', 'Admin','Admin', 'A', 'admin', now());

DELETE FROM TB_ASMI_APP_MASTER WHERE (APP_ID='Admin');
INSERT INTO TB_ASMI_APP_MASTER (APP_ID,PARENT_APPID,CONTAINER_APP,OTA_REQ,REMOTE_DEBUG,EXPIRY_DATE,APP_DESCRIPTION,DEFAULT_LANGUAGE,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_TS,MAKER_ID,CHECKER_ID,CHECKER_TS,AUTH_STATUS,APP_NAME,MICRO_APP_TYPE,APP_ICON,APP_VERSION,IDE_VERSION)
 VALUES('Admin','','N','N','N',TO_DATE('18/01/2038','DD/MM/YYYY'),'Appzillon Admin','en','Admin',now(),'1',now(),'admin','admin',now(),'A','AppzillonAdmin','INTERNAL','appicon.png','1.0.0.0','3.12.0.23072021');
DELETE FROM TB_ASMI_USER WHERE (APP_ID='Admin' AND USER_ID='admin');
INSERT INTO TB_ASMI_USER (USER_ID, APP_ID, PIN, USER_NAME,LOGIN_STATUS, FAIL_COUNT, USER_ACTIVE, USER_LOCKED,LANGUAGE,EXTERNALIDENTIFIER,USER_ADDR1, USER_ADDR2, USER_ADDR3, USER_ADDR4, USER_EML1, USER_EML2, USER_PHNO1, USER_PHNO2, USER_LVL, CREATE_USER_ID, CREATE_TS, VERSION_NO,USER_LOCK_TS,PIN_CHANGE_TS,AUTH_STATUS,MAKER_ID) VALUES('admin','Admin','d9fc787aab72f21dd502ab3c1907e9cd826cbe2f7672a8b3fa29919bbac60bfc','admin','Y',1,'Y','N','en',null,'','','','','','','','',1,'Admin',now(),1,now(),now(),'A','admin');

DELETE FROM TB_ASMI_USER_DEVICES WHERE (APP_ID='Admin' AND USER_ID='admin' AND DEVICE_ID='SIMULATOR');
INSERT INTO TB_ASMI_USER_DEVICES(APP_ID,DEVICE_ID, USER_ID,DEVICE_STATUS,CREATE_USER_ID,CREATE_TS,VERSION_NO,AUTH_STATUS) VALUES('Admin','SIMULATOR','admin','ACTIVE','Admin',now(),'1','A');

DELETE FROM TB_ASMI_USER_ROLE WHERE (APP_ID='Admin' AND USER_ID='admin' AND ROLE_ID='admin');
INSERT INTO TB_ASMI_USER_ROLE(USER_ID,ROLE_ID, APP_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) VALUES('admin','admin','Admin','Admin',now(),'1');

DELETE FROM TB_ASMI_USER_DEVICES WHERE (APP_ID='Admin' AND USER_ID='admin' AND DEVICE_ID='WEB');
INSERT INTO TB_ASMI_USER_DEVICES(APP_ID,DEVICE_ID, USER_ID,DEVICE_STATUS,CREATE_USER_ID,CREATE_TS,VERSION_NO,AUTH_STATUS) VALUES('Admin','WEB','admin','ACTIVE','Admin',now(),'1','A');

DELETE FROM TB_ASMI_USER_APP_ACCESS WHERE (APP_ID='Admin' AND USER_ID='adminauth');
	insert into TB_ASMI_USER_APP_ACCESS (USER_ID, APP_ID, ALLOWED_APP_ID,APP_ACCESS, CREATE_USER_ID, CREATE_TS) VALUES ('adminauth', 'Admin','Admin', 'A', 'admin', now());

DELETE FROM TB_ASMI_APP_MASTER WHERE (APP_ID='Admin');
INSERT INTO TB_ASMI_APP_MASTER (APP_ID,PARENT_APPID,CONTAINER_APP,OTA_REQ,REMOTE_DEBUG,EXPIRY_DATE,APP_DESCRIPTION,DEFAULT_LANGUAGE,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_TS,MAKER_ID,CHECKER_ID,CHECKER_TS,AUTH_STATUS,APP_NAME,MICRO_APP_TYPE,APP_ICON,APP_VERSION,IDE_VERSION)
 VALUES('Admin','','N','N','N',TO_DATE('18/01/2038','DD/MM/YYYY'),'Appzillon Admin','en','Admin',now(),'1',now(),'admin','admin',now(),'A','AppzillonAdmin','INTERNAL','appicon.png','1.0.0.0','3.12.0.23072021');
DELETE FROM TB_ASMI_USER WHERE (APP_ID='Admin' AND USER_ID='adminauth');
INSERT INTO TB_ASMI_USER (USER_ID, APP_ID, PIN, USER_NAME,LOGIN_STATUS, FAIL_COUNT, USER_ACTIVE, USER_LOCKED,LANGUAGE,EXTERNALIDENTIFIER,USER_ADDR1, USER_ADDR2, USER_ADDR3, USER_ADDR4, USER_EML1, USER_EML2, USER_PHNO1, USER_PHNO2, USER_LVL, CREATE_USER_ID, CREATE_TS, VERSION_NO,USER_LOCK_TS,PIN_CHANGE_TS,AUTH_STATUS,MAKER_ID) VALUES('adminauth','Admin','19bf2a35a00ac8d8ccf594a0db46383bfec91a476ecdc336ed46dbf045bcfd8b','admin','Y',1,'Y','N','en',null,'','','','','','','','',1,'Admin',now(),1,now(),now(),'A','adminauth');

DELETE FROM TB_ASMI_USER_DEVICES WHERE (APP_ID='Admin' AND USER_ID='adminauth' AND DEVICE_ID='SIMULATOR');
INSERT INTO TB_ASMI_USER_DEVICES(APP_ID,DEVICE_ID, USER_ID,DEVICE_STATUS,CREATE_USER_ID,CREATE_TS,VERSION_NO,AUTH_STATUS) VALUES('Admin','SIMULATOR','adminauth','ACTIVE','Admin',now(),'1','A');

DELETE FROM TB_ASMI_USER_ROLE WHERE (APP_ID='Admin' AND USER_ID='adminauth' AND ROLE_ID='admin');
INSERT INTO TB_ASMI_USER_ROLE(USER_ID,ROLE_ID, APP_ID,CREATE_USER_ID,CREATE_TS,VERSION_NO) VALUES('adminauth','admin','Admin','Admin',now(),'1');

DELETE FROM TB_ASMI_USER_DEVICES WHERE (APP_ID='Admin' AND USER_ID='adminauth' AND DEVICE_ID='WEB');
INSERT INTO TB_ASMI_USER_DEVICES(APP_ID,DEVICE_ID, USER_ID,DEVICE_STATUS,CREATE_USER_ID,CREATE_TS,VERSION_NO,AUTH_STATUS) VALUES('Admin','WEB','adminauth','ACTIVE','Admin',now(),'1','A');

DELETE FROM TB_ASNF_APP_OS_NOTIF_CODE WHERE (APP_ID='Admin' AND OS_ID='WEB' AND NOTIF_CODE='Notification' AND ACTION_CODE='test1');
insert into TB_ASNF_APP_OS_NOTIF_CODE (APP_ID, OS_ID,NOTIF_CODE,ACTION_CODE,ACTION_DISPLAY,CREATE_TS) VALUES ('Admin','WEB', 'Notification','test1','test1',now());

DELETE FROM TB_ASNF_APP_OS_NOTIF_CODE WHERE (APP_ID='Admin' AND OS_ID='WEB' AND NOTIF_CODE='Notification' AND ACTION_CODE='test2');
insert into TB_ASNF_APP_OS_NOTIF_CODE (APP_ID, OS_ID,NOTIF_CODE,ACTION_CODE,ACTION_DISPLAY,CREATE_TS) VALUES ('Admin','WEB', 'Notification','test2','test2',now());

/* Screens */
DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__AdminOperations' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__AdminOperations','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','AdminOperations','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__AppAccess' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__AppAccess','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','AppAccess','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__ChangePassword' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__ChangePassword','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','ChangePassword','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__ChangePasswordBeforeLogin' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__ChangePasswordBeforeLogin','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','ChangePasswordBeforeLogin','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__Customer' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__Customer','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','Customer','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__Dashboard' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__Dashboard','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','Dashboard','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__DeviceGroup' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__DeviceGroup','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','DeviceGroup','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__DlgMasters' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__DlgMasters','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','DlgMasters','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__FileServices' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__FileServices','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','FileServices','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__InactiveUsers' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__InactiveUsers','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','InactiveUsers','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__Interfaces' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__Interfaces','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','Interfaces','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__Jobscheduler' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__Jobscheduler','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','Jobscheduler','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__Landing' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__Landing','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','Landing','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__Login' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__Login','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','Login','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__Notifications' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__Notifications','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','Notifications','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__PushNotifications' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__PushNotifications','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','PushNotifications','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__Role' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__Role','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','Role','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__Screens' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__Screens','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','Screens','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__SecurityParameters' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__SecurityParameters','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','SecurityParameters','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__Statistics' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__Statistics','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','Statistics','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__TaskRepair' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__TaskRepair','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','TaskRepair','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__TransactionDetails' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__TransactionDetails','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','TransactionDetails','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__Usage' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__Usage','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','Usage','','N');

DELETE FROM TB_ASMI_SCR_MASTER WHERE (SCREEN_ID = 'Admin__User' AND APP_ID='Admin');
INSERT INTO TB_ASMI_SCR_MASTER(SCREEN_ID,APP_ID,SCREEN_DESC,CREATE_USER_ID,CREATE_TS,VERSION_NO,MAKER_ID,MAKER_TS,CHECKER_ID,CHECKER_TS,AUTH_STATUS,SCREEN_TYPE,SCREEN_NAME,SCREEN_ICON,CUSTOMISABLE) VALUES('Admin__User','Admin','New Screen','Admin',now(),1,'admin',now(),'admin',now(),'A','MAIN','User','','N');

