
--------------------------------------------------------
--  File created - Wednesday-July-02-2014   
--------------------------------------------------------


   
 --------------------------------------------------------
--  DDL for Table TB_ASMI_APP_DTLS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_APP_DTLS";
  CREATE TABLE "TB_ASMI_APP_DTLS" 
   (	
	"APP_ID" NVARCHAR(100) NOT NULL, 
	"APP_DESC" NVARCHAR(200), 
	"OS_ID" NVARCHAR(50) NOT NULL, 
	"CREATE_BY" NVARCHAR(100), 
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP, 
	"VERSION_NO" NUMERIC DEFAULT 1,
	CONSTRAINT PK_TB_ASMI_APP_DTLS PRIMARY KEY (APP_ID, OS_ID)
   ) ;
 --------------------------------------------------------
--  DDL for Table TB_ASMI_LOV_QUERIES
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_LOV_QUERIES";
  CREATE TABLE "TB_ASMI_LOV_QUERIES" 
   (	
	"APP_ID" NVARCHAR(100) NOT NULL, 
	"QUERY_ID" NVARCHAR(100) NOT NULL, 
	"QUERY_STRING" NVARCHAR(1000), 
	"DB_JNDI_NAME" NVARCHAR(50), 
	"QUERY_TYPE" NVARCHAR(3) DEFAULT 'SQL', 
	"BINDVAR_COLS" NVARCHAR(300), 
	"BINDVAR_DATA_TYPES" NVARCHAR(300), 
	"FILTER_COLS" NVARCHAR(300), 
	"ORDERBY_COL" NVARCHAR(40), 
	"ORDERBY_TYPE" NVARCHAR(5) DEFAULT 'ASC', 
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP, 
	"UPDATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP, 
	"CREATE_BY" NVARCHAR(50),
	"SESSION_REQD" NVARCHAR(1) DEFAULT NULL,
	"VERSION_NO" NUMERIC DEFAULT 1,
	CONSTRAINT PK_TB_ASMI_LOV_QUERIES PRIMARY KEY (APP_ID, QUERY_ID)
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_OS_DTLS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_OS_DTLS";
  CREATE TABLE "TB_ASMI_OS_DTLS" 
   (
	"OS_ID" NVARCHAR(50) NOT NULL, 
	"OS_DESC" NVARCHAR(200), 
	"CREATE_BY" NVARCHAR(100), 
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP, 
	"VERSION_NO" NUMERIC DEFAULT 1,
	CONSTRAINT PK_TB_ASMI_OS_DTLS PRIMARY KEY (OS_ID)
   ) ;

   
--------------------------------------------------------
--  DDL for Table TB_ASTP_SEQ_GEN
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASTP_SEQ_GEN";
  CREATE TABLE "TB_ASTP_SEQ_GEN" 
   (
	"SEQUENCE_NAME" NVARCHAR(50) NOT NULL, 
	"SEQUENCE_VALUE" NUMERIC, 
	"CREATE_BY" NVARCHAR(20), 
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP, 
	"VERSION_NO" NUMERIC,
	CONSTRAINT PK_TB_ASTP_SEQ_GEN PRIMARY KEY (SEQUENCE_NAME)
   ) ;

--------------------------------------------------------
--  DDL for Table TB_ASNF_DEVICES_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASNF_DEVICES_MASTER";
  CREATE TABLE "TB_ASNF_DEVICES_MASTER" 
   (	
	"APP_ID" NVARCHAR(100) NOT NULL , 
	"NOTIF_REG_ID" NVARCHAR(255 ) NOT NULL , 
	"DEVICE_ID" NVARCHAR(255 ), 
	"DEVICE_NAME" NVARCHAR(255 ), 
	"OS_ID" NVARCHAR(50 ), 
	"OS_VERSION" NVARCHAR(255 ), 
	"STATUS"NVARCHAR(20 ), 
	"CREATED_BY" NVARCHAR(255 ), 
	"CREATED_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"VERSION_NO" NUMERIC(10, 0) DEFAULT 1, 
	"MAKER_ID" NVARCHAR(45),
	"MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP, 
	"CHECKER_ID" NVARCHAR(45),
	"CHECKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP, 
	"AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
	"NOTIF_MSG_SERVER" NVARCHAR(255 ) DEFAULT NULL, 
	 CONSTRAINT PK_TB_ASNF_DEVICES_MASTER PRIMARY KEY(APP_ID, NOTIF_REG_ID)
   ) ;

--------------------------------------------------------
--  DDL for Table TB_ASNF_GROUP_DEVICES
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASNF_GROUP_DEVICES";
  CREATE TABLE "TB_ASNF_GROUP_DEVICES"
   (
	"APP_ID" NVARCHAR(100) NOT NULL , 
	"GROUP_ID" NVARCHAR(255) NOT NULL , 
	"NOTIF_REG_ID" NVARCHAR(255) NOT NULL , 
	"CREATED_BY" NVARCHAR(255), 
	"CREATED_TS" DATETIME NULL DEFAULT CURRENT_TIMESTAMP , 
	"VERSION_NO" NUMERIC(10, 0), 
	 CONSTRAINT  PK_TB_ASNF_GROUP_DEVICES PRIMARY KEY (APP_ID, GROUP_ID, NOTIF_REG_ID)
   ) ;

--------------------------------------------------------
--  DDL for Table TB_ASNF_GROUP_MASTER
--------------------------------------------------------

DROP TABLE IF EXISTS "TB_ASNF_GROUP_MASTER";
  CREATE TABLE "TB_ASNF_GROUP_MASTER"
   (	
	"APP_ID" NVARCHAR(100) NOT NULL , 
	"GROUP_ID" NVARCHAR(255) NOT NULL , 
	"GROUP_DESC" NVARCHAR(500), 
	"CREATED_BY" NVARCHAR(50), 
	"CREATED_TS" DATETIME NULL DEFAULT CURRENT_TIMESTAMP , 
	"VERSION_NO" INT DEFAULT 1, 
	 CONSTRAINT  PK_TB_ASNF_GROUP_MASTER PRIMARY KEY (APP_ID, GROUP_ID)
    ) ;

--------------------------------------------------------
--  DDL for Table TB_ASNF_TXN_DEVICES
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASNF_TXN_DEVICES";
  CREATE TABLE "TB_ASNF_TXN_DEVICES"
   (
	"NOTIF_ID" NUMERIC(10, 0) NOT NULL , 
	"APP_ID" NVARCHAR(100) NOT NULL , 
	"NOTIF_REG_ID" NVARCHAR(255 ) NOT NULL , 
	 CONSTRAINT  PK_TB_ASNF_TXN_DEVICES PRIMARY KEY (NOTIF_ID, APP_ID, NOTIF_REG_ID)
    ); 

--------------------------------------------------------
--  DDL for Table TB_ASNF_TXN_GROUPS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASNF_TXN_GROUPS";
  CREATE TABLE "TB_ASNF_TXN_GROUPS"
   (
	"NOTIF_ID" NUMERIC(10, 0), 
	"APP_ID" NVARCHAR(100), 
	"GROUP_ID" NVARCHAR(255),
	 CONSTRAINT  PK_TB_ASNF_TXN_GROUPS PRIMARY KEY (NOTIF_ID, APP_ID, GROUP_ID)
   ) ;

--------------------------------------------------------
--  DDL for Table TB_ASNF_TXN_LOG
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASNF_TXN_LOG";
  CREATE TABLE "TB_ASNF_TXN_LOG"
   (
	"NOTIF_ID" NUMERIC(10, 0), 
	"APP_ID" NVARCHAR(100),
	"USER_ID" NVARCHAR(100),
	"NOTIF_REG_ID" NVARCHAR(255), 
	"DEVICE_ID" NVARCHAR(255), 
	"STATUS" CHAR(150), 
	"CREATED_BY" NVARCHAR(150), 
	"CREATED_TS" DATETIME NULL DEFAULT CURRENT_TIMESTAMP , 
	"VERSION_NO" NUMERIC(10, 0),
	 CONSTRAINT PK_TB_ASNF_TXN_LOG PRIMARY KEY (NOTIF_ID, APP_ID, NOTIF_REG_ID,DEVICE_ID)
   );

--------------------------------------------------------
--  DDL for Table TB_ASNF_TXN_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASNF_TXN_MASTER";
  CREATE TABLE "TB_ASNF_TXN_MASTER" 
   (
	"NOTIF_ID" NUMERIC(10, 0) NOT NULL , 
	"APP_ID" NVARCHAR(100) NOT NULL , 
	"NOTIF_MSG" NVARCHAR(255) NOT NULL ,
	"TITLE" NVARCHAR(255),
	"SUBTITLE" NVARCHAR(255),
	"IMAGE_URL" NVARCHAR(255),
	"CATEGORY" NVARCHAR(255),
	"CREATE_TS" DATETIME NULL DEFAULT CURRENT_TIMESTAMP ,
	 CONSTRAINT PK_TB_ASNF_TXN_MASTER PRIMARY KEY (NOTIF_ID, APP_ID, NOTIF_MSG)
   );
   
  /*  CREATE TABLE "TB_AFTP_WORKFLOW_DET"
  (
   "TRANSACTION_REF_NO" NVARCHAR(30) NOT NULL ,
   "VERSION_NO"         NUMERIC(10, 0) NOT NULL ,
   "WORKFLOW_ID"        NVARCHAR(100) NOT NULL ,
   "CURRENT_STAGE"       NVARCHAR(100) NOT NULL ,
   "SCREEN_ID"          NVARCHAR(100) NOT NULL ,
   "NEXT_STAGE"         NVARCHAR(100) NULL ,
   "STATUS"             NVARCHAR(20) NULL ,
   "APP_ID"             NVARCHAR(100) NOT NULL ,
   "INTERFACE_ID"        NVARCHAR(100) NOT NULL ,
   "USER_ID"             NVARCHAR(100) NULL ,
   "SCREEN_DATA" NTEXT NULL ,
   "STAGE_SEQ_NO"   NVARCHAR(255) NULL ,
   "ACTION"         NVARCHAR(255) NULL ,
   "CREATE_USER_ID" NVARCHAR(100) NULL ,
   "CREATE_TS" DATETIME NULL DEFAULT CURRENT_TIMESTAMP , 
    CONSTRAINT PK_TB_AFTP_WORKFLOW_DET PRIMARY KEY ( TRANSACTION_REF_NO, VERSION_NO, WORKFLOW_ID, CURRENT_STAGE,SCREEN_ID ,APP_ID ,INTERFACE_ID )
  );*/

--IF exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'TB_ASTP_WORKFLOW_DET')
--------------------------------------------------------
--  DDL for Table TB_ASTP_WORKFLOW_DET
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASTP_WORKFLOW_DET";
   CREATE TABLE "TB_ASTP_WORKFLOW_DET"
  (
    "TRANSACTION_REF_NO" NVARCHAR(30) NOT NULL ,
    "VERSION_NO"         NUMERIC(10, 0) NULL ,
   "WORKFLOW_ID"        NVARCHAR(100) NOT NULL ,
   "APP_ID"             NVARCHAR(100) NOT NULL ,
   "CURRENT_STAGE"       NVARCHAR(100) NULL ,
    "SCREEN_ID"          NVARCHAR(100) NULL ,
    "NEXT_STAGE"         NVARCHAR(100) NULL ,
    "STATUS"             NVARCHAR(20) NULL ,
    "INTERFACE_ID"        NVARCHAR(100) NULL ,
   "USER_ID"             NVARCHAR(100) NULL ,
    "SCREEN_DATA" NTEXT NULL ,
    "STAGE_SEQ_NO"   NVARCHAR(255) NULL ,
    "ACTION"         NVARCHAR(255) NULL ,
    "CREATE_USER_ID" NVARCHAR(100) NULL ,
    "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP ,
    CONSTRAINT "TB_ASTP_WORKFLOW_DET_PK" PRIMARY KEY ("TRANSACTION_REF_NO", "WORKFLOW_ID", "APP_ID")
  );
  
--------------------------------------------------------
--  DDL for Table TB_ASFS_FILE_DETAILS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASFS_FILE_DETAILS";
CREATE TABLE "TB_ASFS_FILE_DETAILS" 
( 
  "APP_ID" NVARCHAR(100) NOT NULL,
  "SCREEN_ID" NVARCHAR(100) NULL,
  "USER_ID" NVARCHAR(100)  NULL,
  "FILE_NAME" NVARCHAR(150)  NOT NULL,
  "FILE_TYPE" NVARCHAR(20) NULL,
  "INTERFACE_ID" NVARCHAR(30),
  "CREATE_USER_ID" NVARCHAR(100) NULL,
  "LAST_UPLOADED_DATE" DATETIME NOT NULL DEFAULT getdate(),
  "RECENT_UPLOADED_DATE" DATETIME NOT NULL DEFAULT getdate(),
  CONSTRAINT PK_TB_ADTP_FILE_DETAILS PRIMARY KEY (APP_ID, FILE_NAME) 
);

--------------------------------------------------------
--  DDL for Table TB_ASMI_APP_USER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_APP_USER";
  CREATE TABLE "TB_ASMI_APP_USER"
   (	 
	"USER_ID" NVARCHAR(50) NOT NULL, 
  	"PARENT_APP_ID" NVARCHAR(100) NOT NULL,
	"CHILD_APP_ID" NVARCHAR(100) NOT NULL, 
	"CREATE_USER_ID" NVARCHAR(50), 
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP, 
	"VERSION_NO" NUMERIC(10, 0) DEFAULT 1, 
	 CONSTRAINT "TB_ASMI_APP_USER_PK" PRIMARY KEY ("USER_ID", "PARENT_APP_ID", "CHILD_APP_ID")
    ) ;
    
--------------------------------------------------------
--  DDL for Table TB_ASMI_APP_FILES
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_APP_FILES";
  CREATE TABLE "TB_ASMI_APP_FILES" 
   (	
	"APP_ID" NVARCHAR(100) NOT NULL, 
	"APP_VERSION" NVARCHAR(10) NOT NULL,
    "OS" NVARCHAR(20) NOT NULL,
    "FILE_NAME" NVARCHAR(100) NOT NULL,
	"FILE_PATH" NVARCHAR(255), 
	"ACTION" NVARCHAR(10),
	"CREATE_USER_ID" NVARCHAR(100), 
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP, 
	"VERSION_NO" NUMERIC(10,0) DEFAULT 1,
	CONSTRAINT "TB_ASMI_APP_FILES_PK" PRIMARY KEY ("APP_ID", "APP_VERSION", "OS", "FILE_NAME")
   ) ;
   
--------------------------------------------------------
--  DDL for Table TB_ASMI_APP_OS_VERSION
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_APP_OS_VERSION";
  CREATE TABLE "TB_ASMI_APP_OS_VERSION"
   (	 
    "APP_ID" NVARCHAR(100) NOT NULL, 
  	"OS" NVARCHAR(20) NOT NULL,
    "APP_VERSION" NVARCHAR(10) NOT NULL, 
    "CREATE_USER_ID" NVARCHAR(50), 
    "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP, 
    "VERSION_NO" NUMERIC(10, 0) DEFAULT 1,
    "APP_ACTION" NVARCHAR(10) NOT NULL DEFAULT 'IGNORE',
    CONSTRAINT "TB_ASMI_APP_OS_VERSION_PK" PRIMARY KEY ("APP_ID", "OS", "APP_VERSION")
    ) ;

/*
 * Changes done by Ripu
 * Appzillon - 3.1 - Task Repair Start
 */
/*CREATE TABLE "TB_AFHS_WORKFLOW_DET"
  (
    "TRANSACTION_REF_NO" NVARCHAR(30) NOT NULL ,
    "VERSION_NO"         NUMERIC(10, 0) NOT NULL,
   "WORKFLOW_ID"        NVARCHAR(100) NOT NULL ,
   "CURRENT_STAGE"       NVARCHAR(100) NOT NULL ,
    "SCREEN_ID"          NVARCHAR(100) NOT NULL ,
    "NEXT_STAGE"         NVARCHAR(100) NULL ,
    "STATUS"             NVARCHAR(20) NULL ,
    "APP_ID"             NVARCHAR(100) NOT NULL ,
    "INTERFACE_ID"        NVARCHAR(100) NOT NULL ,
   "USER_ID"             NVARCHAR(100) NULL ,
    "SCREEN_DATA" NTEXT NULL ,
    "STAGE_SEQ_NO"   NVARCHAR(255) NULL ,
    "ACTION"         NVARCHAR(255) NULL ,
    "CREATE_USER_ID" NVARCHAR(100) NULL ,
    "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP ,
    "HISTORY_VERSION_NO" NUMERIC(10, 0) NOT NULL,
    CONSTRAINT "TB_AFHS_WORKFLOW_DET_PK" PRIMARY KEY ("TRANSACTION_REF_NO", "VERSION_NO", "WORKFLOW_ID", "CURRENT_STAGE","SCREEN_ID" ,"APP_ID" ,"INTERFACE_ID","HISTORY_VERSION_NO" )
  );*/
--------------------------------------------------------
--  DDL for Table TB_ASHS_WORKFLOW_DET
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_WORKFLOW_DET";
CREATE TABLE "TB_ASHS_WORKFLOW_DET"
  (
    "TRANSACTION_REF_NO" NVARCHAR(30) NOT NULL ,
    "VERSION_NO"         NUMERIC(10, 0) NOT NULL,
   "WORKFLOW_ID"        NVARCHAR(100) NOT NULL ,
   "APP_ID"             NVARCHAR(100) NOT NULL ,
   "CURRENT_STAGE"       NVARCHAR(100) NULL ,
    "SCREEN_ID"          NVARCHAR(100) NULL ,
    "NEXT_STAGE"         NVARCHAR(100) NULL ,
    "STATUS"             NVARCHAR(20) NULL ,
    "INTERFACE_ID"        NVARCHAR(100) NULL ,
   "USER_ID"             NVARCHAR(100) NULL ,
    "SCREEN_DATA" NTEXT NULL ,
    "STAGE_SEQ_NO"   NVARCHAR(255) NULL ,
    "ACTION"         NVARCHAR(255) NULL ,
    "CREATE_USER_ID" NVARCHAR(100) NULL ,
    "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP ,
    CONSTRAINT "TB_ASHS_WORKFLOW_DET_PK" PRIMARY KEY ("TRANSACTION_REF_NO", "VERSION_NO", "WORKFLOW_ID", "APP_ID")
  );
  /* Appzillon - 3.1 - Task Repair End*/
  
--------------------------------------------------------
--  DDL for Table TB_ASTP_BEACON_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASTP_BEACON_MASTER";
CREATE TABLE "TB_ASTP_BEACON_MASTER" (
  "APP_ID" NVARCHAR(100) DEFAULT NULL,
  "ID" BIGINT NOT NULL,
  "DEVICE_ID" NVARCHAR(225) DEFAULT NULL,
  "USER_ID" NVARCHAR(100) DEFAULT NULL,
  "ENTRY_TIME" DATETIME,
  "STATUS" NVARCHAR(45) DEFAULT NULL,
  PRIMARY KEY ("ID")
);

--------------------------------------------------------
--  DDL for Table TB_ASTP_OTP_ENGINE
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASTP_OTP_ENGINE";
CREATE TABLE "TB_ASTP_OTP_ENGINE" 
   (	
    "REF_NO" BIGINT NOT NULL, 
	"APP_ID" NVARCHAR(100), 
	"USER_ID" NVARCHAR(255), 
	"INTERFACE_ID" NVARCHAR(255), 
	"SESSION_ID" NVARCHAR(255), 
	"OTP" NVARCHAR(255), 
	"OTP_GEN_TS" DATETIME,
	"OTP_EXP_TS" DATETIME, 
	"OTP_STATUS" NVARCHAR(255) DEFAULT 'N', 
	"OTP_VAL_TS" DATETIME,
	"REQ_LD_REFNO" NVARCHAR(100), 
  	"REQ_NO_RECS" NUMERIC, 
	"REQ_PAYLOAD_STATUS" NVARCHAR(200), 
	"REQ_PAYLOAD_PROCESS_TS" DATETIME, 
	"OTP_VALIDATION_COUNT" NUMERIC,
 	"OTP_RESENT_COUNT" NUMERIC ,
 	"OTP_REGEN_COUNT" NUMERIC DEFAULT 0,
 	"OTP_RESEND_LOCK" NVARCHAR(1),
 	"OTP_RESEND_LOCK_TS" DATETIME,
 	"VERSION_NO" NUMERIC NOT NULL DEFAULT 0,
	CONSTRAINT "TB_ASTP_OTP_ENGINE_PK" PRIMARY KEY ("REF_NO")
   );
   
--------------------------------------------------------
--  DDL for Table TB_ASTP_AR_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASTP_AR_MASTER";
CREATE TABLE "TB_ASTP_AR_MASTER" (
"APP_ID" NVARCHAR(255) DEFAULT NULL,
"ID" BIGINT NOT NULL,
"REGION_CODE" NVARCHAR(255) DEFAULT NULL,
"CATEGORY" NVARCHAR(255) DEFAULT NULL,
"LATITUDE" NVARCHAR(255) DEFAULT NULL,
"LONGITUDE" NVARCHAR(255) DEFAULT NULL,
"TITLE"  NVARCHAR(255) DEFAULT NULL,
"ADDITIONAL_INFO" NVARCHAR(255) DEFAULT NULL,
"DESCRIPTION" NVARCHAR(255) DEFAULT NULL,
"IMAGE" NVARCHAR(255),
 PRIMARY KEY ("ID")
);
--------------------------------------------------------
--  DDL for Table TB_ASMI_SCHEDULER_JOB_EXP
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_SCHEDULER_JOB_EXP";
CREATE TABLE "TB_ASMI_SCHEDULER_JOB_EXP" (
  "JOB_NAME" NVARCHAR(45) NOT NULL,
  "START_DATE" NVARCHAR(45) DEFAULT NULL,
  "END_DATE" NVARCHAR(45) DEFAULT NULL,
  "EXP_START_SEC" NVARCHAR(45) DEFAULT NULL,
  "EXP_SEC" NVARCHAR(45) DEFAULT NULL,
  "EXP_MIN" NVARCHAR(45) DEFAULT NULL,
  "EXP_HR" NVARCHAR(45) DEFAULT NULL,
  "EXP_DOM" NVARCHAR(45) DEFAULT NULL,
  "EXP_MONTH" NVARCHAR(45) DEFAULT NULL,
  "EXP_DOW" NVARCHAR(45) DEFAULT NULL,
  "EXP_YEAR" NVARCHAR(45) DEFAULT NULL,
  "EXPRESSION" NVARCHAR(45) DEFAULT NULL,
  PRIMARY KEY ("JOB_NAME")
);

--------------------------------------------------------
--  DDL for Table TB_ASMI_SCHEDULER_JOB
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_SCHEDULER_JOB";
CREATE TABLE "TB_ASMI_SCHEDULER_JOB" (
  "APP_ID" NVARCHAR(45) DEFAULT NULL,
  "JOB_NAME" NVARCHAR(255) NOT NULL,
  "JOB_CLASS" NVARCHAR(255) DEFAULT NULL,
  "JOB_DATA" NVARCHAR(255) DEFAULT NULL,
  "JOB_STATUS" NVARCHAR(45) DEFAULT 'P',
  "JOB_CREATED_TS" DATETIME,
  "JOB_EXECUTED_TS" DATETIME,
  PRIMARY KEY ("JOB_NAME")
);
--------------------------------------------------------
--  DDL for Table TB_OS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_OS";
CREATE TABLE TB_OS (
  "OS_ID" NVARCHAR(15) NOT NULL,
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (OS_ID)
);

--------------------------------------------------------
--  DDL for Table TB_ASMI_APP_ID_VERSION
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_APP_ID_VERSION";
  CREATE TABLE "TB_ASMI_APP_ID_VERSION"
   (	 
    "APP_ID" NVARCHAR(100) NOT NULL,
    "OS" NVARCHAR(20) NOT NULL,
    "APP_ID_VERSION" NVARCHAR(10) NOT NULL,
    "CREATE_USER_ID" NVARCHAR(50), 
    "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP, 
    "VERSION_NO" NUMERIC(10, 0) DEFAULT 1,
    CONSTRAINT "TB_ASMI_APP_ID_VERSION_PK" PRIMARY KEY ("APP_ID","OS","APP_ID_VERSION")
    );

DROP VIEW IF EXISTS VW_NOTIFY_APPID;
GO
CREATE VIEW VW_NOTIFY_APPID as select DISTINCT(APP_ID) appId from TB_ASNF_DEVICES_MASTER;
GO

DROP VIEW IF EXISTS VW_DIGITS;
GO
CREATE  VIEW VW_DIGITS AS
  SELECT 0 AS digit UNION ALL
  SELECT 1 UNION ALL
  SELECT 2 UNION ALL
  SELECT 3 UNION ALL
  SELECT 4 UNION ALL
  SELECT 5 UNION ALL
  SELECT 6 UNION ALL
  SELECT 7 UNION ALL
  SELECT 8 UNION ALL
  SELECT 9;
 GO

DROP VIEW IF EXISTS VW_NUMBERS;
GO
CREATE VIEW VW_NUMBERS AS
SELECT
ones.digit + tens.digit * 10 + hundreds.digit * 100 + thousands.digit * 1000 AS number
FROM
VW_DIGITS as ones,
VW_DIGITS as tens,
VW_DIGITS as hundreds,
VW_DIGITS as thousands;
GO

DROP VIEW IF EXISTS VW_DATES;
GO
CREATE VIEW VW_DATES AS
SELECT
CAST((GETDATE()-number) as Date) AS date
FROM VW_NUMBERS;
GO

DROP VIEW IF EXISTS VW_OS_DATES;
GO
CREATE VIEW VW_OS_DATES as select d.date osdates,OS_ID AS datesos,appId from VW_DATES d,TB_OS o,VW_NOTIFY_APPID ap;
GO

DROP VIEW IF EXISTS VW_MESSAGE_STATS;
GO
CREATE VIEW VW_MESSAGE_STATS AS
select CAST(tnl.CREATED_TS AS DATE) AS TXNDATE,count(0) AS num,tnm.OS_ID AS os,tnl.APP_ID AS appId
from TB_ASNF_TXN_LOG tnl,TB_ASNF_DEVICES_MASTER tnm
where tnl.NOTIF_REG_ID = tnm.NOTIF_REG_ID
group by CAST(tnl.CREATED_TS AS DATE),tnm.OS_ID,tnl.APP_ID;
GO

DROP VIEW IF EXISTS VW_MESSAGE_NOTIFY_STATS;
GO
CREATE VIEW VW_MESSAGE_NOTIFY_STATS AS
SELECT VW_OS_DATES.appId,osdates,COALESCE(num,0) count,datesos 
FROM VW_MESSAGE_STATS RIGHT OUTER JOIN VW_OS_DATES ON osdates=TXNDATE AND datesos=os and 
VW_OS_DATES.appId=VW_MESSAGE_STATS.appId;
GO

INSERT into TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) values('ADMIN_DOMAIN','1','',SYSDATETIME ( ),'1');
INSERT into TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) values('GROUP_NO','1',NULL,SYSDATETIME ( ),'1');
INSERT into TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) values('NOTIFICATION_NO','1',NULL,SYSDATETIME ( ),'1');
INSERT into TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) values('TXNREF','1',NULL,SYSDATETIME ( ),'1');
INSERT into TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) values('WORKFLOW','1',NULL,SYSDATETIME ( ),'1');
INSERT into TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) values('JMS_MSG_ID','1',NULL,SYSDATETIME ( ),'1');
INSERT into TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) values('ACCESS_REF','1',NULL,SYSDATETIME ( ),'1');  
INSERT into TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) values('BEACON_REF','1',NULL,SYSDATETIME ( ),'1');
INSERT into TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) values('ISO8583_F11','1',NULL,SYSDATETIME ( ),'1'); 
INSERT into TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) values ('OTP_REF_NO',1,NULL,SYSDATETIME(),'1');
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) VALUES ('AR_REF',1,NULL,SYSDATETIME(),'1');
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) VALUES ('SMS_TXNREF',1,NULL,SYSDATETIME(),'1');
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) VALUES ('USSD_TXNREF',1,NULL,SYSDATETIME(),'1');
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) VALUES ('TXT_TXNREF',1,NULL,SYSDATETIME(),'1');
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME, SEQUENCE_VALUE, CREATE_BY, CREATE_TS, VERSION_NO) VALUES ('SOURCE_MSG_ID',1,NULL,SYSDATETIME(),'1');
INSERT INTO TB_ASTP_SEQ_GEN (SEQUENCE_NAME,SEQUENCE_VALUE,CREATE_BY,CREATE_TS,VERSION_NO) VALUES ('CAPTCHA_REF_NO',1,NULL,SYSDATETIME(),'1');

INSERT INTO TB_OS (OS_ID,CREATE_TS) VALUES ('ANDROID',SYSDATETIME());
INSERT INTO TB_OS (OS_ID,CREATE_TS) VALUES ('IOS',SYSDATETIME());
INSERT INTO TB_OS (OS_ID,CREATE_TS) VALUES ('WINDOWS',SYSDATETIME());
