--------------------------------------------------------
--  DDL for Table TB_ASMI_SECURITY_PARAMETERS
--------------------------------------------------------
--IF exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'TB_ASMI_SECURITY_PARAMETERS')
DROP TABLE IF EXISTS "TB_ASMI_SECURITY_PARAMETERS";

  CREATE TABLE "TB_ASMI_SECURITY_PARAMETERS"
   (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"MIN_NUM_NUM" NUMERIC(10,0),
	"MIN_NUM_SPCL_CHAR" NUMERIC(10,0),
	"MIN_NUM_LOWER_CASE_CHAR" NUMERIC(10,0),
	"MIN_NUM_UPPER_CASE_CHAR" NUMERIC(10,0),
	"MIN_LENGTH" NUMERIC(10,0),
	"MAX_LENGTH" NUMERIC(10,0),
	"PASS_CHANGE_FREQ" NUMERIC(10,0),
	"LAST_N_PASS_NOT_TO_USE" NUMERIC(10,0),
	"SESSION_TIMEOUT" NUMERIC(10,0),
	"NOOFFAILEDCOUNTS" NUMERIC(10,0),
	"CREATE_USER_ID" NVARCHAR(100),
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"VERSION_NO" NUMERIC(10,0) DEFAULT 1,
	"SERVER_TOKEN" NVARCHAR(255),
	"FAIL_COUNT_TIMEOUT" NUMERIC(10,0),
	"PASSWORD_COUNT" NUMERIC(10,0),
	"DEFAULT_AUTHORIZATION" CHAR(1) DEFAULT 'Y',
	"RESTRICT_SPL_CHARS" NVARCHAR(100),
	"ALLOW_USER_PASSWORD_ENTRY" NVARCHAR(1) DEFAULT 'N',
	 "AUTO_APPROVE" NVARCHAR(1) DEFAULT 'Y',
	  "PWD_RSET_VALIDATE_PARAMS" NVARCHAR(45) DEFAULT 'BOTH',
	  "PWD_RSET_COMM_CHANNEL" NVARCHAR(45) DEFAULT 'BOTH',
	  "PWD_RSET_ACCEPT_USR_PWD" NVARCHAR(1) DEFAULT 'N',
	  "TXN_LOG_REQ" NVARCHAR(45) DEFAULT 'Y',
	  "MAKER_ID" NVARCHAR(45),
	"MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"CHECKER_ID" NVARCHAR(45),
	"CHECKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	 "PWD_COMM_CHANNEL" NVARCHAR(45) DEFAULT 'BOTH',
	"AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
	"MULTIPLE_SESSION_ALLOWED" NVARCHAR(1) DEFAULT 'Y',
	"TXN_LOG_PAYLOAD" NVARCHAR(10) DEFAULT 'NONE',
	"OTP_LENGTH" NUMERIC(10,0),
	"OTP_VALIDATION_COUNT" NUMERIC(10,0),
 	"OTP_EXPIRY"  NUMERIC(10,0),
   	"OTP_RESEND" NVARCHAR(10) DEFAULT NULL,
   	"OTP_FORMAT" NVARCHAR(20) DEFAULT NULL,
   	"OTP_RESEND_COUNT" NUMERIC(10,0),
  	"OTP_RESEND_LOCK_TIMEOUT" NUMERIC(10,0),
  	"OTP_REGEN_COUNT" NUMERIC(10,0) DEFAULT 0,
  	"PWD_CHANGE_COMM_CHANNEL" NVARCHAR(30) DEFAULT 'BOTH',
  	"PASSWORD_ON_AUTHORIZATION" NVARCHAR(1) DEFAULT 'N',
  	"DATA_INTEGRITY" NVARCHAR(1) DEFAULT 'Y',
  	"FMW_TXN_REQ" NVARCHAR(45) DEFAULT 'Y',
	"FMW_TXN_PAYLOAD" NVARCHAR(10) DEFAULT 'NONE',
 	"ACCESS_TOKEN_EXPIRY" NUMERIC(10,0) DEFAULT 0,
	CONSTRAINT PK_TB_ASMI_SECURITY_PARAMETERS PRIMARY KEY (APP_ID)
   ) ;

--------------------------------------------------------
--  DDL for Table TB_ASLG_JMS_REQ_RESP
--------------------------------------------------------
--IF exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'TB_ASLG_JMS_REQ_RESP')
DROP TABLE IF EXISTS "TB_ASLG_JMS_REQ_RESP";

  CREATE TABLE "TB_ASLG_JMS_REQ_RESP"
   (
	"TRANS_ID" BIGINT NOT NULL,
	"INTERFACE_ID" NVARCHAR(150),
	"APP_ID" NVARCHAR(100),
	"REQ_TYPE" NVARCHAR(150),
	"RES_TYPE" NVARCHAR(150),
	"SENT_DATE" DATE,
	"RECEIVED_DATE" DATE,
	"MSG_ID" NVARCHAR(250),
	"REQ_Q" NVARCHAR(250),
	"RESP_Q" NVARCHAR(250),
	"MSG_STATUS" NUMERIC(10,0),
	"MSG_SENT" NTEXT,
	"MSG_RECEIVED" NTEXT,
	"RESP_DESC" NVARCHAR(250),
	CONSTRAINT PK_TB_ASLG_JMS_REQ_RESP PRIMARY KEY (TRANS_ID)
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASHS_USER_PASSWORDS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_USER_PASSWORDS";
  CREATE TABLE "TB_ASHS_USER_PASSWORDS"
   (
	"USER_ID" NVARCHAR(100) NOT NULL,
	"APP_ID" NVARCHAR(100) NOT NULL,
	"PIN" NVARCHAR(255) NOT NULL,
	"CHANGE_TIME" DATETIME,
	"CREATE_USER_ID" NVARCHAR(100),
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"VERSION_NO" NUMERIC(10,0) DEFAULT 1,
	CONSTRAINT PK_ASHS_USER_PASSWORDS PRIMARY KEY (USER_ID, APP_ID, PIN)
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASLG_TXN_DETAIL
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASLG_TXN_DETAIL";

 CREATE TABLE "TB_ASLG_TXN_DETAIL"
   (
	"TXN_REF" NVARCHAR(255) NOT NULL,
	"USER_ID" NVARCHAR(100),
	"USER_APP_ID" NVARCHAR(100),
  	"APP_USER_ID" NVARCHAR(100),
	"SESSION_ID" NVARCHAR(255),
	"DEVICE_ID" NVARCHAR(255),
	"ST_TM" DATETIME,
	"END_TM" DATETIME,
	"INTERFACE_ID" NVARCHAR(50),
	"APP_ID" NVARCHAR(100),
	"TXN_STAT" NVARCHAR(20),
    "REQ_LD_REFNO" NVARCHAR(100), 
  	"REQ_NO_RECS" int, 
  	"RES_LD_REFNO" NVARCHAR(100), 
  	"RES_NO_RECS" int, 
  	"INFO1" NVARCHAR(255) DEFAULT NULL,
  	"INFO2" NVARCHAR(255) DEFAULT NULL,
  	"INFO3" NVARCHAR(255) DEFAULT NULL,
  	"INFO4" NVARCHAR(255) DEFAULT NULL,
  	"INFO5" NVARCHAR(255) DEFAULT NULL,
    "CREATE_BY" NVARCHAR(200),
     "SOURCE" NVARCHAR(255),
     "LONGITUDE" NVARCHAR(255),
     "LATITUDE" NVARCHAR(255),
     "ORIGINATION" NVARCHAR(255),
     "STATUS" NVARCHAR(255),
    "SUBLOCALITY" NVARCHAR(255),
    "ADMIN_AREA_LVL_1" NVARCHAR(255),
    "ADMIN_AREA_LVL_2" NVARCHAR(255),
    "COUNTRY" NVARCHAR(255),
    "FORMATTED_ADDRESS" NVARCHAR(255),
    "EXT_ST_TM" DATETIME DEFAULT NULL,
	"EXT_END_TM" DATETIME DEFAULT NULL,
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_TB_ASLG_TXN_DETAIL PRIMARY KEY (TXN_REF)
   ) ;

--------------------------------------------------------
--  DDL for Table TB_ASTP_LD_RECS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASTP_LD_RECS";
 
 CREATE TABLE "TB_ASTP_LD_RECS" (
  "REF_NO" NVARCHAR(100),
  "SEQ_NO" int,
  "DATA1" NVARCHAR(MAX),
  "DATA2" NVARCHAR(MAX),
  "DATA3" NVARCHAR(MAX),
  "DATA4" NVARCHAR(MAX),
  "DATA5" NVARCHAR(MAX),
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT PK_TB_ASTP_LD_RECS PRIMARY KEY (REF_NO,SEQ_NO)
);


--------------------------------------------------------
--  DDL for Table TB_ASLG_FMW_TXN_DETAIL
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASLG_FMW_TXN_DETAIL";

 CREATE TABLE "TB_ASLG_FMW_TXN_DETAIL"
   (
	"TXN_REF" NVARCHAR(255) NOT NULL,
	"MASTER_TXN_REF" NVARCHAR(255),
	"INTERFACE_ID" NVARCHAR(50), 
	"REQ_LD_REFNO" NVARCHAR(100), 
  	"REQ_NO_RECS" int, 
  	"RES_LD_REFNO" NVARCHAR(100), 
  	"RES_NO_RECS" int, 
    "ENDPOINT_TYPE" NVARCHAR(255),
	"ST_TM" DATETIME,
	"END_TM" DATETIME,
    "STATUS" NVARCHAR(1),
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_TB_ASLG_FMW_TXN_DETAIL PRIMARY KEY (TXN_REF)
   ) ;

--------------------------------------------------------
--  DDL for Table TB_ASMI_INTF_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_INTF_MASTER";

  CREATE TABLE "TB_ASMI_INTF_MASTER"
   (
	"INTERFACE_ID" NVARCHAR(100) NOT NULL,
	"APP_ID" NVARCHAR(100) NOT NULL,
	"CATEGORY" NVARCHAR(30),
	"TYPE" NVARCHAR(30),
	"DESCRIPTION" NVARCHAR(100),
	"AUTHRZ_REQ" NVARCHAR(1) DEFAULT 'Y',
	"CREATE_USER_ID" NVARCHAR(100),
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"VERSION_NO" NUMERIC(10,0) DEFAULT 1,
	"MAKER_ID" NVARCHAR(45),
	"MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"CHECKER_ID" NVARCHAR(45),
	"CHECKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
        "CAPTCHA_REQ" NVARCHAR(5) DEFAULT 'TEXT',
        "CAPTCHA_TYPE" NVARCHAR(7) DEFAULT 'N',
        "INTERFACE_DEF" NTEXT NULL,
        "DG_TXN_LOG_REQ" NVARCHAR(1) DEFAULT 'Y',
    	"TXN_LOG_REQ" NVARCHAR(1) DEFAULT 'Y',
    	"TXN_LOG_PAYLOAD_REQ" NVARCHAR(10) DEFAULT 'NONE',
    	"FMW_TXN_REQ" NVARCHAR(1) DEFAULT 'Y',
    	"FMW_TXN_PAYLOAD_REQ" NVARCHAR(10) DEFAULT 'NONE',
	CONSTRAINT PK_TB_ASMI_INTF_MASTER PRIMARY KEY (INTERFACE_ID, APP_ID)
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_ROLE_INTF
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_ROLE_INTF";

  CREATE TABLE "TB_ASMI_ROLE_INTF"
   (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"ROLE_ID" NVARCHAR(100) NOT NULL,
	"INTERFACE_ID" NVARCHAR(100) NOT NULL,
	"CREATE_USER_ID" NVARCHAR(100),
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"VERSION_NO" NUMERIC(10,0) DEFAULT 1,
	CONSTRAINT PK_TB_ASMI_ROLE_INTF PRIMARY KEY (APP_ID, ROLE_ID, INTERFACE_ID)
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_ROLE_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_ROLE_MASTER";

  CREATE TABLE "TB_ASMI_ROLE_MASTER"
   (
	"ROLE_ID" NVARCHAR(255) NOT NULL,
	"APP_ID" NVARCHAR(100) NOT NULL,
	"ROLE_DESC" NVARCHAR(255),
	"INTERFACE_ALLOWED" NVARCHAR(1) DEFAULT 'A',
  "SCREEN_ALLOWED" NVARCHAR(1) DEFAULT 'A',
  "CONTROL_ALLOWED" NVARCHAR(1) DEFAULT 'A',
	"CREATE_USER_ID" NVARCHAR(100),
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"VERSION_NO" NUMERIC(10,0) DEFAULT 1,
	"MAKER_ID" NVARCHAR(45),
	"MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"CHECKER_ID" NVARCHAR(45),
	"CHECKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
	CONSTRAINT PK_TB_ASMI_ROLE_MASTER PRIMARY KEY (ROLE_ID, APP_ID)
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_ROLE_SCR
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_ROLE_SCR";

  CREATE TABLE "TB_ASMI_ROLE_SCR"
   (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"SCREEN_ID" NVARCHAR(100) NOT NULL,
	"ROLE_ID" NVARCHAR(100) NOT NULL,
	"CREATE_USER_ID" NVARCHAR(100),
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"VERSION_NO" NUMERIC(10,0) DEFAULT 1,
	CONSTRAINT PK_TB_ASMI_ROLE_SCR PRIMARY KEY (ROLE_ID, APP_ID, SCREEN_ID)
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_SCR_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_SCR_MASTER"; 
  CREATE TABLE "TB_ASMI_SCR_MASTER"
   (
	"SCREEN_ID" NVARCHAR(255) NOT NULL,
	"APP_ID" NVARCHAR(100) NOT NULL,
	"SCREEN_DESC" NVARCHAR(255),
	"CREATE_USER_ID" NVARCHAR(100),
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"VERSION_NO" NUMERIC(10,0) DEFAULT 1,
	"MAKER_ID" NVARCHAR(45),
	"MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"CHECKER_ID" NVARCHAR(45),
	"CHECKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
	"SCREEN_TYPE" NVARCHAR(10) DEFAULT NULL,
    "SCREEN_NAME" NVARCHAR(100) DEFAULT NULL,
    "SCREEN_ICON" NVARCHAR(MAX),
    "CUSTOMISABLE" NVARCHAR(1) DEFAULT NULL,
	CONSTRAINT PK_TB_ASMI_SCR_MASTER PRIMARY KEY (SCREEN_ID, APP_ID)
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_USER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_USER"; 
  CREATE TABLE "TB_ASMI_USER"
   (
	"USER_ID" NVARCHAR(100) NOT NULL,
	"APP_ID" NVARCHAR(100) NOT NULL,
	"PIN" NVARCHAR(300),
	"USER_NAME" NVARCHAR(100),
	"LAST_NAME" NVARCHAR(100),
	"LOGIN_STATUS" NVARCHAR(3),
	"FAIL_COUNT" NUMERIC(10,0),
	"USER_ACTIVE" NVARCHAR(3) DEFAULT 'Y',
	"USER_LOCKED" NVARCHAR(3) DEFAULT 'N',
	"LANGUAGE" NVARCHAR(2) DEFAULT 'en',
	"EXTERNALIDENTIFIER" NVARCHAR(30),
	"USER_ADDR1" NVARCHAR(50),
	"USER_ADDR2" NVARCHAR(50),
	"USER_ADDR3" NVARCHAR(50),
	"USER_ADDR4" NVARCHAR(50),
	"USER_EML1" NVARCHAR(255),
	"USER_EML2" NVARCHAR(255),
	"USER_PHNO1" NVARCHAR(20),
	"USER_PHNO2" NVARCHAR(20),
	"USER_LVL" NUMERIC(11,0),
	"USER_LOCK_TS" DATETIME,
	"PIN_CHANGE_TS" DATETIME,
	"PROFILE_PIC" NVARCHAR(MAX),
	"CREATE_USER_ID" NVARCHAR(100),
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"VERSION_NO" NUMERIC(10,0) DEFAULT 1,
	"MAKER_ID" NVARCHAR(45),
	"MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"CHECKER_ID" NVARCHAR(45),
	"CHECKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"DATE_OF_BIRTH" DATE,
	"AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
	"ADD_INFO1" NVARCHAR(255),
	"ADD_INFO2" NVARCHAR(255),
	"ADD_INFO3" NVARCHAR(255),
	"ADD_INFO4" NVARCHAR(255),
	"ADD_INFO5" NVARCHAR(255),
	CONSTRAINT PK_TB_ASMI_USER PRIMARY KEY (USER_ID, APP_ID)
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_USER_DEVICES
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_USER_DEVICES";

  CREATE TABLE "TB_ASMI_USER_DEVICES"
   (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"DEVICE_ID" NVARCHAR(255) NOT NULL,
	"USER_ID" NVARCHAR(100) NOT NULL,
	"NOTIF_REG_ID" NVARCHAR(255) DEFAULT NULL,
	"DEVICE_STATUS" NVARCHAR(100),
	"CREATE_USER_ID" NVARCHAR(100),
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"MAKER_ID" NVARCHAR(45),
	"MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"CHECKER_ID" NVARCHAR(45),
	"CHECKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
	"VERSION_NO" NUMERIC(10,0) DEFAULT 1,
	CONSTRAINT PK_TB_ASMI_USER_DEVICES PRIMARY KEY (APP_ID, DEVICE_ID, USER_ID)
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_USER_ROLE
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_USER_ROLE";
  CREATE TABLE "TB_ASMI_USER_ROLE"
   (
	"USER_ID" NVARCHAR(100) NOT NULL,
	"ROLE_ID" NVARCHAR(100) NOT NULL,
	"APP_ID" NVARCHAR(100),
	"CREATE_USER_ID" NVARCHAR(100),
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"VERSION_NO" NUMERIC(10,0) DEFAULT 1,
	CONSTRAINT PK_TB_ASMI_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID, APP_ID)
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASTP_LAST_LOGIN
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASTP_LAST_LOGIN";
  CREATE TABLE "TB_ASTP_LAST_LOGIN"
   (
	"USER_ID" NVARCHAR(100) NOT NULL,
	"APP_ID" NVARCHAR(100) NOT NULL,
	"DEVICE_ID" NVARCHAR(255) NOT NULL,
	"REQUEST_KEY" NVARCHAR(255),
	"SESSION_ID" NVARCHAR(255),
	"LAST_REQ_TIME" DATETIME,
	"LOGIN_TIME" DATETIME,
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"VERSION_NO" NUMERIC(10,0) DEFAULT 1,
	"OTP" NVARCHAR(200),
	"OTP_GENERATION_TIME" DATETIME default CURRENT_TIMESTAMP,
	"OTP_STATUS" NVARCHAR(1),
        "OTP_VALIDATION_COUNT" NUMERIC(10,0) DEFAULT 0,
	"LONGITUDE" NVARCHAR(255),
    "LATITUDE" NVARCHAR(255),
     "SUBLOCALITY" NVARCHAR(255),
    "ADMIN_AREA_LVL_1" NVARCHAR(255),
    "ADMIN_AREA_LVL_2" NVARCHAR(255),
    "COUNTRY" NVARCHAR(255),
    "FORMATTED_ADDRESS" NVARCHAR(255),
    "ORIGINATION" NVARCHAR(255),
	CONSTRAINT PK_TB_ASTP_LAST_LOGIN PRIMARY KEY (USER_ID, APP_ID, DEVICE_ID)
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_DEVICE_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_DEVICE_MASTER";
CREATE TABLE "TB_ASMI_DEVICE_MASTER"(
	"APP_ID" NVARCHAR(100) NOT NULL,
	"DEVICE_ID" NVARCHAR(200) NOT NULL,
	"OS" NVARCHAR(20) NULL,
	"OS_VERSION" NVARCHAR(50) NULL,
	"MOBILE_NUMBER1" NVARCHAR(20) NULL,
	"MOBILE_NUMBER2" NVARCHAR(20) NULL,
	"MODEL" NVARCHAR(100) NULL,
	"MAKE" NVARCHAR(100) NULL,
	"SCREEN_RESOLUTION" NVARCHAR(100) NULL,
	"WIPED_OUT" NVARCHAR(1) DEFAULT 'N',
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"DEVICE_NAME" NVARCHAR(100) NULL,
	"LONGITUDE" NVARCHAR(100) NULL,
	"LATITUDE" NVARCHAR(100) NULL,
	"APP_VERSION" NVARCHAR(50) NULL,
	CONSTRAINT "TB_ASMI_DEVICE_MASTER_PK" PRIMARY KEY ("APP_ID", "DEVICE_ID")
);
--------------------------------------------------------
--  DDL for Table TB_ASLG_AUDIT_LOG
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASLG_AUDIT_LOG";
  CREATE TABLE "TB_ASLG_AUDIT_LOG"
  (
    "ACCESS_REF"     BIGINT NOT NULL,
    "APP_ID"         NVARCHAR(100)  NULL,
    "USER_ID"        NVARCHAR(100) NULL,
    "DEVICE_ID"      NVARCHAR(250)  NULL,
    "SESSION_ID"     NVARCHAR(100) NULL,
    "ACTION"         NVARCHAR(30) NULL,
    "START_TIME_STAMP" NVARCHAR(30) NULL,
    "END_TIME_STAMP" NVARCHAR(30) NULL,
    "FIELD1"         NVARCHAR(100) NULL,
    "FIELD2"         NVARCHAR(100) NULL,
    "FIELD3"         NVARCHAR(100) NULL,
    "FIELD4"         NVARCHAR(100) NULL,
    "FIELD5"         NVARCHAR(100) NULL,
    "CREATE_DATE" DATE DEFAULT GETDATE(),
    "CREATE_USER_ID" NVARCHAR(100) NULL,
    "VERSION_NO" NUMERIC(10, 0) DEFAULT 1,
    CONSTRAINT "PK_TB_ASLG_AUDIT_LOG" PRIMARY KEY ( "ACCESS_REF"  )
  );
--------------------------------------------------------
--  DDL for Table TB_ASMI_SMS_USER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_SMS_USER";
 CREATE TABLE "TB_ASMI_SMS_USER"(
  "APP_ID" NVARCHAR(100) NOT NULL,
  "USER_ID" NVARCHAR(100) NOT NULL,
  "MOBILE_NUMBER" NVARCHAR(20),
  "CREATED_BY" NVARCHAR(50),
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"VERSION_NO" NUMERIC(10, 0) DEFAULT 0,
	"SMS_REQ" NVARCHAR(1),
	"USSD_REQ" NVARCHAR(1),
  CONSTRAINT "TB_ASMI_SMS_USER_PK" PRIMARY KEY("APP_ID", "USER_ID")
);
 --------------------------------------------------------
--  DDL for Table TB_ASLG_SMS_TXN
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASLG_SMS_TXN";
 CREATE TABLE "TB_ASLG_SMS_TXN"
   (
                "SMS_TXNREF" NVARCHAR(255) NOT NULL,
                "APP_ID" NVARCHAR(100),
                "MOBILE_NUMBER" NVARCHAR(20),
                "REQUEST" NVARCHAR(4000),
                "MESSAGE_ID" NVARCHAR(20),
                "ORIGINATION" NVARCHAR(20),
                "START_TM" DATETIME,
				"RESPONSE" NVARCHAR(4000),
				"END_TM" DATETIME,
                "CREATED_BY" NVARCHAR(20),
                "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY ("SMS_TXNREF")
   ) ;
 --------------------------------------------------------
--  DDL for Table TB_ASLG_USSD_TXN
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASLG_USSD_TXN";
   CREATE TABLE "TB_ASLG_USSD_TXN"
   (
                "USSD_TXNREF" NVARCHAR(255) NOT NULL,
                "APP_ID" NVARCHAR(100),
                "MOBILE_NUMBER" NVARCHAR(20),
                "REQUEST" NVARCHAR(200),
				"ACTION" NVARCHAR(3000),
				"STEP" NVARCHAR(100),
                "ORIGINATION" NVARCHAR(20),
                "START_TM" DATETIME,
				"RESPONSE" NVARCHAR(200),
				"END_TM" DATETIME,
                "CREATED_BY" NVARCHAR(20),
                "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY ("USSD_TXNREF")
   ) ;
 --------------------------------------------------------
--  DDL for Table TB_ASLG_TXT_MSLG_LOG
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASLG_TXT_MSLG_LOG";
   CREATE TABLE "TB_ASLG_TXT_MSLG_LOG"
   (
                "TXT_TXNREF" NVARCHAR(255) NOT NULL,
                "APP_ID" NVARCHAR(100),
                "MOBILE_NUMBER" NVARCHAR(20),
                "REQUEST" NVARCHAR(1000),
                "PORT" NVARCHAR(10),
                "ORIGINATION" NVARCHAR(20),
                "START_TM" DATETIME,
                "RESPONSE" NVARCHAR(200),
                "END_TM" DATETIME,
                "CREATED_BY" NVARCHAR(20),
                "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY ("TXT_TXNREF")
   ) ;
 --------------------------------------------------------
--  DDL for Table TB_ASMI_CONTROLS_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_CONTROLS_MASTER";
CREATE TABLE "TB_ASMI_CONTROLS_MASTER" (
   "APP_ID" NVARCHAR(100) NOT NULL,
   "CONTROL_ID" NVARCHAR(255) NOT NULL,
   "CONTROL_DESC" NVARCHAR(255) DEFAULT NULL,
   "CREATED_BY" NVARCHAR(100) DEFAULT NULL,
   "CREATED_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
   "MAKER_ID" NVARCHAR(45),
   "MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
   "CHECKER_ID" NVARCHAR(45),
   "CHECKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
   "AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
   "VERSION_NO" NUMERIC(10, 0) DEFAULT 1,
   PRIMARY KEY ("APP_ID","CONTROL_ID")
  ) ;
 --------------------------------------------------------
--  DDL for Table TB_ASMI_ROLE_CONTROLS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_ROLE_CONTROLS";
CREATE TABLE "TB_ASMI_ROLE_CONTROLS" (
   "APP_ID" NVARCHAR(100) NOT NULL,
   "ROLE_ID" NVARCHAR(100) NOT NULL,
   "CONTROL_ID" NVARCHAR(100) NOT NULL,
   "CREATED_BY" NVARCHAR(100) DEFAULT NULL,
   "CREATED_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
   "VERSION_NO" NUMERIC(10, 0) DEFAULT 1,
   PRIMARY KEY ("APP_ID","ROLE_ID","CONTROL_ID")
) ;
--------------------------------------------------------
--  DDL for Table TB_ASHS_SECURITY_PARAMETERS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_SECURITY_PARAMETERS";
  CREATE TABLE "TB_ASHS_SECURITY_PARAMETERS"
   (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "MIN_NUM_NUM" NUMERIC(10,0),
  "MIN_NUM_SPCL_CHAR" NUMERIC(10,0),
  "MIN_NUM_UPPER_CASE_CHAR" NUMERIC(10,0),
  "MIN_NUM_LOWER_CASE_CHAR" NUMERIC(10,0),
  "MIN_LENGTH" NUMERIC(10,0),
  "MAX_LENGTH" NUMERIC(10,0),
  "PASS_CHANGE_FREQ" NUMERIC(10,0),
  "LAST_N_PASS_NOT_TO_USE" NUMERIC(10,0),
  "SESSION_TIMEOUT" NUMERIC(10,0),
  "NOOFFAILEDCOUNTS" NUMERIC(10,0),
  "CREATE_USER_ID" NVARCHAR(100),
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "VERSION_NO" NUMERIC(10,0) DEFAULT 1,
  "SERVER_TOKEN" NVARCHAR(255),
  "FAIL_COUNT_TIMEOUT" NUMERIC(10,0),
  "PASSWORD_COUNT" NUMERIC(10,0),
  "DEFAULT_AUTHORIZATION" CHAR(1) DEFAULT 'Y',
  "RESTRICT_SPL_CHARS" NVARCHAR(100),
  "ALLOW_USER_PASSWORD_ENTRY" NVARCHAR(1) DEFAULT 'N',
   "AUTO_APPROVE" NVARCHAR(1) DEFAULT 'Y',
    "PWD_RSET_VALIDATE_PARAMS" NVARCHAR(45) DEFAULT 'BOTH',
    "PWD_RSET_COMM_CHANNEL" NVARCHAR(45) DEFAULT 'BOTH',
    "PWD_RSET_ACCEPT_USR_PWD" NVARCHAR(1) DEFAULT 'N',
    "TXN_LOG_REQ" NVARCHAR(45) DEFAULT 'Y',
    "MAKER_ID" NVARCHAR(45),
  "MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "CHECKER_ID" NVARCHAR(45),
  "CHECKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
   "PWD_COMM_CHANNEL" NVARCHAR(45) DEFAULT 'BOTH',
  "AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
  "MULTIPLE_SESSION_ALLOWED" NVARCHAR(1) DEFAULT 'Y',
  "TXN_LOG_PAYLOAD" NVARCHAR(1) DEFAULT 'Y',
  "OTP_LENGTH" NUMERIC(10,0),
	"OTP_VALIDATION_COUNT" NUMERIC(10,0),
 	"OTP_EXPIRY"  NUMERIC(10,0),
   	"OTP_RESEND" NVARCHAR(10) DEFAULT NULL,
   	"OTP_FORMAT" NVARCHAR(20) DEFAULT NULL,
   	"OTP_RESEND_COUNT" NUMERIC(10,0),
  	"OTP_RESEND_LOCK_TIMEOUT" NUMERIC(10,0),
  	"PWD_CHANGE_COMM_CHANNEL" NVARCHAR(30) DEFAULT 'BOTH',
  	"PASSWORD_ON_AUTHORIZATION" NVARCHAR(1) DEFAULT 'N',
  	"DATA_INTEGRITY" NVARCHAR(1) DEFAULT 'Y',
  	"FMW_TXN_REQ" NVARCHAR(1) DEFAULT 'Y',
 	"ACCESS_TOKEN_EXPIRY" NUMERIC(10,0),
  CONSTRAINT PK_TB_ASHS_SECURITY_PARAMETERS PRIMARY KEY (APP_ID,"VERSION_NO")
   ) ;
   --------------------------------------------------------
--  DDL for Table TB_ASHS_ROLE_INTF
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_ROLE_INTF";
  CREATE TABLE "TB_ASHS_ROLE_INTF"
   (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "ROLE_ID" NVARCHAR(100) NOT NULL,
  "INTERFACE_ID" NVARCHAR(100) NOT NULL,
  "CREATE_USER_ID" NVARCHAR(100),
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "VERSION_NO" NUMERIC(10,0) DEFAULT 1,
  CONSTRAINT PK_TB_ASHS_ROLE_INTF PRIMARY KEY (APP_ID, ROLE_ID, INTERFACE_ID,"VERSION_NO")
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASHS_ROLE_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_ROLE_MASTER";
  CREATE TABLE "TB_ASHS_ROLE_MASTER"
   (
  "ROLE_ID" NVARCHAR(255) NOT NULL,
  "APP_ID" NVARCHAR(100) NOT NULL,
  "ROLE_DESC" NVARCHAR(255),
  "INTERFACE_ALLOWED" NVARCHAR(1) DEFAULT 'A',
  "SCREEN_ALLOWED" NVARCHAR(1) DEFAULT 'A',
  "CONTROL_ALLOWED" NVARCHAR(1) DEFAULT 'A',
  "CREATE_USER_ID" NVARCHAR(100),
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "VERSION_NO" NUMERIC(10,0) DEFAULT 1,
  "MAKER_ID" NVARCHAR(45),
  "MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "CHECKER_ID" NVARCHAR(45),
  "CHECKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
  CONSTRAINT PK_TB_ASHS_ROLE_MASTER PRIMARY KEY (ROLE_ID, APP_ID,"VERSION_NO")
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASHS_ROLE_SCR
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_ROLE_SCR";
  CREATE TABLE "TB_ASHS_ROLE_SCR"
   (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "SCREEN_ID" NVARCHAR(100) NOT NULL,
  "ROLE_ID" NVARCHAR(100) NOT NULL,
  "CREATE_USER_ID" NVARCHAR(100),
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "VERSION_NO" NUMERIC(10,0) DEFAULT 1,
  CONSTRAINT PK_TB_ASHS_ROLE_SCR PRIMARY KEY (ROLE_ID, APP_ID, SCREEN_ID,"VERSION_NO")
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASHS_USER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_USER";   
  CREATE TABLE "TB_ASHS_USER"
   (
  "USER_ID" NVARCHAR(100) NOT NULL,
  "APP_ID" NVARCHAR(100) NOT NULL,
  "PIN" NVARCHAR(300),
  "USER_NAME" NVARCHAR(100),
  "LAST_NAME" NVARCHAR(100),
  "LOGIN_STATUS" NVARCHAR(3),
  "FAIL_COUNT" NUMERIC(10,0),
  "USER_ACTIVE" NVARCHAR(3) DEFAULT 'Y',
  "USER_LOCKED" NVARCHAR(3) DEFAULT 'N',
  "LANGUAGE" NVARCHAR(2) DEFAULT 'en',
  "EXTERNALIDENTIFIER" NVARCHAR(30),
  "USER_ADDR1" NVARCHAR(50),
  "USER_ADDR2" NVARCHAR(50),
  "USER_ADDR3" NVARCHAR(50),
  "USER_ADDR4" NVARCHAR(50),
  "USER_EML1" NVARCHAR(255),
  "USER_EML2" NVARCHAR(255),
  "USER_PHNO1" NVARCHAR(20),
  "USER_PHNO2" NVARCHAR(20),
  "USER_LVL" NUMERIC(11,0),
  "USER_LOCK_TS" DATETIME,
  "PIN_CHANGE_TS" DATETIME,
  "PROFILE_PIC" NVARCHAR(MAX),
  "CREATE_USER_ID" NVARCHAR(100),
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "VERSION_NO" NUMERIC(10,0) DEFAULT 1,
  "MAKER_ID" NVARCHAR(45),
  "MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "CHECKER_ID" NVARCHAR(45),
  "CHECKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "DATE_OF_BIRTH" DATE,
  "AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
  "ADD_INFO1" NVARCHAR(255),
  "ADD_INFO2" NVARCHAR(255),
  "ADD_INFO3" NVARCHAR(255),
  "ADD_INFO4" NVARCHAR(255),
  "ADD_INFO5" NVARCHAR(255),
  CONSTRAINT PK_TB_ASHS_USER PRIMARY KEY (USER_ID, APP_ID,"VERSION_NO")
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASHS_USER_DEVICES
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_USER_DEVICES";
  CREATE TABLE "TB_ASHS_USER_DEVICES"
   (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "DEVICE_ID" NVARCHAR(255) NOT NULL,
  "USER_ID" NVARCHAR(100) NOT NULL,
  "DEVICE_STATUS" NVARCHAR(100),
  "CREATE_USER_ID" NVARCHAR(100),
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "MAKER_ID" NVARCHAR(45),
  "MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "CHECKER_ID" NVARCHAR(45),
  "CHECKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
  "VERSION_NO" NUMERIC(10,0) DEFAULT 1,
  CONSTRAINT PK_TB_ASHS_USER_DEVICES PRIMARY KEY (APP_ID, DEVICE_ID, USER_ID,"VERSION_NO")
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASHS_USER_ROLE
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_USER_ROLE";
  CREATE TABLE "TB_ASHS_USER_ROLE"
   (
  "USER_ID" NVARCHAR(100) NOT NULL,
  "ROLE_ID" NVARCHAR(100) NOT NULL,
  "APP_ID" NVARCHAR(100),
  "CREATE_USER_ID" NVARCHAR(100),
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "VERSION_NO" NUMERIC(10,0) DEFAULT 1,
  CONSTRAINT PK_TB_ASHS_USER_ROLE PRIMARY KEY (USER_ID, ROLE_ID, APP_ID,"VERSION_NO")
   ) ;
--------------------------------------------------------
--  DDL for Table TB_ASHS_SMS_USER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_SMS_USER";
 CREATE TABLE "TB_ASHS_SMS_USER"(
  "APP_ID" NVARCHAR(100) NOT NULL,
  "MOBILE_NUMBER" NVARCHAR(20),
  "USER_ID" NVARCHAR(100) NOT NULL,
  "CREATED_BY" NVARCHAR(50),
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "VERSION_NO" NUMERIC(10, 0) DEFAULT 0,
  "SMS_REQ" NVARCHAR(1),
  "USSD_REQ" NVARCHAR(1),
  CONSTRAINT "TB_ASHS_SMS_USER_PK" PRIMARY KEY("APP_ID", "USER_ID","VERSION_NO")
);
 --------------------------------------------------------
--  DDL for Table TB_ASHS_ROLE_CONTROLS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_ROLE_CONTROLS";
CREATE TABLE "TB_ASHS_ROLE_CONTROLS" (
   "APP_ID" NVARCHAR(100) NOT NULL,
   "ROLE_ID" NVARCHAR(100) NOT NULL,
   "CONTROL_ID" NVARCHAR(100) NOT NULL,
   "CREATED_BY" NVARCHAR(100) DEFAULT NULL,
   "CREATED_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
   "VERSION_NO" NUMERIC(10, 0) DEFAULT 1,
   PRIMARY KEY ("APP_ID","ROLE_ID","CONTROL_ID","VERSION_NO")
) ;
 --------------------------------------------------------
--  DDL for Table TB_ASMI_USER_APP_ACCESS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_USER_APP_ACCESS";
CREATE TABLE "TB_ASMI_USER_APP_ACCESS" (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "USER_ID" NVARCHAR(100) NOT NULL,
  "ALLOWED_APP_ID" NVARCHAR(100) NOT NULL,
  "APP_ACCESS" NVARCHAR(1) DEFAULT 'D',
  "CREATE_USER_ID" NVARCHAR(100) DEFAULT NULL,
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "VERSION_NO" NUMERIC(10) DEFAULT 1,
  CONSTRAINT "TB_ASMI_USER_APP_ACCESS_PK" PRIMARY KEY ("APP_ID", "USER_ID", "ALLOWED_APP_ID")
 ) ;
 --------------------------------------------------------
--  DDL for Table TB_ASHS_USER_APP_ACCESS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_USER_APP_ACCESS";
CREATE TABLE "TB_ASHS_USER_APP_ACCESS" (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "USER_ID" NVARCHAR(100) NOT NULL,
  "ALLOWED_APP_ID" NVARCHAR(100) NOT NULL,
  "APP_ACCESS" NVARCHAR(1) DEFAULT 'D',
  "CREATE_USER_ID" NVARCHAR(100) DEFAULT NULL,
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "VERSION_NO" NUMERIC(10) DEFAULT 1,
  CONSTRAINT "TB_ASHS_USER_APP_ACCESS_PK" PRIMARY KEY ("APP_ID", "USER_ID", "ALLOWED_APP_ID", "VERSION_NO")
 ) ;
 --------------------------------------------------------
--  DDL for Table TB_ASMI_APP_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_APP_MASTER";
   CREATE TABLE "TB_ASMI_APP_MASTER"
   (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"PARENT_APPID" NVARCHAR(100) NULL,
	"APP_NAME" NVARCHAR(100) NOT NULL,
    "CONTAINER_APP" NVARCHAR(1),
    "OTA_REQ" NVARCHAR(1),
	"REMOTE_DEBUG" NVARCHAR(1),
	"EXPIRY_DATE" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"APP_DESCRIPTION" NVARCHAR(200),
	"DEFAULT_LANGUAGE" NVARCHAR(20),
	"CREATE_USER_ID" NVARCHAR(20),
	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"VERSION_NO" NUMERIC(10, 0) DEFAULT 1,
	 "BASE_APP" NVARCHAR(1),
    "MICRO_APP_TYPE" NVARCHAR(10),
    "PRIMARY_MICRO_APP" NVARCHAR(1) DEFAULT 'N',
    "APP_ICON" NVARCHAR(MAX),
    "APP_VERSION" NVARCHAR(20) NOT NULL,
    "IDE_VERSION" NVARCHAR(20) NOT NULL,
    "MAKER_ID" NVARCHAR(45),
	"MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"CHECKER_ID" NVARCHAR(45),
	"CHECKER_TS" DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	"AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
	"WELCOME_MSG" NVARCHAR(255),
	"ANDROID_SIGNATURE" NVARCHAR(200),
	CONSTRAINT "TB_ASMI_APP_MASTER_PK" PRIMARY KEY ("APP_ID")
	) ;
 --------------------------------------------------------
--  DDL for Table TB_ASMI_APP_MASTER
--------------------------------------------------------
--IF exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'TB_ASHS_USER_ROLE')
DROP TABLE IF EXISTS "TB_ASNF_APP_OS_NOTIF_CODE";
  	CREATE TABLE TB_ASNF_APP_OS_NOTIF_CODE(
  	"APP_ID" NVARCHAR(100) NOT NULL, 
	"OS_ID" NVARCHAR(45), 
	"NOTIF_CODE" NVARCHAR(255),
	"ACTION_CODE" NVARCHAR(255),
    "ACTION_DISPLAY" NVARCHAR(255),
   	"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
   	CONSTRAINT "TB_ASNF_APP_OS_NOTIF_CODE_PK" PRIMARY KEY("APP_ID", "OS_ID", "NOTIF_CODE", "ACTION_CODE")
   	);
 --------------------------------------------------------
--  DDL for Table TB_ASMI_DEVICE_GRPS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_DEVICE_GRPS";

CREATE TABLE "TB_ASMI_DEVICE_GRPS" (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "DEVICE_GROUP_ID" NVARCHAR(100) NOT NULL,
  "DEVICE_GROUP_DESCRIPTION" NVARCHAR(1000) NOT NULL,
  "OS" NVARCHAR(10) NOT NULL,
  "HEIGHT" int NOT NULL,
  "WIDTH" int NOT NULL,
  "ORIENTATION_LOCK" NVARCHAR(10) DEFAULT NULL,
  PRIMARY KEY ("APP_ID","DEVICE_GROUP_ID")
) ;
 --------------------------------------------------------
--  DDL for Table TB_ASMI_SCREEN_LAYOUTS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_SCREEN_LAYOUTS";

CREATE TABLE "TB_ASMI_SCREEN_LAYOUTS" (
  "APP_ID" NVARCHAR(6) NOT NULL,
  "SCREEN_ID" NVARCHAR(100) NOT NULL,
  "LAYOUT_ID" NVARCHAR(100) NOT NULL,
  "LAYOUT_NAME" NVARCHAR(100) NOT NULL,
  "LAYOUT_ICON" NVARCHAR(max),
  "DEFAULT_TEMPLATE" NVARCHAR(100) NOT NULL,
  PRIMARY KEY ("APP_ID","SCREEN_ID","LAYOUT_ID")
) ;
--------------------------------------------------------
--  DDL for Table TB_ASMI_SCREEN_MICRO_APP
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_SCREEN_MICRO_APP";
CREATE TABLE "TB_ASMI_SCREEN_MICRO_APP" (
  "APP_ID" NVARCHAR(6) NOT NULL,
  "SCREEN_ID" NVARCHAR(100) NOT NULL,
  "MICRO_APP_ID" NVARCHAR(6) NOT NULL,
  "CREATE_TS" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("APP_ID","SCREEN_ID","MICRO_APP_ID")
) ;
 --------------------------------------------------------
--  DDL for Table TB_ASMI_SCREEN_WIDGETS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_SCREEN_WIDGETS";

CREATE TABLE "TB_ASMI_SCREEN_WIDGETS" (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "SCREEN_ID" NVARCHAR(100) NOT NULL,
  "CALLFORM_ID" NVARCHAR(100) NOT NULL,
  "CREATE_TS" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("APP_ID","SCREEN_ID","CALLFORM_ID")
) ;
 --------------------------------------------------------
--  DDL for Table TB_ASMI_DESIGN_OBJECTS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_DESIGN_OBJECTS";

CREATE TABLE "TB_ASMI_DESIGN_OBJECTS" (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "SCREEN_ID" NVARCHAR(100) NOT NULL,
  "LAYOUT_ID" NVARCHAR(100) NOT NULL,
  "DESIGN_ID" NVARCHAR(100) NOT NULL,
  "PARENT_ID" NVARCHAR(100) NOT NULL,
  "CHILD_ID" NVARCHAR(100) NOT NULL,
  "CHILD_SEQ" int NOT NULL,
  PRIMARY KEY ("APP_ID","SCREEN_ID","LAYOUT_ID","DESIGN_ID","PARENT_ID","CHILD_ID")
) ;
--------------------------------------------------------
--  DDL for Table TB_ASCZ_SCREEN_LAYOUTS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASCZ_SCREEN_LAYOUTS";

CREATE TABLE "TB_ASCZ_SCREEN_LAYOUTS" (
  "APP_ID" NVARCHAR(6) NOT NULL,
  "SCREEN_ID" NVARCHAR(100) NOT NULL,
  "LAYOUT_ID" NVARCHAR(100) NOT NULL,
  "DEFAULT_TEMPLATE" NVARCHAR(100) NOT NULL,
  "CREATE_TS" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "MAKER_ID" NVARCHAR(45),
  "MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "CHECKER_ID" NVARCHAR(45),
  "CHECKER_TS" DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  "AUTH_STATUS" NVARCHAR(1) DEFAULT 'U',
  "VERSION_NO" int DEFAULT 1,
  PRIMARY KEY ("APP_ID","SCREEN_ID","LAYOUT_ID")
) ;
--------------------------------------------------------
--  DDL for Table TB_ASCZ_TEMPLATE_OBJECTS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASCZ_TEMPLATE_OBJECTS";

CREATE TABLE "TB_ASCZ_TEMPLATE_OBJECTS" (
  "APP_ID" NVARCHAR(6) NOT NULL,
  "SCREEN_ID" NVARCHAR(100) NOT NULL,
  "LAYOUT_ID" NVARCHAR(100) NOT NULL,
  "TEMPLATE_ID" NVARCHAR(100) NOT NULL,
  "PARENT_ID" NVARCHAR(100) NOT NULL,
  "CHILD_ID" NVARCHAR(100) NOT NULL,
  "CHILD_SEQ" int NOT NULL,
  PRIMARY KEY ("APP_ID","SCREEN_ID","LAYOUT_ID","TEMPLATE_ID","PARENT_ID","CHILD_ID")
) ;
--------------------------------------------------------
--  DDL for Table TB_ASTP_SESSION_STORAGE
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASTP_SESSION_STORAGE";

CREATE TABLE "TB_ASTP_SESSION_STORAGE"(
"APP_ID" NVARCHAR(100) NOT NULL,
"USER_ID" NVARCHAR(100) NOT NULL,
"SESSION_ID" NVARCHAR(255) NOT NULL,
"DEVICE_ID" NVARCHAR(255) NULL,
"SESSION_KEY" NVARCHAR(255) NOT NULL,
"SESSION_VALUE" NTEXT NOT NULL,
"CREATED_BY" NVARCHAR(100) NULL,
"CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY ("APP_ID","USER_ID","SESSION_ID", "SESSION_KEY")
);
--------------------------------------------------------
--  DDL for Table TB_DBTP_TXN_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_DBTP_TXN_MASTER";

CREATE TABLE "TB_DBTP_TXN_MASTER" (
  "TXN_REF_NO" NVARCHAR(255) NOT NULL,
  "APP_ID" NVARCHAR(6) NOT NULL,
  "USER_ID" NVARCHAR(100) NOT NULL,
  "CUSTOMER_ID" NVARCHAR(100) NOT NULL,
  "AMOUNT" DECIMAL(22,3) NOT NULL,
  "TXN_TYPE" NVARCHAR(20) NOT NULL,
  "TXN_STATUS" NVARCHAR(1) DEFAULT 'U',
  "CREATION_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "COMPLETION_TS" DATETIME NULL,
   PRIMARY KEY ("TXN_REF_NO")
);

 --------------------------------------------------------
--  DDL for Table TB_ASLG_DEVICE_LOCATION
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASLG_DEVICE_LOCATION";

CREATE TABLE "TB_ASLG_DEVICE_LOCATION" (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "DEVICE_ID" NVARCHAR(255) NOT NULL,
  "LATITUDE" NVARCHAR(255) DEFAULT NULL,
  "LONGITUDE" NVARCHAR(255) DEFAULT NULL,
  "CREATE_TS"  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY ("APP_ID","DEVICE_ID")
 );

 --------------------------------------------------------
--  DDL for Table TB_ASMI_CAPTCHA_DTLS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_CAPTCHA_DTLS";
CREATE TABLE "TB_ASMI_CAPTCHA_DTLS" (
  "CAPTCHA_REF" BIGINT NOT NULL,
  "APP_ID" NVARCHAR(100) ,
  "CAPTCHA_STRING" NVARCHAR(255),
  "AUDIO_CAPTCHA" NVARCHAR(255),
  "INTERFACE_ID" NVARCHAR(100) ,
  "SESSION_ID" NVARCHAR(255),
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "VALIDATE_TS" DATETIME,
  "CAPTCHA_STATUS" NVARCHAR(2) DEFAULT 'NP',
  "VERSION_NO" NUMERIC NOT NULL DEFAULT 0,
  PRIMARY KEY (CAPTCHA_REF)
);

 --------------------------------------------------------
--  DDL for Table TB_ASMI_CNVUI_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_CNVUI_MASTER";

CREATE TABLE "TB_ASMI_CNVUI_MASTER" (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "CNVUI_ID" NVARCHAR(100) NOT NULL,
  "CNVUI_DESC" NVARCHAR(100),
  "CREATE_USER_ID" NVARCHAR(100) DEFAULT NULL,
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "VERSION_NO" NUMERIC(10, 0) DEFAULT 1,
  CONSTRAINT "TB_ASMI_CNVUI_MASTER_PK" PRIMARY KEY ("APP_ID","CNVUI_ID")
);
 --------------------------------------------------------
--  DDL for Table TB_ASMI_DLG_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_DLG_MASTER";

CREATE TABLE "TB_ASMI_DLG_MASTER" (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "CNVUI_ID" NVARCHAR(100) NOT NULL,
  "DLG_ID" NVARCHAR(100) NOT NULL,
  "DLG_DESC" NVARCHAR(100),
  "DLG_TYPE" NVARCHAR(100),
  "DLG_SEQ" NUMERIC(10,0),
  "NXT_DLG_ID" NVARCHAR(100),
  "RESP_DLG_ID" NVARCHAR(100),
  "RESP_TYPE" NVARCHAR(100),
  "SCREEN_ID" NVARCHAR(100),
  "INTERFACE_ID" NVARCHAR(100),
  "CREATE_USER_ID" NVARCHAR(100) DEFAULT NULL,
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "MAKER_ID" NVARCHAR(45),
  "MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "CHECKER_ID" NVARCHAR(45),
  "CHECKER_TS" DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  "AUTH_STATUS" NVARCHAR(45) DEFAULT 'U',
  "VERSION_NO" NUMERIC(10, 0) DEFAULT 1,
  CONSTRAINT "TB_ASMI_DLG_MASTER_PK" PRIMARY KEY ("APP_ID","CNVUI_ID","DLG_ID")
);
 --------------------------------------------------------
--  DDL for Table TB_ASMI_CNVUI_SCR
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_CNVUI_SCR";

CREATE TABLE "TB_ASMI_CNVUI_SCR" (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "SCREEN_ID" NVARCHAR(100) NOT NULL,
  "SCREEN_DESC" NVARCHAR(100),
  "SCREEN_DEF" NVARCHAR(MAX),
  "SCREEN_DESIGN" NVARCHAR(MAX),
  "SCREEN_HTML" NVARCHAR(MAX),
  "SCREEN_LAYOUT" NVARCHAR(MAX),
  "TEMPLATE" NVARCHAR(MAX),
  "CREATE_USER_ID" NVARCHAR(100) DEFAULT NULL,
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "VERSION_NO" NUMERIC(10, 0) DEFAULT 1,
  CONSTRAINT "TB_ASMI_CNVUI_SCR_PK" PRIMARY KEY ("APP_ID","SCREEN_ID")
);
 --------------------------------------------------------
--  DDL for Table TB_ASLG_CNVUI_TXN_LOG
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASLG_CNVUI_TXN_LOG";

CREATE TABLE "TB_ASLG_CNVUI_TXN_LOG" (
  "TXN_REF" NVARCHAR(255) NOT NULL,
  "APP_ID" NVARCHAR(100),
  "CNVUI_ID" NVARCHAR(100),
  "RESP_DLG_ID" NVARCHAR(100),
  "SCREEN_DATA" NVARCHAR(MAX),
  "CREATE_USER_ID" NVARCHAR(100) DEFAULT NULL,
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "UPDATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "TB_ASLG_CNVUI_TXN_LOG_PK" PRIMARY KEY ("TXN_REF")
);

--------------------------------------------------------
--  DDL for Table TB_ASMI_CS_NONCEDETAILS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_CS_NONCEDETAILS";

CREATE TABLE "TB_ASMI_CS_NONCEDETAILS" (
  "DEVICE_ID" NVARCHAR(100),
  "APP_ID" NVARCHAR(100),
  "REQUEST_ID" NVARCHAR(255),
  "CLIENT_NONCE" NVARCHAR(100),
  "SERVER_NONCE" NVARCHAR(100),
  "STATUS" NVARCHAR(100),
  "SERVER_TOKEN" NVARCHAR(100),
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "CREATED_ON" DATE,
  INDEX TB_ASMI_CS_NONCEDETAILS_INDEX ("SERVER_NONCE")

);
/*  create unique index */
    create unique index TB_ASMI_CS_NONCEDETAILS_IDX01 on TB_ASMI_CS_NONCEDETAILS(DEVICE_ID, APP_ID, REQUEST_ID, CLIENT_NONCE, SERVER_NONCE);


 --------------------------------------------------------
--  DDL for Table TB_ASMI_WORKFLOW_DEFN
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_WORKFLOW_DEFN";

CREATE TABLE "TB_ASMI_WORKFLOW_DEFN" (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"WORKFLOW_ID" NVARCHAR(100) NOT NULL,
	"WORKFLOW_DESC" NVARCHAR(255),
	"VERSION_NO" int,
	"MAKER_ID" NVARCHAR(255),
	"MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"CHECKER_ID" NVARCHAR(255),	
	"CHECKER_TS" DATETIME NULL,
	"AUTH_STATUS" NVARCHAR(1),
	"ACTIVE" CHAR(1),
	"TXN_TYPE" NVARCHAR(100),
	"ONCE_AUTH" NVARCHAR(1),
	PRIMARY KEY ("APP_ID", "WORKFLOW_ID")
);
 --------------------------------------------------------
--  DDL for Table TB_ASMI_WORKFLOW_RULES
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_WORKFLOW_RULES";

CREATE TABLE "TB_ASMI_WORKFLOW_RULES"(
	"APP_ID" NVARCHAR(100) NOT NULL,
	"WORKFLOW_ID" NVARCHAR(100) NOT NULL,
	"RULE_ID" NVARCHAR(50) NOT NULL,
	"RULE_DESC" NVARCHAR(255),
	"RULE_BEAN" NVARCHAR(255),	
	"VERSION_NO" int,
	"MAKER_ID" NVARCHAR(45),
	"MAKER_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"CHECKER_ID" NVARCHAR(45),
	"CHECKER_TS" DATETIME NULL,
	"AUTH_STATUS" NVARCHAR(1),
	"ACTIVE" CHAR(1),
	"ONCE_AUTH" NVARCHAR(1),
	
	PRIMARY KEY ("APP_ID", "RULE_ID", "WORKFLOW_ID")
);
 --------------------------------------------------------
--  DDL for Table TB_ASMI_WORKFLOW_STAGES
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_WORKFLOW_STAGES";

CREATE TABLE "TB_ASMI_WORKFLOW_STAGES" (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"WORKFLOW_ID" NVARCHAR(100) NOT NULL,
	"STAGE_ID" NVARCHAR(50) NOT NULL,
	"STAGE_SEQ_NO" int,
	"STAGE_TYPE" NVARCHAR(50),
	"STAGE_DESC" NVARCHAR(255),
	"RULE_ID" NVARCHAR(50),
	"SCREEN_ID" NVARCHAR(50),
	"IS_AUTH_MATRIX_REQD" NVARCHAR(1),
	PRIMARY KEY ("APP_ID", "STAGE_ID", "WORKFLOW_ID")
);

--------------------------------------------------------
--  DDL for Table TB_ASTP_WORKFLOW_TXN_DETAIL
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASTP_WORKFLOW_TXN_DETAIL";
CREATE TABLE "TB_ASTP_WORKFLOW_TXN_DETAIL" (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"WORKFLOW_REF_NO" NVARCHAR(100) NOT NULL,
	"STAGE_ID" NVARCHAR(50) NOT NULL,
	"WORKFLOW_ID" NVARCHAR(100),
	"WORKFLOW_SEQ_NO" int ,
	"TASK_DATA" varchar(max),
	"USER_ID" NVARCHAR(50),
	"STATUS" NVARCHAR(50),
	"UPDATED_NEXT_STAGES" NVARCHAR(255),
	"LAST_EVENT_NO" int,
	"START_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"END_TS" DATETIME NULL,
	"REMARKS" NVARCHAR(255),
	"CUSTOM_FIELD_1" NVARCHAR(100),
	"CUSTOM_FIELD_2" NVARCHAR(100),
	"CUSTOM_FIELD_3" NVARCHAR(100),
	"CUSTOM_FIELD_4" NVARCHAR(100),
	"CUSTOM_FIELD_5" NVARCHAR(100),	
	PRIMARY KEY ("APP_ID", "WORKFLOW_REF_NO", "WORKFLOW_SEQ_NO")
);
 --------------------------------------------------------
--  DDL for Table TB_ASTP_WORKFLOW_EVENT
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASTP_WORKFLOW_EVENT";

CREATE TABLE "TB_ASTP_WORKFLOW_EVENT" (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"WORKFLOW_REF_NO" NVARCHAR(100) NOT NULL,
	"WORKFLOW_SEQ_NO" int NOT NULL,
	"EVENT_SEQ_NO" int NOT NULL,
	"WORKFLOW_ID" NVARCHAR(100),
	"STAGE_ID" NVARCHAR(50) NOT NULL,
	"EVENT_ID" NVARCHAR(50),
	"TASK_DATA" NVARCHAR(MAX),
	"USER_ID" NVARCHAR(50),
	"EVENT_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"REMARKS" NVARCHAR(255),
	"CUSTOM_FIELD_1" NVARCHAR(100),
	"CUSTOM_FIELD_2" NVARCHAR(100),
	"CUSTOM_FIELD_3" NVARCHAR(100),
	"CUSTOM_FIELD_4" NVARCHAR(100),
	"CUSTOM_FIELD_5" NVARCHAR(100),	
	PRIMARY KEY ("APP_ID", "WORKFLOW_REF_NO", "WORKFLOW_SEQ_NO", "EVENT_SEQ_NO")
);
 --------------------------------------------------------
--  DDL for Table TB_ASTP_WORKFLOW_TXN_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASTP_WORKFLOW_TXN_MASTER";
CREATE TABLE "TB_ASTP_WORKFLOW_TXN_MASTER" (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"WORKFLOW_REF_NO" NVARCHAR(100) NOT NULL,
	"WORKFLOW_ID" NVARCHAR(100),
	"STATUS" NVARCHAR(50),
	"START_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"MODIFIED_TS" DATETIME,
	"END_TS" DATETIME,
	"CUSTOM_FIELD_1" NVARCHAR(100),
	"CUSTOM_FIELD_2" NVARCHAR(100),
	"CUSTOM_FIELD_3" NVARCHAR(100),
	"CUSTOM_FIELD_4" NVARCHAR(100),
	"CUSTOM_FIELD_5" NVARCHAR(100),
	PRIMARY KEY ("APP_ID", "WORKFLOW_REF_NO")
);

 --------------------------------------------------------
--  DDL for Table TB_ASHS_WORKFLOW_TXN_DETAILS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_WORKFLOW_TXN_DETAILS";
CREATE TABLE "TB_ASHS_WORKFLOW_TXN_DETAILS" (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"WORKFLOW_REF_NO" NVARCHAR(100) NOT NULL,
	"WORKFLOW_SEQ_NO" int NOT NULL,
	"WORKFLOW_ID" NVARCHAR(100),
	"STAGE_ID" NVARCHAR(50),
	"TASK_DATA" varchar(max),
	"USER_ID" NVARCHAR(50),
	"STATUS" NVARCHAR(50),
	"UPDATED_NEXT_STAGES" NVARCHAR(255),
	"LAST_ACTION" NVARCHAR(50),
	"CUSTOM_FIELD_1" NVARCHAR(100),
	"CUSTOM_FIELD_2" NVARCHAR(100),
	"CUSTOM_FIELD_3" NVARCHAR(100),
	"CUSTOM_FIELD_4" NVARCHAR(100),
	"CUSTOM_FIELD_5" NVARCHAR(100),	
	PRIMARY KEY ("APP_ID", "WORKFLOW_REF_NO", "WORKFLOW_SEQ_NO")
);
 --------------------------------------------------------
--  DDL for Table TB_ASHS_WORKFLOW_TXN_MASTER
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASHS_WORKFLOW_TXN_MASTER";

CREATE TABLE "TB_ASHS_WORKFLOW_TXN_MASTER" (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"WORKFLOW_REF_NO" NVARCHAR(100) NOT NULL,
	"WORKFLOW_ID" NVARCHAR(100),
	"STATUS" NVARCHAR(50),
	"START_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
	"MODIFIED_TS" DATETIME,
	"END_TS" DATETIME,
	"CUSTOM_FIELD_1" NVARCHAR(100),
	"CUSTOM_FIELD_2" NVARCHAR(100),
	"CUSTOM_FIELD_3" NVARCHAR(100),
	"CUSTOM_FIELD_4" NVARCHAR(100),
	"CUSTOM_FIELD_5" NVARCHAR(100),	
	PRIMARY KEY ("APP_ID", "WORKFLOW_REF_NO")
);

 --------------------------------------------------------
--  DDL for Table TB_ASMI_WORKFLOW_LINKED_STAGES
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_WORKFLOW_LINKED_STAGES";

CREATE TABLE "TB_ASMI_WORKFLOW_LINKED_STAGES" (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"WORKFLOW_ID" NVARCHAR(100),
	"STAGE_ID" NVARCHAR(50),
	"LINKAGE_TYPE" char(1),
	"LINKED_STAGE_ID" NVARCHAR(50),
	PRIMARY KEY ("APP_ID", "LINKAGE_TYPE", "LINKED_STAGE_ID", "STAGE_ID", "WORKFLOW_ID")
);

 --------------------------------------------------------
--  DDL for Table TB_ASMI_ROLE_WORKFLOWS
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_ROLE_WORKFLOWS";
CREATE TABLE "TB_ASMI_ROLE_WORKFLOWS" (
	"APP_ID" NVARCHAR(100) NOT NULL,
	"ROLE_ID" NVARCHAR(100) NOT NULL,
	"WORKFLOW_ID" NVARCHAR(100) NOT NULL,
	"STAGE_ID" NVARCHAR(50)NOT NULL,
	PRIMARY KEY ("APP_ID", "ROLE_ID", "WORKFLOW_ID", "STAGE_ID")
);
 --------------------------------------------------------
--  DDL for Table TB_ASMI_APP_ACCESS_TOKEN
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_APP_ACCESS_TOKEN";

CREATE TABLE "TB_ASMI_APP_ACCESS_TOKEN" (
  "APP_ID" NVARCHAR(100),
  "USER_ID" NVARCHAR(100),
  "ACCESS_TOKEN" NVARCHAR(255),
  "CLIENT_NONCE" NVARCHAR(255),
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT "TB_ASMI_APP_ACCESS_TOKEN_PK" PRIMARY KEY ("APP_ID","USER_ID","ACCESS_TOKEN","CLIENT_NONCE")
);
 --------------------------------------------------------
--  DDL for Table TB_ASMI_COOKIES
--------------------------------------------------------
DROP TABLE IF EXISTS "TB_ASMI_COOKIES";

CREATE TABLE "TB_ASMI_COOKIES" (
  "APP_ID" NVARCHAR(100) NOT NULL,
  "USER_ID" NVARCHAR(100) NOT NULL,
  "USR_SELECTOR" NVARCHAR(50) NOT NULL,
  "USR_VALIDATOR" NVARCHAR(255) NOT NULL,
  "CREATE_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "EXPIRY_TS" DATETIME DEFAULT CURRENT_TIMESTAMP,
  "VERSION_NO" NUMERIC(10,0) DEFAULT 1,
  CONSTRAINT "TB_ASMI_COOKIES_PK" PRIMARY KEY ("APP_ID", "USR_SELECTOR")
);

DROP VIEW IF EXISTS VW_LOCATION_DETAILS;
GO
CREATE VIEW VW_LOCATION_DETAILS AS
SELECT * FROM TB_ASTP_LAST_LOGIN A where A.SESSION_ID IS NOT NULL
AND abs(DATEDIFF("second",GETDATE(),LAST_REQ_TIME)) < (SELECT SESSION_TIMEOUT FROM 
TB_ASMI_SECURITY_PARAMETERS C WHERE A.APP_ID=C.APP_ID);
GO

DROP VIEW IF EXISTS VW_ACTIVE_SESSIONS;
GO
CREATE VIEW VW_ACTIVE_SESSIONS AS
SELECT B.OS,A.APP_ID, COUNT(*) as COUNT
FROM TB_ASTP_LAST_LOGIN A,TB_ASMI_DEVICE_MASTER B
WHERE A.APP_ID =B.APP_ID
AND A.DEVICE_ID = B.DEVICE_ID
AND A.SESSION_ID IS NOT NULL
AND abs(DATEDIFF("second",GETDATE(),LAST_REQ_TIME)) <
(SELECT SESSION_TIMEOUT FROM TB_ASMI_SECURITY_PARAMETERS C WHERE C.APP_ID=A.APP_ID)
GROUP BY B.OS, A.APP_ID
union all
SELECT A.DEVICE_ID,A.APP_ID, COUNT(*) as COUNT
FROM TB_ASTP_LAST_LOGIN A
WHERE A.DEVICE_ID IN ('WEB','SIMULATOR')
AND A.SESSION_ID IS NOT NULL
AND  abs(DATEDIFF("second",GETDATE(),LAST_REQ_TIME))
< (SELECT SESSION_TIMEOUT FROM TB_ASMI_SECURITY_PARAMETERS C WHERE C.APP_ID=A.APP_ID)
GROUP BY A.DEVICE_ID, A.APP_ID;
GO

DROP VIEW IF EXISTS VW_ACTIVE_INACTIVE_USERS;
GO
CREATE VIEW VW_ACTIVE_INACTIVE_USERS
AS
SELECT t1.APP_ID, CAST(t1.CREATE_TS AS DATE) as CREATE_TS, count(*) as ACTIVE , 0 INACTIVE
FROM TB_ASMI_USER t1
LEFT JOIN TB_ASTP_LAST_LOGIN t2 ON t2.USER_ID = t1.USER_ID AND t2.APP_ID = t1.APP_ID 
WHERE t2.USER_ID IS NOT NULL AND t1.USER_ACTIVE='Y'
GROUP BY t1.APP_ID, CAST(t1.CREATE_TS  AS DATE)
UNION ALL
SELECT t1.APP_ID,CAST(t1.CREATE_TS AS DATE) as CREATE_TS, 0 ACTIVE, count(*) as INACTIVE
FROM TB_ASMI_USER t1
LEFT JOIN TB_ASTP_LAST_LOGIN t2 ON t2.USER_ID = t1.USER_ID AND t2.APP_ID = t1.APP_ID 
WHERE t2.USER_ID IS NULL AND t1.USER_ACTIVE='Y'
GROUP BY t1.APP_ID, CAST(t1.CREATE_TS AS DATE);
GO

DROP VIEW IF EXISTS VW_LOGIN_REPORT;
GO
CREATE VIEW VW_LOGIN_REPORT AS
select tb.APP_ID,tb.DEVICE_ID,CAST(tb.CREATE_TS AS Date) as AccessDate,count(*) as TotalTxns,0 Logins,0 DistinctLogins
from  TB_ASLG_TXN_DETAIL tb where tb.TXN_STAT='S'
group by tb.APP_ID,tb.DEVICE_ID,CAST(tb.CREATE_TS AS Date)
union all
select tb2.APP_ID,tb2.DEVICE_ID,CAST(tb2.CREATE_TS AS Date) as AccessDate,0 TotalTxns,count(*) as Logins,
count(distinct CAST(tb2.CREATE_TS AS Date)) as DistinctLogins
from TB_ASLG_TXN_DETAIL tb2 where 
(tb2.INTERFACE_ID='appzillonReLoginRequest' OR tb2.INTERFACE_ID='appzillonAuthenticationRequest')
and tb2.TXN_STAT='S' 
Group by tb2.APP_ID,tb2.USER_ID,tb2.DEVICE_ID,CAST(tb2.CREATE_TS AS Date);
GO

DROP VIEW IF EXISTS VW_CUSTOMER_DETAILS;
GO
CREATE VIEW VW_CUSTOMER_DETAILS AS
SELECT APP_ID,USER_ID,CAST(CREATE_TS AS Date) AS AccessDate,SESSION_ID,min(ST_TM) as ST_TM,max(END_TM) as END_TM,Count(*) As 
TotalTxns,0 DistinctTxns,LATITUDE,LONGITUDE,FORMATTED_ADDRESS
FROM TB_ASLG_TXN_DETAIL 
WHERE TXN_STAT='S' 
GROUP by APP_ID,USER_ID,CAST(CREATE_TS AS Date),SESSION_ID,LATITUDE,LONGITUDE,FORMATTED_ADDRESS
UNION ALL
SELECT APP_ID,USER_ID,CAST(CREATE_TS AS Date) AS AccessDate,SESSION_ID,min(ST_TM) as ST_TM,max(END_TM) as END_TM,0 TotalTxns, 
Count(distinct(INTERFACE_ID)) AS DistinctTxns,LATITUDE,LONGITUDE,FORMATTED_ADDRESS
FROM TB_ASLG_TXN_DETAIL 
WHERE TXN_STAT='S'
GROUP BY APP_ID,USER_ID,CAST(CREATE_TS AS Date),SESSION_ID,INTERFACE_ID,LATITUDE,LONGITUDE,FORMATTED_ADDRESS;
GO

DROP VIEW IF EXISTS VW_CUSTOMER_REPORT;
GO
CREATE VIEW VW_CUSTOMER_REPORT
AS
SELECT tb.APP_ID,tb.USER_ID,tb.SESSION_ID,
abs(DATEDIFF("MILLISECOND",MAX(END_TM),MIN(ST_TM))) tm, 
count(*) as TotalTxns,count(distinct(tb.INTERFACE_ID)) as DistinctTxns, 0 Logins, 0 DistinctLogins
FROM  TB_ASLG_TXN_DETAIL tb WHERE tb.TXN_STAT='S' GROUP BY tb.APP_ID, tb.USER_ID, tb.SESSION_ID
UNION ALL
SELECT tb2.APP_ID,tb2.USER_ID, null SESSION_ID,
null tm, 0 TotalTxns,0 DistinctTxns,count(*) as Logins, count(distinct CAST(tb2.CREATE_TS AS Date)) as DistinctLogins
FROM TB_ASLG_TXN_DETAIL tb2 WHERE 
(tb2.INTERFACE_ID='appzillonReLoginRequest' OR tb2.INTERFACE_ID='appzillonAuthenticationRequest')
and tb2.TXN_STAT='S' GROUP BY tb2.APP_ID, tb2.USER_ID;
GO

DROP VIEW IF EXISTS VW_LAT_LON_DETAILS;
GO
CREATE VIEW VW_LAT_LON_DETAILS 
AS
SELECT APP_ID,USER_ID,COUNT(LONGITUDE) as COUNT_LON, LONGITUDE, 
COUNT(LATITUDE) as COUNT_LAT,LATITUDE, FORMATTED_ADDRESS FROM TB_ASLG_TXN_DETAIL GROUP BY LONGITUDE, LATITUDE, FORMATTED_ADDRESS, APP_ID, USER_ID;
GO

DROP VIEW IF EXISTS VW_TXN_APP_USAGE;
GO
CREATE VIEW VW_TXN_APP_USAGE AS
SELECT txn.APP_ID,CAST(txn.CREATE_TS AS Date) AS AccessDate,intf.DESCRIPTION, txn.TXN_STAT,
MIN(abs(DATEDIFF("MILLISECOND",txn.END_TM,txn.ST_TM))) AS MinTime, MAX(abs(DATEDIFF("MILLISECOND",txn.END_TM,txn.ST_TM))) AS MaxTime, 
AVG(abs(DATEDIFF("MILLISECOND",txn.END_TM,txn.ST_TM))) AS AvgTime, count(txn.INTERFACE_ID) AS IntfCount FROM TB_ASLG_TXN_DETAIL txn, 
TB_ASMI_INTF_MASTER intf WHERE txn.INTERFACE_ID = intf.INTERFACE_ID
GROUP BY txn.APP_ID,txn.INTERFACE_ID,CAST(txn.CREATE_TS AS Date),intf.DESCRIPTION,txn.TXN_STAT;
GO



DROP VIEW IF EXISTS VW_ASMI_DEVICE_GRPS;
GO
CREATE VIEW VW_ASMI_DEVICE_GRPS AS
SELECT APP_ID, DEVICE_GROUP_ID, DEVICE_GROUP_DESCRIPTION, OS,HEIGHT, WIDTH, 'PORTRAIT' AS ORIENTATION
FROM TB_ASMI_DEVICE_GRPS WHERE ORIENTATION_LOCK = 'ANY'
UNION ALL
SELECT APP_ID, DEVICE_GROUP_ID, DEVICE_GROUP_DESCRIPTION, OS,HEIGHT, WIDTH, 'LANDSCAPE' AS ORIENTATION
FROM TB_ASMI_DEVICE_GRPS WHERE ORIENTATION_LOCK = 'ANY'
UNION ALL
SELECT APP_ID, DEVICE_GROUP_ID, DEVICE_GROUP_DESCRIPTION, OS,HEIGHT, WIDTH, ORIENTATION_LOCK AS ORIENTATION
FROM TB_ASMI_DEVICE_GRPS 
WHERE ORIENTATION_LOCK != 'ANY';
GO

DROP VIEW IF EXISTS VW_ASMI_MICROAPPS;
GO
CREATE VIEW VW_ASMI_MICROAPPS AS
SELECT T2.APP_ID AS APP_ID, T2.SCREEN_ID, T2.MICRO_APP_ID AS MICRO_APP_ID, T1.APP_NAME AS MICRO_APP_NAME, T1.APP_ICON AS MICRO_APP_ICON,
T1.MICRO_APP_TYPE AS MICRO_APP_TYPE FROM TB_ASMI_APP_MASTER T1, TB_ASMI_SCREEN_MICRO_APP T2
WHERE T1.APP_ID = T2.MICRO_APP_ID AND T1.BASE_APP = 'N';
GO


DROP VIEW IF EXISTS VW_ASMI_NANOAPPS;
GO
CREATE VIEW VW_ASMI_NANOAPPS AS
SELECT T1.APP_ID, T2.SCREEN_ID, T1.SCREEN_ID AS CALLFORM_ID, T1.SCREEN_NAME AS CALLFORM_NAME, T1.SCREEN_ICON AS CALLFORM_ICON
FROM TB_ASMI_SCR_MASTER T1, TB_ASMI_SCREEN_WIDGETS T2
WHERE T1.APP_ID = T2.APP_ID AND T1.SCREEN_ID = T2.CALLFORM_ID AND T1.SCREEN_TYPE = 'CALL';
GO
