apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: {{ .Values.artifactType }}-elasticsearch-secret
  namespace: {{ .Values.nameSpace }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.harborSecret }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: {{ .Values.artifactType }}-elasticsearch-secret
      namespace: {{ .Values.nameSpace }}
    type: kubernetes.io/dockerconfigjson