//
//  StringConstants.swift
//  Appzillon
//
//  Created by Nidhi Agrawal on 06/10/21.
//
// swiftlint:disable all
import Foundation

struct StringConstants {
    struct Generic {
        static let emptyString = ""
        static let whiteSpace = " "
        static let pluginId = "id"
        static let success = "success"
        static let failed = "failed"
        static let yes = "Y"
        static let no = "N"
        static let kTrue = "true"
        static let kfalse = "false"
        static let jscallBackMethod = "Apz.nativeServiceCB"
        static let errorCode = "errorCode"
        static let message = "message"
        static let sandBoxPath = "Assets/apps/"
        static let sourcePath = "srcFilePath"
        static let destinationPath = "destFilePath"
        static let actionType = "actionType"
        static let filePath = "filePath"
        static let fileNotFoundCode = "APZ-CNT-002"
        static let storageErrorCode = "APZ-CNT-048"
        static let webViewUrl = "URL"
        static let jsonPath = "path"
        static let encodedImage  = "encodedImage"
        static let edit = "edit"
        static let delete = "delete"
        static let action = "action"
        static let opnType = "opnType"
        static let imagePath = "imagePath"
        static let create = "create"
        static let name = "name"
        static let sourceType = "sourceType"
        static let album = "album"
        static let photo = "photo"
        static let title  = "title"
        static let fileName = "fileName"
        static let base64 = "base64"
        static let png = "png"
        static let quality = "quality"
        static let encodingTyp = "encodingType"
        static let crop = "crop"
        static let text = "text"
        static let errorMessage = "errorMessage"
        static let content = "content"
        static let fileContent = "fileContent"
        static let pdf = "pdf"
        static let newLine = "\n"
        static let fileCreationFailure = "APZ-CNT-011"
        static let cameraNotFound = "APZ-CNT-035"
        static let fileDestinationPath = "destinationPath"
        static let appzillon = "Appzillon"
        static let dot = "."
        static let location = "location"
        static let otaRequired = "OTAREQUIRED"
        static let landScape = "LANDSCAPE"
        static let portrait = "PORTRAIT"
        static let any = "ANY"
        static let cbEvent = "event"
        static let cancel = "cancel"
        static let comma = ","
        static let fileSize = "fileSize"
        static let appId = "appId" // duplicate
        static let mainAppId = "MAINAPPID"
        static let upgradeRequired = "upgradeRequired"
        static let updateAction = "updateAction"
        static let appPropertiesPlistPath = "/plist/AppProperties.plist"
        static let appVersion = "appVersion"
        static let key = "key"
        static let fileNotExist = "File does not exist"
        static let fileWriteFailure = "File written failure"
        static let onAppLoaded = "ON_APP_LOADED"
        static let url = "url"
        static let ucOk = "OK"
        static let containerProps = "containerprops"
        static let plist = "plist"
        static let cellIdentifier = "CellIdentifier"
        static let pathSeperator = "/"
        static let filesHeading = "Files"
        static let json = "json"
        static let encodeFailBase64 = "APZ-CNT-036"
        static let file = "file"
        static let couldNotCreatedirectory = "APZ-CNT-072"
        static let imageConversionErr = "APZ-CNT-118"
        static let invalidSrc = "APZ-CNT-190"
        static let type = "type"
        static let data = "data"
        static let outputFile = "outputFile"
        static let threshold = "threshold"
        static let value = "value"
        static let back = "Back"
        static let appExpriedMsg = "This Application has been Expired"
        static let uniqueId = "uniqueID"
        static let orientation = "orientation"
        static let hyphen = "-"
        static let started = "started"
        static let stopped = "stopped"
        static let dateFormat = "yyyyMMdd_HHmmss"
        static let image = "image"
        static let address = "address"
        static let lattitude = "latitude"
        static let longitude = "longitude"
        static let save  = "save"
        static let none = "none"
        static let hapticFeedback = "hapticFeedback"
        static let deviceName = "deviceName"
    }
    struct Contact {
        static let noContactFound = "No Contact Found"
        static let requestDenied = "Request Denied to access Contacts"
        static let addSuccessful = "Contact is added succesfully"
        static let addFailure = "Contact can not be added"
        static let editSuccessful = "Contact edited successfully"
        static let editFailure = "Contact cannot be edited"
        static let deleteSuccessful = "Contact deleted successfully"
        static let deleteFailure = "Contact can not be deleted"
        static let noContactForDelete = "No contact found for delete"
        static let multipleContacts = "Multiple Contacts Found, kindly refine your search criteria"
        static let firstName = "firstName"
        static let lastName = "lastName"
        static let phoneHome = "phoneHome"
        static let phoneWork = "phoneWork"
        static let phoneMobile = "phoneMobile"
        static let birthday = "birthday"
        static let mail = "mail"
        static let website = "website"
        static let nickName = "nickName"
        static let encodeImage = "encodedImage"
        static let add = "add"
        static let fetch = "fetch"
        static let fetchAll = "fetchallcontacts"
        static let search = "search"
        static let userDefault = "userDefault"
        static let sortOrder = "sortOrder"
        static let contactAccessFailCode = "APZ-CNT-040"
        static let contactCreationFailCode = "APZ-CNT-041"
        static let contactDeleteFailCode  = "APZ-CNT-043"
        static let contactEditFailCode  = "APZ-CNT-042"
        static let contactNotFoundCode = "APZ-CNT-044"
        static let multipleContactFailCode = "APZ-CNT-045"
        static let searchCriteria  = "searchCriteria"
        static let searchJsonRoot  = "contacts"
        static let deleteCriteria  = "deleteCriteria"
        static let details = "details"
        static let email = "email"
        static let phoneNo = "phoneno"
        static let dateFormat = "dateFormat"
        static let contactDetails = "contactDetails"
        static let contactString = "Contacts"
        static let standardDateFormat = "dd/MM/yyyy"
    }
    struct Calendar {
        static let events = "events"
        static let fullDateFormat = "dd-MM-yyyy HH:mm:ss"
        static let halfDateFormat = "dd-MM-yyyy HH:mm"
        static let eventEditSucees = "Event is edited"
        static let eventDeleteSuccess = "Event is deleted"
        static let alarm = "alarm"
        static let futureEvents = "futureEvents"
        static let alarm5Min = "5M"
        static let alarm15Min = "15M"
        static let alarm1Hour = "1H"
        static let alarm1Day = "1D"
        static let startDate = "startDate"
        static let endDate = "endDate"
        static let recurrenceDate = "recurrenceEndDate"
        static let startTime = "startTime"
        static let endTime = "endTime"
        static let newStartTime = "newStartTime"
        static let newEndTime = "newEndTime"
        static let newStartDate = "newStartDate"
        static let newEndDate = "newEndDate"
        static let priority = "priority"
        static let high = "high"
        static let normal = "normal"
        static let low = "low"
        static let summary = "summary"
        static let frequency = "recurrence"
        static let frequencyDaily = "daily"
        static let frequencyWeekly = "weekly"
        static let frequencyMonthly = "monthly"
        static let accessFailedCode = "APZ-CNT-037"
        static let addFailedCode = "APZ-CNT-084"
        static let deleteFailedCode = "APZ-CNT-038"
        static let editFailedCode = "APZ-CNT-020"
        static let eventSavedFailedCode = "APZ-CAL05"
        static let eventNotFoundFailedCode = "APZ-CNT-039"
        static let titleMissing = "APZ-CNT-087"
        static let invalidDateFormat = "APZ-VAL-008"
        static let addErrorCode = "APZ-CNT-082"
    }
    struct Zip {
        static let zip = "Zip"
        static let unZip = "unZip"
        static let apzDummy = "apzzipdummy"
        static let zipExtension = ".zip"
    }
    struct DeepLink {
        static let packageName = "packageName"
        static let packageScheme = "Package Scheme"
        static let appStoreLink = "appStoreLink"
    }
    struct Locale {
        static let localJson = "locale"
        static let failedGetLocale = "APZ-CNT-049"
    }
    struct Camera {
        static let flash = "flash"
        static let targetHeight = "targetHeight"
        static let targetWidth = "targetWidth"
        static let uncompressed = "unCompressed"
        static let flipRequired = "flipRequied"
        static let rotationRequired = "rotationRequired"
        static let angularScaleRequired = "angularScaleRequired"
        static let aspectRatioRequired = "aspectRatioRequired"
        static let fileToBase64 = "File converted to base 64"
        static let writeSuccess = "File write is success"
        static let fileCreationFailure = "File could not be created"
        static let writeLocationSuccess = "Write location is success"
        static let writeLocationFailed = "Write location is failed"
        static let editFailed = "Edited image cannot save"
        static let cropBoxShape = "cropBox"
        static let htmlId = "elementId"
        static let fileOverwrite = "fileOverwrite"
        static let srcUrl = "srcUrl"
        static let srcBase64 = "srcBase64"
        static let frontCamera = "frontCamera"
        static let base64save = "base64_Save"
        static let maxQuality = "100"
        static let userCancelled = "user cancelled the camera"
        static let fileCouldNotBeCreated = "APZ-CNT-011"
        static let encodeFailBase64 = "APZ-CNT-036"
        static let imageConversionErr = "APZ-CNT-118"
    }
    struct BarcodeScanner {
        static let reqFullScreen = "reqFullScreen"
        static let showGallery = "showGallery"
        static let cameraClosed = "Camera closed"
        static let cameraCloseFailed = "Failed to close the camera."
        static let originY = "originY"
        static let photoGallery = "photoGallery"
        static let scanFailed = "Failed to scan the image"
        static let imagePathNotFound = "Image Path is not available"
        static let errorMessageString = "user cancelled the photo gallery"
        static let galleryClicked = "galleryButtonClicked"
        static let closeClicked = "closeButtonClicked"
        static let scanFailedCode = "APZ-CNT-070"
    }
    struct FileOperation {
        static let fileDeletionFailure = "APZ-CNT-075"
        static let invalidFileExtension = "APZ-CNT-327"
        static let paperRect = "paperRect"
        static let printableRect = "printableRect"
        static let actionRead = "read"
        static let invalidFileOperation = "APZ-CNT-082"
        static let invalidSrc = "APZ-CNT-190"
        static let fileSizeError = "APZ-CNT-289"
        static let invalidFileFormat = "APZ-CNT-275"
        static let documentCancelled = "Document Cancelled"
        static let documentDismiss = "Document Dismissed"
    }
    struct UserLocation {
        static let gpsServicesOffError = "APZ-CNT-057"
        static let subLocality = "subLocality"
        static let locality = "locality"
        static let administrativeArea = "administrativeArea"
        static let postalCode = "postalCode"
        static let country = "country"
        static let errorMessage = "Unable to fetch User Location"
        static let thoroughFare = "thoroughfare"
        static let subThoroughfare = "subThoroughfare"
        static let countryCode = "countryCode"
    }
    struct BarcodeGenerator {
        static let inputString = "inputString"
        static let tempFolderQRCode = "TempFolderQRCode"
        static let dateFormat = "yyyyMMdd_HHmmss"
        static let codeGenerator =  "CIQRCodeGenerator"
        static let inputMessage = "inputMessage"
    }
    struct Vibrate {
        static let unsupportedDevice = "APZ-CNT-134"
    }
    struct ActivityShare {
        static let textToShare = "textToShare"
        static let errorMessage = "Native Share Failed"
        static let successMessage = "Native Share Success"
        static let errorFile = "Native share failed - File does not exist"
        static let errorFilePath = "Native Share Failed - FilePath missing"
    }
    struct VideoGalleryController {
        static let fileBrowserOpenFile = "openFile"
        static let fileBrowserFilter = "filter"
        static let videoAccessDenied = "APZ-CNT-114"
        static let galleryClosed = "Gallery is closed"
        static let dateFormat = "ddMMYYHHmmss"
        static let videoGalleryDirName = "video"
        static let videoGalleryFileName = "video_"
    }
    struct DeleteSubApp {
        static let appPath = "/Assets/apps"
        static let wipeOutFailure = "APZ-CNT-290"
    }
    struct PullDown {
        static let refreshStatus = "refreshStatus"
        static let enable = "enable"
        static let screenId = "screenId"
        static let callId = "callId"
        static let hideRefresh = "HideRefresh"
        static let pluginName = "pullDown"
        static let refreshHiddenSuccess = "Refresh Hidden Succesfully"
        static let refreshing = "refreshing"
    }
    struct Audio {
        static let timeDuration = "timeDuration"
        static let channel = "channel"
        static let stereo = "stereo"
        static let samplingRate = "samplingRate"
        static let bitRate = "bitRate"
        static let wavFileFormat = "wavFileFormat"
        static let wav = "wav"
        static let m4a = "m4a"
        static let audioDirectory = "/audio"
        static let dateFormat = "ddMMYYYYhhmmss"
        static let record = "record"
        static let play = "play"
        static let pause = "pause"
        static let kDefault = "DEFAULT"
        static let external = "EXTERNAL"
        static let errorRecordFail = "APZ-CNT-031"
        static let errorEncoderFail = "APZ-CNT-121"
        static let errorDecoderFail = "APZ-CNT-122"
        static let errorRecorderBusy = "APZ-CNT-029"
        static let errorPlayFail = "APZ-CNT-030"
        static let errorNoRecPlay = "APZ-CNT-033"
        static let maxTimeLimit = 60
    }
    struct DeviceInfo {
        static let deviceId = "deviceId"
        static let hashKey1 = "hashKey1"
        static let hashKey2 = "hashKey2"
        static let deviceGroup = "deviceGroup"
        static let deviceOs = "deviceOs"
        static let screenPpi = "screenPpi"
        static let screenSize = "screenSize"
        static let deviceType = "deviceType"
        static let otaRequired = "otaRequired"
        static let orientation = "orientation"
        static let lockRotation = "lockRotation"
        static let iOS = "iOS"
        static let deviceTypeValue = "IOS"
    }
    struct Biometric {
        static let touch = "TOUCHID"
        static let face = "FACEID"
        static let none = "NONE"
        static let notConfigured = "NOTCONFIGURED"
        static let notSupported = "NOTSUPPORTED"
        static let biometricStatus = "biometricStatus"
        static let biometricNotEnrolled = "Biometry is not enrolled."
        static let defaultPopupMessage = "Are you the device owner?"
        static let popupMessage = "popupMessage"
        static let authenticationSuccess = "Authentication success"
        static let notEnrolledErrorCode = "APZ-CNT-324"
        static let authenticationErrorCode = "APZ-CNT-305"
        static let fingerprintSub = "fingerprintSub"
    }
    struct Connection {
        static let none = "none"
        static let wifi = "wifi"
        static let type2g = "2G"
        static let type3g = "3G"
        static let type4g = "4G"
        static let type5g = "5G"
    }
    struct DeviceDetails {
        static let osName = "osName"
        static let osVersion  = "osVersion"
        static let deviceType = "devType"
        static let screenResolution = "screenResolution"
        static let batteryStatus = "batteryStatus"
        static let connectiontype = "connectionType"
    }
    struct WebView {
        static let cancel = "Cancel"
        static let postData = "postData"
        static let trackURL = "trackURL"
        static let cancelButton = "cancelButton"
        static let questionMark = "?"
        static let ampersand = "&"
        static let equals = "="
        static let lowercaseY = "y"
    }
    struct SplashScreen {
        static let portraitScale1 = "LaunchImages-700-Portrait~ipad.png"
        static let landscapeScale1 = "LaunchImages-700-Landscape~ipad.png"
        static let portraitScale2 = "LaunchImages-Portrait@2x~ipad.png"
        static let landscapeScale2 = "LaunchImages-Landscape@2x~ipad.png"
        static let portrait736 = "LaunchImages-800-Portrait-736h.png"
        static let landscape736 = "LaunchImages-800-Landscape-736h@3x.png"
        static let portrait812 = "LaunchImages-1100-Portrait-2436h@3x.png"
        static let landscape812 = "LaunchImages-1100-Landscape-2436h@3x.png"
        static let portrait667 = "LaunchImages-800-667h@2x.png"
        static let landscape667 = "ContainerImages/Default-Landscape-667h@2x~iphone.png"
        static let portrait568 = "LaunchImages-700-568h@2x.png"
        static let landscape568 = "ContainerImages/Default-Landscape-568h@2x~iphone.png"
        static let portrait480Scale2 = "LaunchImages@2x.png"
        static let landscape480Scale2 = "ContainerImages/Default-Landscape@2x~iphone.png"
        static let portrait480Scale1 = "LaunchImages.png"
        static let landscape480Scale1 = "ContainerImages/Default-Landscape~iphone.png"
    }
    struct GestureRecognizer {
        static let timer = "Timer"
        static let calleeGesture = "gesture"
        static let singleTap = "singletap"
        static let doubleTap = "doubletap"
        static let tripleTap = "tripletap"
        static let pinch = "pinch"
        static let longPress = "longpress"
        static let swipe = "swipe"
        static let swipeDown = "swipeDown"
        static let swipeUp = "swipeUp"
        static let swipeLeft = "swipeLeft"
        static let swipeRight = "swipeRight"
        static let timerExceeds = "timerExceeds"
        static let firstTap = "singleTap"
        static let secondTap = "doubleTap"
        static let treeTaps = "tripleTap"
        static let longPressed = "longPress"
    }
    struct UserPreferences {
        static let userPref = "userprefs"
        static let null = "null"
        static let plistPath = "/plist/UserSettings.plist"
    }
    struct Mail {
        static let clientError = "APZ-CNT-012"
        static let subject = "subject"
        static let recipientId = "recipientMailId"
        static let body = "body"
        static let ccIdList = "ccIdList"
        static let maxAttachmentSize = "maxAttachmentSize"
        static let defaultMaxAttachmentSize = "25"
        static let filePaths = "filePaths"
        static let largeFileErrorCode = "APZ-CNT-322"
        static let sent = "sent"
        static let saved = "saved"
    }
    struct FileEncryption {
        static let failCode = "APZ-CNT-048"
        static let failMessage = "File encryption failed"
        static let successMessage = "File encryption success"
    }
    struct FileDecryption {
        static let failCode = "APZ-CNT-046"
        static let failMessage = "File decryption failed"
        static let successMessage = "File decryption success"
    }
    struct Encrypt {
        static let stringToEncrypt = "stringToEncrypt"
        static let encryptId = "encryptionId"
    }
    struct Decrypt {
        static let stringToDecrypt = "stringToDecrypt"
        static let decryptId = "decryptionId"
    }
    struct AppzillonMain {
        static let appTokenStatus = "appTokenStatus"
        static let localStorage = "localStorage.clear();"
        static let wipeOut = "wipedOut"
        static let hyphen = "-"
    }
    struct AppzillonViewHandler {
        static let disable = "disable"
    }
    struct Browser {
        static let invalidUrl = "APZ-CNT-131"
        static let browserSuccess = "Browser Opened Successfully"
    }
    struct Base64_File {
        static let filetoB64 = "filetoB64"
        static let fileToBase64Error = "APZ-CNT-270"
        static let directoryCouldNotCreate = "APZ-CNT-072"
        static let base64ToFileFailed = "APZ-CNT-271"
        static let fileNameMissing = "APZ-CNT-169"
        static let pathExtensionMissing = "File Path Extension is Missing"
    }
    struct ImageViewController {
        static let imageViewFailed = "Image View failed"
        static let cancelImageView = "user cancelled the image view"
    }
    struct FileExtensions {
        static let mp3 =  ".mp3"
        static let amr = ".amr"
        static let caf = ".caf"
        static let mp4 = ".mp4"
        static let mpg = ".mpg"
        static let mpeg = ".mpeg"
        static let png = ".png"
        static let docx = ".docx"
        static let xlsx = ".xlsx"
        static let ppt = ".ppt"
        static let jpg = ".jpg"
        static let pdf = ".pdf"
        static let jpeg = ".jpeg"
        static let xls = ".xls"
    }
    struct AppDelegateUtility {
        static let staticfiles = "staticfiles"
        static let files = "Files"
    }
    struct ProcessImage {
        static let inputFile = "inputFile"
        static let imageAction = "imageAction"
        static let blackAndWhite = "BW"
        static let imageCouldNotProcess = "ProcessImage failed"
        static let thersholdOrImageActionMissing = "Image Action or Thersold Value not Available"
        static let fileNameorFileEncoding = "Filename or File Encoding not Available"
        static let defaultQuality = "100"
    }
    struct SecureStorage {
        static let storeCredentialsSecurely = "PLGN_STR_CRD_SECURELY"
        static let storeSecurely = "PLGN_STR_SECURELY"
        static let retrieveSecurely = "PLGN_RTR_SECURELY"
        static let loginSecurely = "PLGN_LOGIN"
        static let command = "command"
        static let userId = "userId"
        static let password = "password"
        static let hashValue = "###@@@###"
        static let keyUnderscore = "key_"
        static let keyOrUserIdMissing = "APZ-CNT-231"
        static let biometricNotEnrolled = "APZ-CNT-324"
        static let bioMetricDomainState = "BioMetricDomainState"
        static let isBiometricNeeded = "isBiometricNeeded_"
        static let result = "result"
        static let successful = "Successful"
        static let keychainOperationFailed = "APZ-CNT-232"
        static let promptBiometric = "promptBiometric"
        static let params = "params"
        static let isBiometric = "isBiometric"
        static let resFull = "resFull"
        static let appzillonHeader = "appzillonHeader"
        static let status = "status"
        static let deviceBiometricChanged = "APZ-CNT-234"
        static let fingerPrintChanged = "Fingerprint Changed."
        static let appzillonErrors = "appzillonErrors"
        static let reqId = "reqId"
    }
    struct PhoneCallAndSMS {
        static let phone = "phoneNo"
        static let notSupported = "APZ-CNT-262"
        static let telePrompt = "telprompt://"
        static let connected = "connected"
        static let disconnected = "disconnected"
        static let typing = "typing"
        static let incoming = "incoming"
        static let unableToSendSMS = "APZ-CNT-246"
        static let sms = "sms:"
        static let simAvailability = "SIM is not Available"
        static let phoneNoDoesNotExist = "Phone Number not available"
    }
    struct FilesViewController {
        static let fileBrowserIcons = "fileBrowserIcons"
        static let filterPredicate = "SELF ENDSWITH %@"
    }
    struct FileBrowser {
        static let fileCategory = "fileCategory"
        static let photoCategory = "PHOTO"
        static let videoCategory = "VIDEO"
        static let audioCategory = "AUDIO"
        static let defaultCategory = "DEFAULT"
        static let invalidFileCategory = "APZ-CNT-064"
        static let appFilesEmpty = "APZ-CNT-069"
        static let fileNotFound = "APZ-CNT-002"
        static let locationSeperator = "~"
        static let locationiOS = "ios-downloads"
        static let dateFormat = "ddMMYYHHmmss"
        static let imageAccessFailed = "APZ-CNT-065"
        static let imageAccessDeined = "APZ-CNT-066"
    }
    struct AppBrowser {
        static let title = "App Browser"
        static let selectedFile = "Selected File"
        static let directories = "Directories"
        static let createFile = "createFile"
        static let selectedIdentifier = "SelectedIdentifier"
    }
    struct Sensor {
        static let gpsOffError = "APZ-CNT-057"
        static let invalidTimeInterval = "APZ-VAL-006"
        static let gpsRunningError = "APZ-CNT-017"
        static let gpsStoppedError = "APZ-CNT-058"
        static let gpsNetworkOff = "APZ-CNT-059"
    }
    struct GPS {
        static let distanceAccuracy = "distanceInterval"
        static let periodicity = "periodicity"
        static let onChange = "onChange"
        static let distanceBased = "distanceBased"
        static let timed = "timed"
        static let timeAccuracy = "timeInterval"
        static let altitude = "altitude"
        static let accuracy = "accuracy"
        static let altitudeAcc = "altitudeaccuracy"
        static let heading = "heading"
        static let speed = "speed"
    }
    struct EventMonitor {
        static let on = "on"
        static let off = "off"
        static let allEvents = "allEvents"
        static let appPausedEvent = "appPausedEvent"
        static let appResumedEvent = "appResumedEvent"
        static let appCallStartEvent = "appCallStartEvent"
        static let appCallEndEvent = "appCallEndEvent"
        static let appPaused = "appPaused"
        static let appResumed = "appResumed"
    }
    struct KeyBoardListner {
        static let show = "show"
        static let hide = "hide"
    }
    struct GpsStatus {
        static let checkLocationAvailabitlty = "CHECK_LOCATION_AVAILABILITY"
        static let redirectToSettings = "REDIRECT_TO_SETTINGS"
        static let gpsEnabled = "GPS enabled"
        static let gpsDisabled = "GPS disabled"
        static let redirectSuccess = "Redirected to settings"
        static let redirectFailed = "Failed to redirect to settings"
    }
    struct AddNotificationDB {
        static let insertQuery = "insert into tb_notifications(message ,timeStamp,readFlag) values('%@','%@','N')"
    }
    struct Logger {
       static let runTimeDebugSeverityFatal = "F"
       static let runTimeDebugSeverityError = "E"
       static let runTimeDebugSeverityWarn = "W"
       static let runTimeDebugSeverityInfo = "I"
    }
}
// swiftlint:enable all
