/*
 * Migration script from 3.27.2 to 3.27.3
 */
ALTER TABLE `TB_ASTP_BEACON_MASTER`
MODIFY COLUMN `ID` BIGINT NOT NULL;

ALTER TABLE `TB_ASTP_OTP_ENGINE`
MODIFY COLUMN `REF_NO` BIGINT NOT NULL;

ALTER TABLE `TB_ASTP_AR_MASTER`
MODIFY COLUMN `ID` BIGINT NOT NULL;