/*
 * Migration script from 3.27.2 to 3.27.3
 */
ALTER TABLE `TB_ASLG_JMS_REQ_RESP`
MODIFY COLUMN `TRANS_ID` BIGINT NOT NULL;

ALTER TABLE `TB_ASLG_AUDIT_LOG`
MODIFY COLUMN `ACCESS_REF` BIGINT NOT NULL;

ALTER TABLE `TB_ASMI_CAPTCHA_DTLS`
MODIFY COLUMN `CAPTCHA_REF` BIGINT NOT NULL;