variable "cluster_name" {}
variable "vpc_cidr_block" {}
variable "private_subnet_cidr_blocks" {}
variable "public_subnet_cidr_blocks" {}
variable "instance_type" {}
variable "cluster_vpc_id" {}
variable "cluster_oidc_issuer_url" {}
variable "dashboard_dns" {}
variable "filesystem_id" {}
variable "image_repos" {}