{{- if .Values.openshift.cluster }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: prometheus-registry-secret
  namespace: {{ .Values.nameSpace}}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.prometheus_registrySecret }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: prometheus-registry-secret
      namespace: {{ .Values.nameSpace}}
    type: kubernetes.io/dockerconfigjson
{{- end }}
