package com.iexceed.plugins

object PluginConstants {    
	const val APZ_PLUGIN_CAMERA = "PLGN_OPN_CAMERA"
	const val APZ_PLUGIN_AUTOCAPTURE = "PLGN_OPN_AUTOCAPTURE"
	const val APZ_PLUGIN_SELFIECAPTURE = "PLGN_OPN_SELFIECAPTURE"
	const val APZ_PLUGIN_IMG_PROC = "PLGN_IMG_PROC"

	const val APZ_PLUGIN_CALL = "PLGN_CALL_NMB"
	const val APZ_PLUGIN_BASE64TOFILE = "PLGN_B64_TO_FILE"
	//
	const val PLGN_IS_APPTOKENSET = "PLGN_IS_APPTOKENSET"

	//public static final String APZ_PLUGIN_MISSEDCALLS = "PLGN_MSD_CALLS";
	const val APZ_PLUGIN_GETCALLLOGS = "PLGN_GET_CALLLOGS"

	const val APZ_PLUGIN_OPENURL = "PLGN_OPEN_URL"
	const val APZ_PLUGIN_FILETOBASE64 = "PLGN_FILE_TO_B64"
	const val APZ_PLUGIN_GETFILESIZE = "PLGN_FILE_SIZE"
	const val APZ_PLUGIN_LAUNCHWEBVIEW = "PLGN_LNCH_WEBVW"
	const val APZ_PLUGIN_CLOSEWEBVIEW = "PLGN_CLS_WEBVW"
	const val APZ_PLUGIN_FILEDOWNLOADMGR = "PLGN_FILE_DOWNLOADMGR"

	//	public static final String APZ_PLUGIN_INBOXSMS = "PLGN_GET_INBX_SMS";
	const val APZ_PLUGIN_NOTIF_SHOW = "PLGN_SHW_NOTIF"
	const val APZ_PLUGIN_NOTIF_DELETE = "PLGN_DLT_NOTIF"

	const val APZ_PLUGIN_CURRENTLOCATION = "PLGN_GET_LOCATION"
	const val APZ_PLUGIN_ZIP = "PLGN_ZIP"
	const val APZ_PLUGIN_UNZIP = "PLGN_UNZIP"
	const val PLGN_DEV_INFO = "PLGN_DEV_INFO"
	const val PLGN_GET_USER_PREF = "PLGN_GET_USER_PREF"
	const val PLGN_ENCRPT_DATA = "PLGN_ENCRPT_DATA"
	const val PLGN_DECRPT_DATA = "PLGN_DECRPT_DATA"
	const val PLGN_HASH_PWD = "PLGN_HASH_PWD"

	const val PLGN_NTV_EXT = "PLGN_NTV_EXT"
	const val PLGN_IS_APPTOKENSETN = "PLGN_IS_APPTOKENSET"

	const val APZ_PLUGIN_CAL_CREATE = "PLGN_CRT_CAL_EVT"
	const val APZ_PLUGIN_CAL_DELETE = "PLGN_DLT_CAL_EVT"
	const val APZ_PLUGIN_CAL_EDIT = "PLGN_EDT_CAL_EVT"

	const val APZ_PLUGIN_ENCRYPT_DATA = "PLGN_ENCRPT_DATA"
	const val APZ_PLUGIN_DECRYPT_DATA = "PLGN_DECRPT_DATA"
	const val APZ_PLUGIN_SQL = "PLGN_EXE_SQL"
	const val APZ_PLUGIN_DEVICEINFO = "PLGN_DEV_DETAILS"
	const val APZ_PLUGIN_BATRY_START = "PLGN_BT_MTR_START"
	const val APZ_PLUGIN_BATRY_STOP = "PLGN_BT_MTR_STOP"
	const val APZ_PLUGIN_ENCRPT_FILE = "PLGN_ENCRPT_FILE"
	const val APZ_PLUGIN_DECRPT_FILE = "PLGN_DECRPT_FILE"
	const val APZ_PLUGIN_GPS_START = "PLGN_LOC_TRCK_START"
	const val APZ_PLUGIN_GPS_STOP = "PLGN_LOC_TRCK_STOP"
	const val APZ_PLUGIN_GESTURE_START = "PLGN_GSTR_START"
	const val APZ_PLUGIN_GESTURE_STOP = "PLGN_GSTR_STOP"
	const val APZ_PLUGIN_FILE_BROWSER = "PLGN_BRWS_FILE"
	const val APZ_PLUGIN_FILE_CONTENT = "PLGN_FILE_CONTENT"
	const val APZ_PLUGIN_FILE_CREATE = "PLGN_CRT_FILE"
	const val APZ_PLUGIN_FILE_DELETE = "PLGN_DEL_FILE"
	const val APZ_PLUGIN_FILE_OPEN = "PLGN_OPN_FILE"
	const val APZ_PLUGIN_MAIL = "PLGN_SEND_MAIL"
	const val APZ_PLUGIN_CONTACT_ADD = "PLGN_ADD_CONT"
	const val APZ_PLUGIN_CONTACT_DELETE = "PLGN_DEL_CONT"
	const val APZ_PLUGIN_CONTACT_SEARCH = "PLGN_SRCH_CONT"
	const val APZ_PLUGIN_CONTACT_EDIT = "PLGN_EDIT_CONT"
	const val APZ_PLUGIN_CONTACT_FETCH = "PLGN_FETCH_CONT"

	const val APZ_PLUGIN_LOCALE = "PLGN_CRNT_LOCALE"
	const val APZ_PLUGIN_SIGNATUREPAD = "PLGN_SIGN_PAD"

	const val APZ_PLUGIN_IDLETIMEOUT = "PLGN_IDLE_TMR_START"
	const val APZ_PLUGIN_LCK_ROTN = "PLGN_LCK_ROTN"
	const val APZ_PLUGIN_UNLCK_ROTN = "PLGN_UNLCK_ROTN"
	const val APZ_PLUGIN_ORIENTATION = "PLGN_SET_ORTN"
	const val APZ_PLUGIN_VIBRATE = "PLGN_VIBRATE"
	const val APZ_PLUGIN_VOICE = "PLGN_VOICE"
	const val APZ_PLUGIN_CONTROLEVENTS = "PLGN_DET_EVE"
	const val APZ_PLUGIN_WIPEOUT = "PLGN_WIPEOUT"
	const val APZ_PLUGIN_GET_IP = "PLGN_GET_IP"
	const val APZ_PLUGIN_APP_VERSION = "PLGN_APP_VERSION"
	const val APZ_PLUGIN_CLS_APPCTN = "PLGN_CLS_APPCTN"

	const val APZ_PLUGIN_PULDWN_ENABLE = "PLGN_EN_PLDN"
	const val APZ_PLUGIN_PULDWN_DISABLE = "PLGN_DIS_PLDN"

	const val APZ_PLUGIN_AUTH = "PLGN_BIO_AUTH"
	const val APZ_PLUGIN_AUDIO = "PLGN_AUDIO"

	const val APZ_PLUGIN_DELETESUBAPP = "PLGN_SUBAPP_DEL"
	const val APZ_PLUGIN_GETINSTRUCTIONS = "PLGN_GET_INST"
	const val APZ_PLUGIN_UPGRADEREQUIRED = "PLGN_UPGRD_REQ"
	const val APZ_PLUGIN_UPGRD_APP = "PLGN_UPGRD_APP"
	const val APZ_PLUGIN_UPDATE_ACTION = "PLGN_UPDATE_REQ"
	const val APZ_PLUGIN_SETSETTINGS = "PLGN_SET_USER_PREF"
	const val APZ_PLUGIN_LOADSETTINGS = "PLGN_LOAD_STNGS"
	const val APZ_PLUGIN_SENDSMS = "PLGN_SMS_SEND"
	const val APZ_PLUGIN_SMS_LSTN_STRT = "PLGN_SMS_LSTN_START"
	const val APZ_PLUGIN_SMS_LSTN_STOP = "PLGN_SMS_LSTN_STOP"
	const val APZ_PLUGIN_HIDEREFRESH = "PLGN_HIDE_REFRESH"
	const val APZ_PLUGIN_KEYBD_LSTN_STRT = "PLGN_KEYBD_LISTR_STRT"
	const val APZ_PLUGIN_KEYBD_LSTN_STOP = "PLGN_KEYBD_LISTR_STOP"
	const val APZ_PLUGIN_ORIENTATION_LISTN = "PLGN_ORTN_LISTR"
	const val APZ_PLUGIN_NOTIF_LSTN_STRT = "PLGN_NOT_LISTR_STRT"
	const val APZ_PLUGIN_NOTIF_LSTN_STOP = "PLGN_NOT_LISTR_STOP"
	const val APZ_PLUGIN_SET_PREF = "PLGN_SET_PREF"
	const val APZ_PLUGIN_GET_PREF = "PLGN_GET_PREF"
	const val APZ_APP_AVAILABILITY = "PLGN_APP_AVAILABILITY";
	const val APZ_NOTIF_STATUS = "PLGN_NOTIF_STATUS"
	const val APZ_PLUGIN_FILEUPLOAD = "PLGN_UPLD_FILE"
	const val APZ_PLUGIN_FILEDOWNLOAD = "PLGN_DWLD_FILE"
	const val APZ_PLUGIN_FINGERPRINT = "PLGN_ENB_FINGERPRINT"

	const val APZ_PLUGIN_GET_SIM_INFO = "PLGN_GET_SIM_INFO"

	const val APZ_PLUGIN_READ_FILE = "PLGN_READ_FILE"

	const val APZ_PLUGIN_DEEPLNKNG = "PLGN_DEEP_LNK"

	const val APZ_PLUGIN_TRACK_LOC = "PLGN_TRACK_LOC"
	const val APZ_PLUGIN_NATIVE_SERVER_CALL = "PLGN_N_SRVRCALL"
	const val APZ_PLUGIN_CREATE_PDF = "PLGN_GEN_PDF"
	const val APZ_PLUGIN_GEN_BARCODE = "PLGN_GEN_BARCODE"

	//Secure Data 3.5.1
	const val APZ_PLUGIN_SECURE = "PLGN_STORE_RETRIEVE_SECURE"

	//PreventReplayAttack and DataIntegrity changes in Android
	const val APZ_PLUGIN_RESETNONCE = "PLGN_REFSVRNONCE"
	const val APZ_BIOMET_AVAIL = "PLGN_BIOMET_AVAIL"
	const val APZ_CHANG_PWD = "PLGN_CHNG_PWD"
	const val APZ_NATIVE_SHARE = "PLGN_NATVE_SHARE"
	const val PLGN_SECURITY_UTIL = "PLGN_SECURITY_UTIL"

	// recent barcode and gallery developments
	const val PLGN_SCN_BARCODE = "PLGN_SCN_BARCODE"
	const val PLGN_GALRY__SCN_BARCODE = "PLGN_GALRY_SCN_BARCODE"
	const val APZ_NETWORK_MONITOR = "PLGN_NETWORK_MONITOR"
	const val APZ_NOTIFY_DOWNLOAD = "PLGN_NOTIFY_DOWNLOAD"
	const val APZ_CUSTOM_URL = "PLGN_CUSTOM_SERVERCALL"
	const val PLGN_SDK_CALLBACK = "PLGN_SDK_CALLBACK"
	const val APZ_PLUGIN_SHORT_LSTN_STRT = "PLGN_SHORT_LISTR_STRT"
	const val APZ_PLUGIN_SHORT_LSTN_STOP = "PLGN_SHORT_LISTR_STOP"
	const val APZ_PLUGIN_IS_NFC_SUPPORTED = "PLUGIN_IS_NFC_SUPPORTED"
	const val PLGN_CHECK_GPS_STATUS = "PLGN_CHECK_GPS_STATUS"
	const val PLGN_REDIRECT_TO_SETTINGS = "PLGN_REDIRECT_TO_SETTINGS"
      const val APZ_PLUGIN_STATUS_BAR_COLOR = "PLGN_STATUS_BAR_COLOR"

	const val APZ_PLUGIN_SMS_SIMDET = "PLGN_SMS_GET_SIMDET"
	const val PLGN_IS_NETWORK_AVAILABLE = "PLGN_IS_NETWORK_AVAILABLE"
	const val PLGN_LOAD_MAP = "PLGN_LOAD_MAP"

	//DatabaseOperations
	const val APZ_PLUGIN_DB_OPERATION = "PLGN_DB_OPERATION"

	const val PLGN_INAPP_REVIEW = "PLGN_INAPP_REVIEW"


	// request codes
	const val APZ_REQ_DEFAULT_PERMISSIONS = 101
	const val APZ_REQ_CAMERA = 102
	const val APZ_REQ_CALL_PHONE = 103
	const val APZ_REQ_CALENDAR = 104
	const val APZ_REQ_LOCATION = 105
	const val APZ_REQ_FINGERPRINT = 106
	const val APZ_REQ_FINE_LOCATION = 107
	const val GOOGLE_PLUS_SIGN_IN = 108
	const val APZ_REQ_WRITE_STORAGE = 109
	const val APZ_REQ_RECORD_AUDIO = 110
	const val APZ_REQ_CONTACTS = 111
	const val APZ_REQ_READ_SMS = 112
	const val APZ_REQ_WRITE_SETTINGS = 113
	const val APZ_REQ_BLUETOOTH = 114
	const val REQUEST_CODE_PHOTO_LIBRARY = 115
	const val REQUEST_CODE_ALL_FILE_ACCESS = 115
	const val RESULT_LOAD_IMAGE = 116
	const val RESULT_LOAD_VIDEO = 117
	const val RESULT_LOAD_AUDIO = 118
	const val BROWSE_FILE = 119
	const val CODE_WRITE_SETTINGS_PERMISSION = 120
	const val FACE_IMG_PREV = 121
	const val RESULT_LOAD_MAIL = 122
	const val IMG_PREVIEW = 123
	const val SEND_NFC = 124
	const val RECEIVE_NFC = 125
	const val DEVICE_RECEIVE_NFC = 126
	const val CAPTURE_SIGN = 127

	const val REQUEST_GPS_DIALOG = 1031
	const val REQUEST_GPS_SETTINGS = 1032

	const val properties = "USER_PREFS"
	const val OPEN_DIRECTORY_REQUEST_CODE = 112

}
