/*
 * Migration script from 3.27.2 to 3.27.3
 */
ALTER TABLE TB_ASLG_JMS_REQ_RESP DROP CONSTRAINT PK_TB_ASLG_JMS_REQ_RESP;

ALTER TABLE TB_ASLG_JMS_REQ_RESP
MODIFY TRANS_ID NUMBER(20,0);

ALTER TABLE TB_ASLG_JMS_REQ_RESP ADD CONSTRAINT PK_TB_ASLG_JMS_REQ_RESP Primary Key ( TRANS_ID );

ALTER TABLE TB_ASLG_AUDIT_LOG DROP CONSTRAINT PK_TB_ASLG_AUDIT_LOG;

ALTER TABLE TB_ASLG_AUDIT_LOG
MODIFY ACCESS_REF NUMBER(20,0);

ALTER TABLE TB_ASLG_AUDIT_LOG ADD CONSTRAINT PK_TB_ASLG_AUDIT_LOG Primary Key ( ACCESS_REF );

ALTER TABLE TB_ASMI_CAPTCHA_DTLS DROP CONSTRAINT TB_ASMI_CAPTCHA_DTLS_PK;

ALTER TABLE TB_ASMI_CAPTCHA_DTLS
MODIFY CAPTCHA_REF NUMBER(20,0);

ALTER TABLE TB_ASMI_CAPTCHA_DTLS ADD CONSTRAINT TB_ASMI_CAPTCHA_DTLS_PK Primary Key ( CAPTCHA_REF );
