/*
 * Migration script from 3.27.2 to 3.27.3
 */
ALTER TABLE TB_ASTP_BEACON_MASTER DROP CONSTRAINT TB_ASTP_BEACON_MASTER_PK;

ALTER TABLE TB_ASTP_BEACON_MASTER
MODIFY ID NUMBER(20,0);

ALTER TABLE TB_ASTP_BEACON_MASTER ADD CONSTRAINT TB_ASTP_BEACON_MASTER_PK Primary Key ( ID );

ALTER TABLE TB_ASTP_OTP_ENGINE DROP CONSTRAINT TB_ASTP_OTP_ENGINE_PK;

ALTER TABLE TB_ASTP_OTP_ENGINE
MODIFY REF_NO NUMBER(20,0);

ALTER TABLE TB_ASTP_OTP_ENGINE ADD CONSTRAINT TB_ASTP_OTP_ENGINE_PK Primary Key ( REF_NO );

ALTER TABLE TB_ASTP_AR_MASTER DROP CONSTRAINT TB_ASTP_AR_MASTER_PK;

ALTER TABLE TB_ASTP_AR_MASTER
MODIFY ID NUMBER(20,0);

ALTER TABLE TB_ASTP_AR_MASTER ADD CONSTRAINT TB_ASTP_AR_MASTER_PK Primary Key ( ID );
