apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: elastic-secret
  namespace: {{ .Values.nameSpace }}
spec:
  encryptedData:
    password:  {{ .Values.password }}
    username:  {{ .Values.username }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: elastic-secret
      namespace: {{ .Values.nameSpace }}
