redis.password=FQHPcFWPSx/5jlI5bUqKfwSeoZTxsTdykQDsybxZgJgTLgODc56DBrTR55PdQjb0Rpav+XMbJG64r8FT
redis.usessl=true
redis.verifyPeer=true

redis.cluster0.host=172.31.45.102
redis.cluster0.port=6379
 
redis.cluster1.host=172.31.33.99
redis.cluster1.port=6379
 
redis.cluster2.host=172.31.41.90
redis.cluster2.port=6379

redis.cluster3.host=172.31.36.157
redis.cluster3.port=6379

redis.cluster4.host=172.31.41.247
redis.cluster4.port=6379

redis.cluster5.host=172.31.32.194
redis.cluster5.port=6379